### ISSUE TITLE
Flux architecture

### ISSUE THREAD

**Issue by giltig** [Polymer/polymer#1059]
Hi, 
There's no denying that flux and React have a very unique and efficient way to remove state handling and complications of mvc.
Are there any plans for polymer to adapt those changes? because web components are great - It's better than writing your html inside the js (like React does) but the problem is that we have a problem to manage state across our entire application with all those components... Any solution by Polymer?

**Comment by kieran** [comment]
Unless I'm mistaken, Flux is just an architecture pattern:

![Flux architecture](https://github.com/facebook/flux/raw/master/docs/img/flux-diagram-white-background.png)

I don't see why you Polymer wouldn't fit nicely in the View role, replacing the `React Views` box in the diagram above.

Wiring up the other elements in the Flux pattern would be outside the scope of Polymer alone.

**Comment by giltig** [comment]
The problem is handling the state.
Flux architecture goes nicely with React elements because it has a deterministic state and you don't have to worry about it.
It's like we use to press F5 (refresh) in conservative web sites in order to get the latest data from the web site (just without the post back..).
With Polymer due to the data binding you to handle the state your self and when you have a data list that changes and updates it becomes difficult to manage it.
I wonder if in Polymer there will be an option to render elements without data binding but instead with a representation of some sort for the latest state of the data (instead of handling with element to add or remove in the DOM and where according to the data behind which is changing.

**Comment by vnen** [comment]
@giltig I made a sample app based on the Polymer tutorial using Backbone.js for stores and the Flux architecture. You can check it at https://vnen.github.io/polymer-flux.

One thing I did miss, however, was a way to "repaint" the element, so it updates the style according to the last attribute changes.

**Comment by tpluscode** [comment]
I have been experimenting with Flux architecture and Polymer, using Reflux as the Flux implementation. You can look at the code at https://github.com/tpluscode/polymer-flux/tree/vs-react/

General idea was to wrap actions and stores into Polymer elements to take advantage of data binding. It's not perfect and introduces some coupling, which may be undesired.

However I've just realized that with Polymer (and Web Components in general) you may not need any Flux library at all to implement the pattern. That is unless you don't require some fancy features like synchronizing actions, etc. You see, Flux essentially revolves around events. Actions are events and store updates are also events. With Web Components, the DOM is your only API. That is tags (elements), their attributes and events.

I created a sample [plunk](http://plnkr.co/edit/dGdyWQ?p=preview) where I use `document` as the dispatcher and simply fire events instead of actions. A store element does the heavy lifting and data-binding takes care of updating views. Alternatively you could simply fire another event in the store and handle it in views (much like `store.trigger()` is used in the original Flux).

**Comment by devinivy** [comment]
I think the way Reflux is built allows it to play quite nicely with Polymer– particularly because they use mixins under the hood to build that can just as easily be used as Polymer behaviors.

I took advantage of this to make a Polymer-Reflux bridge.  It's called funk: https://github.com/devinivy/funk.

You create Polymer elements which are Reflux stores.  When you change a property on the store (with `set()`, `push()`, `splice()`, etc.), your Polymer views can observe those changes on a global `state` object (which is shared using a behavior).  This is nice because your entire app's state lives in a single place.

@tpluscode I thought your project was clever, and it was a good point of reference while I considered using flux with Polymer.  Your project is definitely straightforward and has the virtue that it doesn't do very much "magic".  I like that it took advantage of standard Polymer features.  Funk admittedly has a little more magic going on, but I think it's a worthwhile sort of magic that makes the overall flux pattern more apparent and readily available to the Polymer developer.

**Comment by azakus** [comment]
You can make your app use a Flux pattern, Polymer does not plan on enforcing that architecture at this time.
