### ISSUE TITLE
Documentation Wrong and no worked Data binding on IE11

### ISSUE THREAD

**Issue by nim** [Polymer/polymer#1067]
This example(https://www.polymer-project.org/docs/polymer/databinding-advanced.html#autobinding) not work in IE11. See my question http://stackoverflow.com/questions/27751373/i-have-error-document-registerelement-underfined.

And See this issue https://github.com/Polymer/polymer/issues/1063 

This is what a mess! The second example is taken at random does not work in IE11 !!!! Tell me what I should do that would work in her ?????

Please correct docs!

**Comment by ebidel** [comment]
The docs are correct. You need to include the webcomponents polyfill if you're working in a browser that lacks native support. We don't include the polyfill in a lot of the standalone (more advanced) code snippets because it's assumed folks have read the intro material.

For example, it's mentioned here:
https://www.polymer-project.org/docs/start/creatingelements.html#creatapp

**Comment by nim** [comment]
I think that beginners this can be misleading. Example that should work, but that does not work ... While on the other hand you need to carefully read the documentation.
