### ISSUE TITLE
ShadowDOM CSS shimmer converting CSS counter() to string

### ISSUE THREAD

**Issue by richieb** [Polymer/polymer#1076]
First, @ebidel, I trust you have seen my findings on issues with using SASS (especially nesting) and Polymer here: #1073 

In addition to that, I found one other problem with using CSS in Polymer Elements: It appears Polymer converts all CSS values (including variables) to strings, which is causing rendering issues in my Polymer app. For example, in non-shadow DOM browsers, Polymer is converting this:
```content: counter(someNumber);```

to this:
```content: "counter(someNumber)";```

This issue occurs only in Polymer elements. If I move the Polymer element CSS to the main CSS file (i.e., outside a Polymer element), it works fine. Also note that the conversion to string is not happening in shadow DOM supported browsers.

**Comment by ebidel** [comment]
I suspect this is an issue with the Shadow DOM CSS shimmer not round tripping correctly. A good way to test would be to use the  `shim-shadowdom` on your main page stylesheet that contains this rule. If it also barfs, it's definitely the shimmer.

cc @sorvell

**Comment by richieb** [comment]
Again, I must thank you for responding promptly to the issues I have been raising, especially since I am under time constrain as I develop relatively complex Polymer app. And I continue to look forward to your timely responses :).

Unfortunately (below, I explain why I use this word), I am using `shim-shadowdom` on my main page. If I don't use it, my CSS breaks, since I am using some shadow DOM selectors on the main CSS file. Incidentally, I am discovering a few issues (not errors, but optimization issues), and now I am wondering if there is documentation somewhere on Polymer best practices. 

Here are a couple of important issues I am worried about:
1. I noticed there is no `IfElse` helper for the templates. I am using the templates in a similar manner to using Handlebars templates, so `IfElse` is almost essential. See my examples below. Am I even using the templates correctly by doing this? I have been using the Topeka app as my only reference for how to build a Polymer app.

Is this a bad pattern for using the templates?
```
 <template if="{{dataSource.title}}">                 
                    <h2>{{dataSource.title}}</h2>
                </template>

                <template if="{{dataSource.subTitle}}">
                <h3>{{dataSource.subTitle}}</h3>
                </template>

                <template if="{{dataSource.page === 'home'}}">
                    <show-home-element></show-home-element>
                </template>

<template if="{{dataSource.poll}}">
                    <show-poll-element></show-poll-element>
                </template>
```

2. I learned somewhere online that we get a performance hit every time we use `shim-shadowdom`. This is the reason I used the word "unfortunately" earlier when I said I am using `shim-shadowdom` on the main CSS file. The Polymer documentation alluded to the performance hit as well. Should I avoid using `shim-shadowdom` at all cost by reducing my use of `/deep/` and other such selectors? 

3. After reading the article at the link below, I am wondering if I should stop creating all my Polymer elements with their own shadow DOM (that is, inside the template tag), since it appears the shadow DOM polyfill is quite hefty.
http://developer.telerik.com/featured/web-components-arent-ready-production-yet/

4. I read quite a bit of the Polymer documentation (which is well-written and quite helpful, btw, except for a few issues that I will share in another post) and I am continuing to read it as the need arises. But I haven't see anything noteworthy about what **we should or shouldn't do to optimize performance** for a Polymer app. Could you touch on this a bit. Keep in mind that my app will help to promote Polymer, so every optimization tip would be very welcomed. We don't want chaps criticizing Polymer apps for performance issues do we?

**Comment by ebidel** [comment]
> . I noticed there is no IfElse helper for the templates. 

yep, there's no else template. Just negate the conditional if you need the opposite behavior.

This isn't the best place to ask these follow up questions but answers inlined.

> 1. performance hit every time we use `shim-shadowdom`...

Any time you use this attr AND are running in a polyfill'd browser, Polymer has to parse the css file and run it through the Shadow DOM styling shimmer to fix up the rules. For a large stylesheet, this of course can be a source of potential perf issue.

My recommendation is to separate out your shadow dom rules from your normal CSS rules. For example, in projects I usually do:

    <link rel="stylesheet" href="main.css">
    <link rel="stylesheet" href="main_sd.css" shim-shadowdom>

Where main_sd.css contains a few ::shadow, /deep/ rules. The bulk of the css is in main.css and does not go through the parser.

> 2. After reading the article at the link below,

Be wary of what you read online. There's a lot of old content and misunderstood practices. IMO, the benefits of SD style scoping and dom encapsulation outweigh the cost of the polyfill. Yes, a polyfill is slower than native, but we'll soon have two browsers with native SD :) The SD polyfill has also seen a number of perf improvements since that article was written. Always test and see if it _actually_ is perf issue for your app. I suspect it won't be.

> 3. I read quite a bit of the Polymer documentation 

Thanks! Please file individual bugs against https://github.com/polymer/docs. We have an outstanding item to create a best practices section: https://github.com/Polymer/docs/issues/339. There are some tips there but keep in mind, things may change with polymer 0.8. That's why we're holding off on writing it.

**Comment by arthurevans** [comment]
I think most of these questions would be better addressed on Stack Overflow, as @ebidel said.

One note on the conditional templates: you should be aware that when you use conditional templates, you're creating and destroying DOM elements when the condition changes, which can have performance implications.

If the condition is one that's set when the element's created, and doesn't change (or doesn't change often), the conditional template may be what you want. Especially if it prevents a large chunk of DOM from being created needlessly. 

If you're just conditionalizing a single element, or the condition is going to change frequently, we often recommend using CSS to show/hide the elements rather than using conditional templates.

**Comment by richieb** [comment]
Cool. Thanks for the tips, Eric. Your recommendations are helpful.

@arthurevans, thanks for the additional bits about using the templates. I am indeed using the conditional templates for when the elements are created the first time, on page load, not dynamically. But I imagine I will need to use some dynamically generated HTML, and I will use the `injectBoundHTML()` method for that.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
