### ISSUE TITLE
0.8-preview: newline confuses findAnnotatedNode

### ISSUE THREAD

**Issue by morethanreal** [Polymer/polymer#1078]
http://jsbin.com/nulupa/1/edit?html,output

If there's a newline between the opening and closing tags, I get an exception. Otherwise, there is no error.

```html
<!-- this is ok -->
<x-something><x-something>

<!-- throws exception -->
<x-something>
</x-something>
```

**Comment by sjmiles** [comment]
When there is no <content> in the template, _useContent is false, so the lightChildren are ignored. Then the stamped DOM is combined with whatever was in light DOM, causing the annotation data to be incorrect. 

Seems like we dealt with a flavor of this before, so I'm not sure if this came up anew because of changes around projection?

I suppose any light DOM needs to be snarfed up any time there is a template.

**Comment by sorvell** [comment]
We now create a localDom (shadyRoot) whenever localDom is created. This should that light dom nodes are properly accounted for in composition, and as a side effect of this, they should not get in the way of the annotator.

Fixed by https://github.com/Polymer/polymer/commit/a68e2fc0723b622719212a2c361523c0a1a1c0de
