### ISSUE TITLE
Safari is not opening the demo page of polymer

### ISSUE THREAD

**Issue by alobintechnologies** [Polymer/polymer#1088]
What will be the cause of safari not supporting the polymer demo?

**Comment by ssorallen** [comment]
Can you link to the Polymer demo you were viewing and which version of Safari you're using?

**Comment by Nevraeka** [comment]
:+1 @ssorallen

**Comment by alobintechnologies** [comment]
![polymersiteerror safaribrowser](https://cloud.githubusercontent.com/assets/4425667/5797094/119a157a-9fda-11e4-8452-d2dee1b29dc7.png)

Check this attached screenshot.

**Comment by ebidel** [comment]
Safari 5 is an unsupported browser.

**Comment by ssorallen** [comment]
@alobintechnologies, Polymer is designed to work "evergreen" browsers; browsers that update themselves. Apple has stopped updating [Safari on Windows](http://appleinsider.com/articles/12/07/25/apple_kills_windows_pc_support_in_safari_60) since its last release in 2012, and so it is not in the list of [supported browsers for Polymer](https://www.polymer-project.org/resources/compatibility.html).

I suggest trying Polymer in [Firefox](https://www.mozilla.org/en-US/firefox/new/), [Chrome](https://www.google.com/chrome/), or [Internet Explorer](http://www.microsoft.com/en-us/download/internet-explorer-11-for-windows-7-details.aspx).
