### ISSUE TITLE
Polymer animated pages not fully showing on mobile

### ISSUE THREAD

**Issue by JasperDre** [Polymer/polymer#1101]
Polymer's core animated pages[1] isn't working on mobile devices. I tested both the official website and mine with the element and it goes off-screen when selecting the card. Am I forgetting some css or javascript? Preview:
![stack](https://cloud.githubusercontent.com/assets/6676026/5790262/7d83c79a-9e90-11e4-99f1-5d2fa0229b8d.jpg)

[1] = https://www.polymer-project.org/components/core-elements/demo.html#core-animated-pages

**Comment by SneakyKoala** [comment]
I'm also a bit noob on viewports.

**Comment by gertcuykens** [comment]
Bad example try https://www.polymer-project.org/apps/topeka/ but because that demo has allot of things going on at the same time, you can look at the simple version about animation https://www.polymer-project.org/components/core-elements/demo.html#core-animated-pages to have a idea how it works. I can write a book about that page like for example the background that disappears etc but it all makes it way more difficult to understand the code if you consider all does things.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
