### ISSUE TITLE
paper-tab doesn't stretch

### ISSUE THREAD

**Issue by lyricalpolymath** [Polymer/polymer#1149]
Hello
I'm following the tutorial https://www.polymer-project.org/docs/start/tutorial/step-1.html
and trying to add one more tabs, some with a long <span> and others with the image like it's suggested in the "Explore" section...
but long tabs overflow are hidden and don't expand to fill the parent
they share the width of the parent paper-tabs

I've tried to comment out this
@media (min-width: 481px) {
    #tabs {
      /*width: 200px;*/
    }
so that paper-tabs would stretch as much as needed
but I can't figure out how to have all buttons float left, but at the same time stretch each for it's own content.

any ideas?
this whole component thing makes Css even harder than it was before not knowing what rules are being applied and where (if inside the component or outside of it.

thanks

**Comment by LM450N** [comment]
The comment syntax in your CSS is wrong.
To comment one line it's like this :

@media (min-width: 481px) {
#tabs {
/*width: 200px;*/
}

**Comment by lyricalpolymath** [comment]
yeah thanks that was a typo, but that didn't solve the issue anyways.
how do you style paper-tab { } so that it expands to fill its contents? I've tried multiple combinations of flex, layout and direct css manipulation but I haven't been able to do it

**Comment by LM450N** [comment]
I tried now.
Disable the width just like you suggested works.
I refreshed my browser page after have saved the updates, that's all.
Retry once and if the issue is still here, create a [Gist][1] if you have some modifications.

[1]:https://gist.github.com/

**Comment by arthurevans** [comment]
This kind of question is really better suited to stack overflow.

The short answer is that paper-tabs is using flexbox layout under the hood. The paper-tabs and paper-tab elements have default [layout elements](https://www.polymer-project.org/docs/polymer/layout-attrs.html) applied to them. If you look in DevTools, you'll see the flexbox rules that are being applied to individual elements based on the attributes (also: see the [layout.html](https://github.com/Polymer/polymer/blob/master/layout.html) file where the rules are defined).

To override the default styling, you need to apply a more specific CSS selector than the ones in the layout.html file. That turns out to be something like this:

```
html /deep/ paper-tab.override {
  flex: 0 1 auto;
}
```

Then add `class="override"` on your `paper-tab`.

**Comment by lyricalpolymath** [comment]
Hi, thanks for trying to answer, I lost track of this issue so by now, with Polymer 1.0 this might be solved....and you are right, this question was better for stack overflow.
I' closing the issue for these reasons
thanks
