### ISSUE TITLE
core-ajax - Firefox passing back xml when contentType 'application/json' specified

### ISSUE THREAD

**Issue by TimWillis** [Polymer/polymer#1168]
I'm having the same issue found here: 
https://groups.google.com/forum/#!msg/polymer-dev/iomONXdUAVM/CYHOQepIY6EJ

using polymer 0.5.4 
        <core-ajax url="/api/countries/"
                   handleas="json" auto
                   on-core-response="{{countriesResponse}}"
                   on-core-error="{{ajaxError}}"
                   id="ajax_countries">
        </core-ajax>
The request header "accept" from the above ajax request is asking for ("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
So my server is responding with xml, which throws an error in the json.parse since it is returning xml.

thanks
Tim

**Comment by arthurevans** [comment]
@garlicnation @sjmiles I see three possible solutions here:

1) Have core-ajax set the "accept" header automatically when you specify `handleAs` JSON or XML. Kind of weird because people may need to set the "accept" header for other types of data.

2) Document that setting handleAs _doesn't_ set the accept header, and they need to set it using `headers`.

3) Like 2, but also expose `accept` as a property, like we expose `contentType`, as a convenience.

Thoughts?

**Comment by garlicnation** [comment]
2, then 3 sounds good. I'd be happy to merge a PR for 2.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
