### ISSUE TITLE
[0.8] Undefined method in constructor

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer#1207]
Given this sample element:

```js
var XBaz = Polymer({

  is: 'x-baz',

  constructor: function(name) {
    var el = document.createElement(this.is);
    el.name = name;
    el.createTextContent(el.name);
    return el;
  },

  createTextContent: function(name) {
    this.textContent = 'Hello, from ' + name;
  }

});

var el = new XBaz('x-baz');
document.body.appendChild(el);
```

I get an error saying `createTextContent` is an undefined function.

**Comment by peterwmwong** [comment]
@robdodson I think this is the same as #1151.  I do have a PR for this #1152, which does seem to fix your testcase above: http://jsbin.com/nitedo/5/edit?html,output

**Comment by kevinpschaaf** [comment]
Fixed in https://github.com/Polymer/polymer/commit/24a29141ca7001ba2f0e4f97795a82bbc9e77620 (didn't take PR #1152 as the implementation has changed a bit). Note the API change, such that the custom constructor need not call `document.createElement` and return the element.  This will be done automatically; the user constructor should only configure the instance (`this`).

**Comment by kevinpschaaf** [comment]
New API looks like this: http://jsbin.com/nijiyohoqa/2/edit
