### ISSUE TITLE
Why calling polymer.js instead of polymer.min.js?

### ISSUE THREAD

**Issue by oswaldomilet** [Polymer/polymer#1213]
![captura de tela 2015-02-23 as 08 26 47](https://cloud.githubusercontent.com/assets/10772835/6327064/a050a00a-bb36-11e4-8d1f-1b76a20024e7.png)

**Comment by phestermcs** [comment]
I'm guessing it's because your pre-vulcanized source is `<link>`ing to `polymer.html`, which itself is `<script>`ing to `polymer.js`. Vulcanize should probably special-case processing `polymer.html` but doesn't seem to at the moment. As a quick workaround, just make your own `polymer.html` file that `<script>`s in `polymer.min.js`; the original is only two lines long.

**Comment by oswaldomilet** [comment]
It worked as a workaround, thanks. Would be nice if someone fix it ;)
I believe something like gulp-uglify is missing as a build task after vulcanize in generator-polymer...

**Comment by ebidel** [comment]
For production, you should switch polymer.html over to use polymer.min.js. Alternatively, you can vulcanize your imports so this happens automagically.

**Comment by robdodson** [comment]
@oswaldomilet I believe you can fix this by adding the `inline: true` option to the gulp task that runs vulcanize in the generator. 

Moving issue over there: https://github.com/yeoman/generator-polymer/issues/151
