### ISSUE TITLE
paper-autogrow-textarea bug

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1255]
(exampel link removed let me know if you need a new one)

Can you confirm paper-autogrow-textarea has a bug or maybe vulcanize doing something wrong?

The very last line is a paper-autogrow-textarea. On the iphone4 simulator in chrome it can not be selected.
And also in desktop chrome it does not display the label, but when you put text in and remove it again then the label appears?

**Comment by gertcuykens** [comment]
After allot of frustration I conclude `paper-autogrow-textarea` is broken 
This fixed it a little bit

```
<paper-input-decorator label="Intoductie">
        <paper-autogrow-textarea style="min-height:16px;">
               <textarea name="intro" style="overflow:hidden;">{{intro}}</textarea>
         </paper-autogrow-textarea>
</paper-input-decorator>
```

**Comment by gertcuykens** [comment]
https://www.polymer-project.org/0.5/docs/elements/paper-autogrow-textarea.html

t1.value = 'some\ntext';
a1.update();

This also does not seem to fix the problem

**Comment by miztroh** [comment]
Instead of setting min-height on the autogrow and hiding the overflow on the textarea, you could simply set rows="1" on the textarea.

You are right in saying that paper-autogrow-textarea's update() function doesn't seem to fix the multiline issue you're describing.

You should probably close this issue and file a new one on the appropriate repository.

https://github.com/polymer/paper-input

**Comment by gertcuykens** [comment]
ok thanks ps can you fix my plunker so i can include a demo in the new issue :) http://embed.plnkr.co/js3uFQSRsIR7SuGLt2gP/preview
