### ISSUE TITLE
[0.8] Style scoped immediate descendant selector no longer matches projected content

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#1312]
Consider the following Polymer custom element template:

```html
<dom-module id="x-foo">
<style>
  paper-button > span {
    color: red;
  }
</style>
<template>
  <paper-button>
    <span>Label</span>
  </paper-button>
</template>
</dom-module>
```

In ShadeyDOM, the style selector will be rewritten to:

```css
paper-button[style-scope=x-foo] > span[style-scope=x-foo] {
  color: red;
}
```

But since paper-button projects its content into a child of its own shadow / shade, the DOM will be arranged analogously to this:

```html
<paper-button style-scope="x-foo">
  <some-container style-scope="paper-button">
    <span style-scope="x-foo">Label</span>
  </some-container>
</paper-button>
```

And the rule will no longer match.

**Comment by sorvell** [comment]
Structural selectors like this are problematic in the context of non-native projection. Instead, it's better to select the element directly (e.g. span). Because an element's css is scoped to element's local dom structural selectors should be needed much less than previously. It is possible to use a descendant selector but it's better for performance to select the element explicitly.
