### ISSUE TITLE
[0.5] Publishing properties implemented via an accessor on the native prototype causes an exception

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#1321]
Now that Chrome properly puts native property accessors on the HTMLElement.prototype, its easy to see this exception if, for example, 'title' is published.

See: https://code.google.com/p/chromium/issues/detail?id=469349

**Comment by azakus** [comment]
This works mostly correctly in 0.5 due to our system to check for overriding accessors like this: https://github.com/Polymer/polymer/commit/82d04a226623472859a4ede702596f9dfc48d066.

However, sheriff-o-matic was built with Polymer 0.4.2, which does not contain this feature.
We're not going to backport anything into 0.4, so this is a WontFix.
