### ISSUE TITLE
[0.8] notify: true Bad idea unless it has a huge performance gain

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1379]
https://www.polymer-project.org/0.8/docs/migration.html#property-bindings

This new one way default binding bothers me allot, it took me months to get used to the two way bindings and now that I finally used to it I can't program without it anymore lol :)

Can we just get rid of the  "notify: true" because it is too verbose to set up two way binding and we already have a way to specify one way binding `[[one way]]`

Suggest to just use `[[one way]]` and `{{two way}}` 

And for god sake do not in any circumstances allow `{{one way}}` One way bindings should always ALWAYS be marked as `[[one way]]` You don't have to be a google scientist to understand that one way and two way should be marked very very clearly in the code!

**Comment by justinfagnani** [comment]
`{{two way}}` and `notify: true` serve two different purposes:

 * `notify: true` indicates that you _publish_ changes to your own property.
 * `{{two way}}` indicates that you _listen_ to changes from a child element's property.

Both notifying and listening have some costs, and opting in to them apparently does have performance benefits, since the performance improvement of 0.8 over 0.5 is significant.

You're right that using a `{{two way}}` binding to a non-notifying property doesn't make sense, so I hope we can offer a hint in a linter for that case.

**Comment by sorvell** [comment]
`{{ }}` doesn't mean "two-way", it means "automatic."

One can successfully write an entire app using `{{ }}` and bindings will be two-way only when the target property is `notify: true`, and otherwise will be one-way, and there is no loss of fidelity. Reducing varieties of punctuation and syntax has a value.

The `[[]]` syntax means only "prevent two-way" in scenarios where it would otherwise occur. This is provided primarily for folks that prefer explicit syntax.
