### ISSUE TITLE
[0.8] observers as an object.

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#1452]
I was trying to use the observer object to observe for changes to properties and apparently it only expects arrays.
Reference: https://www.polymer-project.org/0.8/docs/devguide/properties.html#observing-path-changes

```js
_addComplexObserverEffects: function(observers) {
      if (observers) {
        // Error: Uncaught TypeError: observers.forEach is not a function
        observers.forEach(function(observer) {
          this._addComplexObserverEffect(observer);
        }, this);
      }
}
```
Stack trace:
```
Polymer.Base._addFeature._addComplexObserverEffects (effects.html:120)
Polymer.Base._addFeature._prepBehavior (polymer.html:50)
Polymer.Base._addFeature._prepBehaviors (behaviors.html:47)
Polymer.Base._addFeature._registerFeatures (polymer.html:41)
Polymer.Base.registerCallback (base.html:22)
desugar (polymer-bootstrap.html:37)
window.Polymer (polymer-bootstrap.html:21)
(anonymous function) (iron-range.html:92)
```

**Comment by kevinpschaaf** [comment]
In v0.8.0-rc.5, an API change was made such that complex observers (for multiple dependencies or paths) are specified in an array of strings that specify a method signature, using the same format as computed properties.

https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#multiple-property-observation

Unfortunately, the website documentation for 0.8 is lagging the code by a week or two, although we try to keep the primer I linked to in lock-step with the code since it's in the same repo.

**Comment by aoisensi** [comment]
:+1:

**Comment by blasten** [comment]
Thanks!
