### ISSUE TITLE
[0.9] binding allows dot notation but not bracket lookup

### ISSUE THREAD

**Issue by mcarey1590** [Polymer/polymer#1504]
I can bind a variable inside the template using object.property but not object[property]

**Comment by arthurevans** [comment]
I think this one belongs to @kevinpschaaf or maybe @sorvell.

**Comment by kevinpschaaf** [comment]
No near-term plans to support this.  Polymer 0.5 had a complex expression parser used for bindings that we have eliminated for simplicity and performance.  There are alternate patterns you can use today to achieve similar results that just require you to be more explicit.

If `property` in your example is actually static, right now just use `object.property` rather than `object['property']`.

If you wish `property` to be a string-typed variable to dereference on `object` and have the result re-evaluated when either `object` or `property` change, you can do this:

`{{computeObjectProperty(object, property)}}`

```js
computeObjectProperty: function(object, property) {
  return object && object[property];
}
```

**Comment by kevinpschaaf** [comment]
Closing, no immediate plans to add more complex expression binding.

**Comment by kevinpschaaf** [comment]
There is an experimental 1.0-compatible opt-in version of PolymerExpressions on a branch here: https://github.com/Polymer/polymer-expressions/tree/2.0-preview

There are no plans to incorporate this into the core library.
