### ISSUE TITLE
[0.9] hidden$="{{isHidden}}" vs hidden=$"{{isHidden}}"

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#1548]
The second one is much more easier and faster to read for humans, is it technically possible or are we talking html violation here?

hidden$="{{isHidden}}" 
hidden=$"{{isHidden}}"

**Comment by gertcuykens** [comment]
I can also live with this 
hidden="${{isHidden}}"

**Comment by gertcuykens** [comment]
hidden=${{isHidden}}

**Comment by kevinpschaaf** [comment]
The only reason we use this syntax is because IE validates and will excise any invalid attribute content (like `{{`) for certain attributes like `href` and `style` before Polymer ever gets to see it.  Using <attribute-name>$="..." is a workaround, since the attribute name becomes `href$` and is thus not validated.  It is an ergonomic compromise for cross-platform capability.

**Comment by gertcuykens** [comment]
Ok thanks for answering
