### ISSUE TITLE
Release process should have change log

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#1553]
Every time you tag new release there is no change log for it (which is true for WebComponents.js, even though it is separate now). Every time I scan all your blogs and nothing!

Now I was reading 0.8 docs, but it was just updated to 0.9. And how the hell should I know which sections changed and which are not so that I don't have to spend so much time reading everything once again?

My suggestion - create file `release-notes.md`, so that it will not rely on GitHub releases, put all anyhow significant changes there.
Format might be [like this](https://github.com/nazar-pc/CleverStyle-CMS/blob/master/release-notes.md#1402build-853-huge-leap-forward-to-the-future-websockets-and-shop-modules-added).
Keeping such `release-notes.md` up to date (I do so for [small projects](https://github.com/nazar-pc/just-backup-btrfs/blob/master/changelog.md)) or updating right before each release (I do so for bigger projects) is crucial for successful migration to new versions.

Yes, we are early adopters, we find bugs, dig into source code and even sending bug fixes back, just don't make it even more complex to use than it should be.

**Comment by arthurevans** [comment]
Is this what you're looking for?

https://www.polymer-project.org/0.9/docs/release-notes.html

**Comment by nazar-pc** [comment]
Wow, somehow I missed that. Would be nice to post that link in release tag on GitHub, also to have all such release notes in one place kept, so that it would be possible to see all release notes, since https://www.polymer-project.org/0.8/docs/release-notes.html link is not working.
BTW, do you have link like that for WebComponents.js? Would be really helpful.

**Comment by arthurevans** [comment]
Hi @nazar-pc. I like the idea of posting the link in the release tag -- I'll ask our release maestro about that.

This is the first release we've done formal release notes on the doc site, but going forward I'm planning on keeping the running release notes on the doc site. 

We don't have separate release notes for 0.5 => 0.8; because it was such a big, disruptive release, we created a migration guide. But that's guide's been updated to cover 0.5 => 0.9 to minimize the number of docs people had to read. That doc is here:

https://www.polymer-project.org/0.9/docs/migration.html

Hopefully the two docs cover most people's needs.  After 0.9, we hope to return to a more normal release cycle -- with release notes!

**Comment by nazar-pc** [comment]
Super, thanks!
