### ISSUE TITLE
dom-repeat filter/sort needs to be able to observe parent scope

### ISSUE THREAD

**Issue by mbleigh** [Polymer/polymer#1572]
Right now, the `dom-repeat` filter and sort only refire on array mutations or item subproperty changes with the `observe` attribute. However this ignores a very common use case for filtering and sorting: user-driven changes to filter. Imagine for instance a simple list of items with a "text search" filter:

```html
<template is="dom-repeat" filter="search">
  <span>[[item.name]]</span>
</template>

<script>
Polymer({
  search: function(item) {
    return item.name.toLowerCase().indexOf(this.q.toLowerCase()) >= 0;
  }
});
</script>
```

In this scenario, there is no way to make the template re-stamp when an *external* parameter changes (e.g. `q` in the example).

**Comment by mbleigh** [comment]
Note that because of this limitation I am currently manually calling through to the private `_render()` method in my app code. I didn't see any other way to achieve the desired effect.

**Comment by kevinpschaaf** [comment]
Since `dom-repeat` isn't bound to that data (`q` in your example), it won't receive notifications for changes to it (as opposed to `items`, which is why the convenience `observe` property is possible).

For now, the pattern will be for external dependencies of sort/filter, the user will need to observe those properties and call `render()` manually to refresh the list.  This doesn't quite work right now (as you noted), but I'll push a fix this morning to make that go.

**Comment by euclid1990** [comment]
@kevinpschaaf How to call render from below code:

```
<template id="resultList" is="dom-repeat" items="{{ schedules }}" filter="filterRoom" as="schedule" index-as="scheduleId">
...
</template>
```
???

**Comment by kevinpschaaf** [comment]
@euclid1990 

```
this.$.resultList.render();
```

Call that after you change any external dependencies to the `filterRoom` function.
