### ISSUE TITLE
[0.9] Documentation issue (unbind & dispose)

### ISSUE THREAD

**Issue by cedric-marcone** [Polymer/polymer#1607]
I couldn't find anything in the documentation regarding unbinding and disposal policies when an element is detached.

In 0.5 we could play with `preventDispose` and `cancelUnbindAll`.

Any hints on the correct migration path ?

**Comment by kevinpschaaf** [comment]
Due to the difference in binding systems, `preventDispose` and `cancelUnbindAll` are no longer relevant or necessary.  Detaching an element from the DOM doesn't detach any binding connections with that element's local DOM scope like it did in 0.5.

Note that in Polymer 1.0, we currently don't support the dynamic addition or removal of elements that carry bindings to their host; for any elements with bindings in a template, it is assumed that those elements are static in the template and will not be dynamically removed.  The exceptions are when using `dom-repeat` and `dom-if`, which allow for dynamic stamping of nested templates that can access their host scope and avoid leaking references related to bindings when the elements are removed.
