### ISSUE TITLE
[0.9.1, 0.9.2] Polymer.dom().appendChild() no longer working

### ISSUE THREAD

**Issue by hawkett** [Polymer/polymer#1612]
* [0.9.0 working jsbin](http://jsbin.com/baqelakafi/2/edit?html,output)
* [0.9.2 failing jsbin](http://jsbin.com/ziluhucoke/1/edit?html,output)

Change was introduced in 0.9.1

**Comment by sorvell** [comment]
That this worked in 0.9.0 was actually a bug. The behavior you're seeing now is correct. 

The `iron-icon` element is being added as a child to `dynamic-add`, but `dynamic-add` has a local DOM which renders in place of its children. In order to distribute/render children, add an insertion point (`<content>`) to `dynamic-add` like this:

http://jsbin.com/zodefo/1/edit?html,output
