### ISSUE TITLE
Use consistent name for bower_components folder

### ISSUE THREAD

**Issue by lifeelement** [Polymer/polymer#1651]
"Bower adds a bower_components/ folder in the root of your project and fills it with Polymer and its dependencies."

NO it does not. Running "bower install --save Polymer/polymer#^1.0.0" creates a "components" folder that contains directories "polymer" and "webcomponentsjs". Please destroy any mentions of bower_components in your documentation as it's generating high confusion.

ref: https://www.polymer-project.org/1.0/docs/start/getting-the-code.html

**Comment by SmokyBob** [comment]
I think you have an old version of bower, or some configuration on your local install that creates the `components` folder instead of `bower_components`.

if you look at the (bower site)[http://bower.io/] the folder is supposed to be `bower_components`

**Comment by lifeelement** [comment]
From the sample project 0.5, it was indeed configured to use components
instead of bower_components.

**Comment by kevinpschaaf** [comment]
This is a bower nuance, not a Polymer nuance.

Bower will by _default_ install into `bower_components`, and since it's the default most Bower users get.

One can override the directory bower installs components into by placing a `.bowerrc` file with a `directory` field in the project root: http://bower.io/docs/config/#directory.  The sample project you are referring to likely did that.

@arthurevans Can you make sure we're consistent in our 1.0 docs?

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#1161
