### ISSUE TITLE
when i pass params in element is not readable inside the element 

### ISSUE THREAD

**Issue by arezki1990** [Polymer/polymer#1669]
i have ceate this element 
  <template>
  <paper-drawer-panel responsiveWidth="8000px" id="paperDrawerPanel" forceNarrow="true">
      <div drawer>
         <paper-header-panel class="blue">
       
      <paper-toolbar class="medium-tall">
        <div>her serch par</div>
        <div title class="bottom">Bottom Title</div>
      </paper-toolbar>
        
        <div class="menu">
          
        </div>
      </paper-header-panel>
      </div>
      <div main>
       <paper-header-panel class="blue">
       
      <paper-toolbar id="header" class="medium-tall">
        <div>her serch par</div>
        <div title class="bottom">Bottom Title</div>
      </paper-toolbar> 
        
        <div class="content">
          
        </div>
      </paper-header-panel>
      </div>
    </paper-drawer-panel>

  </template>

</dom-module>
<script>

  Polymer({
    is: 'sidebar-layout',
    properties: {
      hasSubHeader:{
        type:Boolean,
        notify: true,
        value:false

      }
  
    },
    ready:function(){
      console.log(this.$.paperDrawerPanel)  ;  
      this.$.paperDrawerPanel.closeDrawer()

    }
  });

</script>

but when i pass the params hasSubHeader doesn't change inside the element
<sidebar-layout hasSubHeader="true"></sidebar-layout>

**Comment by kevinpschaaf** [comment]
You filed this issue under the Polymer core issue tracker;  it sounds like you're running into a problem in using elements built with Polymer (but it's not clear what it is; `hasSubHeader` isn't an API I'm familiar with).  Can you please file this issue under the repo for the element you are having trouble with, and include more information about how to repro your issue and what the expected behavior is?

Thanks.

**Comment by arezki1990** [comment]
thanks for replaying , the problem was in data binding didn't support string concatenating
