### ISSUE TITLE
Need to parameterize path to fonts

### ISSUE THREAD

**Issue by RNCRyan** [Polymer/polymer#1674]
Hey,

I'm building a new app at my current employer with Apache Cordova and Polymer.  This is being built in Visual Studio 2015, with the goal of deploying it to Android, iOS, and Windows.  Exciting stuff.

Except the path to fonts isn't parameterized in the core Polymer controls, and, once installed on a mobile device, my packaged app is failing to retrieve fonts successfully (since it's trying to retrieve the fonts under file://....; not to mention it's trying to make a call over-the-wire, which I want to avoid by serving these fonts locally).  Would it be possible to parameterize the path to fonts in the polymer controls?  I'd *really* like to avoid having to diverge from the trunk on the polymer controls.

Thanks!  I'm very open to alternatives if there's a better way of solving this problem....

Ryan

**Comment by kevin-smets** [comment]
I'm trying to do the same, but wrapping everything inside [Electron](http://electron.atom.io/). So everything is served from `file://`, this makes the font loading impossible. Plus, having an online dependency is weird for an application... Obviously, I can serve everything from a server, but this is a solution I would like to avoid when I distibute this as a standalone application.

**Comment by kevinpschaaf** [comment]
Right now, the Roboto font is loaded via the `paper-styles` element.  We'll move this issue there.

There isn't a great way to parameterize the URL used by that stylesheet, since it's not maintained by Polymer (and we probably wouldn't want to fork _that_).

However, we can probably just fall back to the solution we had in 0.5, which was to separate `font-roboto` into a separate component imported into `paper-styles`, so that the end user can just swap in a local-URL based `font-roboto` implementation for deployment.  To be clear, you can do this now, but you'd be overwriting [a file](https://github.com/PolymerElements/paper-styles/blob/master/typography.html#L11) that contains more than just the font, whereas the 0.5 `font-roboto` file _only_ contained [this one thing](https://github.com/Polymer/font-roboto/blob/master/roboto.html#L9).

**Comment by RNCRyan** [comment]
Sounds good; and I agree that sounds like a workable solution.  Easy enough to do a pre-build copy on that one file.  Thanks!

**Comment by tjsavage** [comment]
auto-moving this issue to PolymerElements/paper-styles#33 and closing this one
