### ISSUE TITLE
! operator doesn't apply to inverse boolean values in bindings upward?

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer#1715]
Jsbin: http://jsbin.com/coxucaduyu/1/edit?html,console,output

Given:

    <x-checkbox is-checked="{{!hostChecked}}">

I would expect that if the checkbox sets `this.isChecked = true` then `hostChecked` should be set to false, but this doesn't seem to be the case. Is the `!` operator in bindings not meant to perform this inverse, or am I doing something dumb in the jsbin?

**Comment by TimvdLippe** [comment]
I started to work on this issue and got it working. The code is available [here](https://github.com/TimvdLippe/polymer/tree/negated-notifying-bindings).

However, the test-suite `unit/notify-path` completely breaks as a result of these changes. This is because of the removed [`!effect.parts[0].negate`](https://github.com/TimvdLippe/polymer/commit/782146c48e37debeebaae428634d73206ad670b6#diff-2b35a2bb7d7a78a65bc1e4c391ac1793L21). The notify-path suite is inserting numbers into `obj.value` which is then negated. Previously the value would be left untouched (as described in this issue) but now the value is correctly negated. Therefore a lot of assertions break in the test suite.

Debugging this issue is rather hard, as Mocha completely bails out on failed assertions with the element. In my eyes, the negation of the value should not be performed on a number and the test suite should be changed accordingly.

If the negated `obj.value` [here](https://github.com/Polymer/polymer/blob/master/test/unit/notify-path-elements.html#L17) is removed, only the negation test fails. This test however can be performed on a different element that also has a negated binding, but on a boolean attribute. @kevinpschaaf WDYT?
