### ISSUE TITLE
Custom CSS properties specificity

### ISSUE THREAD

**Issue by bogdan-nourescu** [Polymer/polymer#1720]
I tried to use iron-icon that is using custom css properties that adds 2 classes on my element:
"x-scope iron-icon-0".
My element already has a class "big", but the 2 added classes get added after my defined class, so they have greater priority. (the classes should be added before, not after,  my defined classes)
Example:

```
<iron-icon icon="" class="big"></iron-icon>
<style>
.big{
        width:100px;
        height:100px;
    }
</style>
```

The above code doesn't apply my style. There are 2 ways to make it work: add !important, or add the tag name before the class.

**Comment by kevinpschaaf** [comment]
`iron-icon` exposes a [custom-property API](https://github.com/PolymerElements/iron-icon/blob/master/iron-icon.html#L66) for sizing the icon, so you can do something like this in an element's stylesheet (or in a `<style is="custom-style">` from the main document:

```
:root {
  --iron-icon-width: 64px;
  --iron-icon-height: 64px;
}
```

Since custom properties inherit, you don't need to define this everywhere you use an icon, you can define it at the top of a tree and it will apply to all icons below that point.

Since `iron-icon` exposes an explicit inheriting custom property API for defining height/width, you should use these rather than `height` and `width` properties directly.

The documentation for `iron-icon` will be updated to reflect this here:
https://github.com/PolymerElements/iron-icon/pull/22

**Comment by sorvell** [comment]
Using the custom properties is preferred, but we may still be able to address this at the shim level. That would better match the behavior of native custom properties.

**Comment by TimvdLippe** [comment]
This appears to be fixed in Polymer 2: http://jsbin.com/nepawes/edit?html,console,output Classes are now appended instead of prepended.
