### ISSUE TITLE
[1.0] Track gestures sometimes stops text selection

### ISSUE THREAD

**Issue by wuxiaoying** [Polymer/polymer#1726]
The track gesture can stop text selection. Dragging and selecting ends up either not selecting at all or only selecting one character. I first saw it happening with paper-drawer-panel (it has a track listener). 

My guess is that e.preventDefault() in gestures.html (under the track gesture) is causing this.

```
 var movefn = function movefn(e) {
        var x = e.clientX, y = e.clientY;
        if (self.hasMovedEnough(x, y)) {
          // first move is 'start', subsequent moves are 'move', mouseup is 'end'
          self.info.state = self.info.started ? (e.type === 'mouseup' ? 'end' : 'track') : 'start';
          self.info.addMove({x: x, y: y});
          self.fire(t, e);
          e.preventDefault();
          self.info.started = true;
        }
      };
```

Also, I usually see it happening on Chrome, but not IE/Firefox.

**Comment by atotic** [comment]
I also got bitten by preventDefault(). It prevented tracked elements from scrolling, which was unexpected. Suggestion: let track event consumers call preventDefault() if needed.

**Comment by jfrazzano** [comment]
You have the hover function that will allow a second api for specific selection of targets desired.  The helper method enabled by the drag start is much more useful than I first could have imagined.  I really over looked it.  But it can help a ton with above.

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction for us to be able to debug and potentially fix.

Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
