### ISSUE TITLE
[1.0] hidden$ should make use of "display: none !important;"

### ISSUE THREAD

**Issue by lambertsteven** [Polymer/polymer#1748]
If you use `hidden$` on an element that already has a it's CSS display property set, it won't be hidden. `hidden$` should make use of `display: none !important` to override any display property already set on the element.

**Comment by dzhioev** [comment]
@lambertsteven, that is how browsers implement 'hidden' attribute. In my opinion such behavior is wrong, but Blink devs think it's fine. See http://crbug.com/179220
Polymer has nothing to do with this problem.

**Comment by lambertsteven** [comment]
If that's the case, then I think advocating the use of `hidden$` in place of `dom-if` for elements that hide/show often in the [Polymer docs](https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-if) is misleading. No browser correctly handles the hidden attribute when a class on the element gives it a display property, so there is no reason to use it if it doesn't work and I have to provide my own override. I might as well just conditionally add a class and style it to `display: none !important`.

**Comment by kevinpschaaf** [comment]
Think of `hidden` as a convenience attribute that you can use rather than writing your own `display: none` rule for each scope.

Because in Shadow(/Shady) DOM, you are in full control of your element's CSS scope, the only way for `hidden` to be overridden is by a class that _you_ the author put on your element's children, and in that case it may not be appropriate to use `hidden`.

As mentioned, we aren't really interested in differing from the spec for `hidden` here.
