### ISSUE TITLE
The Shadows sucks

### ISSUE THREAD

**Issue by eusouomatt** [Polymer/polymer#1788]
Boys, what a mess those shadows. No good. At all.

**Comment by vsimonian** [comment]
If you're referring to the Material Design shadows displayed on paper elements, the best repo to provide feedback at would be the [paper-styles repo](https://github.com/PolymerElements/paper-styles), in which the shadow styles are defined.

I'd recommend leaving some more specific feedback about *what exactly* it is about the shadows that make them 'a mess,' so to speak; otherwise it leaves it up to everyone's interpretation. :smile:

**Comment by arthurvr** [comment]
Yeah, let's close this ticket.

Everybody is free to use the styling they want with polymer, and this is how the material design spec wants it. You like it or not, that's just an opinion. 

If you was referring to the shadow DOM instead, that's how web components work and I honestly don't see how that would suck.

**Comment by ebidel** [comment]
Boys and gals!   :bulb: + :closed_umbrella:  = :black_circle:
