### ISSUE TITLE
Registration failed: A type with that name is already registered

### ISSUE THREAD

**Issue by Kivol** [Polymer/polymer#1808]
I made a package of my own custom elements info a single library and I'm importing it into my project. The library uses ````paper-ripple```` element and my project uses ````paper-button```` element, which depends on ````paper-ripple````. Then the script stops with this message:

    Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'paper-ripple'. A type with that name is already registered.

While I know it's defined on w3c document that the script has to be stopped with NotSupportedError when trying to register the existing element, I still think it's quite inconvenient to manually manage the dependencies to the ````paper-*````(or ````iron-*````) elements and polymer needs some walkthrough for this type of error.

**Comment by Kivol** [comment]
Any update or suggestion on this?

**Comment by kevinpschaaf** [comment]
HTML Imports de-dupe based on URL (this is a part of the spec that the authors intend to address at some point), and so you must take care to not import the same resources from multiple locations.  We typically avoid this by bower installing all dependencies into a common project and recommending users build/vulcanize their project dependencies, rather than importing pre-vulcanized dependencies.

We are building a linter to help catch common errors, and we'll consider adding warning support to try and catch this case.

**Comment by azakus** [comment]
The [polylint](https://github.com/polymerlabs/polylint) tool will tell you if you have duplicate element definitions, and what imports were causing that.

**Comment by MajorBreakfast** [comment]
I accidentally capitalized "Polymer" in my URL and it worked for a while until I encountered this error because I currently work on Windows. So, make sure you don't do that :)

**Comment by raffaeu** [comment]
@MajorBreakfast  oh my god, I had the same problem after I executed a bower update and somehow my editor Capitalized all URLs containing /polymer/polymer.html into /Polymer/polymer.html
I was going mad ... 
Thanks again I would never figure it out this one 😆 🤣
