### ISSUE TITLE
key/value iteration support for template dom-repeat

### ISSUE THREAD

**Issue by tam4s** [Polymer/polymer#1846]
Currently it's very clumsy to iterate over JavaScript Objects:

http://stackoverflow.com/questions/30781500/how-can-i-iterate-over-a-js-objects-key-values-in-polymer-1-0

It should be as simple as 

    <template is="dom-repeat" items="[[myobj]]">
        <span>[[item.key]]</span>: <span>[[item.value]]</span>
    </template>

**Comment by arodic** [comment]
@tam4s the solution from stack overflow will not observe the object changes so any change you make to the object after binding will not be reflected in dom-repeat.

The need for this feature has been expressed numerous times [here](https://github.com/Polymer/polymer-expressions/issues/11), [here](https://github.com/Polymer/TemplateBinding/issues/116), [here](https://github.com/Polymer/polymer/issues/1062) and ultimately, the issue was moved [here](https://github.com/Polymer/polymer/issues/1385) by @kevinpschaaf to be implemented in 1.0.

**Comment by kevinpschaaf** [comment]
Closing, as the feature request is covered by #1385 and will be tracked there.
