### ISSUE TITLE
Polymer icon set not scaling with size

### ISSUE THREAD

**Issue by ManojAMK** [Polymer/polymer#1881]
![polymer_not_scaling_icons](https://cloud.githubusercontent.com/assets/11471878/8174750/38ad4266-13fe-11e5-9a07-1b31994a8a4f.png)

As you can check the screenshot of the URL: [**iron-iconset**](https://elements.polymer-project.org/elements/iron-iconset?active=iron-iconset&view=demo:demo/index.html) I am not sure if the icons are meant to be scaled with ratio like 2x, 3x such as in Fontawesome, Gylphicons. Current icon set looks distorted.

**Comment by arthurevans** [comment]
This is not a demo of the icons, it's a demo of how you can create a custom iconset (in this case using PNG files): 

https://github.com/PolymerElements/iron-iconset/blob/master/demo/index.html

You're probably looking for iron-icons. The iron-icons demo is missing from the left navigation due to a catalog bug, but you can find it here:

https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html

These icons are SVG, so they scale smoothly.
