### ISSUE TITLE
If I set element property before component registered I cannot change it anymore

### ISSUE THREAD

**Issue by cwayfinder** [Polymer/polymer#1882]
If we create an element and set some properties previously to being initialized like in the following example:

```
<script>
  var selector = document.createElement("iron-selector");
  selector.selected = 1;
  selector.setAttribute('id', 'selector');
  selector.innerHTML = "<div>Item 1</div><div>Item 2</div><div>Item 3</div>";
  document.body.appendChild(selector);

  Polymer.Base.importHref('bower_components/iron-selector/iron-selector.html');

  console.log('hasOwnProperty', selector.hasOwnProperty('selected'));
</script>
```
then in console  line `selector.selected = 2;`does nothing.

Cause: own property in the selector overrides the property with setter and getter in behavior (`IronSelectableBehavior`).

The same issue happens with many other elements as well.

**Comment by cwayfinder** [comment]
Polymer creates setter and getter in the `accessors.html` [line #154](https://github.com/Polymer/polymer/blob/master/src/lib/bind/accessors.html#L154)

**Comment by sorvell** [comment]
This behavior is by design. When element declarations are loaded lazily via HTML imports, it's necessary to wait for the declarations to register and  for existing elements to upgrade. In general, the callback method in `Polymer.Base.importHref` can be used as a ready signal. For example, here's a working version of the code posted above:

```
Polymer.Base.importHref('bower_components/iron-selector/iron-selector.html', function() {
  var selector = document.createElement("iron-selector");
  selector.selected = 1;
  selector.setAttribute('id', 'selector');
  selector.innerHTML = "<div>Item 1</div><div>Item 2</div><div>Item 3</div>";
  document.body.appendChild(selector);
});
```

While it's true that Polymer could attempt to save and re-apply property values that were set prior to element registration/upgrade, this could *not* be done for methods, and we've chosen instead to avoid trying to sugar over the general issue that elements can exist in 2 states: un-upgraded and upgraded. User code should be written such that it deals with this fact.

**Comment by manolo** [comment]
Although I might agree about not running accessors with previous property values, I think it should not prevent the accessor not working at all if the property was set, because the component remains unusable if the user has set some property previously. Thus imho, when accessors are configured, if not reapplied it should delete previous property values, so as new accessors are usable.
