### ISSUE TITLE
Exception when accessing a property in the created callback (Polymer 1.0)

### ISSUE THREAD

**Issue by timeu** [Polymer/polymer#1886]
I am not sure if this is by desig, but when accessing a `property` inside the `created` callback, an Exception is thrown. See here: http://jsbin.com/decayi/edit?html,console,output

I guess this is because the `__data__` structure hasn't been initialized at that time. Wrapping the property access inside a `async` call fixes the issue. 

If this behavior is by design, at least the documentation should highlight/mention this (I couldn't find anything in the docs)

**Comment by robrez** [comment]
I did find this bit in the migration guide:
>If value is a function, the function is invoked during the configuration phase (after the created callback and before ready) and the return value is used as the value of the property.

https://www.polymer-project.org/1.0/docs/migration.html#default-values

I don't know if that's any hint as to what you're seeing since your property does not use a value function.

I'm not sure if property initialization is considered part of local-dom init. If so, then this states that it won't be available in `created`:

https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#initialization-order

**Comment by timeu** [comment]
Unfortunately the behavior is the same, even if there is a default value (see the updated jsbin in the initial post).

**Comment by kevinpschaaf** [comment]
This is by design.  Since Polymer's binding system uses accessors set up at _prototype time_ that access nodes in the local DOM, we do not support setting properties in `created`, which is called _before_ the local DOM is stamped.  As such, there is very little useful work that can be done in `created` (at this point we're mostly only supporting it because it's a native CE callback, and users might have esoteric legitimate uses for it).  

Note that `ready` is generally a better callback from which you can safely interact with your local DOM elements and set properties, however it's almost always bad form to do any one-time setup in `created` or `ready`, since we want elements to dynamically configurable and not have one-time conditional state locked in when created; as such, it's almost always better to use property observers to setup (or reset) state.

As far as the confusion about `created` limitations I've updated the docs here to be a little more clear about it, and we'll work on getting this clarified on the polymer-project.org docs as well.
https://github.com/Polymer/polymer/blob/master/PRIMER.md#basic-callbacks

**Comment by arthurevans** [comment]
The docs section has been improved, but I missed this bug when I was updating it. Kevin's updates to the primer have more detail on created that we should upstream into the docs.
