### ISSUE TITLE
Default to Shadow DOM if browser supports it

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#1887]
Currently, Polymer 1.0 defaults to Shady DOM. If the browser supports Shadow DOM (faster + benefits), we should consider using it by default. 

This gets a bit tricky for users since they'll be targeting SD and would then have to test in other browsers to see polyfill behavior...but that's no different than 0.5 days. It also helps developers target the native API when it becomes available in other browsers. In 1.0, we've moved to a test in shady dom first, then native SD with `?dom=shadow` :\

**Comment by indolering** [comment]
I recently ran into an issue that stemmed from not using the Shadow DOM polyfill.  When I switched over the majority of my styling was broken.  I discussed this with ktiedt on Slack and s/he has seen similar issues.  

Which is to say that I think moving to the Shadow DOM automatically has the potential to break a lot of code and should instead be tied to a major/minor point release. 

Perhaps there are ways to catch these issues early through the WCT or static analysis.  The documentation could certainly do a better job of warning developers.  It's also confusing that Polymer is still handling polyfill functionality instead of WebComponents.js, I had assumed that I had switched from `webcomponents-lite.js` to `webcomponents.js` I was using the full-blown shim.

**Comment by ebidel** [comment]
@indolering that should be the case. webcomponents.js will give you the full shadow dom polyfill.

I agree with you about breaking users. I REALLY wish we had done this at the beginning of Shady DOM. When other browsers ship shadow dom (they're all implementing it as we speak), we going to see a lot of apps try to use it. However, they will most certainly have styling issues because folks have relied on the behavior of shady dom instead of programming to the native stuff.

We saw this when Chrome first landed native Shadow DOM. A lot of people had incorrectly written their styles against the polyfill instead of authoring it against the native API. As such, there was a couple of months of pain.

**Comment by indolering** [comment]
> @indolering that should be the case. webcomponents.js will give you the full shadow dom polyfill.

But I have to set Polymer to `window.Polymer.dom = 'shadow';` to turn it on....

**Comment by ebidel** [comment]
Interesting. That's a change then that I wasn't aware of.

**Comment by indolering** [comment]
@ebidel This JSBin won't redirect mouse input appropriately if you comment out the `window.Polymer.dom = 'shadow'` section.

**Comment by indolering** [comment]
@ebidel any movement on this?  This is semi-blocking my use of a CSP header because it requires another round-trip to the server to fetch a 2-line file before rendering can occur.  Should I create a new ticket for the dependency on  `window.Polymer.dom = 'shadow'` somewhere and if so where?

**Comment by ebidel** [comment]
@kevinpschaaf @azakus 

We've talked about enabling shadow dom once it's in 1-2 other browsers. Realistically, I dont think we can make it the default again...yet :)

I may have been mistake about the the full polyfill. Choosing between shady and shadow is at the polymer level, but it would be cool to have native SD be the default if you're using the full polyfill.

**Comment by azakus** [comment]
We will revisit this later this year, and hopefully more browsers will support native ShadowDOM by then!

**Comment by ebidel** [comment]
@abdonrd . use the thumbs up on the top comment :)

**Comment by TimvdLippe** [comment]
The default for Polymer 2 is shadow dom: https://github.com/Polymer/polymer/blob/master/lib/utils/settings.html#L25

**Comment by TimvdLippe** [comment]
Closing per above comment.
