### ISSUE TITLE
Some elements duplicate markup at template <content> when in an Angular ng-repeat

### ISSUE THREAD

**Issue by rgthree** [Polymer/polymer#1890]
First, Polymer v0.5 works fine so I'm assuming this a Polymer issue since it has regressed.

With some paper elements (and, likely a broader issue) some markups I duplicated when inside of an Angular `ng-repeat`.

```
<!-- This when written: -->
<paper-button ng-click="ngCtrl.doSomething()" raised>{{ngCtrl.btnLabel}}</paper-button>

<!-- Should be in the DOM like: -->
<paper-button role="button" tabindex="0" aria-pressed="false" aria-disabled="false" class="x-scope paper-button-0 ng-scope x-scope paper-button-0" pressed="">
  <paper-ripple class="style-scope paper-button" animating="">
    <div id="background" class="style-scope paper-ripple" style="opacity: 0; background-color: rgb(0, 0, 0);"></div>
    <div id="waves" class="style-scope paper-ripple"><div class="wave-container style-scope paper-ripple" style="top: -52.5390625px; left: 0px; width: 185.828125px; height: 185.828125px; transform: translate3d(15.3046875px, 1.25px, 0px);"><div class="wave style-scope paper-ripple" style="opacity: 0.25; transform: scale3d(1.2929157262899, 1.2929157262899, 1); background-color: rgb(0, 0, 0);"></div></div></div>
  </paper-ripple>
  <paper-material id="material" class="content style-scope paper-button x-scope paper-material-0" animated="" elevation="0">
    The button label
  </paper-material>
</paper-button>

<!-- But is actually like: -->
<paper-button role="button" tabindex="0" aria-pressed="false" aria-disabled="false" class="x-scope paper-button-0 ng-scope x-scope paper-button-0" pressed="">
  <paper-ripple class="style-scope paper-button" animating="">
    <div id="background" class="style-scope paper-ripple" style="opacity: 0; background-color: rgb(0, 0, 0);"></div>
    <div id="waves" class="style-scope paper-ripple"><div class="wave-container style-scope paper-ripple" style="top: -52.5390625px; left: 0px; width: 185.828125px; height: 185.828125px; transform: translate3d(15.3046875px, 1.25px, 0px);"><div class="wave style-scope paper-ripple" style="opacity: 0.25; transform: scale3d(1.2929157262899, 1.2929157262899, 1); background-color: rgb(0, 0, 0);"></div></div></div>
  </paper-ripple>
  <paper-material id="material" class="content style-scope paper-button x-scope paper-material-0" animated="" elevation="0">
    The button label
    <paper-ripple class="style-scope paper-button" animating="">
      <div id="background" class="style-scope paper-ripple" style="opacity: 0; background-color: rgb(0, 0, 0);"></div>
      <div id="waves" class="style-scope paper-ripple"><div class="wave-container style-scope paper-ripple" style="top: -52.5390625px; left: 0px; width: 185.828125px; height: 185.828125px; transform: translate3d(15.3046875px, 1.25px, 0px);"><div class="wave style-scope paper-ripple" style="opacity: 0.25; transform: scale3d(1.30811213631653, 1.30811213631653, 1); background-color: rgb(0, 0, 0);"></div></div></div>
    </paper-ripple>
    <paper-material id="material" class="content style-scope paper-button x-scope paper-material-0 ng-binding x-scope paper-material-0" animated="" elevation="0">
      {{ngCtrl.btnLabel}}
    </paper-material>
  </paper-material>
</paper-button>
```

You can see above that, in addition to having the correctly bound label from angular, the entire button template is duplicated again at that spot. This happens without any angular binding as well, simply being in an Angular `ng-repeat` does it.

There isn't a good way I could find to jsbin/fiddle with Polymer, but here is it happening with `paper-radio` and `paper-button`: http://output.jsbin.com/najohe/1

**Comment by sorvell** [comment]
This behavior is a result of Polymer's Shady DOM implementation. We're working on ways to improve these issues. Here's an example of Polymer 1.0 and Angular 1 working together:

http://jsbin.com/bezomequja/edit?html,output

#### More Info

Out of the box to perform dom manipulation with Polymer, the [Polymer.dom](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html) api must be used. Shady DOM is a shim for the Shadow DOM web platform feature which is currently implemented only in Chrome. You can read more about the motivation and reasoning behind [Shady DOM here](https://www.polymer-project.org/1.0/articles/shadydom.html).

Of course, other frameworks like Angular don't know about Shady DOM, and there are some issues with composition between Angular and Polymer 1.0. We're working on ways to improve support for using Polymer 1.0 with other major frameworks.  Our working strategy is to provide enough basic dom compatibility to facility interoperability. We have an experimental HTMLImport that can be loaded with Polymer to enhance interoperability (used in the code example above).

We encourage you to experiment with this an give us feedback. It's also possible to turn on native Shadow DOM support in Polymer to address these issues where Shadow DOM is supported. You can also use the Shadow DOM polyfill to support other browsers; however, we don't recommend this for production use since the polyfill's performance is sub-optimal.

**Comment by M0nter0** [comment]
I'm migration from 0.5 to 1.0. In order to solve the same problem that mention @rgthree I'm using this experimental dom-patch. It's working fine in a basic environment as you can check in this [stack overflow question](http://stackoverflow.com/questions/31646460/custom-element-duplicates-content-inside-ng-repeat) related to this issue.

But when I import the patch-dom experimental, I'm receiving several errors thrown at (_atEndOfMicrotask function of async.html)[https://github.com/Polymer/polymer/blob/master/src/lib/async.html#L57] without too much info. Errors I'm getting are:

- Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
- Uncaught TypeError: Illegal invocation

And also from [_ready function at ready.html ](https://github.com/Polymer/polymer/blob/master/src/mini/ready.html#L106)

- this._afterClientsReady is not a function

I'm trying to isolate them, but is being difficult.

**Comment by sorvell** [comment]
If you can stand up a basic repro at a public url, we'd be happy to take a look.
