### ISSUE TITLE
TypeError on BlackBerry 10 browser

### ISSUE THREAD

**Issue by BojanKogoj** [Polymer/polymer#1904]
On https://elements.polymer-project.org/

throws in console (found through web inspector):

```
TypeError: undefined is not an object (evaluating 'this.ripples.forEach') 
[native code]:1
    dispatchEvent
    [native code]:1
    (anonymous function)        webcomponents.min.js:10
    n        webcomponents.min.js:10
    r        webcomponents.min.js:10
    dispatchEvent        [native code]:1
    parseImport        webcomponents.min.js:10
    parseLink        webcomponents.min.js:10
    parse        webcomponents.min.js:10
    parseNext        webcomponents.min.js:10
    r        webcomponents.min.js:10
```

Other sites work. Tested on BlackBerry 10.3.1 and 10.3.2

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with Polymer 2/3 for us to be able to debug and potentially fix. Polymer 2/3 fixes a large amount of issues, probably including this one as well.

Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with Polymer 2/3.  Thank you!
