### ISSUE TITLE
`reflectToAttribute` on a List or Map doesn't always update

### ISSUE THREAD

**Issue by jakemac53** [Polymer/polymer#1939]
If  you set a sub-property of a map, or call one of the list apis, then the attribute does not update. It only updates if you re-set the entire list or map. Example below:

```js
<script>
  Polymer({
    is: 'my-element',
    properties: {
      myMap: {
        type: Object,
        value: function() { return {foo: 'bar'}; },
        reflectToAttribute: true
      },
      myList: {
        type: Array,
        value: function() { return [1]; },
        reflectToAttribute: true
      }
    },
    ready: function() {
      console.log(this.attributes['my-map']);
      this.set('myMap.baz', 'bar');
      console.log(this.attributes['my-map']);

      console.log(this.attributes['my-list']);
      this.push('myList', 2);
      console.log(this.attributes['my-list']);
    }
  });
</script>
<my-element></my-element>
```

**Comment by kevinpschaaf** [comment]
The current behavior is as intended, and we don't plan on making this "more" correct.  Attributes generally should only be used for statically configuring markup, rather than for runtime data-passing, as the serialization/deserialization cost is much more expensive than passing data as JS objects (aka property binding).  As such, that we include array/object deserialization at all is somewhat dubious, and we've considered removing it.

That said, you can accomplish this manually as follows:

```js
  Polymer({
    is: 'my-element',
    properties: {
      myMap: {
        type: Object,
        value: function() { return {foo: 'bar'}; },
      }
    },
    observers: [
      'reflectObject(myMap.*)'
    ],
    reflectObject: function(change) {
      this.setAttribute('my-map', JSON.stringify(change.base));
    }
```

**Comment by jakemac53** [comment]
Ok, fair enough. I also can't think of a use case for this, and would be totally fine with the feature being dropped entirely :). I just ran across this when writing tests for the polymer dart version.
