### ISSUE TITLE
Scoped style nth-child doesn't work on specific syntax

### ISSUE THREAD

**Issue by arnellebalane** [Polymer/polymer#1956]
Consider a Polymer custom element with a scoped style containing the following selector:

```
:host:nth-child(2n) {
    ...
}
```

This works as expected, as well as subsitituting `2n` with `even` and `odd`. But when I use `2n+1`, it doesn't work anymore. I tried out other values for it and noticed that it doesn't work when you add the `+b` part (syntax: `:nth-child(an+b)`).

Another thing that I tried is to manually change the selector within DevTools. So I used `:host:nth-child(2n)` first, which works. And then from within the styles section in DevTools, I manually changed the selector to `:host:nth-child(2n+1)`, and it works correctly.

**Comment by cdata** [comment]
Just confirming that this is a problem. The `+` and `-` in the expression seem to get scoped (in error) by ShadyDOM. For example, `:nth-child(4n - 1)` becomes `.scope:nth-child(4n -.scope 1)`

**Comment by cdata** [comment]
I can also confirm that a workaround is to remove the space between the `-` and the number. E.g., `:nth-child(4n - 1) => :nth-child(4n -1)`.

**Comment by TimvdLippe** [comment]
Hm, it seems that `:host:nth-child(2n)` now no longer works: http://jsbin.com/pecejim/edit?html,console,output As this is using native shadow dom, I am not sure if native shadow dom allows these kind of selectors on `:host`.

**Comment by Westbrook** [comment]
You should be able to get this to work with `:host(:nth-child(2n - 1))` in both native shadow DOM and shady DOM, a la: http://jsbin.com/ravavudosu/1/edit?html,console,output which I can load in both Chrome and Firefox. I was always of the understanding that any selector against `:host`, complex or otherwise, require that syntax as per: https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-the-host-element. Is that not so?

If this is still occurring against a 1.x code base, it seems you need to be a little more precise and use `:host(:nth-child(2n-1))`, notice the lack of spaces similar to @cdata's note, a la http://jsbin.com/detacarope/1/edit?html,console,output

**Comment by TimvdLippe** [comment]
Ah yes, http://jsbin.com/tihicatuti/edit?html,console,output is now working for me as well 👍 

This was probably an issue with shadycss, which seems to be fixed. Closing this issue. Thanks @Westbrook for the explanation.
