### ISSUE TITLE
Polymer 1.0 -Firefox initial Render Slow

### ISSUE THREAD

**Issue by safiresh** [Polymer/polymer#1957]
hi team, 
we have recently work on with polymer 1.0. we are rending slow for firefox browser with white blank page few secounds then render initial page. but other browser like safari and chrome  working well.

**Comment by nickretallack** [comment]
I have noticed this also.  When I load my page in Chrome, there is a 280ms gap between when it fetches the normal assets and when it fetches the HTML imports.  In Firefox, this gap is consistently over 1 second long.

I would assume this is because Firefox requires more polyfills for web components features, but then why would Safari perform better?

**Comment by ebidel** [comment]
Can you post a jsbin or example code? My guess is it's the unresolved
attribute that's causing the blank white page. It's meant as an easy
solution to control FOUC but maybe it isn't right for your app. Also, be
sure to vulcanize all imports so they load faster in polyfilled browsers.

**Comment by nickretallack** [comment]
I'm not using the "unresolved" attribute.

Do the elements still need to be vulcanized even if they are fully cached and no http requests happen?

**Comment by ebidel** [comment]
Vulcanizing is always a good idea for perf, esp under the polyfill.

**Comment by dhubler** [comment]
I found this when there was a a lot CSS imported in each component.  In my
case it was 90% unnec. because I didn't remove any unec. CSS.   Try
removing all css imports in components just to narrow down if it's CSS
related.

**Comment by marconi1992** [comment]
I have the same problem, the html imports are vulcanized, the head only contains the webcomponents.js and the import from the elements vulcanized. But with the firefox performance test I found several expensive tasks related with webcomponents.js and the last operation is draw. I found that the vulcanized in the the polymer web page is different, How vulcanize in this way?
![vulcanized](https://cloud.githubusercontent.com/assets/11670923/10490101/dd05f352-7264-11e5-85f2-1a53daada35d.jpg)

**Comment by ebidel** [comment]
@marconi1992 I'm not sure what you mean by vulcanized differently? Keep in mind the site is using Polymer 0.5.

Performance issues can be a number of different things, most often, specific to the app. It's useful for us to see a jsbin bin/repo of the issue. @nickretallack or @safiresh can you please provide a demo link or jsbin of the issue? Otherwise, we'll close this issue.

**Comment by marconi1992** [comment]
@ebidel sorry, I have a few days learning polymer, but now i  am working with yeoman/generator-polymer, so then the issue about vulcanized in the Polymer web page has become clear to me through this topic https://github.com/yeoman/generator-polymer#gotchas

**Comment by safiresh** [comment]
@ebidel  thanks for reply. We had vulcanized our app so now app work better no blank page getting initial time
