### ISSUE TITLE
Grey overlay in mobile Safari

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#1970]
Moved from https://github.com/PolymerElements/paper-drawer-panel/issues/75

Gesture events such as `tap` and `track` also attach a `click` and `mousedown` event handlers. This will result in a grey overlay in mobile safari.

We could remove those listeners if possible or use:
```css
-webkit-tap-highlight-color: rgba(0,0,0,0);
-webkit-touch-callout: none;
```
Ref: http://stackoverflow.com/questions/5106934/prevent-grey-overlay-on-touchstart-in-mobile-safari-webview

**Comment by frankiefu** [comment]
This is the POC fix for the issue: https://github.com/Polymer/polymer/commit/078f35892dfeb152aaf2f1da869c01a996b82d9a

**Comment by addyosmani** [comment]
@frankiefu If I understand correctly, the POC in https://github.com/Polymer/polymer/commit/078f35892dfeb152aaf2f1da869c01a996b82d9a negates the need to use the `-webkit-tap-highlight-color` workaround on body, right? We're running into this issue in PSK and might hold out for the upstream fix rather than monkey-patching in the short term.

**Comment by blasten** [comment]
@addyosmani right!
