### ISSUE TITLE
Nested templates unexpected behavior

### ISSUE THREAD

**Issue by dimshik100** [Polymer/polymer#1997]
Hi,

I have a child polymer element inside a dom-if template of a parent polymer element.

The dom-if template condition is "false" by default, when changed to "true" the inner contents are shown as expected.
When i change the condition back to "false", i expect that all the template contents will be removed.

Actual result: all the template contents except the child polymer element change to hidden.
Also (sub issue), all the hidden elements are accessible via Polymer.dom API.

i have an example that describes this issue : http://jsfiddle.net/dimshik/mprej0j4/

Thank you :)

**Comment by kevinpschaaf** [comment]
This is as-designed behavior, as described here: https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-if (read the section after the example).

If you would like to avoid the more efficient hide/reuse of DOM optimization, you can place the `restamp` attribute on `dom-if` and it will remove and re-create DOM each time it toggles.

**Comment by tsachyg** [comment]
Thanks kevinpschaaf,

good to know we can use restamp :)
though, you didn't answered us about the real issue. why does the child element is still visible?

here are steps to reproduce on the sample above (http://jsfiddle.net/dimshik/mprej0j4/):
1. click on "Show Content" button
2. click on "Hide Content" button

see that nothing happens

expected result is: child element should disappear. 

adding "restamp" solve it, but, I guess it should work also without "restamp"...

**Comment by tsachyg** [comment]
Hן @kevinpschaaf,
Please answer my question above, if this is a bug in Polymer, than let us know if it will be fixed or not. Otherwise, let us understand what are we doing wrong

**Comment by kevinpschaaf** [comment]
As mentioned in the docs I linked, by default `dom-if` _hides_ its children when `if==false`.  Since you are stamping a `<content>` and because hiding a `<content>` (setting `style.display = 'none'`) does not hide the distributed children, you do not see the children hidden.   You can do one of two things:

1. Place `restamp` attribute on `dom-if`, which causes nodes to be removed and destroyed (rather than hidden), which will result in the `<content>` being removed along with its distributed children

2. Wrap the `<content>` with a wrapper node like a `<div>`, so that the distributed children go inside the div, which can be properly hidden.  Example: http://jsfiddle.net/qw4ym7La/1/

**Comment by tsachyg** [comment]
Thank you, @kevinpschaaf,
I am already aware of those workarounds, and I can use it, though, it is still looks to me like a bug because it will not happen in real shadow Dom and shady Dom should be as close as possible.
Anyway, thank you very much for responding.

**Comment by kevinpschaaf** [comment]
This doesn't have anything to do with native Shadow vs. Shady: setting `style.display = 'none'` on `<content>` won't hide distributed children in native Shadow DOM either.  

This just has to do with the optimization that `dom-if` does by default to hide children rather than remove them, which is not compatible with `<content>`.  You simply have to remove a content to remove the children (1, use restamp), or else hide the parent of the distributed children (2, wrap the content with a div that can be hidden).
