### ISSUE TITLE
Can't style local DOM from light DOM

### ISSUE THREAD

**Issue by mflorence99** [Polymer/polymer#2000]
Following the docs [here](https://www.polymer-project.org/1.0/docs/devguide/styling.html) I'm trying to define a custom style in my component:

```javascript
<dom-module id="my-toolbar">
  <style>
    .title {
      color: var(--my-toolbar-title-color);
    }
  </style>
  ...
</dom-module>
```

Then set it in a demo page (in the light DOM):

```javascript
<style>
  .warning {
    --my-toolbar-title-color: red;
  }
 </style>

<my-toolbar class="warning"></my-toolbar>
```

I think I can see why it doesn't work, in that Polymer only has control over Polymer components. Also the documentation only shows cross-scope styling from one component to another.

The only way I made it work was using ```/deep/``` something like this (thanks to Eric Bidelman's 
[tutorial](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/):

```javascript
<style>
  my-toolbar /deep/ #container {
    color: red;
  }
 </style>
```

Surely there's a better way? Many thanks for any help!

**Comment by arthurevans** [comment]
As you determined, because custom properties is a shim, there are several limitations, and one is that you can't just define them at the document level in an ordinary `<style>` tag.

Fortunately, there's a solution: the `custom-style` element:

```
<style is="custom-style">
  .warning {
    --my-toolbar-title-color: red;
  }
 </style>
```

Docs here: 
https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-style

You can define global rules in the `custom-style` using the `:root` selector:

```
<style is="custom-style">
 :root {
    --my-toolbar-title-color: blue;
  }
  .warning {
    --my-toolbar-title-color: red;
  }
</style>
```

These rules inherit down the tree, but _are only applied at the Polymer element level_. That is, `<my-toolbar class="warning">` gets styled, but if you have the following in an element's local DOM:

    <div class="warning">
      <my-toolbar>Not styled, eh?</my-toolbar>
    </div>

The toolbar does _not_ get styled red. 

Here's a demo:

http://plnkr.co/edit/EatzFFs9aXf2BQPUCpJz?p=preview

**Comment by mflorence99** [comment]
Absolutely brilliant! Thank you so much for the excellent explanation and references -- very helpful for me as a dev new to Polymer. Everything works perfectly now :)
