### ISSUE TITLE
Off-by-n error in <dom-repeat> when Polymer.Base.splice used on items array

### ISSUE THREAD

**Issue by mgiuffrida** [Polymer/polymer#2018]
```
<template is="dom-repeat" items="[[myArray]]">
  <div style$="[[getStyle(item, item.prop)]]"></div>
</template>
```

When I update `myArray[i].prop` for some `i` via `this.setPath` or data binding, the corresponding element in the `dom-repeat` updates its style property by calling `getStyle`.

When I call `this.splice('myArray', j, n)`, from then on, changes to `myArray[i].prop` for `i >= j` do not cause `getStyle` to be called for that item. So the element's style doesn't update when I update the item's properties.

However, if I make a change to `myArray[i + n]` for `i >= j`, then `getStyle` **is** called for element `i`, i.e. with the parameters (`myArray[i]`, `myArray[i].prop`).

The effect is that changes to items in the list aren't propagated until items later in the list are changed. For example, with `this.splice('myArray', 5, 2)`, items at indices 5 and greater don't reflect changes made to their `prop` property until the item 2 slots ahead of them in the array has its property changed.

**Comment by kevinpschaaf** [comment]
Hi @mgiuffrida, sorry for the delay in taking a look at this.

I attempted to create a repro according to your description in the jsBin below.  If you press the two buttons in order, it basically performs `this.splice('myArray', 5, 2)` followed by `this.set(['myArray', lastIdx, 'prop'], newValue);`.  The results seem to be as expected:
http://jsbin.com/vowoze/1/edit?html,output

Could you take a look and confirm whether you are still having this problem, and if so try and modify the jsBin so that it exhibits the problem?  Thanks!

**Comment by mgiuffrida** [comment]
Obsolete and can't repro anymore.
