### ISSUE TITLE
Issue with auto-binding and href.

### ISSUE THREAD

**Issue by PaulHMason** [Polymer/polymer#2019]
Hi

I'm having an issue which is confusing me. If item is of form "./xxx" it is inserted into the href attribute as is and not resolved to the full url, as is the case when there is no binding (the root url being localhost/something. 

Any idea how to get the correct url expansion? Chrome is happy with the "./xxx" but IE and Firefox aren't. Angular 1.x has a separate ng-href directive for such cases, does Polymer as well?

```html
<!-- href resolves to "./xxx" -->
<template is="dom-repeat" items="{{myItems}}">
  <a data-route$="{{item.DataRoute}}" href="{{item.HRef}}">
    <span>{{item.DisplayText}}</span>
  </a>
</template>

<!-- href resolves to "http://localhost/something/xxx" -->
<a data-route="home" href="./xxx">
  <span>Home X</span>
</a>
```

**Comment by kevinpschaaf** [comment]
Polymer will automatically resolve relative urls found in templates (for a whitelist of attributes known to contain URLs) so that they are relative to the import document, which is why your second case correctly resolves.

However, if you are binding data into URL attributes like `href` and you want the URL to be relative to the import document containing the element's template, you can use the `resolveUrl` API on polymer elements to resolve the URL.  This can be used as an inline computing function directly in the template like so:

```html
<template is="dom-repeat" items="{{myItems}}">
  <a data-route$="{{item.DataRoute}}" href="{{resolveUrl(item.HRef)}}">
    <span>{{item.DisplayText}}</span>
  </a>
</template>
```
