### ISSUE TITLE
[1.0] proposel to switch attribute and properties $ syntax

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#2026]
`<div class$="{{attribute}}" myproperty="{{property}}"></div>`

I think it makes more sense to do it the other way arround

`<div class="{{attribute}}" myproperty$="{{property}}"></div>`

And even more sense to change the syntax like this :)

`<div class="{{attribute}}" $myproperty="{{property}}"></div>`

**Comment by SmokyBob** [comment]
It's encouraged to use property binding instead of attribute binding as much as possible, so it make sense that the more "natural" way to specify a binding is used for property binding.
Property binding set the property of the child element only in the JS side, instead of changing the attribute on the DOM.

Can you elaborate why "makes more sense" to bind to attribute as default?

**Comment by gertcuykens** [comment]
For me 7 out of 10 bugs is because I had to use $, and they are really hard to find. When using properties you don't see them in your chrome element inspector. But you do see the changes when using `$=`. Stuff like `data-myatribute$=` ,`class$=`,... are more common then properties. So if you switch them around you letting the developer know don't forget this thing is a hidden polymer property that you can only see in the console using $0... Also it makes code more compatible if there are multiple flavours of polymer :) And because they are properties you can make it look like `$mypropertie=` witch is soooo much nicer to read. My brain and i think most non polymer developers really can't get used to `class$=` stuff or default attributes they have been looking at in plain html code for a decade :D Trust me `$mypropertie=` is more then encouraging enough to use them and makes it very clear we are dealing with polymer stuff.

**Comment by wesleycho** [comment]
This is tangentially related, but what about attributes with a particular semantic such as `disabled`? `disabled` does not take any value, and should only be present or not - the binding syntax does not seem to support this use case.

**Comment by gertcuykens** [comment]
I fail to understand why `disabled={{true}}` shouldn't work if it get parsed by polymer as attribute instead of property? Actually you have a bug already prevented if $ was a property syntax instead of a attribute syntax :)

**Comment by wesleycho** [comment]
I wasn't necessarily speaking against your suggestion FWIW. I was just adding a point of consideration why maybe some support for an attribute binding of some sort might be ideal - I think this is one part of consideration of why Angular 2 supports binding to DOM node properties.

**Comment by arthurevans** [comment]
@wesleycho the use case you describe is handled by `disabled$="{{booleanProp}}"`. It does exactly what you want here. See:

https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-serialization

**Comment by kevinpschaaf** [comment]
Polymer defaults its non-prefixed binding to property binding because for the vast majority of cases property binding is sufficient and is _much more efficient_ than attribute binding.  Serializing property data to a string, incurring the non-trivial browser cost of setting an attribute, running an `attributeChanged` callback, and deserializing the value back to a property is much more expensive than just setting the property directly.  As such, you should not default to attribute binding where it is unnecessary because it will cause measurable impact on binding performance.  

FWIW, the only reason you can't use property binding to `class` and `style` are for esoteric browser quirks: The JS property for the `class` attribute is `className`, not `class` (you can actually property bind to `class-name="{{myClass}}"` if you find that more intuitive than attribute binding to `class`).  The JS property for the `style` attribute is `style.cssText`, and also IE won't allow any text that doesn't parse to valid CSS (e.g. binding annotations) in the `style` attribute, so we require `style$={{...}}` binding for style).

We may still try to improve the issues with binding to class, but we certainly won't flip the property vs. attribute syntax at this point.

**Comment by gertcuykens** [comment]
Ok, thank you for the feedback
