### ISSUE TITLE
hidden$="{{hide(activepage, item.id, 'true')}}"

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#2033]
Why does polymer not execute hide when I do this or give me a error message ?

`hidden$="{{hide(activepage, item.id, true)}}"`

I need to do this before something happens

`hidden$="{{hide(activepage, item.id, 'true')}}"`

**Comment by SmokyBob** [comment]
with 

> hidden$="{{hide(activepage, item.id, true)}}"

you are telling polymer to execute a call to the hide function with 3 properties/variables: activepage, item.id and *true* <- as a property/variable not the boolean value true

If you have to provide constants from the markup to a function, you need to provide it as a literal
(see [docs] (https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#literals))

P.S. please use the [SlackChannel](https://polymer.slack.com) or [SO](http://stackoverflow.com/search?tab=newest&q=%23polymer) to ask questions instead of opening an issue if not reporting an issue or feature request

**Comment by gertcuykens** [comment]
ok fair enough but stil think the current behaviour of crashing silently could be improved to at least a console error message

**Comment by SmokyBob** [comment]
I agree on the need of more verbose errors... I think there is already an issue about that (but I'm from mobile and it's difficult to search)
