### ISSUE TITLE
Javascript error when adding or removing a class on a component

### ISSUE THREAD

**Issue by Toddses** [Polymer/polymer#2038]
The following error is thrown when a class is changed on a custom component.

```
Uncaught TypeError: Cannot read property 'dashToCamelCase' of undefined
```

This is from `polymer-micro.html:417`.

Example:

```
<flux-panel id="panel" class="bordered">bunch of content</flux-panel>
```

Now say, use javascript to add the class `is-active` to the panel. That's when you get the error. I did a little debugging to see what the issue was. In this function

```
_setAttributeToProperty: function (model, attrName) {
  if (!this._serializing) {
    var propName = Polymer.CaseMap.dashToCamelCase(attrName); // this is line 417
    var info = this.getPropertyInfo(propName);
    if (info.defined || this._propertyEffects && this._propertyEffects[propName]) {
      var val = this.getAttribute(attrName);
      model[propName] = this.deserialize(val, info.type);
    }
  }
}
```

At the time of the error, `attrName` is `class`, so its triggering this function call when the class attribute changes. However, `Polymer` isn't loaded. If you throw a

```
console.log(Polymer);
```

in there you get the following in the console

```
function (){throw new Error('You tried to use polymer without loading it first. To load polymer, <link rel="import" href="components/polymer/polymer.html">')}
```

But of course I have indeed loaded polymer.

**Comment by kevinpschaaf** [comment]
Can you share a minimum reproduction case, or a link to a URL displaying the problem?

It doesn't quite wash, since [`_setAttributeToProperty`](https://github.com/Polymer/polymer/blob/v1.0.5/polymer-micro.html#L417) is defined after [`Polymer.CaseMap.dashToCamelCase`](https://github.com/Polymer/polymer/blob/v1.0.5/polymer-micro.html#L366) is defined in the same file, and all of that is defined on `Polymer` hanging off of window.  So we are going to need to see some code that exercises the problem to understand how you could be observing what you are.

**Comment by Toddses** [comment]
I tracked this down after I couldn't reproduce with a simplified test case. I was explicitly including webcomponentsjs in the html, and it was also mistakenly being included in a build script. So I was dual loading webcomponentsjs, which is bad.
