### ISSUE TITLE
Can not modify array with 3 or more dimensions?

### ISSUE THREAD

**Issue by masaoliou** [Polymer/polymer#2046]
`this.set` yields error: `Uncaught TypeError: Invalid value used as weak map key` from   polymer.html line# 3282.

index.html:

    <!DOCTYPE html>
    <html>
      <head>
        <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
        <link rel="import" href="my-element.html">
      </head>
      <body>
        <my-element></my-element>
      </body>
    </html>

my-element.html:

    <link rel="import" href="bower_components/polymer/polymer.html">
    <link rel="import" href="bower_components/iron-input/iron-input.html">
    <dom-module id="my-element">
        <template>
        </template>
    </dom-module>
    <script>
        Polymer({
            is: "my-element",
            properties:{
                arr:{
                    type:Array,
                    value:[[1,[2,null],3],[11,[22,null],33]]
                }
            },
			ready:function(){
				for(var i=0;i < this.arr.length;++i){
					console.log(this.arr[i][1][0]+1);
					this.set("arr."+i+".1.1",this.arr[i][1][0]+1);
				}
			}
        });
    </script>

**Comment by kevinpschaaf** [comment]
I can reproduce the bug on Safari, but not Chrome here:
http://jsbin.com/kuhava/edit?html,console,output

The bug seems to be on [this line](https://github.com/Polymer/polymer/blob/v1.0.5/polymer.html#L3281), which is doing a `WeakMap` `get` on `null`, and WeakMap keys must be objects.  That operation throws on Safari, but not on Firefox or Chrome stable/canary for some reason (and the error message you included doesn't match Safari's warning of `TypeError: A WeakMap cannot have a non-object key`).

@masaoliou I can fix that issue, but can you clarify what browser/OS you encountered the error so I can test the fix?  Thanks.

**Comment by kevinpschaaf** [comment]
A fix was made on master (should be released shortly) that _should_ address the error you saw; can you test and close the issue if it resolved it?  Thanks.

**Comment by masaoliou** [comment]
I have been using Chomium `Version 40.0.2214.91 Built on 8.0, running on Debian`. The browser does not complain about [your code](http://jsbin.com/kuhava/edit?html,console,output). So I guess the code in master fix this issue.

Thank you very much!
