### ISSUE TITLE
call `factoryImpl` before `ready`

### ISSUE THREAD

**Issue by nippur72** [Polymer/polymer#2075]
Not sure my reasoning is correct, but:

currently `factoryImpl()` is called after `ready` and before `attached`, making it ambiguous whether during the `ready` event the element is fully initialized or not. 

IMO the `ready` event should occur when everything is initialized, so I suggest to move the factoryImpl call before the `ready` event. 

Example:

``` JavaScript
var elMaker = Polymer({
      is: 'my-greeter',

      properties: { greet: { value: "hello" } },

      ready: function () {
         console.log( this.greet + " world");
      },

      factoryImpl: function (greetWord) {
         this.greet = greetWord;
      }
})

var el = new elMaker("hola"); // configure to salute with hola
document.body.appendChild(el);

// output is "hello world" instead of "hola world"
```

**Comment by lgrignon** [comment]
:+1:

**Comment by nazar-pc** [comment]
In fact, until this is fixed documentation is lying.
I have in `cs-label` such thing:
```coffeescript
	ready : ->
		console.log @querySelector('input').checked
```
And then I'm using it:
```html
<label is="cs-label-button">
	<input checked="[[group_permission_state(group.id, '-1')]]" name$="[[concat('groups[', group.id, ']')]]" type="radio" value="-1">
	<span>[[L.inherited]]</span>
</label>
```

Guess what? Even if `checked` is eventually `true` I'm getting `false` in console, changing callback from `ready` to `attached` solves and issue, while documentation explicitly states:
> The ready callback is called when an element’s local DOM is ready.

> It is called after the element’s template has been stamped and all elements inside the element’s local DOM have been configured (with values bound from parents, deserialized attributes, or else default values) and had their ready method called.

> Implement ready when it’s necessary to manipulate an element’s local DOM when the element is constructed.

So this is simply not true currently. I'd increase priority to p1...

**Comment by sjmiles** [comment]
@nippur72: Elements are created in JavaScript via `document.createElement` which allows no configuration. Therefore no **imperatively created element**  ever has anything but default configuration, and all user property settings occur after the construction process fully completes (after `ready`).

`factoryImpl` provides a spot to implement a factory function that can do work on an element immediately **after** it is constructed, as a user might. This is really just a convenience method.

Given:

```
factoryImpl: function(a, b) {
  this.propertyA = a;
  this.propertyB = b
}
```

Then these are equivalent:

```
var e = new XFoo('a', 'b');
```

And

```
var e = document.createElement('x-foo'); // `ready` is invoked before returning
e.propertyA = 'a';
e.propertyB = 'b';
```

Or, using another Polymer utility method:

```
var e = Polymer.Base.create('x-foo', {propertyA: 'a', propertyB: 'b'});
```

Fwiw, because elements can be dynamically reconfigured by the user, it's generally a design-flaw to rely on property values in `ready`. Instead, one should write observers that can take action on property changes that may occur at any time.

@nazar-pc: it's not clear your comments have anything to do with `factoryImpl` which is what this ticket is about. Please re-file as necessary, and if you do, please simplify your problem statement, I'm afraid your example is too complicated to clearly reveal a deficiency.

**Comment by nazar-pc** [comment]
@sjmiles, sorry, I was looking for some issue not to create duplicate, it seems I found wrong one, I'll re-create another issue. I'll drop that comment afterwards

**Comment by TimvdLippe** [comment]
Closing as `factoryImpl` has been removed.
