### ISSUE TITLE
this.shadowRoot with Polymer 1.0

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2111]
I'm trying to migrate my Firefox OS app from Polymer 0.5.5 to 1.0.7.
Since I've used `this.shadowRoot` directly I want to use it directly in future.
But the problem is that even though I've set `Polymer.dom` to `shadow` before including Polymer itself, I do not have `this.shadowRoot` property on any custom element.
I've included full version of WebComponents.js that works fine with Polymer 0.5.

Are there any additional tricks here or is this a bug?

**Comment by timeu** [comment]
I might be wrong but I guess `this.shadowRoot` is called now simply `this.root`. 

If you want to add `DOM` elements to your local DOM you could use: `Polymer.dom(this.root).insertBefore...`. See [here](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api-examples) for more infos.

**Comment by nazar-pc** [comment]
Wait, I mean `this.shadowRoot`, I do not care what `this.root` is, it doesn't exists in ShadowDOM spec as far as I remember.
Also, I know about ugly `Polymer.dom(..)`, which is why I've mentioned explicitly:
> Since I've used this.shadowRoot directly I want to use it directly in future

With `Polymer.dom = shadow` it should be used under the hood, but looks like in fact it is not.

**Comment by timeu** [comment]
I think `this.root` is just an alias for `this.shadowRoot` (see [here](https://github.com/Polymer/polymer/blob/3b0d10b4da804703d493da7bd0b5c22fc6f7b173/src/mini/shadow.html#L34)).

**Comment by nazar-pc** [comment]
> But the problem is that even though I've set Polymer.dom to shadow before including Polymer itself, I do not have this.shadowRoot property on any custom element.

**Comment by timeu** [comment]
I would recommend to use `this.root` instead of `this.shadowRoot`. 
Nevertheless `this.shadowRoot` should also work provided that you set  `Polymer.dom = 'shadow'`.

See here: http://jsbin.com/dexeku/edit?html,console

Also the recommend approach is to use `WebComponents-lite.js` instead of `WebComponents.js`.

**Comment by nazar-pc** [comment]
Unbelivable...
I'm using WebComponents for more than a year, I KNOW WHEN TO USE `WebComponents-lite.js` AND WHEN `WebComponents.js`, I DO NOT CARE ABOUT `this.root` AT ALL BECAUSE I WANT TO USE NATIVE API DIRECTLY AND HOPED THAT WAS CLEAR FROM SECOND LINE.

And if you didn't read first line, I'll repeat:
> I'm trying to migrate my Firefox OS app from Polymer 0.5.5 to 1.0.7.
> Firefox OS

Where there is no native support for Shadow DOM. And your example results in `undefined` under Firefox (obviously, you'll have `this.shadowRoot` under Chromium).

**Comment by timeu** [comment]
Seriously, you should chill and relax a little bit! This will be my last comment on this issue. 

Apparently Firefox has some kind of a timing issue so that this code  https://github.com/webcomponents/webcomponentsjs/blob/master/src/WebComponents/dom.js#L81
runs **AFTER** setting `window.Polymer = 'shadow'` and thus the `Polymer.dom` value is lost. 
When `Polymer` later checks whether to use ShadowDOM polyfill or not, it will not fallback to ShadyDOM (https://github.com/Polymer/polymer/blob/master/src/lib/settings.html#L29)

Chrome works fine even when opting into the ShadowDOM polyfill (polyfill='true' in webcomponent.js url). See [this jsbin](http://jsbin.com/xejoja/edit?html,console)).  

As a workaround you can use `Polymer = {'dom':'shadow'}` instead and it will work fine. (see [jsbin](http://jsbin.com/nisuwokiku/edit?html,console)).

However I am not sure, if this won't cause problems, because according to the [docs](https://www.polymer-project.org/1.0/docs/devguide/settings.html), `webcomponent.js` already creates a `window.Polymer` stub and with the above method you are basically overwriting it. 

But this might be only relevant if you have a call to `Polymer()` somewhere in your main document/body.

**Comment by nazar-pc** [comment]
Thanks a lot about this, @timeu, it really makes sense!
`window.Polymer === polymerStub` will work because this is true if and only if we compare object with itself, so, even modified object would work and thus `window.Polymer` will be replaces with another stub.

I do not actually like that WebComponents.js tries to do something with Polymer, lets wait for core developers, what they think.

**Comment by sorvell** [comment]
Sorry for the confusion about this issue. The recommended way to turn on ShadowDOM for all browsers is like this:

```
<script src="components/webcomponentsjs/webcomponents.js"></script>
<script>
  Polymer = {dom: 'shadow'};
</script>
<!-- import Polymer / elements -->
```

We'll go ahead and modify the webcomponentsjs polyfill to avoid the problem described here.
Closing this issue in favor of https://github.com/webcomponents/webcomponentsjs/issues/354.

**Comment by nazar-pc** [comment]
@sorvell, still issue is not resolved indeed.
Even having all of `Polymer.Settings.(has|use|want)Shadow` set to `true` I do not see `this.shadowRoot` property on elements: http://jsbin.com/jahicoxamo/edit?html,console
However, there is some `this.polymerShadowRoot_` property...
Polymer 1.0.8

**Comment by sorvell** [comment]
In order to use the Shadow DOM polyfill, load `webcomponents.js` not `webcomponents-lite.js` which omits the polyfill. Here's an example: 

http://jsbin.com/kagedowati/1/edit?html,output

**Comment by nazar-pc** [comment]
Yes, finally got it working, thanks
