### ISSUE TITLE
Polymer.dom(elem).cloneNode(true) does not copy the values of changed properties

### ISSUE THREAD

**Issue by timeu** [Polymer/polymer#2112]
I am not sure if this is by design or a bug, but If I modify a property of an element and later clone it, the cloned instance has the original value. 

Here is a jsbin: http://jsbin.com/vijiji/edit?html,console

**Comment by kevinpschaaf** [comment]
This is by design.  The native HTML `cloneNode` only clones _HTLM attributes_, not _JS properties_.

Polymer provides a `reflectToAttribute: true` setting for `properties` you can use to keep the attribute in sync with the property, which will allow the current values to be copied when cloned, however updating attributes on elements is a fairly expensive operation and can impact performance 

Depending on the circumstance, it may be better to implement a `cloneWithProperties` API on your element which calls `Polymer.dom(this).coneNode(true)` and then copies properties over.

Hope that helps.

**Comment by vitoexe** [comment]
@kevinpschaaf This is grate idea. 
Without "reflectToAttribute: true" .setAttribute('data', JSON) on clonedNODE don't bind data.
How to set/copy these properties?
