### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by lbonapfel** [Polymer/polymer#2119]
Hello,
 I have noticed that it is much more light-weight if files are minified before vulcanization. So I was wondering why there is no minified files for official Polymer related elements and Polymer itself ?

**Comment by manustays** [comment]
Hi @lbonapfel,

Its more light-weight is files are minified before vulcanization because vulcanize does not minify the files any more.

If you use a gulp based build process (or, polymer-starter-kit), you may try the following configuration in your gulpfile.js to minify vulcanized file:

```javascript
// In the beginning of gulpfile.js:
var minifyHTML = require('gulp-minify-html');
var minify_CSS_JS = require('gulp-minify-inline');
var cheerio = require('gulp-cheerio');


// Modified the 'vulcanize' function. Search "gulp.task('vulcanize', function" and modify as needed:
gulp.task('vulcanize', function () {
  var DEST_DIR = 'dist/elements';

  // Options for minify_CSS_JS
  var css_js_options = {
      js: {
	      compress: {
		      drop_console: true,
		      dead_code: true,
		      drop_debugger: true,
		      join_vars: true,
		},
      },
      jsSelector: 'script', //jsSelector: 'script[type!="text/x-handlebars-template"]',
      css: false,
  };

  return gulp.src('dist/elements/elements.vulcanized.html')
    .pipe($.vulcanize({
      dest: DEST_DIR,
      strip: true,
      inlineCss: true,
      inlineScripts: true
    }))

    .pipe(minifyHTML({
            quotes: true,
            empty: true,
            spare: true
        }))
    .pipe(minify_CSS_JS(css_js_options))


    // Custom optimize CSS..................
    .pipe(cheerio(function ($, file) {
      // OPTIMIZE CSS
      $('style').each(function () {
        var style = $(this);
        style.text( style.text()
			.replace(/^[ \t]+/mg, '')				// remove indentations
			.replace(/[ \t]*\/\*(.|[\n\r])*?\*\//g, '')		// remove comments
			.replace(/[\n\r]+/g, '\n')				//
			.replace(/;[\n\r\t ]+/g, ';')				//
			.replace(/,[\n\r\t ]+/g, ',')
			.replace(/[ \t\n\r]+{/g, '{')
			.replace(/{[ \t\n\r]+/g, '{')
			.replace(/[ \t\n\r;]+}/g, '}')
			.replace(/}[ \t\n\r]+/g, '}')
			.replace(/:[ \t\n\r]+/g, ':')
		);
      });
    }))
    .pipe($.if('*.html', $.replace(/;<\/script><script>/ig, ';')))
    .pipe(gulp.dest(DEST_DIR))
    .pipe($.size({title: 'vulcanize'}));
});
```

**Note 1:** The above script works with the polymer-starter-kit setup. I have modified the gulpfile.js that comes with it.

**Note 2:** You need to install the required gulp modules:
> npm i gulp-minify-inline --save-dev
> npm i gulp-cheerio --save-dev

**Note 3:** The gulp-minify-inline module was buggy to be used with polymer. It was disrupting the page style. So, after experimenting with many settings, I finally disabled its CSS minification and added my own code to minify my CSS using gulp-cheerio module and my custom regex. Your needs may vary.

**Comment by kevinpschaaf** [comment]
We expect many/most users will vulcanize+minify their element code with Polymer to create the files served for production.  Releasing un-minified code has proven to be helpful in helping users debug code during development.

Note in addition to the guidance in the previous comment, we have also developed an all-in-one tool called `polybuild` that vulcanizes and minifies for maximum compactness: https://github.com/PolymerLabs/polybuild
