### ISSUE TITLE
dom-if does not hide distributed content

### ISSUE THREAD

**Issue by plequang** [Polymer/polymer#2120]
Hi,

The documentation for conditional templates states :

> If the if property becomes falsy again, by default all stamped elements are hidden (but remain in the DOM tree). This provides faster performance should the if property become truthy again. 

This works for local DOM content, but not for content distributed with `<content>` element.

For example this element :
```
<dom-module id="test-dom-if">
    <template>
        <button on-click="toggleShow">toggle show</button>
        <!-- **** add restamp to template -->
	    <template is="dom-if" if="{{show}}" >
                <content></content>
                <div>
                    Local dom content
                </div>
            </template>
    </template>
</dom-module>
```

If I use it as follows :
```
<test-dom-if id="test">
    <div>My content</div>
</test-dom-if>
```

Then `My content` is displayed when `show` becomes true, but never gets hidden, whereas `Local dom content` is displayed/hidden accordingly to the `show`property.

Test jsbin: http://jsbin.com/honitihefi/edit?html,console,output

I know about the restamp attribute, and it works fine with it, but I was wondering if this is a normal behavior.

Also, I know I could solve this by using something like the following instead of `dom-if`:
```
<div hidden$="{{show}}">
    <content></content>
</div>
```
, but the content of my element is inside an iron-selector, which allows only direct children as selectable elements.

**Comment by kevinpschaaf** [comment]
> I know about the restamp attribute, and it works fine with it, but I was wondering if this is a normal behavior.

This is the intended behavior.  By default, `dom-if` [hides its children](https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-if) when if becomes falsy as a performance optimization, since it is generally must faster to hide/show frequently changing DOM than to destroy/re-create it.  However, since setting `display: none` on a `<content>` element does not hide the distributed children.  Wrapping the `<content>` is often a good answer that preserves the performance enhancement, but as you stated that would violate the `iron-selector` API, therefore `restamp` is the correct solution for you.
