### ISSUE TITLE
Databinding to computed properties does not update

### ISSUE THREAD

**Issue by danimoh** [Polymer/polymer#2122]
Hola.

It seems that data binding to computed properties does not update.
The used Polymer version is 1.0.6.
Here an example snippet:

**Using computed properties** (not working):

```HTML
<dom-module id="friends-list">
	<style>
		:host {
			display: block;
		}
	</style>
	<template>
		<div>
			Friends of: <span>{{user.name}}</span>
			<br/>
			Friends count: <span>{{friendsOfUser.length}}</span>
			<br/>
			Friends count computed: <span>{{computeFriendsCountOfUser(friendsOfUser.*,user.name)}}</span>
			<br/>
			Friends: <span>{{friendsOfUser}}</span>
		</div>
	</template>
</dom-module>
<script>
	(function () {
		Polymer({
			is: 'friends-list',

			properties: {
				friends: {
					type: Object,
					value: function() {
						return {
							'Lukas': ['Marie', 'Hans'],
							'Hans': ['Harry']
						};
					},
					notify: true
				},
				friendsOfUser: {
					type: Array,
					computed: 'computeFriendsOfUser(friends.*, user.name)',
					notify: true
				},
				user: {
					type: Object,
					value: function() {
						return {
							name: 'Lukas'
						};
					}
				}
			},

			computeFriendsOfUser: function(friendsChanges, userName) {
				console.log('computeFriendsOfUser called', friendsChanges);
				return friendsChanges.base[userName] || [];
			},

			computeFriendsCountOfUser: function(friendsOfUserChanges, userName) {
				return friendsOfUserChanges.base.length;
			},

			ready: function() {
				var that = this;

				window.debug = window.debug || {};
				window.debug.getThis = function() {
					return that;
				}
			}
		});
	})();
</script>
```
Especially mind, the use of
```HTML
Friends count: <span>{{friendsOfUser.length}}</span>
<br/>
Friends: <span>{{friendsOfUser}}</span>
```

**Using computed bindings** (working):

```HTML
<dom-module id="friends-list">
	<style>
		:host {
			display: block;
		}
	</style>
	<template>
		<div>
			Friends of: <span>{{user.name}}</span>
			<br/>
			Friends count: <span>{{computeFriendsCountOfUser(friends.*, user.name)}}</span>
			<br/>
			Friends: <span>{{computeFriendsOfUser(friends.*, user.name)}}</span>
		</div>
	</template>
</dom-module>
<script>
	(function () {
		Polymer({
			is: 'friends-list',

			properties: {
				friends: {
					type: Object,
					value: function() {
						return {
							'Lukas': ['Marie', 'Hans'],
							'Hans': ['Harry']
						};
					},
					notify: true
				},
				user: {
					type: Object,
					value: function() {
						return {
							name: 'Lukas'
						};
					}
				}
			},

			computeFriendsOfUser: function(friendsChanges, userName) {
				console.log('computeFriendsOfUser called', friendsChanges);
				return friendsChanges.base[userName] || [];
			},

			computeFriendsCountOfUser: function(friendsChanges, userName) {
				return (friendsChanges.base[userName] || []).length;
			},

			ready: function() {
				var that = this;

				window.debug = window.debug || {};
				window.debug.getThis = function() {
					return that;
				}
			}
		});
	})();
</script>
```
Especially mind, the use of
```HTML
Friends count: <span>{{computeFriendsCountOfUser(friends.*, user.name)}}</span>
<br/>
Friends: <span>{{computeFriendsOfUser(friends.*, user.name)}}</span>
```

**Data changes that work in both cases:**
```Javascript
window.debug.getThis().set('user.name', 'Hans');
window.debug.getThis().set('user.name', 'Lilli');
window.debug.getThis().set('user.name', 'Lukas');
```

**Data changes that do not work for computed properties:**
```Javascript
window.debug.getThis().push('friends.Lukas', 'Lilli');
```

Have a nice day and thanks for your great work on Polymer

**Comment by kevinpschaaf** [comment]
First, when you return a value from a computing function, Polymer does an assignment to the computed property name.  So `computeFriendsOfUser` it is effectively doing

```
this.friendsOfUser = this.friends.Lukas;
```

However, Polymer's data-binding system relies on the links you create between data when you create bindings in the template to know how data is associated.  But when you do an assignment of one name to another, although you propagate the data, you lose the linkage between the two named paths.  So when a notification for `this.friends.Lucas.*` comes into the element (e.g. when you mutate the array), the notification will not properly be routed to elements that may bind to `this.friendsOfUser`.

For this purpose, Polymer provides a `linkPaths` API that allows you to tell the system when you associate two paths imperatively (i.e. outside the template).  In your example, if you call this in the computed function when you return the selected friends array, the two paths will be associated and notifications from one will propagate to the other. 

Here is an example:
http://jsbin.com/vetiha/1/edit

Note that this is only required when the return value of a computed property is an Object/Array (not primitive value) that has a different name in the same element (e.g. `friendsOfUser` vs. `friends.Lucas`).

Also note there was one other issue with your example that is slightly nuanced.  You were binding `friendsOfUser` (in the first example) and `computeFriendsOfUser(...)` (in the second example) directly to the `textContent` of a `span`.  Although the value being set is identical before and after the push in both cases (it's the same the array reference), the text updated in the second example but not in the first only because with the first example, Polymer re-computes the computed property, but because it doesn't change (it is the same array reference after the push), Polymer doesn't re-set it to the span's `textContent`.  Using an inline computing function skips Polymer's property-based dirty check and re-sets the computed value directly to the span (which itself does not dirty-check, and re-serializes the array).  However, if you were binding `friendsOfUser` to an element that accepts arrays (such as a `dom-bind`), re-setting the same array will be dirty-checked and won't result in updates.  As such, you shouldn't rely on that behavior, and instead use wildcard arguments (as in the `printArray`function) to ensure deep changes result in re-computing.

Hope that helps.

**Comment by kevinpschaaf** [comment]
I opened a separate issue to consider a more ergonomic API for achieving your use case.  As such, I'll go ahead and close this issue.
