### ISSUE TITLE
Setting properties of object type is broken

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2132]
Lastest version as for now, reproducing: https://jsfiddle.net/x694vqhj/2/
It is incomparably more awkward and difficult that in 0.5, but even that seems to be broken...

Chromium 44.0.2403.30:
> Uncaught TypeError: Cannot read property 'owner' of undefined

Firefox Nightly 42.0a1 (2015-07-18):
> TypeError: this.\__data\__ is undefined

**Comment by kevinpschaaf** [comment]
It is a difference with 0.5 due to the differing data observation systems.  See the section in the primer here on lifecycle callbacks: https://github.com/Polymer/polymer/blob/master/PRIMER.md#basic-lifecycle-callbacks

> Note that properties with side-effects (bindings, observers, computed property dependencies) must not be accessed during created. In general, most lifecycle work should be performed in one of the other callbacks below

You can initialize data via the `value` property in `properties` (note, you should use a function to return new instances of objects/arrays to avoid shared data across instances).  Any subsequent changes should occur in `ready` or after.

http://jsbin.com/hisega/edit?html,output
