### ISSUE TITLE
[1.0] Elements inside dom-if evaluated even when 'if' is falsy

### ISSUE THREAD

**Issue by tpluscode** [Polymer/polymer#2137]
Please have a look at my code below.

``` html
<dom-module id="ld-resource">
    <template>
        <sw-object object="{{resource}}"></sw-object>
        <template is="dom-if" if="{{hasImage}}">
            <schema-image image="{{image}}"></schema-image>
        </template>
    </template>
</dom-module>

<script>
    Polymer({
        is: 'ld-resource',
        properties: {
            resource: {
                type: Object,
                notify: true
            },
            hasImage: {
                computed: 'resHasImage(resource)'
            },
            image: {
                computed: 'getImage(resource)'
            }
        },
        resHasImage: function(resource){
            return !!resource['http://schema.org/image'];
        },
        getImage: function(resource){
            return resource['http://schema.org/image'][0];
        }
    })
</script>
```

The inner `<template>` doesn't render when `resHasImage` method returns false. However, even when it does, the `image` property still gets evaluated, even though the template will not get rendered. In my code that causes an error when applying the index. 

Is this by design? Do I have to add guards to computed properties used inside a conditional template?

**Comment by timeu** [comment]
AFAIK this is by design. 
Because of performance reason the [default behavior](https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-if) of `dom-if` is to just hide the contents using `display:none`. If you really need to create/destroy the DOM elements you can add `restamp=true` to  it (i.e. `<template is="dom-if" restamp="true">` )

See also this issue: https://github.com/Polymer/polymer/issues/2120

**Comment by tpluscode** [comment]
Hi @timeu, thank you for your response. I'm not sure it is the case actually. This happens initially when the component is first displayed and `if == false` from the start. So the inner template is never actually rendered but evaluated nonetheless.

**Comment by kevinpschaaf** [comment]
This behavior is by design.  Computed properties compute based on changes to their dependencies, independent of their use in templates.  Polymer uses a "push" model (i.e. changes in dependencies push forward to cause side effects), as opposed to a "pull" model (i.e. a template needs a value and causes it to be computed based on its dependencies).

You defined a computed property `image` that has a dependency on `resource`.  Thus `image` will be re-computed each time `resource` changes.  That it would be _consumed_ in the template only if the `dom-if` stamped (when `hasImage` computes to true) has no effect on the computation of `image`.

Your `image` computing function either needs to be defensive against cases where the image is not present:

```js
        properties: {
            resource: {
                type: Object,
                notify: true
            },
            hasImage: {
                computed: 'resHasImage(resource)'
            },
            image: {
                computed: 'getImage(resource)'
            }
        },
        resHasImage: function(resource){
            return !!resource['http://schema.org/image'];
        },
        getImage: function(resource){
            var image = resource['http://schema.org/image'];
            return image && image[0];
        }
```

Or else it could depend on `hasImage` and use it there (maybe overkill):
```js
        properties: {
            resource: {
                type: Object,
                notify: true
            },
            hasImage: {
                computed: 'resHasImage(resource)'
            },
            image: {
                computed: 'getImage(hasImage, resource)'
            }
        },
        resHasImage: function(resource){
            return !!resource['http://schema.org/image'];
        },
        getImage: function(hasImage, resource){
            return hasImage && resource['http://schema.org/image'][0];
        }
```

**Comment by tpluscode** [comment]
Thank you
