### ISSUE TITLE
Computed bindings: Subproperties

### ISSUE THREAD

**Issue by Jamtis** [Polymer/polymer#2155]
Computed bindings are only called when their arguments change.

But what if the computed value depends on subproperties of the arguments...

Is it possibly to tell the binding to recompute on subproperty changes?
If not is there a way to manually trigger the computation?

I also made a [fiddle](https://jsfiddle.net/Lhv8szwj/27/).

PS: Notifing on the arguments (see fiddle) does not cause a recomputation.

**Comment by kevinpschaaf** [comment]
In order to recompute a value on sub-property changes, you simply need to use the [wildcard syntax for deep-path observation](https://www.polymer-project.org/1.0/docs/devguide/properties.html#deep-observation).

In your example, I changed your binding to 
```html
<div>{{computeValue(first.*, second)}}</div>
```
and note that wildcard arguments receive an info object describing the path that changed, so your computing function needed a small tweak:
```js
    computeValue: function (firstInfo, second) {
        return firstInfo.base.join("-") + ", " + second;
    },
```

I also removed your call to `notifyPath`, which you should only need to use if you are not using the Polymer API for modifying data.

Working example:
https://jsfiddle.net/7ee702La/2/

**Comment by Jamtis** [comment]
I suppose to state this out explicitly in the docs.
