### ISSUE TITLE
Allow computed bindings as parameters of computed bindings

### ISSUE THREAD

**Issue by miztroh** [Polymer/polymer#2163]
Contrived example.  `and` determines if all arguments are true.  `or` determines if one argument is true.  The example below is the equivalent of `((foo && bar) || (hello && world))`.

```
<template is="dom-if" if="{{or(and(foo, bar), and(hello, world))}}"></template>
```

**Comment by kevinpschaaf** [comment]
In Polymer 1.0, we have focused on avoiding creating a complex domain-specific language for the binding syntax that would require a full JS parser, in order to keep the library code tight and simple.  This effectively means writing simpler templates and pushing the JS logic into the JS.  This obviously comes at the expense of expressiveness in the templates, but we also find it's a matter of personal taste how much developers want "logic" in the template as opposed to in the JS, so we're trying to strike the right balance of core library complexity vs. expressiveness.

I appreciate the suggestion and we'll keep this on the backlog for consideration, but likely won't be tackled in the short-term.

**Comment by TimvdLippe** [comment]
Closing per above comment. For more extensible bindings, check out solutions like [lit-html](https://github.com/polymerlabs/lit-html) where you can take advantage of all features in JavaScript. In the future, a mixin integration from Polymer with lit-html can enable this working in Polymer.
