### ISSUE TITLE
Using polymer v1 for Apache Cordova Windows App

### ISSUE THREAD

**Issue by Prontsevich** [Polymer/polymer#2168]
I was trying to create a windows app (for windows 8.1) using apache cordova and polymer v1. I built a simple test project and found that polymer works fine with android but doesn't work with windows app. I created 2 simple components for polymer from examples. I can see this controls when I start application for android, everything works, I can see the components' content. But when I start  this app as windows app I can't see my components. I used page inspector and saw empty tags of my components, there was no any content. I was using Visual Studio 2015. I uploaded test project to GitHub, here is the link - https://github.com/Prontsevich/TestCordovaPolymer.git

**Comment by kevinpschaaf** [comment]
@Prontsevich Are there any errors from the console you can provide to help in debugging?  Also, can you confirm your issue is in Windows 8.1 desktop (as opposed to mobile)?

My intuition is that this may be an issue with the `HTMLImports` polyfill, which uses XHR to load files relative to index.html (which would be local/`file://` files on Cordova).

I've opened an issue on the web components issue tracker here: https://github.com/webcomponents/webcomponentsjs/issues/364 to cover this.

**Comment by Prontsevich** [comment]
Hi, there were no any errors in the console. And actually I tried to start Windows 8.1 app for desktop, not mobile. But it's the same behavior as for desktop and also as for mobile, there are no any errors in console and no any content in controls.

**Comment by azakus** [comment]
Closing in favor of webcomponents/webcomponents#364
