### ISSUE TITLE
Error while passing parameters to Google Map

### ISSUE THREAD

**Issue by Euphrates-Media** [Polymer/polymer#2172]
I displayed simple Google Map successfully :

```
<google-map
    latitude="30.283"
    longitude="57.083"
    zoom="12"
    language="fa"
    disable-default-ui
    >
```
    
But when I try to add position style, it doesn't apply it and zoom control disappears, I guess the problem is in the way I add additional-map-options, but I don't know how to fix it:

```
<google-map
    latitude="30.283"
    longitude="57.083"
    zoom="12"
    language="fa"
    disable-default-ui
    additional-map-options='{"zoomControl" : "true",
    "zoomControlOptions" : {"style" : "google.maps.ZoomControlStyle.SMALL",
    "position" : "google.maps.ControlPosition.BOTTOM_RIGHT"}
  }'>
```

**Comment by timeu** [comment]
The `google-maps.ControlPosition` is a javascript `Object {TOP_LEFT: 1, TOP_CENTER: 2, TOP: 2, TOP_RIGHT: 3, LEFT_CENTER: 4…}` with numeric properties (i.e. `BOTTOM_RIGHT = 12`).

If you pass properties of type `Object` (i.e. `additional-map-options`) decleratively as a String, Polymer will deseralize it to an `Object` using `JSON` and thus `google.map.ControlPosition.BOTTOM_RIGHT` will be converted to a `String`, but google maps expects a numeric value between 1 and 12. 

There are 2 workarounds: 

1. Don't pass it decleratively but use a computed function to set the property directly (make sure that the google maps library is loaded, otherwise `google.maps` will be undefined)

```
<google-map additional-map-options="{{_computeAdditionalOptions()}}">

_computeAdditionalOptions: function() {
    return  {zoomControlOptions:....,position: google.maps.ControlPosition.BOTTOM_RIGHT};
}
```

2. Pass the numeric value for `BOTTOM_RIGHT`: 
```
<google-map
    latitude="30.283"
    longitude="57.083"
    zoom="12"
    language="fa"
    disable-default-ui
    additional-map-options='{"zoomControl" : "true",
    "zoomControlOptions" : {"style" : "1",
    "position" : "12"}
  }'>
```

P.S.: `google.maps.ZoomControlStyle.SMALL` has the value of `1`.

**Comment by kevinpschaaf** [comment]
Closing, as the answer above provides two approaches, and this tracker is for the Polymer core library; if there are follow-on issues, please file them in the google-map issue tracker: https://github.com/GoogleWebComponents/google-map/issues.  Thanks!
