### ISSUE TITLE
Access filtered and sorted result of a dom-repeat

### ISSUE THREAD

**Issue by eibens** [Polymer/polymer#2183]
I would like to access the result of a `dom-repeat` after the filter and sort functions have been applied. I am thinking along the line of a `<dom-repeat>.result` property.

Right now I can apply the filter and sort myself manually in the element. But this is not DRY and most of all I lose the automatic data-binding for the array items.

**Comment by lukas-eibensteiner** [comment]
Use cases:

- Placeholder for empty list by computing whether the result is empty.
- Display number of results, for example when searching a list.
- Passing the filtered result to a child element, when I don't want the child to know all items from the original list.

If there already are patterns for these use-cases that support data-binding I'd love to hear about them. 

Thanks!

**Comment by kevinpschaaf** [comment]
Good feedback.  This has been on our radar, but we lacked concrete use cases, so this will help us consider how to approach it.  The main concern will be not incurring performance overhead of keeping an externally-bindable output array in sync if it is not used.

**Comment by lukas-eibensteiner** [comment]
I gave this some more thought. What I basically wish for is a declarative way to filter, sort, and maybe even map a collection that also preserves bindings.

It seems to me that this would fit well into a standalone element or behaviour, since `dom-repeat` implies that the result is rendered; I don't always need that. I guess `array-selector` actually serves a very similar purpose to what I am proposing.

**Comment by maria-le** [comment]
I agree with this. We desperately need `iron-list` functionality AND sorting and filtering capabilities IN THE SAME LIST!

**Comment by eibens** [comment]
#3571 would fix this.

**Comment by joshuahiggins** [comment]
We ran into a use case for this as well. In our usage, we need each element in a `dom-repeat` to be able to observe a single property from the sibling before and after itself. However, the `dom-repeat` has a sort, so we can't rely on the `index`.

**Comment by jfrazzano** [comment]
You could independently index, or otherwise distinguish, OR you could use the polymer collection keys, which are immutable and visible in events (they even have their own api);

I believe this is the text on the api:https://www.polymer-project.org/1.0/docs/api/dom-repeat <https://www.polymer-project.org/1.0/docs/api/dom-repeat>

there are a lot of other ways to also keep track, you can put a “homing beacon” on your elements… basically when a parent needs the child the child clicks, [this.child.click()] no click no child.  The child was removed by a filter or … well, off screen would just give you weird result. Note: the click method will also give you absolute position on the click element.  If the sort, filter, or key down/up were in a list or drop down, you could—in the past have used attribute follows or class follows, to maintain your own positioning, focus, and highlighting.  I used it to maintain highlight and focus on key downs for drop downs on search selects thousands of items long.  I was able to keep the focus on the top element as it flew through the list.  The helper function is set to be removed, I will likely make a proxy for it if you want it, just ask.

hope this helped

sincerely, 

jason

keyForElement <https://www.polymer-project.org/1.0/docs/api/dom-repeat#method-keyForElement>(el) ➙ any
el HTMLElement
Element for which to return the key.
Returns any
Key associated with the element.
Returns the Polymer.Collection key associated with a given element stamped by this dom-repeat.



here is the link:
