### ISSUE TITLE
Two-way binding to input doesn't work when using $= syntax

### ISSUE THREAD

**Issue by randrey** [Polymer/polymer#2191]
The [docs](https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#native-binding) say:

> Due to cross-browser limitations with the ability to place binding braces {{...}} in some of these attribute values, as well as the fact that some of these attributes map to differently named JavaScript properties, **it is recommended to always use attribute binding (using $=) when binding dynamic values to these specific attributes, rather than binding to their property names.**

So, in my template I have an input, which is bound to the *foo* property, like this:

```html
<dom-module id="x-test">
  <template>
    <input type="text" value$="{{foo::input}}">
    <div>[[foo]]</div>
  </template>
</dom-module>
```

... and it doesn't work - the foo property remains unchanged as I type in the input box. The solution is to change **value$=**"{{foo::input}}" to **value=**"{{foo::input}}", but it goes against the aforementioned advice, which is confusing.

[JSBin Repro](http://jsbin.com/vizemusiye/1/edit?html,output)

**Comment by kevinpschaaf** [comment]
That section of the docs is for _specific_ problematic properties of native elements where binding to the attribute is required (or when it eliminates confusion); it's not meant to be general guidance to _always_ use attribute binding.  `<input>`'s value property is not one in that short list, and so you should use property binding and not attribute binding.

Property binding is normally much more efficient that attribute binding (since it avoids string serialization, deserialization, and the custom element `attributeChanged` callback), so you should only use attribute binding in very specific cases (as outlined in the docs) where it's required, and use property binding for everything else.  Hope that helps.

**Comment by randrey** [comment]
I see. Thought those were just examples, not the definite list. Thanks for clarification.
