### ISSUE TITLE
If I just update a Object no 'computed properties' are fired.

### ISSUE THREAD

**Issue by marcus7777** [Polymer/polymer#2208]
If I just update the Object no 'computed properties' are fired:
```
  var new_obj_filters = this._setFilter(title, index, by, max, this.obj_filters);
  this.obj_filters = new_obj_filters; .
```
But If I clone the Object it fires just fine:
```
  var new_obj_filters = this._setFilter(title, index, by, max, this.obj_filters);
  this.obj_filters = clone(new_obj_filters); // TODO why clone ??? but fixed!
```

**Comment by marcus7777** [comment]
on stack here http://stackoverflow.com/questions/31784547/polymer-v1-0-computed-properties-not-recalculating/31826920#31826920

**Comment by kevinpschaaf** [comment]
In Polymer 1.0, you can assign data directly to element properties, but performing assignments to object sub-properties outside of Polymer's purview require using Polymer's set API for the changes to be observable (`set` performs both the assignment and the notification).

Your `_setFilter` function takes an object as an argument (`obj_filters`), and then assigns new values to it; this is the exact case mentioned above where the use of `this.set('obj_filters.subpath', newValue).` is required for the changes to be observable.

Alternatively as you've discovered, deeply cloning the entire object and re-setting it will also cause all side-effects of that object's properties to run, since this defeats the dirty-checking logic that is used to minimize extra work.  This is a tradeoff; it allows you to write data handling code that can be agnostic to Polymer and its data mutation API's, at the cost of the deep data clone and re-running all side-effects (possibly unnecessarily).
