### ISSUE TITLE
jQuery error with dom-repeat and delegate event handler (demo included)

### ISSUE THREAD

**Issue by pkaske** [Polymer/polymer#2210]
**Hello polymer team and community,**

**First of all:**
Here's the [demo](http://pkaske.github.io/polymer-problems/jquery-event-delegation/index.html)

All relevant output show's up in the browser's console.
Here's a screenshot that shows the line in jQuery where the problem happens.
(You can see that `elem` is a `document-fragment`)
![selection_008](https://cloud.githubusercontent.com/assets/11567985/9084426/e9871192-3b73-11e5-8e19-7cd9f1b75dde.png)

**Source of the demo**
Can be found [here](https://github.com/pkaske/polymer-problems/tree/master/jquery-event-delegation)

**Situation**
You have a delegate click event handler that targets elements by a specific attribute
`$(document).on('click', '[some-attribute]', function() {...});`

You have a custom element that uses a `dom-repeat` to show some items.
Each item has a button that, when clicked, removes the parent item.
`this.splice('items', e.model.index, 1);`

**What happens**
The click event bubbles up to the point that jQuery tries to use `getAttribute` (because of the `[some-attribute]` selector used in the event declaration) on a `document-fragment` and throws an error.

**Workaround**
Wrapping the `this.splice` in a `this.async` prevents the issue. I'm not sure why, but this doesn't seem to be the best solution to the problem...  
I tried to stop the event with `preventDefault` and `stopPropagation` but without luck. This probably doesn't work because of jQuery's own event api additions???

**Comment by kevinpschaaf** [comment]
jQuery is throwing because the `on-tap` handler that removes the item runs before jQuery's `on('click')` handler; by the time jQuery sees the event the DOM node has been removed from the DOM (and placed in a dom fragment).  jQuery's event filtering based on a selector seems to be not robust enough, and assumes the parent will always be null or an element (ignoring the case that it could be a DOM fragment, which does not have a `getAttribute` API).

I would recommend filing a bug on jQuery, pointing out this case.  As a workaround, rather than using `jQuery's` selector filtering, you could filter events yourself in a safer way, e.g. something like the following (not tested):

```js
$(document).on('click', function(e) {
  if (e.target.matches('[some-attribute], [some-attribute] *') {
    ...
  }
});
```

(Note, depending on browser you may need to use prefixed versions of `matches`, or it may be more straightforward to walk up the parentNode tree and check for attribute manually)

**Comment by pkaske** [comment]
Thanks for clearing that up to me. I will file a bug on jQuery.

**Comment by yrral86** [comment]
Just in case anyone else runs across this, `e.detail.sourceEvent.stopPropagation()` seems to work for preventing the jQuery handler.
