### ISSUE TITLE
Dom-repeat populated with old items in new instance

### ISSUE THREAD

**Issue by pkaske** [Polymer/polymer#2223]
Hello Polymerians,

I have a simple `x-foo` element that uses a `dom-repeat` template to list some simple divs (2 by default).
After adding a third item with `this.push('items', {...})` the item is added and shows up, everything fine.

Now comes the strange part:
- Remove the `x-foo` from the page by setting innerHTML of the parent element.
- Set the innerHTML of the same parent element with a new string that contains a `x-foo` element

Result: The `x-foo` with it's list is shown, but **with** the third item that was added before clearing the parent element. I would expect the get a new `x-foo` with only the two default items.

Here is a JS Bin to try this:
[http://jsbin.com/moboxoneqo/edit?html,output](http://jsbin.com/moboxoneqo/edit?html,output)

**Comment by kevinpschaaf** [comment]
When you define default `value`s in the `properties` block, those values are stored on the element's _prototype_.  This is normally fine for primitives (e.g. number, string, etc.), but will lead to shared data between all instances for objects and arrays (since those are stored by reference in JS, not by value).

For this reason, the `value` property accepts a function that will be called to return the default value for each instance, specifically for the purpose of creating a new (unshared) object/array as the default value for each instance.

I've updated your jsBin here:
http://jsbin.com/yozodi/edit?html,output

Cheers!

**Comment by pkaske** [comment]
This is a perfectly logical explanation. Thanks for teaching me that. And again, one more little puzzle piece in my way to polymer mastery.

Thaaaaank you!
