### ISSUE TITLE
Computed/observers do not observe property changes of other elements

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2224]
Do `computed` properties and `observers` not observe `HTMLElement.property` as dependencies? Particularly, I don't see my callbacks getting called for a property I've defined myself.

Use case is a custom element that references another DOM (custom) element:

```
available: {
    'computed': '_computeAvailable(el.available)'
}
observers: [
  '_observeAvailable(el.available)'
],
ready: function() {
  this.el = document.qS('#id');
}
```

Both `_computeAvailable` and `_observeAvailable` are never called.

Repo: http://jsbin.com/vuzahifuta/edit?html,output

Is this expected? If so, what's the best way to make this work? I'm seeing a lot of users start to do this type of thing.

**Comment by sjmiles** [comment]
The short answer is that Polymer does not observe properties on arbitrary objects in any scenario, unless they are data-bound (and even then sub-properties are only observed if they are changed via `set` or the change is signaled via one of the `notify` protocols). 

For example, this will not work either:

```javascript
observers: [
  '_observeAvailable(el.available)'
],
ready: function() {
  this.el = { do: function() { this.available = true; } };
  this.el.do();
}
```

The fact that `el` in your example is an element doesn't matter. It probably feels like it should matter because elements participate in bindings, but In this case there is no binding. Bindings (`{{ }}` expressions in the template) create listeners that act on notification events sent from the bindee. Even when there is a binding, the data only flows upward if the the bindee sends a notification event (i.e. if the bindee's property is `notify: true`).

Today, to observe changes in non-bound elements, you can listen for `<property>-change` events manually. Using your original example, if we observe a local property instead of `el.available`:

```js
observers: [
  '_observeAvailable(elAvailable)'
],
```

(note the differences between `el.available` and `elAvailable`)

The we can setup a notification listener and bind the data to that local property:

```javascript
    // listen to change notification for el.available
    elChanged: function(el, old) {
      this.unlisten(old, 'available-changed', '_elAvailableHandler')
      this.listen(el, 'available-changed', '_elAvailableHandler')
    },
    
    // handle change notification from el.available
    _elAvailableHandler: function() {
      this.elAvailable = this.el.available;
    },
```

Modified live example: http://jsbin.com/gikuwu/edit?html,console,output

There is discussion about adding API for dynamic bindings, but it's still on the drawing board.

**Comment by ebidel** [comment]
Thanks for the explanation @sjmiles. I arrived a similar solution by using the `prop-changed` event. Yours even goes a step further and handles changes to `el`! I like it.

**Comment by ebidel** [comment]
@arthurevans @kaycebasques can we mention this stuff in the docs somewhere as a tip?

**Comment by pengying** [comment]
Follow up question for array properties.  

So `this.elArrayProperty = this.el.arrayProperty` doesn't work with arrays since events need to be fired for each array mutation.

The event argument in the property-changed handler seems like it contains each of these array mutation events.  Is there anyway to pipe that event from `this.el.arrayProperty` to the local `this.elArrayProperty` so all the binded elements are updated?  Or do I need to manipulate the local array to using event.detail like so:

      if(event.detail.path ==='items.splices'){
          var keySplices = event.detail.value.keySplices;
          var indexSplices = event.detail.value.indexSplices;
          if(keySplices) {
            keySplices.forEach(function(keySplice) {
              if (keySplice.added.length > 0) {
                this.splice.apply(this, ['items', keySplice.index, 0].concat(keySplice.added));
              } else if (keySplice.removed.length > 0) {
                this.splice('items', keySplice.index, keySplice.removed.length);
              }
            }.bind(this));
          } else if (indexSplices) {
            indexSplices.forEach(function(indexSplice) {
              if(indexSplice.addedCount > 0) {
                var queueSlice = this.queue.items.slice(indexSplice.index, indexSplice.addedCount);
                this.splice.apply(this,
                    ['items', indexSplice.index, 0].concat(queueSlice));
              } else if (indexSplice.removed.length > 0) {
                this.splice('items', indexSplice.index, indexSplice.removed.length);
              }
            }.bind(this));
          }
        }

**Comment by TimvdLippe** [comment]
This has been adressed in https://www.polymer-project.org/2.0/docs/devguide/observers#computed-properties
> Arguments to computing functions may be simple properties on the element, as well as any of the arguments types supported by observers, including paths, paths with wildcards, and paths to array splices. The arguments received by the computing function match those described in the sections referenced above.

and in https://www.polymer-project.org/2.0/docs/devguide/observers#complex-observers
> In addition to properties, observers can also observe paths to sub-properties, paths with wildcards, or array changes.
