### ISSUE TITLE
Custom style properties can be incorrect when composing elements of the same type

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#2230]
Example:

```
<x-stuff>
  <x-stuff></x-stuff>
</x-stuff>
```

Due to the way style property data is shimmed, elements in the inner `x-stuff`in the example above may be styled with property data calculated for the outer `x-stuff` element. 

We can potentially address this by having a stronger (slower) scoping mechanism for shimming property data which is employed in cases where same type nesting is detected.

This issue came up while debugging: https://github.com/Polymer/polymer/issues/2218

**Comment by TimvdLippe** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
