### ISSUE TITLE
Sentence. Easier polymer registration

### ISSUE THREAD

**Issue by deni35** [Polymer/polymer#2233]
I have an idea. I think a such registration more convenient.

``` js
Polymer('my-element-id')
.properties({
...
})
.ready(function() {
...
});
```

**Comment by deni35** [comment]
I have another idea. 
When I use a hyphen in Id's name I can't access to dom element using this way: this.$.my-element. The only way: this.$['my-element'].
It would be good if $ array contains second reference on element, but with name: my_element. Then I would be able to use the first way: this.$.my_element.

**Comment by TimvdLippe** [comment]
Since Polymer elements are based on custom elements, the provided lifecycle callbacks and properties/observers are on the class. Since this issue has been opened, the Polymer legacy syntax has been replaced by the custom element native syntax. Therefore I am closing this issue, thank you for your suggestion!
