### ISSUE TITLE
Some default computed bindings methods

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2237]
There are some very often cases that should be available out of the box, for instance, I have following and similar methods in multiple places:
```coffeescript
icon_class : (icon) ->
	"fa fa-#{icon}"
```

I suggest following list of default methods for computed bindings:
* `if(condition, then [, else [, prefix [, postfix]]])` - allows conditionally applying `active` CSS class alongside with other "constant" classes and the likes
* `join(array [, separator = ','])` - might be used for applying array of classes and things like that
* `concat(thing [, another [,...]])` - allows to do simple concatenations, like in example above
* `and(x, y [, z [,...]])` - since it is not allowed to use any expressions except negation, this might be useful for boolean attributes/properties
* `or(x, y [, z [,...]])` - similar to previous
* `xor(x, y [, z [,...]])` - similar to previous

This is bare minimum I think, with #2163 implemented this will cover most of trivial cases without any need to reinvent the wheel.

**Comment by kevinpschaaf** [comment]
Thanks for the feedback.

Other than helpers that require nesting functions (which we're not likely to support in the short term), most of the others can be trivially implemented on behavior added to your elements.

We're definitely planning on adding helpers for CSS class application, and we'll review these suggestions for inclusion as well.

**Comment by nazar-pc** [comment]
I know it is possible to achieve with behaviors, just would be nice to avoid everyone writing the same things again and again.

**Comment by miztroh** [comment]
Agreed, @nazar-pc.

**Comment by eximius313** [comment]
+1

**Comment by nazar-pc** [comment]
Implemented in PR #2247

**Comment by tjsavage** [comment]
I'm on the fence as to whether we want to add these directly to Polymer. Certainly see the use, but I think open-sourcing this as a separate optional behavior might be the right idea for the short-term? Among other things, I'd worry that this would be a potentially high-risk source of breaking changes.

**Comment by samccone** [comment]
I am -1 to adding any more computed helpers, while I agree @nazar-pc they would be useful, the more functionality we add to the computed bindings the more people will use these features instead of creating methods, thus polluting the DOM with logic and making things much harder to reason about and test.

**Comment by nazar-pc** [comment]
But if logic needed - it will be there. The only difference is whether it will be available out of the box or everyone will reinvent the wheel.
I mean, if I need simple concatenation or simple AND operation - I'll get it anyway. From my perspective there is nothing wrong in offering this by default rather than forcing everyone do it again and again.

However, some part of requirements might be fulfilled with support for Polymer 0.5-like expressions from #2182 (seems to be limited to string concatenations only).

**Comment by azakus** [comment]
Sorry for the delay.

We think that adding more complexity to the databinding layer is not really justified with our goal of keeping Polymer small and performant at the core.

Instead, one should use a behavior that adds these features so that the cost to payload and runtime is only incurred by the elements that would use those features. As it happens, the experimental [polymer-expressions](https://github.com/Polymer/polymer-expressions) library/behavior may be a place for these functions to live (if equivalents don't exist already)

cc @justinfagnani

**Comment by justinfagnani** [comment]
FYI, polymer-expressions as a behavior is in the 2.0-preview branch: https://github.com/Polymer/polymer-expressions/tree/2.0-preview

It needs a couple of more hooks to work properly with dom-repeat and wildcards, but you can try it now for simple things.

**Comment by nazar-pc** [comment]
@justinfagnani, looks promising, but I'm afraid 1k lines of code will not be very fast, especially comparing to my implementation with 47 lines of ridiculously simple JavaScript that doesn't need to additionally parse each expression. Having sometimes a lot of elements this will be too big performance penalty (just my thoughts, haven't tried it yet).

**Comment by justinfagnani** [comment]
There's a very slippery slope for things included with the default expression parser, more and more features can be added as special cases, until you approach a full expression language, yet as special cases the features are often incomplete compared to real expressions, and don't meet developer expectations.

Expression support is already spotty: There's support for unary negation, but no other unary or binary operators. Property paths, but no index notation. Function calls, but no nesting or chained method calls or property access on the result. Number and string literals, but commas in strings have to be escaped, unlike JS, and no boolean, map or list literals.

Adding more features at this point brings us further down the slope. Especially adding things to the prototype chain so that they can be accessed from within expressions seems bad as the surface area of element APIs is already so huge. There's an increasing chance of name collision.

I think the best thing at this point is to keep the built-in expressions very simple (I'd personally even make them simpler in 2.0 - just simple names ideally) and offer an opt-in, full featured, expression parser via a mixin/behavior.
