### ISSUE TITLE
Cannot stamp out HTMLElements from Array in dom-repeat 

### ISSUE THREAD

**Issue by nourikhalass** [Polymer/polymer#2239]
It is currently not possible to stamp out the content of an Array that is filled with HTMLElements into an element using an dom-repeat template.

[Issue on JSBin](http://jsbin.com/yexoho/edit?html,output)

*Possible workaround (not sure if it is a good practice to preform)*
Create a toDOM function which attaches the element to the local DOM

````HTML
<!-- Make sure there is no whitespace between the template tags -->
<template is="dom-repeat" items="{{childern}}">{{toDOM(item)}}</template>
````

````javascript
// Attach an HTMLElement the local DOM of the main element
toDOM: function(element){
    Polymer.dom(this.root).insertBefore(element, Polymer.dom(this.root).childNodes[0]);
}
````

[Workaround on JSBin](http://jsbin.com/fopige/edit?html,output)

Downside: you lose all the benefits of using an Array and dom-repeat like updating when the content of an Array changes

**Comment by kevinpschaaf** [comment]
You're correct, this is not supported by `dom-repeat`.  Its purpose is to transform an array of _user data_ into a UI representation based on a template.

I struggle to understand the use case where maintaining a list of DOM elements as an array (and having the machinery of dom-repeat insert that back into the DOM) is better than just thinking about that array in terms of `children` of a parent, and using `appendChild` in place of `push` and `insertBefore` in place of `splice`.  If it's that you want to delegate the management of that list of children to a user of an element but insert the list of elements somewhere deep in the private local-DOM, that's exactly what Shadow DOM's distribution mechanism is via `<content>`.

As such, rather than trying to "fix" or workaround this issue, we would rather approach the problem using the idiomatic facilities of the platform: element children and shadow DOM distribution.
