### ISSUE TITLE
API inconsistency for notifyPath

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#2248]
I have noticed strange inconsistency in [Polymer.Base API](http://polymer.github.io/polymer/).

There are few methods, like `set`, `splice`, `notifyPath`, etc. that uses `path` as an argument.
However it occurred not to be the same thing.
For example `set`, and `splice` uses a path which uses natural indexes of arrays in provided data, but the `notifyPath` uses different kid of path which uses Polymer's Collection keys.

That leads to very confusing behavior like one at http://jsbin.com/mukafo/edit?html,output

Is that desired behavior?

 I would say that public method should not require user, to know the underlying internals, to perform `Polymer.Collection.get(array).getKey(prop)` for each array node. To use this method correctly I had to implement ugly [path translator](https://github.com/Juicy/dom-bind-notifier/blob/master/dom-bind-notifier.html#L250).

I believe it led to problems like #2068.

**Comment by kevinpschaaf** [comment]
Yes, the inconsistency in API is bad. Our plan is to disambiguate keys and indices in paths, so that the API's can interchangeably accept either paths with indicies or keys.  See https://github.com/Polymer/polymer/issues/2007#issuecomment-119305600.  There is a branch with an exploratory implementation of this here, which will hopefully make its way in soon: https://github.com/Polymer/polymer/compare/2007-kschaaf-key-disambiguate

**Comment by tomalec** [comment]
Thanks! I really wait for this disambiguate paths to come. `#` notation is really clean.

**Comment by kevinpschaaf** [comment]
Closing, resolved in https://github.com/Polymer/polymer/pull/2513.
