### ISSUE TITLE
Dynamic dom-bind templates + iOS 7 not working

### ISSUE THREAD

**Issue by nomego** [Polymer/polymer#2287]
Importing a template like https://gist.githubusercontent.com/nomego/515a3681142c8d0d14f1/raw/106f90338652730860f3e0ed50d0964ba60232c5/template.html and appending it to the main DOM causes Polymer to break with `TypeError: 'undefined' is not an object (evaluating 'node.nodeType')`, which is from `_parseNodeAnnotations()` called by `parseAnnotations()` called by `_prepAnnotations()`, called by `render()` called by what originally seems to be the `MutationObserver` polyfill.

So `this._template` exists but it doesn't have neither `._content` nor `.content`.

Sample JSBin with iOS 7 HTML Imports polyfill workaround at http://jsbin.com/zalegepudi/edit?html,console,output

Related to #2157 and webcomponents/webcomponentsjs#382

**Comment by nomego** [comment]
Actually, we can remove HTML imports from the equation for now and just try to dynamically create and insert a dom-bind template into the DOM:

http://jsbin.com/cavicehiba/edit?html,console,output

The dom-bind template present in the HTML on load works, but the two dynamically created ones doesn't.
However, they all work in Chrome, Firefox and iOS 8.

**Comment by azakus** [comment]
A big problem with your example is that `template.innerHTML` can't be made to populate `template.content` like in other browsers because of a bug in Safari 7: https://github.com/webcomponents/webcomponentsjs/blob/master/src/Template/Template.js#L38-L66

This means that when the dom-bind boots up, the template element does not have a `content` and that causes the exception.

The best option you have is to use your own Polymer element and create one in the main document.

If that doesn't work for you there are two workarounds that work in Safari 7

1. Build the dom yourself: http://jsbin.com/qagube/edit?html,output
2. A hacky workaround for innerHTML: http://jsbin.com/behuxe/edit?html,output

**Comment by nomego** [comment]
Thanks for your response and workarounds!

I tried to find a middle ground where I don't have to explicitly build the DOM myself but rather use a template source (`.innerHTML`) but also skip doing any async work like `requestAnimationFrame` or resetting the template state to "unrendered" and re-rendering.

This works fine on iOS 7 for simpler templates, but not when introducing `dom-repeat` within that template.
See example working/not working templates here:
http://jsbin.com/yajocufuqu/edit?html,console,output

I'm getting the same `undefined' is not an object (evaluating 'node.nodeType')` on iOS 7.

Also, the dom-repeat version doesn't work under Chrome either.
It starts to make sense why there was a recursive DOM-copy solution in #2157, which I guess brings any Safari template/importNode up to par with the error that now is present in Chrome:

```"Polymer::Attributes: couldn`t decode Array as JSON"```

The `myItems` is somehow looped over but the template has already broken down because of that error ?
In another, local, example I'm getting `DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist.` on iOS 7 for a more complex template.

Even though all this is because of bugs in (older) Safari, would it be possible to add these workarounds to Polymer itself once we have a stable, predictable solution?
