### ISSUE TITLE
Polymer.updateStyles() doesnt update styles with new styling system.

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#2299]
Use case is an element like highlight-element which dynamically updates its local dom.  `<style include="shared-styles"></style>` does not pick up new styles if you call `Polymer.updateStyles()`/`this.updateStyles()`.

**Comment by sorvell** [comment]
See, for example: https://github.com/Polymer/highlightjs-element/pull/3

**Comment by ebidel** [comment]
Note: to repo this in https://github.com/Polymer/highlightjs-element/pull/3, be sure to take out the custom-style in the main doc (https://github.com/Polymer/highlightjs-element/pull/3/files#diff-3e22c50371c76d64ea9738dbc46a6e57R20).

**Comment by sorvell** [comment]
* it doesn't look like any custom properties are used. That would be the only reason you'd ever need to call `updateStyles`

* I'm not sure this is the case but it would explain the behavior you're seeing: there's a 3rd party library involved that's adding DOM inside the element's local DOM. DOM in Polymer elements needs to be added via `Polymer.dom`. One reason is so that it gets the proper scoping classes added such that the styles properly apply. When a library is used that doesn't know about `Polymer.dom`, you can use an element's `scopeSubtree(container, shouldObserve)` method. See the [api docs](http://polymer.github.io/polymer/) for more info.

**Comment by ebidel** [comment]
Yea this works great! https://github.com/Polymer/highlightjs-element/pull/4

Didn't know about `scopeSubtree`.

**Comment by ebidel** [comment]
Closing
