### ISSUE TITLE
Invalid fragment childNodes

### ISSUE THREAD

**Issue by eeid26** [Polymer/polymer#2334]
https://jsbin.com/yejizipile/edit?html,console,output
different path from #2311

for what it's worth, my temp fix is to always check in _updateChildNodes/shady.html if the real parentNode is the container.  See code below.

```javascript
_updateChildNodes: function(container, children) {
        var composed = getComposedChildren(container);
        var splices =
          Polymer.ArraySplice.calculateSplices(children, composed);
        // process removals
        for (var i=0, d=0, s; (i<splices.length) && (s=splices[i]); i++) {
          for (var j=0, n; (j < s.removed.length) && (n=s.removed[j]); j++) {
            if (container === n.parentNode) {
                remove(n);
            }
            composed.splice(s.index + d, 1);
          }
          d -= s.addedCount;
        }
        // process adds
        for (var i=0, s, next; (i<splices.length) && (s=splices[i]); i++) {
          next = composed[s.index];
          for (var j=s.index, n; j < s.index + s.addedCount; j++) {
            n = children[j];
            insertBefore(container, n, next);
            composed.splice(j, 0, n);
          }
        }
      },
```

**Comment by sorvell** [comment]
Thanks for your patience and help tracking down these issues. 

Yes, it looks like the issue is that removing the `span` from `my-element` and putting it into the fragment puts it in the fragment and then prompts `my-element` to distribute. When that happens, `my-element` assumes the `span` is still its responsibility and removes it. Your suggestion probably makes sense, thanks.

**Comment by eeid26** [comment]
I really appreciate the work you are doing. I know how difficult the code you are dealing with. Please keep the great work you are doing.
