### ISSUE TITLE
the docs say dom-repeat filter "follows the standard  Array filter API" but it doesn't

### ISSUE THREAD

**Issue by sjmiles** [Polymer/polymer#2361]
In particular, [Array filter API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) callback is "Invoked with arguments (element, index, array) ", but dom-repeat only sends `element`.

One could say this is a bug in the docs, but it seems better to make it true than to change to docs.

**Comment by samccone** [comment]
:+1: good call @sjmiles

**Comment by rohni** [comment]
:+1: also suffering from this, as trying to ellipsis content of an array kind of needs the index

**Comment by arthurevans** [comment]
@kevinpschaaf any thoughts on this? When @sjmiles first mentioned this, I didn't open a docs issue because it wasn't clear to me whether the correct fix was to update the docs or the code. 

But looking at it again, it appears to me that given the way you're optimizing added items, this is not really practical: 

https://github.com/Polymer/polymer/blob/master/src/lib/template/dom-repeat.html#L461

**Comment by kevinpschaaf** [comment]
Unfortunately, `dom-repeat` fundamentally works on stable array "keys" rather than indices, and at the point where the user `filter` function may be called, index of the item is not always known (and lookup would be O(n)), hence it's not a trivial fix to add this.

If you forgo the performance impact of doing the lookup, you could lookup the index of the item in the filter function:

```
filter: function(o) {
  var idx = this.items.indexOf(o);
  ...
}
```

**Comment by rohni** [comment]
Ach well, I worked around it, and if it is a lot of work probably not worth it. But, I *do* think that the docs should be updated, because it is misleading at the moment.

**Comment by arthurevans** [comment]
@rohni: absolutely agree. I've opened a docs issue to track this and will try and get it fixed this week.

**Comment by kevinpschaaf** [comment]
Closing per https://github.com/Polymer/docs/issues/1381; website documentation is updated.
