### ISSUE TITLE
Bindings only update when using full path or by replacing object

### ISSUE THREAD

**Issue by ZackAdams** [Polymer/polymer#2373]
I have a an array being displayed by a dom-repeat template where I am trying to update individual values using a separate object for convenience. Updating the array using the temporary object yields no updates to template even though the model has changed.

Here is an example of a few methods of trying to get the template to update and reflect the changes. 

http://plnkr.co/edit/0PsFzJrdZwXYPlcG8NTK?p=preview

Only setting the value using the full path or by creating a new object seems to work. This can be annoying when updating several properties at once.

**Comment by azakus** [comment]
From what I understand, the way the Array observation works in Polymer requires that you modify the array values in a way that changes either the identity of the property, or a subproperty directly.

Trying to modify an item in the array without explicitly notifying using that path will not work because the effect of the modification is not observable.

@kevinpschaaf can update if I'm incorrect.

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/picocijute/edit?html,console,output
