### ISSUE TITLE
Polymer.dom(event).localTarget returns undefined

### ISSUE THREAD

**Issue by urandom** [Polymer/polymer#2374]
Under certain conditions, calling Polymer.dom(event).localTarget returns undefined. I was under the assumption that the property will always be defined, so if that's not the case, please close this issue. The conditions I noticed this in are a bit specific for me, though I think the 'dom-if' element is most likely the cause of it. This is essentially what I have:

``` html
<my-custom-scaffold>
<paper-drawer-panel>
   <paper-header-panel drawer>
     ...
  </paper-header-panel>

   <paper-header-panel main>
     <paper-toolbar>
      <template is="dom-if" if="[[ narrow ]]" restamp>
        <content select=".main-title"></content>
      </template>
    </paper-toolbar>
   <div class="content">
       <template is="dom-if" if="[[ !narrow ]]" restamp>
        <content select=".main-title"></content>
      </template>
   </div>
  </paper-header-panel>
</paper-drawer-panel>
</my-custom-scaffold>
```

``` html
<my-custom-scaffold>
   <div class="main-title">
       <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
   </div>
</my-custom-scaffold>
```

Essentially the paper-drawer-toggle didn't do anything because the _onTap listener in the drawer-panel did get a valid localTarget.

**Comment by jaichandra** [comment]
This is definitely a bug with ShadowDOM.
https://github.com/Polymer/polymer/issues/1921#issuecomment-282802436

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with Polymer 2 for us to be able to debug and potentially fix. Polymer 2 fixes a large amount of issues, probably including this one as well.

Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with Polymer 2.  Thank you!
