### ISSUE TITLE
font-face support?

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2386]
Style referenced using `link[rel=import][type=css]`.
`@font-face` declaration inside it is ignored in Chromium 44, there is even no HTTP request in Network panel of Dev Tools, but works fine in Firefox.
Shadow DOM.

**Comment by seaneking** [comment]
Pretty sure this is due to a long ongoing issue with the scoping of certain at-rules in a shadow root (primarily `@font-face`). See [this chrome bug](https://code.google.com/p/chromium/issues/detail?id=336876) discussing it.

Quick fix is to chuck `@font-face` rules in a separate `<style>` outside your dom-module. Just be aware that they'll be part of the global scope though.

**Comment by nazar-pc** [comment]
I already did so just for `@font-face`, but it is quite ugly

**Comment by seaneking** [comment]
Yup, agree. Only way around it AFAIK though.

**Comment by vdhpieter** [comment]
Is there already a solution to use custom fonts in polymer?

**Comment by TimvdLippe** [comment]
Sadly this is an upstream bug of HTML imports in combination with `@font-face` (as @seaneking pointed out there is a discussion at https://bugs.chromium.org/p/chromium/issues/detail?id=336876). To resolve this issue Chrome would need to fix the incompatibility. We can take another look once the issue would be fixed.
