### ISSUE TITLE
add api for extend behaviors for previous registered elements

### ISSUE THREAD

**Issue by Punk-UnDeaD** [Polymer/polymer#2438]
I need listen 'create' event for iron-iconset-svg element.
For this I scan Polymer.telemetry.registrations and search needed element proto, and add behaviour to array

But I think this not good idea, i want official api for this

**Comment by azakus** [comment]
We're not interested in supporting monkeypatching of already-registered elements as a first class feature.

FWIW, you can use `Object.getPrototypeOf(document.createElement('iron-iconset-svg'))` and modify the prototype that way.

*Note*: modifying custom elements' prototypes may not work as expected in IE 10, because the prototype chain is not exposed correctly.
