### ISSUE TITLE
Internal property is exposed as attribute 

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#2440]
The primer and web site docs both imply that you need to add a property to the `properties` object to get deserialization from an attribute: https://github.com/Polymer/polymer/blob/master/PRIMER.md#attribute-deserialization and here: https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-deserialization

However, it appears that if I bind a value -- even a "private" property -- it's automatically exposed as an attribute. See:

http://jsbin.com/mecoha/edit?html,console,output

I'm not sure if this is intentional or a side-effect of some other feature, but it seems buggy that you can't _not_ publish something as an attribute, and weird that it's a side-effect of binding the value (i.e., it doesn't work with just _any_ property, only the ones that are bound or in properties).

**Comment by samccone** [comment]
woah excellent catch @arthurevans I agree, this is unexpected!

**Comment by kevinpschaaf** [comment]
This is intentional.  The `type` in `properties` has only ever served to determine _how_ attributes are deserialized, not _if_ they are.  Not requiring a property to be in the properties block to deserialize was added as an (undocumented?) shorthand, and the case you suggested in the jsBin -- a user explicitly defining an underscore-prefixed attribute should be considered as bad-form as a user referencing an underscore-prefixed property, i.e. the user knows they're doing something wrong.

That said, the `micro-perf` branch that will be merged soon will filter out `_`-prefixed properties from deserialization as a performance optimization (needless attempt at deserializing can add up): https://github.com/Polymer/polymer/compare/micro-perf?diff=split&name=micro-perf?w=1#diff-954b2c8fdbb5ae157e3d0957dd1c5d66R158, which I think should eliminate the main concern you highlighted.

**Comment by TimvdLippe** [comment]
Issue seems to be fixed in Polymer 2: http://jsbin.com/tawudayeda/edit?html,console,output
