### ISSUE TITLE
Manually notifying parent property, which child changes

### ISSUE THREAD

**Issue by tpluscode** [Polymer/polymer#2449]
Hi. In [this plunk](http://plnkr.co/edit/dGdyWQ?p=preview) I'm changing a child of data-bound property but I'm not binding to those subproperties directly but only to the root.

How can can I force binding recalculation? Currently I'm unsetting and setting the value but it's ugly at best

```
this.clickHistory = null;
this.clickHistory = clickHistory;
```

I tried using the `notifyPath` method but that didn't work.

**Comment by jfrazzano** [comment]
You can flush, use an iron signal, bounce off the cache, use a service worker element, use the select in a content drop point, or even go so far as to create your own named function, which you make self calling, wrap in another function and then "bind" it to .window.   The function then becomes global and capable of more or less notifying anything. If you have a simple array of "things" to notify, it's low brow hack that is resource cheap.  

We did it with a "clock" to create a poor man's event API. By running the clock in one instance but effectively everywhere, it turned out to be  no more resource expense than running a list or other animation.  

If the => method becomes standard, well notifying and binding without much rigamarole become standard fare. 

Could be real cool real soon.

**Comment by sorvell** [comment]
Here's a working plunkr: http://plnkr.co/edit/eHT2mqVWP2Sp3YCml14K?p=preview

As you can see using `set` does work. One missing bit in your code is that you need to depend on `clicks.*` to see changes to sub-properties of `clicks`.

Having to inform Polymer of all of your changes to object sub-properties is something with which we're definitely not happy. We're working on improving this. Closing this bug in favor of: #3343

**Comment by tpluscode** [comment]
Cool, thanks! Is the wildcard notation as in `clicks.*` documented somewhere?

**Comment by MeTaNoV** [comment]
You can have an explanation here: https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#dependent-properties
