### ISSUE TITLE
Polymer components installed through bower

### ISSUE THREAD

**Issue by shatakshidixit** [Polymer/polymer#2465]
I am using polymer components in angular2.

when i install any component say paper-button with bower in command line,the version of component installed with bower is different from the one which is used in polymer demo.

The problem here is that the versions of components(say paper-button and paper-spinner) installed from bower needs to have different versions of polymer.

Please update the bower so we can easily install all components from bower that are up to date and needs the same version of polymer.

**Comment by azakus** [comment]
Bower updates automatically from tags, so as soon as we tag an element on github, it is available in bower.

I suspect your issue is that you are mixing elements from the Polymer org and the PolymerElements org.

If you are using Polymer 1, use repos from PolymerElements org. If you are using Polymer 0.5, use repos from Polymer org.

Sorry that this is confusing, but we are trying to still support users of Polymer 0.5, and if we removed the older repos it would break those uses.

**Comment by shatakshidixit** [comment]
ok thanks :+1:
