### ISSUE TITLE
Unknown the meaning of this selector

### ISSUE THREAD

**Issue by itamayo** [Polymer/polymer#2474]
I don't know if is a bug or I don't understand the way this type of selectors works.

http://jsbin.com/nawanoqiju/edit?html,js,output

A div with id innner is inside the x-test component, the stylesheets returns this selector:
#inner.x-test As far as I know "." is reserved for class and could not concate with any other token.
Could anyone explain me how this works ?

Best

**Comment by zoechi** [comment]
Stackoverflow.com would be a better place for such generic development questions. This selector looks for elements with id `inner` AND class `x-test`. If you leave a space like `#inner .x-test` it looks for descendants of the element with id `inner` which have the class `x-test`. `#inner.x-test` is a bit weird because usually an id identifies a single element because the DOM should not contain mir than 1 element with the same id. I don't know how shady DOM handles multiple custom elements which have an element with an id in their content.

**Comment by zoechi** [comment]
Please close this issue.
