### ISSUE TITLE
Auto-binding template and event bubbling

### ISSUE THREAD

**Issue by mikaelharsjo** [Polymer/polymer#2480]
Should events bubble up from child elements to auto-binding templates?

If I do:
```js
  this.fire('lasers');
```
In a custom element wrapped by an auto binding template declared like:
```html
<template is="dom-bind" id="app">
```

And in my main script do:

```js
  var app = document.querySelector('#app');
  app.addEventListener('dom-change', function() {    
    app.addEventListener('lasers', function(){
      console.log('app caught lasers event')
    });

    document.addEventListener('lasers', function(){
      console.log('document caught lasers event')
    });
  });
```

Only the listener declared on `document` is called. Since events bubble to other elements I assumed it would bubble to auto-binding templates as well.

**Comment by ebidel** [comment]
Pretty sure this is because template children are stamped as siblings, not children. Check where the element that's firing `lasers` is in the DOM.

For example:
<img width="581" alt="screen shot 2015-09-25 at 10 36 27 am" src="https://cloud.githubusercontent.com/assets/238208/10107652/6dea73a0-6371-11e5-9b7e-2ff8304b42e5.png">

I wouldn't expect the template so see that event, but it does bubble, so `document` gets it.

**Comment by mikaelharsjo** [comment]
Ok, makes sense. Thanks.
