### ISSUE TITLE
Inconsistent property types when they are overridden.

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#2493]
A property is defined in behavior `A` and then overridden in behavior `B`. However, it uses  different property info depending on whether this attribute is set in the element. Here's a simple repro case: http://jsbin.com/labaxo/edit?html,output

**Comment by azakus** [comment]
I'm not 100% sure what *should* happen, but I guess the first behavior to "accept" a resolved value wins.

**Comment by kevinpschaaf** [comment]
Related to https://github.com/Polymer/polymer/issues/2242

**Comment by sorvell** [comment]
This issue has been addressed in Polymer 2.x:

* Fixed in 2.x: http://jsbin.com/labaxo/edit?html,output
* Bug in 1.x: http://jsbin.com/waxoxufova/1/edit?html,output

We're going to go ahead and close this since we're only making necessary maintenance fixes to 1.x and it would be difficult or impossible to address this behavior without introducing a breaking change.
