### ISSUE TITLE
Please add a callback to act or get notified when an element is registered

### ISSUE THREAD

**Issue by kristianmandrup** [Polymer/polymer#2499]
Then can be used in all kinds of interesting ways!!! Provides way more flexibility and power.
I'll make a PR for this shortly as I find this essential to my needs.
Currently I see only the following, where `_registrate` is called on registration and the prototype is added to an internal list. Would be nice with a much more powerful API. Cheers ;)

``` js
  Polymer.telemetry = {
    registrations: [],
    _registrate: function(prototype) {
      this.registrations.push(prototype);
    },
```

**Comment by niflostancu** [comment]
An official API for fetching a registered element's prototype would be great.

Meanwhile, I implemented a library for doing just this (disclaimer: a bit hackish / experimental / WorksForMe™): 
https://github.com/niflostancu/polymer-reflection

It basically intercepts the calls of several Polymer internal methods (e.g. `Polymer.Base.registerCallback`) so that it can provide notifications when a specific element is registered (allowing you to inject custom properties / methods, even behaviors).

Of course, this may break when the Polymer's implementation changes, but `bower` can help us here with its conflict resolution: we have the choice of staying with the old version if something breaks ;) 

There are many reasons of using this (e.g. patching third party elements, avoiding forking & modifying their source code). Mine was to enhance iron / paper form input elements (a much more powerful validation system, model data binding etc.).

**Comment by kristianmandrup** [comment]
Awesome @niflostancu !! I came up with a similar approach to fit my needs ;)

https://github.com/kristianmandrup/polymer-ext

I'll have a look at your reflection. We need Polymer framework to be open for extension, not closed as it is now :)

**Comment by TimvdLippe** [comment]
This has been implemented natively as [`whenDefined`](https://w3c.github.io/webcomponents/spec/custom/#dom-customelementregistry-whendefined)
