### ISSUE TITLE
Shadow Dom Conflict when integrating with Angular2

### ISSUE THREAD

**Issue by tapas4java** [Polymer/polymer#2526]
How to ask Polymer to work nicely with `Angular2`? 
I am facing the content distribution issue.

**Comment by ebidel** [comment]
Can you please add more details to this bug. A code snippet would be nice too.

There's an experimental [patch-dom](https://github.com/PolymerLabs/polymer-experiments/blob/master/patch-dom.html) feature that you can try to make other frameworks place nicely with Shady DOM. Example usage: https://github.com/Polymer/polymer/blob/c263ad590639b565fadc7f94f162b398f219d55a/test/smoke/patch/patch-dom.html

**Comment by tapas4java** [comment]
Rob discussed this content distribution issue on [AngularU](https://www.youtube.com/watch?v=7WgEuNZCCHk). 

Let me know if you want to look into my repo?

**Comment by tapas4java** [comment]
@ebidel , After using `webcomponets.js` instead of lite one and with below code, that issue got resolved.
But I want to know how to use this `patch-dom` and how this approach is different than current solution??

```
	var Polymer = Polymer || {};
	Polymer.dom = 'shadow';
```

**Comment by ebidel** [comment]
Fair enough, When filing a bug though, you need to help maintainers understand "this content". We don't have context from AngularU :) Unless you have a snippet of code that's not working, I think this bug post would a better question for slack/mailing list.

To answer your question, webcomponents.js is the full shadow dom polyfill. Angular/other frameworks work well with shadow dom b/c the composition model is transparent to them. If you use it, you don't need `Polymer.dom = 'shadow';` because the polyfills will use shadow dom (or poyfill it in non-supported browsers). In wc-lite.js, you get shady dom instead of shadow dom. `Polymer.dom = 'shadow';` opts you in to native shadow dom if it's available in the browser.

In 1.0, shady dom requires usage of the `Polymer.dom()` APIs to work with the DOM. Angular/other frameworks don't know about these APIs, therefore things can break. An example is using Angular's data binding system to stamp content. Under the hood, it will try to do so using `node.appendChild()` instead of `Polymer.dom.appendChild()`. patch-dom.html wraps the native DOM methods with the correct `Polymer.dom()` calls. In that way, frameworks making those DOM calls will let shady dom know things like distribution have changed.

**Comment by tapas4java** [comment]
Thanks for the explanation @ebidel,

Sorry regarding the less context(I thought its a common issue). Will take care next time :)

**Comment by AndreasGalster** [comment]
Hi Eric, this explanation of how shady dom works and opts in to use the native shadow dom when available and the overall explanation of the patch-dom is really great. I feel like an explanation on several occasions on the polymer-project site would probably be very useful until shadow dom is widely supported!

**Comment by ebidel** [comment]
Have you seen @sjmiles most excellent article? https://www.polymer-project.org/1.0/articles/shadydom.html

**Comment by Analect** [comment]
@tapas4java 
Have you been able to get a sample app working that combines Angular2 with Polymer and uses this patch-dom?  It would be great to see it in action. Thanks.

**Comment by tapas4java** [comment]
@Analect 
I didn't tried patch-dom approach however native shadow dom approach works for me.

**Comment by Analect** [comment]
@tapas4java 
Thanks. I don't suppose you have a public repo with Angular/Polymer together you could share?

**Comment by tapas4java** [comment]
There you go [ng2polymer](https://github.com/tapas4java/ng2polymer)....shows just basic `Angular2` and `Polymer` integration.
