### ISSUE TITLE
Can't access polymer member externally in firefox

### ISSUE THREAD

**Issue by Xeemed** [Polymer/polymer#2529]
The following very simple example works perfectly in chrome but does not work in firefox. 

Error message: TypeError: e.test is not a function

component.html:
```javascript
<link rel="import" href="bower_components/polymer/polymer.html">

<dom-module id="dom-element">
    <template>
        <p>I m a DOM element.</p>
    </template>
    <script>
        Polymer({
            is: "dom-element",
            test: function() {
                console.log("test");
            }
        });
    </script>
</dom-module>
```

index.html:
```javascript
<html>
<head>
    <link rel="import" href="component.html" />
    <script type="text/javascript" src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
</head>
<body>
    <dom-element id="element"></dom-element>
    <script>
            var e = document.getElementById('element');
            e.test();
    </script>
</body>
</html>
```

**Comment by ebidel** [comment]
FF needs the polyfills to boot up the html imports. As such, you need to wait for the `WebComponentsReady` event to fire before touching the element's properties/methods:
http://webcomponents.org/polyfills/html-imports/#the-webcomponentsready-event

This works in chrome because it has native imports and custom elements. The element is registered by the time it gets to your code on the bottom of the page.
