### ISSUE TITLE
dom-repeat instances not updated properly with square brackets data-binding

### ISSUE THREAD

**Issue by alberthier** [Polymer/polymer#2564]
I am using two nested `dom-repeat` templates. Their `items` collections are passed with square brackets data binding.
The model may be altered by two different user actions but, unfortunately the corresponding DOM instances aren't kept in sync.

I made a small testcase showcasing the issue:
https://jsbin.com/nokutowovi/1/edit?html,output

Each displayed item may be "toggled" by clicking on it.
All items can be "toggled" with the "Toggle All !" button.

Steps to reproduce:
* Click on "item 1.1"
  * => "TOGGLED" appears after, **OK**
* Click on the "Toggle All !" button
  * => The "TOGGLED" state of all items is reversed, **OK**
* Click on "item 1.1" again
  * => "TOGGLED" appears after, all items are in the same state, **OK**
* Click on the "Toggle All !" button
  * => "item 1.1" is left unchanged, **NOK**

If I replace the square brackets in the `items` attribute of each `dom-repeat`, everything works as expected.
Another workaround I found is to use the element's `set` method:
`this.set('items.' + itemIndex + '.subitems.' + subItemIndex + '.toggled', !this.items[i].subitems[j].toggled);`
in `onItemClicked` instead of
`event.model.set('subitem.toggled', !event.model.subitem.toggled)`

The documentation states that square brackets can be used for one-way data binding which is the case here. Or I misunderstood something and square brackets are only for static data ?

**Comment by jobbo** [comment]
I think this is expected behavior of ony-way binding.
So in this case, it mean outer dom-repeat data model and inner dom-repeat data model are NOT in-sync

when you change the subitem.toggled using below method.
        `onItemClicked: function(event) {
          event.model.set('subitem.toggled', !event.model.subitem.toggled);
        },`
it will change the inner data model

but when you change all subitem.toggled using onButtonClick function, it will change the outer data model.

if you replace square brackets [[ to {{ it will works because it's two-way binding that sync outer data model and inner data model.

**Comment by alberthier** [comment]
I don't agree, the documentation defines "data binding" as the relation between the Javascript model containing the data and the DOM.

I understand it as:
* Square brackets: JS => DOM (ex: an `<input>` **won't** modify the JS model)
* Curly braces: JS <=> DOM (ex: an `<input>` **will** modify the JS model)

Maybe my first testcase was too complicated, I noticed the bug has nothing to do with `dom-repeat` nesting.

Here is a testcase with a single `dom-repeat` reproducing the issue too:

https://jsbin.com/ruzanugewi/edit?html,output

**Comment by ebidel** [comment]
I believe this reduces to the way you're updating .toggled. In this case:

    onItemClicked: function(event) {
          event.model.set('item.toggled', !event.model.item.toggled);
    },

    <template is="dom-repeat" items="[[items]]">
        <li on-click="onItemClicked">
          <span>[[item.val]]</span>
            <template is="dom-if" if="[[item.toggled]]">
              <span>TOGGLED</span>
            </template>
        </li>
      </template>

You're updating an individual item using `event.model`. The `items="[[items]]"` binding doesn't see the updated item.toggle because it's download. If you change it to two-way (`items="{{items}}"`), it will see the update and re-render.

Safer, would be to use `this.set()` instead of `event.model`. So the update gets pushed down through the dom-repeat:

    onItemClicked: function(e) {
      this.set(['items', e.model.index, 'toggled'], !this.items[e.model.index].toggled);
    },

If you do that, you can also keep the `[[]]` bindings everywhere.
