### ISSUE TITLE
Automatically unregister listeners and node observers on detachment

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#2567]
The introduction of this feature https://github.com/Polymer/polymer/pull/2548 got me thinking of how often people might forget to **un**register an observed node https://github.com/PolymerElements/iron-selector/blob/observe-nodes/iron-selectable.html#L144

Thus creating a memory leak :fountain: (my fav)

What would you think about Polymer automatically cleaning up these registrations for us on (detached), unless we explicitly opt out per element.

---

**R:** @ebidel @cdata @tjsavage

**Comment by ebidel** [comment]
Gets a :+1:  from me. Polymer's goal is to make developers' lives easier, and this type of cleanup is something we can smooth over. Since we provide helpers (listen/unlisten/observeNodes), those should be even more helpful than their native equivalents. If someone doesn't want this behavior, we could have an optional param...or better yet, that's the case to use the native methods :) @tjsavage for prioritization.

**Comment by azakus** [comment]
In 0.5 we had an asynchronous "deflate" that would remove event listeners, etc.
Maybe that is worth re-exploring.
