### ISSUE TITLE
Shim not adding element name class to child elements

### ISSUE THREAD

**Issue by relicmelex** [Polymer/polymer#2623]
I'm not sure where to point this, so here's the description:

When using `let elem = document.createElement( * )`  and `this.querySelector( * ).appendChild( elem )` the classList is not appended the name of the element which is necessary for any `<style>` attributes that are defined in the `<dom-module>` to the children elements.

Maybe this is intentional?

**Comment by ebidel** [comment]
Is http://jsbin.com/lovabijona/edit?html,output what you mean?

The shimmer is applying the scoping for me when using `document.createElement`.

![screen shot 2015-10-26 at 3 29 27 pm](https://cloud.githubusercontent.com/assets/238208/10744366/99e243be-7bf6-11e5-8def-69d118f22c2c.png)

**Comment by relicmelex** [comment]
hrm... I had to manually add it to the classList... let me see if I can give you a better set of steps to repeat

**Comment by relicmelex** [comment]
Ahhh, in fact the link you posted is not what I meant... I meant: http://jsbin.com/relitibeza/1/edit?html,output
<img width="326" alt="screen shot 2015-10-27 at 9 18 47 am" src="https://cloud.githubusercontent.com/assets/1679501/10764509/dd485aae-7c8b-11e5-8c43-4cd65a673cd5.png">

**Comment by Atawergi** [comment]
Hi guys, is there anyone

**Comment by azakus** [comment]
This is probably related to the other limitations of the styling system: https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-properties-shim---limitations-and-api-details

@sorvell, is there a way to add an element to the styling system dynamically?

**Comment by arthurevans** [comment]
@relicmelex That's because you're not using the Polymer DOM API. Instead of `this.appendChild`, use: 

          Polymer.dom(this.root).appendChild( div );

And the styles are scoped properly. 

In shady DOM, `this.children` is basically the _composed_ tree (local DOM and light DOM nodes together) so the browser can render it correctly. Shady DOM does a bunch of bookkeeping internally to make sure nodes get distributed and scoped correctly.

Using the Polymer DOM API maintains the integrity of the shady DOM, and is also compatible with native shadow DOM. 

For more information, see:

https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api

**Comment by relicmelex** [comment]
@arthurevans not even sure where I'd have looked to find that in the docs. Thanks, I'll dive into this.

**Comment by relicmelex** [comment]
@arthurevans Thanks :+1:
