### ISSUE TITLE
Styling per conditional template

### ISSUE THREAD

**Issue by BartKoppelmans** [Polymer/polymer#2627]
When I have two styles for a conditional template, it takes the last style. Example:

```html
<dom-module>
<template>
    <style>
      :host {
        --common styling--
      }
    </style>
  
    <iron-media-query query="min-width: 720px" query-matches="{{isWide}}"></iron-media-query>
    
    <template is="dom-if" if="{{!isWide}}">
      <style>
        :host {
          --specific styling 1--
        }
      </style>      
    </template>

    <template is="dom-if" if="{{isWide}}">
      <style>
        :host {
          --specific styling 2--
        }
      </style>      
    </template>
</template>
</dom-module>
```

The "specific styling 2" will be used in this case, the wanted behaviour would be to use the "specific styling 1".

Don't know if this is normal behaviour and if a workaround is needed for me, or if it is a problem. Please let me know how to solve this.

**Comment by ebidel** [comment]
This is expected and due to the way Polymer handles styling. 

The css shimmer prefixes (scopes) element styles with the name of the element and moves them into the `<head>` of the main page. That's how shady dom does its magic to work x-browser.

<img width="479" alt="screen shot 2015-10-26 at 9 05 47 am" src="https://cloud.githubusercontent.com/assets/238208/10734575/3186c0e0-7bc1-11e5-813a-2e3046c07c87.png">

Under native shadow dom, `<style>` stay in the element's shadow root:

<img width="490" alt="screen shot 2015-10-26 at 9 08 07 am" src="https://cloud.githubusercontent.com/assets/238208/10734572/2b090386-7bc1-11e5-933c-99dd1ce71da8.png">

Instead, I recommend keeping all styles in the top-most `<style>` in your element and use a class to style differently based on the width. Alternatively, you can set `isWide` to `reflectToAttribute: true` and style the host based on that :+1: 

    :host([is-wide]) { ... }

[Example how paper-header-panel does this](https://github.com/PolymerElements/paper-header-panel/blob/master/paper-header-panel.html#L159)
