### ISSUE TITLE
<content> needs to be wrapped in a container for dom-if to properly hide distributed nodes

### ISSUE THREAD

**Issue by mhusm** [Polymer/polymer#2635]
I've asked this already on [Stackoverflow](http://stackoverflow.com/questions/33363795/polymer-nesting-a-content-tag-inside-a-conditional-template), but since it could be a bug I'm also filing it here.
I'm using a conditional template to distribute content that is passed into the element. If the condition is true, it will show the first content element, otherwise the second. I noticed that when I update the condition the already distributed content is not updated. Once it is visible it will remain visible. Local content in contrast is updated as expected. I've created a [plunker](http://plnkr.co/edit/LbKbJbEK6ZXv9LMl8zsT?p=preview) that demonstrates the behaviour.
Someone on Stackoverflow pointed out that I could use `restamp`, which does solve the problem. Still, I would expect the distributed content to be hidden just like the local dom when `restamp` is not used.

**Comment by ebidel** [comment]
It looks like the bug is that the `<content>` needs to be wrapped in a container for dom-if to apply `[hidden]` to it. This also works:

    <div>Local content one</div>
    <div><content select=".first"></content></div>

`restamp` works because it destroys the dom and recreates it when the binding is truthy. Without `restamp`, Polymer just applies the `hidden` attribute (e.g. hides the content using css).

@kevinpschaaf @sorvell  for thoughts

**Comment by kevinpschaaf** [comment]
This is as-designed, per @ebidel's answer.  Hiding a `<content>` has no effect on the visibility of its distributed children (per spec), so your options are to wrap the content with a wrapper element that _can_ be hidden (and will hide the distributed children), or use `restamp` which will pull the `<content>` out of the DOM all together.

It is slightly unintuitive that the `restamp` and non-restamp setups work differently, however it is a result of the non-restamp behavior which hides rather than destroying DOM as a performance optimization.

**Comment by ebidel** [comment]
BTW, you can verify this with native shadow dom. `<content hidden>` does not participate in rendering. It's simply a location to invite content into the shadow dom.

**Comment by mhusm** [comment]
Thanks for clarification.

**Comment by ansarizafar** [comment]
@ebidel restamp is not destroying async loadied light dom element even If  <content> is wrapped in a container. Is it a bug or normal behavior. If its a bug, is there any workaround?

**Comment by ebidel** [comment]
Sounds like a lot going on there. Please file a new ticket with a repro.
