### ISSUE TITLE
set and bind doesn't work from outside

### ISSUE THREAD

**Issue by fooloomanzoo** [Polymer/polymer#2638]
If you try to set a value from outside, it doesn't notify the changes. Also a factoryImpl-Constructor, which binds data by caling set, doesn't bind so that the element notifies it.

``` javascript
<dom-module id="name-tag">

  <template>
    <section on-click="adduser">Click to add a user</section>
    <section id="main">
    </section>
    <ul>
      <template is="dom-repeat" items="{{user}}">
        <li>{{item.name}}</li>
      </template>
    </ul>
  </template>

  <script>
    Polymer({
      is: "name-tag",
      properties: {
        user: {
          type: Array,
          value: function() { return [] },
          notify: true
        }
      },
      ready: function() {
        var dynamicEl = new ChildElement(this.user);
        //var dynamicEl = document.createElement('child-element');
        //this.set('user',this.user,dynamicEl);
        //dynamicEl.notifyPath('user',this.user);
        this.$.main.appendChild(dynamicEl);

        // set some users
        this.push('user', { name: "Shakh", surname: "Samat", age: 15 });
        this.push('user', { name: "Jambyl", surname: "Samat", age: 17 });
        this.push('user', { name: "Aiganym", surname: "Samat", age: 18 });
      },
      adduser: function() {
        // add a user
        this.push('user', { name: "William", surname: "Sulo", age: 19 });
        console.log("added");
      }
    });
  </script>
</dom-module>

<dom-module id="child-element">
  <template>
    <div>
      <ul>
        <template is="dom-repeat" items="{{user}}">
          <li>{{item.name}}</li>
        </template>
      </ul>
    </div>
  </template>
  <script>
    ChildElement = Polymer({
      is: 'child-element',
      factoryImpl: function(users) {
        this.set("user", users);
        //this.notifyPath("user",this.user);
      },
      properties: {
        user: {
          type: Array,
          value: function() { return []; },
          notify: true
        }
      }
    });
  </script>
</dom-module>
```

Link: http://plnkr.co/edit/Ybv7m1ecwzcwSjGXKDpT?p=preview

**Comment by arthurevans** [comment]
The path you're setting is always _relative_ to the element you're calling `set` on. When you create a binding between a host element and a target element in its local DOM, you create a mapping between two different paths: the host path and the target path.

Because you don't have a data binding here, Polymer doesn't have any _path_ relationship between `<name-tag>.user` and `<child-element>.user`, _even though they're the same object._ So `this.set` is updating the shared _object_, but `<child-element>` never receives a notification.

**Comment by fooloomanzii** [comment]
That's totally right and I see it the same way. The favored data elements are always in a diferent relative level to each other. The question is, how to realize a notified data binding from calling factoryImpl or from outside, because this is what a constructor would implicate?

**Comment by azakus** [comment]
What's missing here is the ability to hook a dynamically created element into the data binding system.
Providing `factoryImpl` is not enough because the data binding hooks are processed from HTML syntax.

You can try copying some of the steps that `<template is="dom-bind">` uses to establish itself in the data binding system, but I have no guarantees it will work, nor that it will be stable to use (these are all private APIs).

@kevinpschaaf, adding API for registering an element into the data binding flow might be something worth considering in the future.

**Comment by hickscorp** [comment]
@azakus +1 for the programmatically bindings.

I had this use case recently:

- Consider a list of non-homogeneous objects that you want to render.
- Based on each list element nature, a different component could be used.
- A dom-repeat is ruled out because it would complexify the code.

I ended-up trying to instantiate the components programatically... Then I realized that once I had the bunch of components in the DOM, I had no idea how to establish bindings to them.

I have done some research regarding this, and found those innerBoundHTML thingies, but yet have no idea on how to use them (I'm fairly new to Polymer).

So feature request: bindings API from the javascript code :+1:

**Comment by bedeoverend** [comment]
@azakus Looks related to #1796 - bringing back data binding API?

**Comment by warpech** [comment]
+1

**Comment by kaste** [comment]
Can you take a look at #3456 (and its related PR #3460) and perhaps comment if that would fix your issue.

**Comment by fooloomanzii** [comment]
@kaste It would be nice, if you post an example of working code, so that it is better understandable, which situation your solution is suitable for.
