### ISSUE TITLE
Polymer DOM nextSibling/prevSibling operations are slow

### ISSUE THREAD

**Issue by Artur-** [Polymer/polymer#2645]
Import Polymer
```
var l = document.createElement("link");
l.setAttribute("rel","import");
l.setAttribute("href","https://rawgit.com/Polymer/polymer/v1.2.0/polymer.html");
document.head.appendChild(l);
```

Use nextSibling
```
var ul = document.createElement("ul");
for (i=0; i < 1000; i++) {
  var li = document.createElement("li");
  ul.appendChild(li);
}

var start = window.performance.now();
var e = ul.firstElementChild;
for (i=0; i <999; i++) 
  e = e.nextSibling;

console.log(e);
console.log("Native performance: "+(window.performance.now()-start)+"ms");

var start = window.performance.now();
var e = ul.firstElementChild;
for (i=0; i <999; i++) 
  e = Polymer.dom(e).nextSibling;

console.log(e);
console.log("Polymer performance: "+(window.performance.now()-start)+"ms");
```

Results on Chrome:

Native performance: 1.680000000000291ms
Polymer performance: 315.79499999999825ms

**Comment by nazar-pc** [comment]
With full Shadow DOM polyfill it is not that bad (Firefox):
Native: 2.665000000000873ms
Full Shadow DOM polyfill: 5.674999999999272ms
Polymer under full Shadow DOM poyfill: 6.005000000001019ms

Polymer performance using native Shadow DOM is also good (Chromium):
Native: 1.269999999999527ms
Polymer: 1.3450000000002547ms

So the problem seems to be in Shady DOM itself. It is rather surprising that even full Shadow DOM polyfill seems to perform much faster here.

**Comment by sorvell** [comment]
This is due to the fact that these lookups are O(n) in Polymer.dom currently. This was known and should be fairly easy to fix. We weren't sure of the severity of the issue so it's good to have this feedback.
