### ISSUE TITLE
Is it possible to add a behavior to an existing custom element?

### ISSUE THREAD

**Issue by hobbyquaker** [Polymer/polymer#2675]
I know that extending custom elements like in 0.5 isn't possible in 1.0, but what about adding just additional behaviors?

**Comment by zoechi** [comment]
Sure, s what behavbehaviors are for. https://www.polymer-project.org/1.0/docs/devguide/behaviors.html

**Comment by hobbyquaker** [comment]
Hmm, then I fear I don't fully understand the Docs ;)
I will try to explain a bit further what I'm trying to do:
I created a Behavior that does some publishing to a mqtt broker when the checked attribute of the element changes. How can I add this behavior to f.e. paper-checkbox? 
Right now I worked around the Problem (of not knowing how to add the behavior to an existing element) by encapsulating paper-checkbox in my own custom element, but I think that isn't a real good solution, so I'd like to add my behaviors/properties to e.g. paper-checkbox directly.

**Comment by arthurevans** [comment]
The short answer is _no_, you can't add a behavior to an existing element, and your best course of action is to use composition as you are now.

The elements folks have tried to factor out as much code into behaviors as possible, so it's easier to reuse that code in your own elements. But in this case, I think you want all of `paper-checkbox`, so that doesn't really help you.

The ability to extend an element is still on the roadmap, but it's a complicated one. You can follow that bug: https://github.com/Polymer/polymer/issues/2280.

**Comment by hobbyquaker** [comment]
Thanks for the Information!
