### ISSUE TITLE
dom-repeat doesn't reflect to computed property properly when array mutation occurs

### ISSUE THREAD

**Issue by jobbo** [Polymer/polymer#2687]
I've tried to use computed property array 
```javascript
   <template id="repeater" is="dom-repeat" items="{{filter(arr.*)}}">
```

please see example here http://jsbin.com/zikelazayo/edit?html,console,output

as you can see that without this.`$.repeater.render();` in `isarrChanged`, trying to tweak array in arr property won't reflect to dom-repeat UI.

however, when trying to return the new arr reference, (which in this case occurred by using filter to return new set of array, the dom-repeat UI reflect to new array without `this.$.repeater.render();`

is this expected behavior?

*Please note that in my real project my array contain a complex array structure which will be rendered into tree-like structure, so the dom-repeat filter feature provided by Polymer wont fit my requirement, so I need to implement filter function myself.

**Comment by azakus** [comment]
You should use the filtering API that dom-repeat provides: https://www.polymer-project.org/1.0/docs/devguide/templates.html#filtering-and-sorting-lists

If you put the filter function into `items`, that breaks the link between the array and the dom-repeat because the array returned from your filter function is not the same array object.

Here is a working example: http://jsbin.com/hamujow/edit?html,output
