### ISSUE TITLE
Bindings in <style> no longer work under polyfill

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#270]
According to http://stackoverflow.com/questions/18702448/mustache-expressions-not-working-anymore-in-polymer-styling, bindings in `<style>` no longer work. 

Try: http://jsbin.com/ODEGika/3/edit

Canary works correctly for me but Chrome 29 (polyfill) does not.

**Comment by Nevraeka** [comment]
@tjsavage - this one appears working now for me. Can we close this?

Based on @dustindowell22 's jsbin example I created a codepen to test this out.
[Codepen example of style binding](http://codepen.io/Nevraeka/pen/qEJxBr?editors=101)

**Comment by tjsavage** [comment]
Thanks! yes we can close this

**Comment by Mygod** [comment]
Wait what? That example isn't working for me in Firefox 36.0.1...

**Comment by Nevraeka** [comment]
I didn't add shims for styling because the selectors were the issue. I'll update ASAP

**Comment by bigdave** [comment]
@tjsavage @Nevraeka The Codepen example above seems to work in Chrome, but not Firefox.  Can we reopen this?

**Comment by caiowilson** [comment]
FF is a major pain. That's why i've been away from polymer for a while. I had to make a decision about my project and shift it away (for now) from polymer as the deadline got shorter and it's definitely not ready for production. Chrome is as smooth as butter yet firefox just seems like it's purposely making it harder for the web components trend. Can't know why, maybe it's about focusing on FF OS maybe it's about being a jerk and going against google (mainly chrome).

**Comment by dhubler** [comment]
I didn't see a lot of FF only issues in 0.5 so it appears mileage may vary.
@caiowilson, feel free to post a list of important FF issues for others can
be aware.

**Comment by caiowilson** [comment]
I am sorry, right now I don't have the time. But i'll sure do as soon as I can.

**Comment by Nevraeka** [comment]
im working w/ my codepen now. Just to reiterate so we are on the same page, FF seems good on bindings not in the CSS from what I can see. CSS works other than the obvious binding so this makes me think its either in the binding part of polymer or the shadowCSS in webcomponents.js. Looking into this now

**Comment by bigdave** [comment]
Verified the same behavior in IE11 as in Firefox: bindings seem to work everywhere except in <style> tags.

**Comment by davidmaxwaterman** [comment]
We have a css rule :

```
    [data-role="tree"] {
      transition: background-color {{ANIMATION_LENGTH_SECS / 2}}s ease-in;
      -webkit-transition: background-color {{ANIMATION_LENGTH_SECS / 2}}s ease-in;
    }
```

and the webkit line is ignored by safari. If I hard-code the binding, then it's fine. I wonder if someone can tell me how I can get it working, if it can.

**Comment by caiowilson** [comment]
@davidmaxwaterman I've been away from polymer but if you could provide a codepen/jsbin/whatever I'd try to help you. :)

**Comment by davidmaxwaterman** [comment]
Sorry, it's too big. I think the snippet is pretty clear...the binding doesn't work, so it's as simple as that. 

I think the answer is either 'it doesn't work' in a polyfill, and/or I need to do something special about it for polyfill to work as expected. I see some of both of those in the discussion above, but I'm not sure what to try. What are the options?

I'm wondering about ```no-shim``` - seems easy to try so I'll give it a shot.

Suggestions welcome (using 0.5.5).

Thanks.

**Comment by davidmaxwaterman** [comment]
OK, I found out how to make it work. It was more a matter of understanding how the polyfill works, and then applying generic css rules taking those into account. A combination of no-shim and working out where the targets actually were.
One problem was the use of IDs in elements - am I correct in thinking we can't use them if they're not unique in the document, while that is perfectly ok in a shadowDom (of course)?
I ended up putting a class on some elements so that I could target them specifically - similar elements occurred in other places, so I wanted specific style to the instances.
It was complicated further by paper-dialog - it moves everything so it is a child of <body>.
Anyway, while a bit messy now, it works and has made some sense.
Thanks.
