### ISSUE TITLE
Dirty-checking not occuring on native Date values 

### ISSUE THREAD

**Issue by bendavis78** [Polymer/polymer#2719]
Polymer's dirty-checking seems to overlook date values:

``` javascript
Polymer({
  /* ...snip... */
  _dateChanged: function(value, oldValue) {
    console.log(value === oldValue); // false
    console.log(value.getTime() === oldValue.getTime()); // true
  }
});
```

If a property is defined using the native `Date` type, polymer should convert to timestamps before dirty-checking.

**Comment by ebidel** [comment]
This is a gotcha. Polymer doesn't use dirty checking at all. Instead, it uses getters/setters and looks at the old/new values to see if something has changed for the data binding system to update itself.

I don't know how you're setting your dates, but I suspect what's happening is that you're creating new Date objects, which JS treats as different. For example, `new Date(123) != new Date(123)` because they're different objects.

I wonder if we can do something to smooth this over?

**Comment by bendavis78** [comment]
Yeah, maybe I was using the term dirty-checking incorrectly? I know Polymer uses getters and setters, but the setter function also checks for inequality before changing the value in `__data__`.  If the values are equal then it doesn't do anything, and no effects are effected.

The benefit of this is to help prevent the "ping-pong"recursion you can sometimes get with more complex binding dependencies. It caught me off guard at first, and I was confused for a long while until I finally decided to dig in and learn how bindings worked internally.

I suppose one could run into the same issue with plain objects or arrays, and of course I wouldn't expect Polymer to check for equality in those. However, a `Date` object represents nothing more than an integer timestamp, so maybe an equality check here is merited?

**Comment by Zecat** [comment]
Is this related that dates doesn't notify when using native methods ?
```js
this.date.setYear(2000) // no call to date's observer
this.date = new Date(this.date.setYear(2000)); // call to date's observer
```

**Comment by TimvdLippe** [comment]
The dirty checking is performed [here](https://github.com/Polymer/polymer/blob/master/src/lib/bind/accessors.html#L50). Since two dates are different objects, `!==` returns true.

To solve this, you could check for `value instanceof Date` and perform actions accordingly. It is then the question whether we want this behavior to be added in this function for performance reasons. One of the core developers could comment on that.

**Comment by TimvdLippe** [comment]
The best solution I could come up with was utilizing prototypes, my implementation is submitted as #3238.

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/xuduqagumo/edit?html,output
