### ISSUE TITLE
CSS variables in shared style modules are not applied correctly

### ISSUE THREAD

**Issue by thomashigginbotham** [Polymer/polymer#2731]
According to the documentation at https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules:

> The shared styles are applied before the styles defined inside the body of the &lt;style&gt; tag, so the shared styles can be overridden by the styles defined in the body.

However, if you use a CSS variable in a shared style, the rule is applied after the module body styles. Here's an example: https://jsfiddle.net/f1wc03r2/

**Comment by ebidel** [comment]
In the first example, `p` never turns green because `--paragraph-color: green;` never gets shimmed.
To use css props/mixins in the main page, you need to stick them in a 'custom-style':

```
<style is="custom-style">
x-foo {
  --paragraph-color: green;
}
</style>
```

The reason `p` never turns blue is a bug in the specificity. I believe https://github.com/Polymer/polymer/pull/2642 will fix it.

**Comment by thomashigginbotham** [comment]
Thanks. I understand about the variable not being shimmed, and I see that #2531 (referenced by #2642) is the same specificity issue I was noticing.
