### ISSUE TITLE
<content> not being displayed if too deep.

### ISSUE THREAD

**Issue by dannyfritz** [Polymer/polymer#283]
Is there a limitation to how `<content>` is inserted into a polymer element's `<template>`?

If I put the `<content>` in something like `<div><span><content></content></span></div>` it doesn't show.

Here is a jsfiddle demonstrating the problem: http://jsfiddle.net/dannyfritz/vqCFw/6/

I'm on Chrome 29.

![41gsxt2](https://f.cloud.github.com/assets/315788/1170134/6bd7a75e-20ca-11e3-949a-d0d7ae3223aa.png)

**Comment by yattias** [comment]
@peterwmwong The link to the issue is private. I am getting a 404.

I have been told it's been fixed, can you share a link to the fix please?

**Comment by peterwmwong** [comment]
@yattias no idea man, its been 2 years and they rewrote Polymer since I commented on this issue.

**Comment by dannyfritz** [comment]
Yeah, I have no idea what the current status is too.

**Comment by arthurevans** [comment]
This is long fixed. The shadow DOM bug isn't private; the link is broken because the polyfills were combined into to a single repo and moved to https://github.com/webcomponents/webcomponentsjs.

I took a look at the list of closed issues that mentioned "content" and nothing's leaping out at me.

AFAIKT, the _original_ jsfiddle listed above now works fine. 

And here's a version of the original bug repro in modern polymer, which also doesn't show the described symptoms:

http://jsbin.com/dupine/edit?html,console,output

So, short answer—bug fixed in 2013. If you're seeing something that you think is the same problem, it probably isn't.
