### ISSUE TITLE
Reading element's property when child is attached results in null value

### ISSUE THREAD

**Issue by govis** [Polymer/polymer#3058]
This seems to be the case when parent is declared at page level on WebComponentsReady event. It looks like parent's ready fires after the child is attached, so accessing parent's property yields an undefined even though it has been initialized with a default value:

<pre><code>&lt;head>
&lt;script src="/import/webcomponentsjs/webcomponents-lite.js">&lt;/script>
&lt;link rel="import" href="/import/polymer/polymer.html" />
&lt;link rel="import" href="child-element.html" />
&lt;dom-module id="parent-element">
    &lt;template>
        &lt;child-element>&lt;/child-element>
    &lt;/template>
    &lt;script>
    window.addEventListener('WebComponentsReady', function (event) {
        Polymer({
            is: 'parent-element',

            properties: {
                data: {
                    type: String,
                    value: 'abc'
                }
            },

            listeners: {
                'element-register': '_registerElement'
            },

            _registerElement: function (event) {
                //this.data is undefined here
            }
        });
     });
    &lt;/script>
&lt;/dom-module>
&lt;/head>
&lt;body>
    &lt;parent-element>&lt;/parent-element>
&lt;/body>

&lt;!--child-element.html-->
&lt;dom-module id="child-element">
    &lt;template>
        &lt;div>Test&lt;/div>
    &lt;/template>
    &lt;script>
        Polymer({
            is: 'child-element',

            attached: function () {
                this.fire('element-register');
            }
        });
    &lt;/script>
&lt;/dom-module>
</code></pre>

**Comment by govis** [comment]
Updated the snippet to show that it's somehow related to <code>WebComponentsReady</code> and if <code>parent-element</code> is imported from a separate .html file it works as expected.

**Comment by arthurevans** [comment]
Yeah, different scenarios can change the timing somewhat. Since `ready` (the callback that indicates the local DOM is created and value configured) is fired for local DOM children _before_ the host element, we can **guarantee** that when the child's `ready` callback is invoked, the parent is not yet configured (i.e., `this.data` is not set). 

What we can't guarantee is the ordering between child's `attached` and parent's `ready` methods (@sorvell, @sjmiles correct me if I'm wrong here), since different scenarios (polyfill, native, elements in main document waiting for WebComponentsReady, all elements in separate documents) yield different timing.

So what can you do?

1.  Don't rely on precise timing. Use an `async` call from inside the 
     child's `attached` method to delay the event a cycle and let the parent get ready, as described here:
     https://www.polymer-project.org/1.0/docs/devguide/registering-elements.html#ready-method

    For example: http://plnkr.co/edit/O4tn7BRtW6Siao6xZgdY?p=preview

2.  Even simpler, use data binding to propagate the parent value to the child. 

         <child-element data="[[data]]"></child-element>

**Comment by govis** [comment]
Thanks for explaining. If the order of events isn't guaranteed - we need to keep that in mind as changes could lead to some unwelcome implications in the logic of an app. A mention of it in the docs somewhere would be nice.

I agree that data binding is the best bet. In some cases I need to establish a contextual connection between elements models, so it's not always trivial via declarative binding so I do it in code. I will try to stick with importing elements as most of polymer's samples are done this way, so there's probably a better chance of ensuring some level of consistency.

Please close as you see fit.

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: http://jsbin.com/yedibamuja/edit?html,console,output
