### ISSUE TITLE
Template bound variables which are undefined leave a space between open and closing tag

### ISSUE THREAD

**Issue by klebba** [Polymer/polymer#3086]
It's not possible to use the css `:empty` selector on a template bound property which is `undefined` because there is a space inserted in the tag.

For example:

```
<span>[[myBoundVar]]</span>
```

when `myBoundVar === undefined`, the tag will look like `<span> </span>` -- note there's a space inserted here

when `myBoundVar === ''` the tag will look like `<span></span>` and then its possible to use `:empty` selectors on the tag

This behavior is new in Polymer 1.0 -- previous versions handled `undefined` and `''` the same way in template bindings

Repro: http://codepen.io/klebba/pen/jbovye

**Comment by JeremybellEU** [comment]
After a quick investigation, it appears that [the parser of text annotations](https://github.com/Polymer/polymer/blob/master/src/lib/annotations/annotations.html#L182) is the culprit. However, this seems intentional reading the note of @kevinpschaaf [in the test suite](https://github.com/Polymer/polymer/commit/2f1bd31d4e75b00407647cc822477d98db6c2d0f#diff-f34edf90299c8a4197ca5874d411e293R770).

Therefore it seems necessary to instantiate empty `String`s with `''` to prevent this from happening (and breaking in other browsers such as IE).

This is maybe a good thing to add in the documentation. cc @ebidel

**Comment by klebba** [comment]
Thanks for investigating -- it would be nice to know if this is strictly an IE workaround. It's strange that if I initialize the property with an empty string it works as expected. This seems contrary to the inline comments, or maybe I misunderstood them

**Comment by JeremybellEU** [comment]
Speculation:

On startup, the initial value of the `span` is `' '`. IE checks if the span is empty, which is not, so it leaves the node intact. Then Polymer assigns the default value to the node and sets the `span` to `''`.

This is pure speculation, a core developer could maybe clarify.

**Comment by kevinpschaaf** [comment]
What @JeremybellEU said is correct.  When cloning the template on IE, the text node inside `<span>{{foo}}</span>` that originally contained `{{foo}}` becomes empty, and thus IE removes it when calling `importNode` to clone the template.  Rather than complicate/slow the system with logic to re-insert textNodes in these positions after cloning, we took this simple approach or inserting a space.

The only immediate workaround is to ensure the value being bound is initialized to an empty space.

**Comment by klebba** [comment]
Ok, got it. Thanks for the explanation. This is a slight bummer because I'm not actually targeting IE

**Comment by klebba** [comment]
@kevinpschaaf will Polymer 2.x incorporate this same workaround?

**Comment by jehna** [comment]
@klebba At least the current `2.0-preview` branch seems to have the same issue & workaround (as I tested on #4295)

**Comment by klebba** [comment]
@jehna Dang. Worth noting that if you bind to an object's undefined property it does not fill with a space, e.g. `<div>[[empty.empty]]</div>` where you have defined an object property like `empty: { type: Object, empty: undefined }`

**Comment by TimvdLippe** [comment]
This is an unfortunate known limitation of the data-binding system. We should add a mention of this limitation in https://www.polymer-project.org/2.0/docs/devguide/data-binding#bind-to-text-content with a workaround noting that assigning an empty string does work (http://jsbin.com/kudezurohi/2/edit?html,output)

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/docs#2426
