### ISSUE TITLE
Add pre-hook to properties

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#3099]
This issue originates from the discussion at #2677 .

**Current post-hook**
Polymer currently allows developers to be notified whenever a property is changed. This is achieved by assigning the name of the function to be called to the `observer` field at the property in the `properties`. This hook is very useful to adding logic whenever we need to update according to the new value.

**Definition pre-hook**
In the PR linked above, it becomes apparent that developers want to insert logic to validate, transform or perform actions before the value is updated.

Therefore the new pre-hook should:
- Be called before the value is updated
- When the pre-hook returns a value (`!== undefined`), the value should be the value to update

**Example code**
Element `x-foo` declares a property `bar`:

``` js
Polymer({
  is: 'x-foo',
  properties: {
    bar: {
      type: Number,
      set: 'checkBar'
    }
  },
  checkBar: function(value) {
    if (value < 0) {
      return 0;
    }

    return value;
  }
})
```

`bar.set` references the name of the function to be called. The function has 1 argument: the value to be set. The function returns the overridden value. Therefore if bar is updated to `-1`, this value is changed to `0`. If bar is updated to `5`, the value becomes `5`.

**Use-cases**
The pre-hook allows developers to extend the properties to achieve:
1. **Validate values**<br>
   The original PR added logic to validate values to be set on to properties. This callback allows developers to insert such logic on their own, even if they are put into behaviours.
2. **Transform values**<br>
   Another use-case is transforming data. Based on the input given by the user, the element can determine if it should alter the value in order to satisfy an invariant.

**Implementation**
The added code should be fairly minimal. It requires a lookup for the `set` field in the property, a call to the function and check the return value. All other implementations of developers can extend from this hook and put into seperate behaviours to minimize the file size of the core library.

**Comment by MeTaNoV** [comment]
+1
This would be useful in my use-case to validate Enum value as input.

**Comment by jongeho1** [comment]
[computed properties](https://github.com/Polymer/polymer/blob/master/PRIMER.md#computed-properties) do not already allow these extensions primitively? how does this differ? better performance? less indirection? 

 I find myself using computed properties for validation + value transformations. It also helps separate the properties used in the "public" attribute api from validation and transformation logic. If the computed function is common enough, then it is teased out of the element into a behavior and shared among other elements.

**Comment by zoechi** [comment]
@jongeho1 with comuted properties you always need two properties to achieve this, don't you? Doesn't this become cumbersome where you otherwise could use two-way-binding?

**Comment by ebidel** [comment]
You don't need a computed property either. Property observers can contain their own validation logic and adjust their value accordingly: 

    _barChanged: function() {
      if (this.bar < 0) { // validate bar
        this.bar = 0;
      }
    }

http://jsbin.com/wexejesori/edit?html,output

**Comment by MeTaNoV** [comment]
oh, the observer is also called when initializing a property from an attribute, good to know!

**Comment by jongeho1** [comment]
I don't know or understand the justification for a "pre-hook" for ```observer```. If it is a necessary evil, then a ```computed``` equivalent might be necessary when it comes to "validation" or "transformation" behavior of a property especially when the constraints are not encapsulated and permitted to change. 

@zoechi yes, it does implicate another property for ```computed properties```. If you are just using an ```annotated computed property``` in your template, then no. I don't find it cumbersome reading the properties object or reading the template as long it offers some information about what it is doing (and removing imperative calls). You may use the properties object to see/infer how your property is altered or validated as a result of a change by reading the properties declaration or template annotation (depending on how well you name your functions and avoidance of changing the property imperatively in code). 

@ebidel I don't believe that allows for easy porting into behaviors without some marshalling. Does observer function's pass the attribute name? It may only be the new value and old value. It seems like those are more difficult (outside of properties object) to generalize (behavior) due to insufficient context in function arguments.  Perhaps implementing ```attributeChanged``` in a behavior would be an option for those whom like to generalize?  Otherwise, outside of generalization and accepting a little recursion, that seems to work when a property only seems to care about itself changing and not its constraints.

If the framework is intended to be the dom, then I typically start by looking at existing HTML elements. For example, the ```input``` element accepts in attributes like ```value```, ```maxlength``` or ```pattern``` that potentially invalidate the ```value``` attribute (there is more but for simplification). Translating to Polymer some, ```Observers``` would work well to validate the constraints, like ```maxlength```, but a ```computed property``` or ```annotated computed property``` would be necessary when validating the ```value``` attribute since it has dependencies on its constraints changing.

**Comment by JeremybellEU** [comment]
Thank you for the workarounds, however both unwanted side-effects.

Computed properties require a new property to be declared. If validation is done inside this computed property and the original property is reassigned, this triggers the computed property again. This could cause infinite loops or severe performance degredation. Additionally, managing multiple computed properties alongside their original properties makes reasoning about properties rather difficult.

The same is caused by changing a property within its observer. The actual value was already delegated throughout the program. If the observer overwrites the value, the updated value is delegated again. Moreover, the sequence of delegation determines if the original value is received by other observers/bindings or the updated value because the observer was called earlier.

By pre-emptively allowing the developer to validate/transform, such issues can be prevented. Moreover it is more readible and easier to reason about the logic in the application.

**Comment by kriscooke** [comment]
+1  I think @ebidel's example actually demonstrates your value proposition really well. By using a property observer, we had to first annoy the user with an alert containing invalid data before the property observer could catch, validate, and then change it - and then trigger any prop-changed listeners yet again after it's been corrected by the observer. I would like to be able to catch it *before* all the dependent observers and listeners are unecessarily fired based on bad data.

One of the things I love about Polymer is how easy it is to set everything up with valid (as in type-constrained) default values so there are often way less errors on page load.

Computed properties are okay if you don't ever need to bind or set that prop explicitly, but in this particular case I often find myself writing validation code all over the place; ideally I should only need to specify constraints in one place.

I do quite a bit of prototyping, and I notice this more once I start to re-use an element a lot - this would provide some protection against parent elements that may want to feed it garbage values.

**Comment by TimvdLippe** [comment]
I have tried to implement the pre-hook, but sadly partially succeeded. It was working when effects of the property exist (computed, observer, etc..) but not in vanilla with just a type and a setter. If anyone is familiar with that piece of the codebase, that would greatly help.

**Comment by TimvdLippe** [comment]
I was able to figure it out and submitted #3234 to implement the pre-hook.

**Comment by TimvdLippe** [comment]
This is now possible in Polymer 2 with overriding `_setProperty`: http://jsbin.com/foliqiwaga/edit?html,console,output For documentation check out https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-_setProperty
