### ISSUE TITLE
Is Polymer a framework or not after all?

### ISSUE THREAD

**Issue by nicholaswmin** [Polymer/polymer#3155]
>In computer systems, a framework is often a layered structure indicating what kind of programs can or should be built and how they would interrelate. Some computer system frameworks also include actual programs, specify programming interfaces, or offer programming tools for using the framework

With all these build tools that are being introduced(WCT, Polybuild) and the very localised styling practises(see `style-modules`) it looks to me that Polymer is a framework, *by definition*.

**Comment by abdonrd** [comment]
I think that Polymer is only the library for create Web Components.

But... The set of tools and elements (especially `carbon-elements`) created with the Polymer library would be the framework.

**Comment by jongeho1** [comment]
framework is the dom to my knowledge or atleast intended to be

**Comment by nicholaswmin** [comment]
Well, I'm also getting a bit nervous with all the architectural decisions that the Polymer team is taking so far.

If it's a library that just sugars some compatibility on top of the *WebComponents spec* then I'm fine with that since it allows dropping Polymer(at least relatively easily), when the spec get's implemented cross-browser.

If this is headed towards a full-on framework, with specific Polymer tools and specific architectural patterns then I'm smelling "vendor lock-in".


Just wanted to clear things up.

**Comment by BLamy** [comment]
@nicholaswmin I think it's unfair to hold style modules as an argument for classifying polymer as a framework. In my opinion, polymer's job is to beta test the web components spec and get a feel for what is needed and what isn't. They tried following the shadow dom v0 spec and implemented shadow and /deep/ however, they found it didn't work as expected and that is why style-modules exist.

Polymer is shaping the standard, their design philosophy is always putting interop and working with other frameworks as a priority.  Where as most frameworks don't care about this. 

Polymer is no longer labeled as an experiment but honestly it kind of is. As someone who primarily develops in polymer, I would rather see polymer fail and have a more stable web components spec. Than have polymer constantly playing it safe and get a broken platform that I need to monkey patch for the next 20-30 years.

**Comment by nicholaswmin** [comment]
Yeah, Exactly my point

**Comment by BLamy** [comment]
So what's the issue?

**Comment by MeTaNoV** [comment]
He is just complaining, let him do! :D

**Comment by ebidel** [comment]
I don't equate build tools with frameworks. They're intended to make developers lives easier when building production apps. The difference is that they're completely optional and you're welcome to not use any of them. I don't see how that's lock-in or framework-like.

FWIW, Polymer's new styling system is based off of working proposals or standards browsers are implementing: 

- CSS custom properties - https://drafts.csswg.org/css-variables/
- CSS mixins (`@apply`) - http://tabatkins.github.io/specs/css-apply-rule/

We wouldn't have introduced either if discussions weren't happening in the browser space.

**Comment by nicholaswmin** [comment]
@ebidel 

> I don't equate build tools with frameworks.

Ok this makes sense.

>Polymer's new styling system is based off of working proposals or standards browsers are implementing:

The `.html` format/having styles as components is what threw me off as I thought it was something the Polymer team designed as a solution which wouldn't apply/is not mentioned in the actual spec, but if it's something discussed at the browser vendor level, then I guess there's no other way to go about it.

**Comment by arthurevans** [comment]
The styles as components (style modules) isn't something that's currently a standards proposal. (I think @ebidel  was talking about custom properties and mixins.)

Style modules using existing standards proposals (HTML imports, custom elements) to fill a gap in the platform for which there is no existing mechanism (or proposal). That is, loading CSS in a performant way _without the browser parsing it_, so the styles can be shimmed for shady DOM. This mechanism lets multiple elements share a single style sheet, without leaking styles outside the elements.

On the one hand, Polymer != the web component polyfills. It's an opinionated library for creating web components. There are features in Polymer (such as data binding), that aren't standards track. They're in the library because the Polymer developers found them useful in creating custom elements. 

These features are based on a fair amount of experience with building useful, beautiful, performant custom elements. And IMO they're pretty awesome. But they're just one way of building custom elements. If you really just want the proposed native web components APIs, you can use the polyfills by themselves.
