### ISSUE TITLE
API doc for lifecycle callbacks is inconsistent

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer#3174]
Docs include `attachedCallback` (with note to use `attached` instead), `ready`, but **don't** include `attached`, `created`, `detached`, `detachedCallback`, `registeredCallback`, etc.

**Comment by MeTaNoV** [comment]
It would be indeed useful to know at each callback:
- the state of the component
- the state of its local dom children
- the state of its light dom children
and also, what can be done during each of them!
Great coming addition!

**Comment by arthurevans** [comment]
Bump?

**Comment by arthurevans** [comment]
API docs for attachedCallback: 

https://www.polymer-project.org/1.0/api/#Polymer.Base:method-attachedCallback

https://github.com/Polymer/polymer/blob/273ab0fbe641209fa3fc3ce8368bb78f83db9b10/src/mini/ready.html#L153

No docs for all the methods mentioned above (also `attributeChanged`/`attributeChangedCallback`, which I missed above).

**Comment by danostrowski** [comment]
I don't know if this is the appropriate place to leave this, but the `detached` documentation also doesn't seem to include when the method is called for children of a parent Polymer element.

Example that I'm thinking of:
```html
<link rel="import" href="../../bower_components/polymer/polymer.html">

<dom-module id="sub-element">
    <template>
        <div>{{stuff.name}}</div>
    </template>
    <script>
        Polymer({
            is: 'sub-element',
            properties: {
                stuff: Object
            },
            ready: function() {
                console.log('sub-element ', this.stuff.name, ' ready.');
            },
            detached: function() {
                console.log('sub-element ', this.stuff.name, ' detached!');
            }
        })
    </script>
</dom-module>
```
```html
<dom-module id="example-element">
    <template>
        <div style="width:100px;height:100px;background-color: cadetblue" on-tap="onTap"></div>
        <template is="dom-if" if="{{mainthing}}">
            <sub-element stuff="{{mainthing}}"></sub-element>
        </template>
        <template is="dom-repeat" items="{{things}}" as="t1">
            <sub-element stuff="{{t1}}"></sub-element>
        </template>
    </template>
    <script>
        Polymer({
            is: 'example-element',
            properties: {
                things: Array,
                mainthing: Object
            },
            ready: function() {
                this.things = [
                    {name: 'Moe'},
                    {name: 'Larry'},
                    {name: 'Curly'}
                ];
                this.mainthing = {name: 'Boris'};
            },
            onTap: function(evt) {
                this.pop('things');
                this.mainthing = null; // or {}, no difference
            }
        })
    </script>
</dom-module>
```

Running this example with the necessary imports will log "sub-element  Boris  ready." but not "sub-element  Boris  detached!"

Maybe it's because I'm thick, but I don't understand why. When the `dom-if` is re-evaluated, I would think it would detach the node in the same way that `.pop`ing from things does, but I guess not?

Anyhow, something like this MIGHT make sense in the docs about lifecycles, though, perhaps in extended docs.

**Comment by TimvdLippe** [comment]
@arthurevans https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element includes `attributeChangedCallback(name, old, value)`, `connectedCallback()` and `disconnectedCallback()` Per https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements it misses `adoptedCallback(oldDocument, newDocument)` and I think that is because Polymer elements do not actually use this specific callback. Should we add this one or leave it up to the official docs?

**Comment by web-padawan** [comment]
@TimvdLippe FYI, this [section](https://github.com/webcomponents/custom-elements/blob/master/README.md#known-bugs-and-limitations) in the polyfill readme states that `adoptedCallback` is not supported.

**Comment by TimvdLippe** [comment]
@web-padawan yes that is correct, but that is a limitation of the polyfill. That does indeed have the implication that cross-browser Polymer applications can not use `adoptedCallback`, so maybe we are better off leaving it out from the docs. @arthurevans if you agree, feel free to close this issue :tada:

**Comment by TimvdLippe** [comment]
Closing per above comment.
