### ISSUE TITLE
two level adding element not working

### ISSUE THREAD

**Issue by arvindashtekar** [Polymer/polymer#3210]
adding two level element dynamically is not showing.
here is plunker
http://plnkr.co/edit/7WUcBhOm0SvTEVprVP91?p=preview

**Comment by azakus** [comment]
I'm getting this message in the console:
```
Imported resource from origin 'http://element-party.xyz' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access. The response had HTTP status code 404
```

I don't think your demo is going to work due to Cross Origin rules on plunkr.

**Comment by arvindashtekar** [comment]
yes. Sorry I don;t know how I  tested earlier on plunker. But I don;t see to run it locally. Issue still persist for two level addition.

**Comment by TimvdLippe** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
