### ISSUE TITLE
There is not way to get event about changing native property

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#3225]
Initially commented https://github.com/Polymer/polymer/issues/2815#issuecomment-166150694, but turns out to be different issue.
Example: http://jsbin.com/gudomudaja/edit?html,output

``` html
<script>
  // only need this when in the main document and on non-Chrome
  addEventListener('WebComponentsReady', function () {
    Polymer({
      is        : 'x-textarea',
      extends   : 'textarea',
      listeners : {
        change : '_changed',
        input  : '_changed'
      },
      _changed : function () {
        this.notifyPath('value', this.value);
      }
    });
  });
</script>

<dom-module id="x-test">
    <template>
      <textarea id="t1" is="x-textarea" value="{{content}}"></textarea>
      <textarea id="t2" is="x-textarea" value="{{content}}"></textarea>
    </template>
    <script>
        addEventListener('WebComponentsReady', function () {
            Polymer({
                is         : 'x-test',
                properties : {
                  content: String
                },
                ready : function () {
                    var t2 = this.$.t2;
                    // No events fired on #t2 unfortunately
                    t2.addEventListener('change', function () {console.log('change');});
                    t2.addEventListener('input', function () {console.log('input');});
                    t2.addEventListener('value-changed', function () {console.log('value-changed');});
                }

            });
        });
    </script>
</dom-module>

<x-test></x-test>
```

When typing something in `#t1` I can't find a way to detect changes in `#t2`, while content is propagated properly.

**Comment by nazar-pc** [comment]
Well, I think there is a need to fire some event in case of native properties, since otherwise it is not possible to know about any change.
For instance, with `value` property, `change` event should be triggered afterwards for `input`, `textarea` and `select` elements I guess. Or at least make it possible somehow otherwise.

**Comment by ebidel** [comment]
Have you seen https://www.polymer-project.org/1.0/docs/devguide/data-binding.html#two-way-native?

**Comment by nazar-pc** [comment]
Sure, I know about it, but it will not work for multi-line content of `textarea` which I need in this example.
I understand why there are no observers for such properties, but if data binding system gets notification from outside and changes property - I should be able to hear about this.

**Comment by arthurevans** [comment]
So to be specific--the issue you have here is that the second textarea doesn't generate an event when it's updated from the outside, via data binding?

If so, that would be the outcome I'd expect, because data binding is basically setting a property imperatively. And the spec says:

"Any time *the user causes the element's raw value to change*, the user agent must queue a task to fire a simple event that bubbles named input at the textarea element." (emphasis added)

However, I'm not positive whether that's the issue you're reporting here.

**Comment by nazar-pc** [comment]
> So to be specific--the issue you have here is that the second textarea doesn't generate an event when it's updated from the outside, via data binding?

Exactly.
However I didn't get precisely what does your quote mean in context of this issue. I'm not expecting UA to generate any event, because of changing value directly it is Polymer's job to generate such an event.

**Comment by kaste** [comment]
But if you change the value of an textarea-element programmatically say:

```
 var t2 = ...getElelement..
 t2.value = 'Hello';
```
 the element - the __native__ element - will not fire any of the events (`change`, `input`) you're listening to. Correct?

Your custom element does not add this behavior as well. Clearcase, close the ticket. :lollipop:

**Comment by nazar-pc** [comment]
@kaste, we are talking about Polymer, more specifically about data binding system. Polymer already provides a lot of features native elements doesn't have. In this case Polymer does know that value was changed, why developer is not able to know that as well?

Yes, `input` event is generated on `t1` when typing, but since Polymer distributes data using data binding system to `t2`, `t2` MUST be able to know its property was changed, however since `value` is native property and Polymer changes it directly there is no way to know that currently. This is what this issue about.

**Comment by kaste** [comment]
Just wanted to refine the problem, @nazar-pc. From outside of `x-textarea` you obviously know that the value changed b/c you can observe `content`. What you want is: Inside of `x-textarea`, how can I observe __incoming__ user data on the (native) `value` property. Right?

**Comment by nazar-pc** [comment]
Yes, exactly.
The only trick is that Polymer is the guy who changes native property, but any observers like following doesn't work:
```
...
    observers : [
        "_value_changed(value)"
    ],
...
```
Live example: http://jsbin.com/tixufudebo/edit?html,console,output

**Comment by azakus** [comment]
Hmm, this seems even simpler in this bin: http://jsbin.com/neyayo/edit?html,console,output
The observer never fires, even though the value updates in the parent.

**Comment by kaste** [comment]
Not quite __that__ simple http://jsbin.com/xeluyif/edit?html,console,output

**Comment by nazar-pc** [comment]
Yes, @azakus's example is not correct

**Comment by kevinpschaaf** [comment]
For the time being, in Polymer 2.x we're not supporting type-extension custom elements, so the severity of this issue is lower, since `HTMLElement` has fewer useful properties one might want to observe changing via accessor.  However, there are still a few (one could conceivably override, e.g. `hidden` on HTMLElement), and type-extension custom elements could eventually come one day, so wanted to show _a way_ this can be achieved in 2.x.

The accessors that Polymer 2.x generates to detect and perform property effects when properties change are implemented using overridable API's: `_setPendingProperty` and `_getProperty` (erk, the latter one is exposed but not actually called by the getter, so it's not technically overridable -- this should probably be fixed for the most correct implementation, but most of this still applies).

In the following jsBin, I've shown a simple mixin that can be applied to a `Polymer.Element` to allow adding property effects (e.g. observers) to native properties.  It generates a list of all of the native properties on `HTMLElement` and then calls the native setter/getters from the accessor implementations that Polymer uses:

http://jsbin.com/wasabum/edit?html,console,output

Note, Polymer effects won't be run if the native value changes without setting the setter.  This could be achieved by mapping events to the native properties, but I didn't handle that here.

**Comment by kevinpschaaf** [comment]
Lowering priority since there are user-space workarounds now.
