### ISSUE TITLE
way to track where style mixins are applied

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer#3227]
Hi,

I've been porting a 0.5 app to 1.X, and have been switching away from /deep/ and ::shadow in the process.

One thing I have found is that it is a bit difficult to see in the style inspector in the chrome dev tools when I have successfully applied the mixin.

For example, deep in my app's element hierarchy I have several paper-button elements, and want to replace a /deep/ styling for that element; so at the level the /deep/ was, I set the corresponding custom css property. However, if I select a paper-button element in the dev tools, there is quite a list of styles that is applied and it's quite difficult to see if the one I am attempting to apply is there.

My hacky solution to this problem is to add an invalid property that is the name of the mixin - eg `paper-button-mixin: 1;`, and that then appears in the css inspector in the dev tools - actually, since it is invalid, it is quite obvious and so I can spot it easily. It only works because the css engine ignores invalid rules.

My first attempt was to add a comment, but those don't make it through.

It occurred to me that what I really want is something like the css mapping (like `gulp-ccsnext` does) but for @apply. So, perhaps this is actually asking for an enhancement to the dev tools. Since @apply is part of the standard, perhaps this is a good thing to have anyway, even for non-Polymer projects.

**Comment by TimvdLippe** [comment]
@apply is probably going to be replaced by `::part` and `::theme`. Nonetheless, the @apply shim makes use of CSS variables to make this magic happen. The DevTools show this quite clearly: 
![image](https://user-images.githubusercontent.com/5948271/30996403-7dcab608-a475-11e7-8e4e-324ab12ec58d.png)
Here, the mixin name is placed first and then after that the actual property name. Since Polymer makes use of standars, I am closing this issue for now as there is no actionable item for the Polymer team. Feel free to raise further issues on the dev tools issue list if you feel ergonomics are lacking!
