### ISSUE TITLE
Dom-repeat not working for updated arrays

### ISSUE THREAD

**Issue by hartjus** [Polymer/polymer#3256]
Does not work in Firefox or IE; works in Chrome.

When I'm trying to modify the element of an array property on a Polymer Element, the dom-repeat in the template is not updating.  This seems to work on Chrome OK, but not in FF.

Any ideas here as to why the template is not updating?  Is this a Polymer bug or a bug in Firefox?

Polymer code:
```
<link rel="import" href="/bower_components/polymer/polymer.html" />

<dom-module id="test-element">
    <template>
        <h1>Test Element</h1>
        <template is="dom-repeat" items="{{ headers }}" as="header" index-as="headerIndex">
            <div> {{ header }} </div>
        </template>
    </template>

    <script>
        Polymer({
            is: 'test-element',
            properties: {
                incomingData: {
                    type: Object,
                    observer: 'dataChanged'
                },
                headers: {
                    type: Array,
                    value: ['Z', 'Z','Y']
                }
            },
            dataChanged: function(newVal, oldVal){
                console.log(newVal.headers);
                this.set('headers', newVal.headers);
                //this.headers = newVal.headers;
            }
        });
    </script>
</dom-module>
```

HTML referencing the component (notice that I am instantiating the component programmatically):
```
<html>
    <head>
        <link rel="import" href="src/app/elements/test-element.html" />
        <script src="bower_components/webcomponentsjs/webcomponents.js"></script>
        <style>
            BODY {
                font-family: Verdana, sans-serif;
                font-size: 16px;
            }
        </style>
    </head>

    <body>
        <div id="content"></div>
        <script>
            var data = {
                foo: 'bar',
                headers: ['header A', 'header B', 'header C', 'header D', 'header E']
            };
            var el = document.createElement('test-element');
            //el.set('incomingData', data);
            el.incomingData = data;
            document.getElementById('content').appendChild(el);
        </script>
    </body>
</html>
```

**Comment by hartjus** [comment]
If it helps, I tried to make the `headers` property of the Polymer element a computed property from `incomingData`, but ended up with the same result.  The dom-repeat is not updating its template with the new data that is set in `headers`.  :(

Browsers:
* Chrome 47.0.2526.106 m (WORKING)
* Firefox 43.0.3 (NOT WORKING)
* Internet Explorer 11.20.10586.0 (NOT WORKING)

**Comment by Paras-avantsoft** [comment]
@hartjus : I think you just need to add ```notify: true``` in ```headers``` property

**Comment by hartjus** [comment]
Unfortunately, that didn't work either.  I get the same result. (Would have been a simple fix!)

Reading the docs, the `notify` property is used for notifying other components that are two-way bound of changes.  I don't think you would need it to be used within the same component? But I could be reading it wrong too.

I'm just speculating here, but I think it has something to do with the fact that the component was instantiated programmattically and the data being set on the object.

**Comment by kevinpschaaf** [comment]
This is due to a timing gotcha with the HTMLImports polyfill.

You are importing an element's definition with `<link rel="import">`, and then creating an instance of the element in a `<script>` in the main document.  With native HTML Imports (Chrome), execution of the `<script>` is guaranteed to be blocked on any scripts in the import loading and running, hence the element is registered before you created it.  However, there is no way to simulate this behavior in the polyfill; the other browsers zoom past the `<link rel="import">` and will execute the script before the polyfill has a chance to load the import.  As such, what happens is that you set the `incomingData` property on the `test-element` instance before it is upgraded, and once it is upgraded (after the element definition loads and is registered), it has already missed the notification of the data changing.  Instead, you need to ensure the element is upgraded first before you set any properties on it.

The HTMLImports polyfill provides the `HTMLImports.whenReady` function for the exact purpose of dealing with the inability to polyfill the script blocking behavior of the spec.  Just wrap any scripts in the main document that depend on element definitions being loaded with `HTMLImports.whenReady(function() { ... });`, and you should be fine:

Like so:
http://jsbin.com/husuji/edit?html,console,output

Note, you only need to do this in the main document; script execution in documents loaded using `<link rel="import">` are sequenced correctly since the polyfill can control the timing of when those scripts are run.
