### ISSUE TITLE
Move attribute deserialization to after template stamping

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3266]
It would be beneficial to move attribute deserialization to after template stamping, so that custom `deserialize` methods can deserialize strings to elements.  This has proven useful for element API's that require referencing other elements, such as scroll targets, activate targets, etc. as a means to provide declarative association.

**Comment by sorvell** [comment]
We elected not to make this change since it would not be helpful for the noted use case since attribute can occur before an element is in the dom and therefore another element in the element's scope could not be found. An alternate approach was used where the element discovers another referenced element when it's attached.
