### ISSUE TITLE
on-tap not firing where on-up does

### ISSUE THREAD

**Issue by maxsteenbergen** [Polymer/polymer#3347]
Consider the following code:

```
listeners: {
        'childTaskNode.tap': '_openChildTask',
        'childTaskNode.track': '_moveChildTask',
      },
```

Fairly straight forward. However, no matter what approach I try —including inline `<... on-tap="_openChildTask"...>`— the event is not fired when using desktop Chrome. The `on-up` event does fire like expected.

**Comment by azakus** [comment]
Hi, can you provide a JSBin containing a set of reproducible steps? See [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) for details.

**Comment by TimvdLippe** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
