### ISSUE TITLE
this.updateStyles does not update child elements

### ISSUE THREAD

**Issue by paranoid-android** [Polymer/polymer#3378]
Hello,

I am attempting to set some colors at run time. In an effort to do this, I have some [shared styles](https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules). As demonstrated in [this plunk](http://plnkr.co/edit/v0hi2Lkyvxo5fcxfuuU8?p=preview), the colors do not propogate down the visual tree. 

When clicking the "Go Blue" button, I am anticipating both bullets turning blue. If a user clicks the "Go Green" button, I am expecting both bullets to turn green. However, only the bullet in the container is changing colors. In my mind, I could understand `this.updateStyles` changing the color of just the container and `Polymer.updateStyles` changing colors in the entire visual tree, yet, this is not happening. No matter what I try, I cannot seem to get style changes to propagate through the visual tree.

I'm trying to understand if this is a bug in `this.updateStyles` or if there is something that I am overlooking.

**Comment by miztroh** [comment]
To dynamically update a custom element's local DOM, call ``this.scopeSubtree(this.$.containingNode, true);``.  Here's an updated version of your example.

http://plnkr.co/edit/3Prh0kPIeKdXIXPt7Jt3?p=preview

**Comment by paranoid-android** [comment]
Fascinating. Thank you for sharing. I'm going to have to dig into that a lot more.

**Comment by arthurevans** [comment]
The fix @miztroh proposes is making this work by breaking the style system. You should use `scopeSubtree` when you add nodes directly to your local DOM _without_ using `Polymer.dom` (for example, using a third-party library. It says, "these nodes should be styled as part of my local DOM").

But in this case you have a child element with the proper style scoping, and you're telling it, "treat everything in here as part of its parent's local DOM." So you're getting the styles you want, but you're getting them because both dots appear to the styling system to be in the app-shell's local DOM.

To see why this is an issue, try setting `div { background-color: blue; }` in the parent and `div { background-color: red; }` in the child. The child's styling should win in its own local DOM, but instead you see all blue.

I think the problem here is the style module. You're importing the `:host` rule into _both_ elements which is the same as setting it locally. Think about setting another value that inherits, like `background-color`. If you set one value in the parent and another value in the child, the child's value wins. Same for your `--selected-color` custom property.

If you set the property once at the app-shell level, the value will inherit down the tree, and _then_, if you update the style in app-shell, the value will pass down the tree correctly:

http://plnkr.co/edit/Lqi8NYqvOnSFCsFvTu9R?p=preview

**Comment by miztroh** [comment]
@arthurevans I guess I didn't look deeply enough into his issue.  However, the call to ``scopSubtree`` from the ``ready`` function comes straight from the docs.  If that breaks the style system, then something about that function needs changed / clarified.  I mean, what if you have a scenario where both a third-party lib and the element itself are modifying local DOM?

**Comment by arthurevans** [comment]
So, the section here: https://www.polymer-project.org/1.0/docs/devguide/styling.html#scope-subtree 
Starts with, "If you are using a third-party library that adds local DOM nodes to your Polymer element, you may notice that styles on the element do not update properly..."

In this case, there's no third-party library involved (or any imperative DOM manipulation at all), so it's really not an issue.

You're right, there should be a little more guidance in that section. Here's the basic idea:

- If you have third-party libraries that add DOM nodes, the new nodes won't get scoped properly. To avoid this problem: 
    1. Create a container node inside your element's local DOM, and have your third-party library create DOM under that container node.
    2. Call `scopeSubtree` on the container node. This causes the entire subtree to be styled as if it was
        inside the host element's local DOM.

- Don't call `scopeSubtree` on a node that has Polymer elements as descendants. If the subtree that you scope contains any Polymer elements with local DOM, `scopeSubtree` will cause the descendants' local DOM to be styled incorrectly.
