### ISSUE TITLE
Computed property based on local dom element?

### ISSUE THREAD

**Issue by flawyte** [Polymer/polymer#3390]
Hi,

I want to know if it's possible (and if yes, how) to set a computed property's value based on the value of local dom elements. Something like this:

```html
<dom-module id="my-element">

  <template>
    <color-picker></color-picker>
  </template>

  <script>
    (function() {
      Polymer({
        is: 'my-element',
        properties: {
          red: {
            computed: 'getRed()'
            type: Number
          }
        },
        getRed: function() {
          return this.$$('color-picker').red;
        }
      });
    })();
  </script>
</dom-module>
```

**Comment by kevinpschaaf** [comment]
No, computed properties won't work like that.  Polymer's data system (bindings, computed properties, observers, etc.) uses a _property effects_ system, whereby when a property changes, any side-effects will be invoked.  This requires declaring dependencies of effects (like computed properties), such that when a property dependency changes, the effect will go.  With `getRed` you have not (and cannot) declare `this.$$('color-picker').red` as the dependency to `getRed`, which would be required for `getRed` to always run on changes, since dependencies must be properties of the element itself.  As such, you'd need to listen for changes to `red` on the `<color-picker>` and bring those into properties on `my-element`.

What you are attempting to do should be trivial using 2-way binding:

```html
<dom-module id="my-element">

  <template>
    <color-picker red="{{red}}"></color-picker>
  </template>

  <script>
    (function() {
      Polymer({
        is: 'my-element',
        properties: {
          red: {
            type: Number
          }
        }
      });
    })();
  </script>
</dom-module>
```

We always try to highlight that 2-way binding is simply sugar for listening for property changed _events_ on local DOM elements to propagate changes to local DOM elements into properties on the host element, equivalent to this:

```html
<dom-module id="my-element">

  <template>
    <color-picker red="[[red]]" on-red-changed="getRed"></color-picker>
  </template>

  <script>
    (function() {
      Polymer({
        is: 'my-element',
        properties: {
          red: {
            type: Number
          }
        },
        getRed: function(e) {
          this.red = e.target.red;
        }
      });
    })();
  </script>
</dom-module>
```

Hope that helps.

**Comment by flawyte** [comment]
I get it. Thanks!
