### ISSUE TITLE
Why is /deep/ required within a custom element?

### ISSUE THREAD

**Issue by stephenbunch** [Polymer/polymer#3400]
Hey guys,

I'm using Polymer 1.2.x, and it seems like `/deep/` is required when I'm inside a custom element and I want to select a child of another polymer element inside the template. If I use `/deep/` outside, chrome throws a warning (as it should). This behavior seems inconsistent. I'd expect to be able to select elements the same way whether I'm inside or outside a custom element.

http://codepen.io/stephenbunch/pen/bEObay

In the codepen above, I change the text color of a child element to blue using a regular child selector. If I had used `/deep/` here, it would have worked, but chrome would have thrown a warning. When I'm inside the `outer-element` definition, I have two styles changing the background color. The first uses `/deep/` and successfully changes the background color to red. The second which is supposed to change it to yellow fails. Also notice that no chrome warnings are thrown. If /deep/ is depreciated, I shouldn't be required to use it.

**Comment by azakus** [comment]
So, what you're seeing is Polymer scoping the styling of your elements as if they were using ShadowDOM, which has style encapsulation. Your example of a style in the page works because the style scoping is not free, and we only scope styles that are inside Polymer element definitions.

ShadowDOM spec has removed `/deep/`, and Chrome has deprecated it, and we instead recommend people use [Custom CSS Properties](https://www.w3.org/TR/css-variables-1/) (previously CSS Variables) for scoping between elements: https://www.polymer-project.org/1.0/docs/devguide/styling.html#xscope-styling

We still support `/deep/` for now, but it will go away at some point (in a semver-major release).

**Comment by stephenbunch** [comment]
@azakus Ahh, that makes sense. Thanks for the clarification!
