### ISSUE TITLE
Merging of properties between behaviors and element is inconsistent

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3418]
- effects are added for all behaviors so if you have an `observer` in a behavior and then override that property, you still get the observer. This is probably the right behavior.
- if you `notify: true` the same property multiple times, you get multiple notifications. This is undesirable and needs to be fixed.
- if you `readOnly: true`, then you get the readOnly setter based on first property object found in  prototype first then oldest to youngest behavior (this order is probably wrong, but this is also the answer you get in `getPropertyInfo`). However, deserialization and avoid binding readOnly props based on 'first truthy value in a property object' in order behavior oldest to youngest then proto (standard behavior order for other stuff).

**Comment by sorvell** [comment]
Related to #2493

**Comment by TimvdLippe** [comment]
As a Polymer user, I would expect that a property defined by a child overrides configuration of a parent. However, since observers do not interfere between classes in the inheritance chain, I would expect that every observer of the property in the inheritance chain to be called.

The reason that notify is called multiple times is because [PropertyEffects](https://github.com/Polymer/polymer/blob/master/src/standard/effectBuilder.html#L52-L63) are added for every property in the chain. That means that if a parent and child both define `notify: true`, the effect is added twice. The fix would be to let `_addPropertyEffects` iterate over [`_propertyInfo`](https://github.com/Polymer/polymer/blob/master/src/micro/properties.html#L140) which is a merged array of all properties.

**Comment by kevinpschaaf** [comment]
Related repro from #2242: http://jsbin.com/xebehe/edit?html,console,output

**Comment by TimvdLippe** [comment]
Will this be incorporated into 2.0 while you have the window of opportunity

**Comment by sorvell** [comment]
Since these issues have been addressed in Polymer 2.x we're going to close this issue. The rules are detailed [here](https://github.com/Polymer/polymer/blob/master/lib/mixins/element-mixin.html#L150).

Since the changes that would not be breaking to 1.x are minor performance enhancements, we're electing not to address them.
