### ISSUE TITLE
Uncaught error when using track event

### ISSUE THREAD

**Issue by idoshamun** [Polymer/polymer#3425]
When adding listener to a track event, an error is being thrown:
`Uncaught TypeError: Cannot read property '_bound' of null`

This is how I add the listener:

``` javascript
listeners: {
  'container.track': 'handleTrack'
}
```

and this is the handler:

``` javascript
handleTrack: function(e) {
  var track = event.detail;
  if (track === 'start') {
    var style = window.getComputedStyle(this.$.container);
    this.transformX = parseInt(style.transform.split(',')[4]);
    console.log(this.transformX);
  }
}
```

**Comment by MeTaNoV** [comment]
Hi Idosh,
I don't get any such error when configuring a listeners like this? Can you provide more information on your element?
Also, there is a small mistake in your handler:
`track === 'start'` => `track.state === 'start'`

**Comment by idosh** [comment]
I'll try to reproduce it later on, but I get the same error when running the polymer starter kit and clicking on a paper button there.

**Comment by azakus** [comment]
Hi, can you provide a JSBin containing a set of reproducible steps? See [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md#filing-bugs) for details.

**Comment by idosh** [comment]
I can't manage to reproduce it, I think it's because JSBin uses the web components polyfill and not the native support of Chrome.
Running the polymer starter kit or clicking on a paper-button reproduces the bug

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with Polymer 2 for us to be able to debug and potentially fix. Polymer 2 fixes a large amount of issues, probably including this one as well.

Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with Polymer 2.  Thank you!
