### ISSUE TITLE
property observers should not fire before the elements ready event

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer#3438]
### Description

Given a polymer element

``` js
Polymer({
  is: 'wow-elm',
  observers: ['_amaze(zap)'],
  amaze: function(zap) {
    console.log(this.$);
  }, 
});
```

It is possible that `amaze` will be called and `this.$` will be undefined because the observer fired before the ready event on the element. **This is unexpected**, and causes me to have to add guard clauses in my observers functions due to this behavior.

Now a solution might be to pass `$` to my observer registration, however I kinda expect observers to not run until the element has been upgraded.

Is there a reasonable use-case for why you would want something to fire before ready? I can not come up with one but possibly am just overlooking something.

---

version: Polymer 1.2.4

**Comment by MeTaNoV** [comment]
Konwn for a long tiiiiiime! :) +1

**Comment by kaste** [comment]
That's not about use-cases, that's just the reasonable implementation of an event system.  Your observer is a registered listener on _zap_. It gets called when _zap_ fires. You cannot just disregard the first events here (until readied). You cannot debounce the delivery of the event, b/c the value might be wrong then.... What options do we have here?

**Comment by kaste** [comment]
Cough, actually I cannot reproduce this. The observers fire before ready, but `this.$` is already there. https://jsbin.com/jiyizoxotu/edit?html,console,output :confused:

**Comment by kbenjamin** [comment]
@samccone is only scratching the surface of this problem. It is real but reproduction is hard due to timing issues. Sometimes It Just Works. Sometimes It Just Doesn't Work. The more complex the app, the more these issues arise.

I did an [extensive write-up](https://github.com/kbenjamin/polymer-issues) on this and other databinding issues which I mentioned in #3492 and hasn't had any feedback yet.

Resolving this isn't as trivial as waiting for `ready()` or even `attached()` to fire. You may have databindings from an element that is ready that are linked to a parent which isn't yet. More troublesome are databindings between siblings which may become ready at different times:

```
<my-item value="{{mydata}}"></my-item> // ready fast and sets the value of mydata a couple of times during initialization
<my-other-item the-data="{{mydata}}"></my-other-item> // ready slow and relies on observing theData for a specific change
```

My workaround has been to defer any code execution that has these sorts of dependencies until `WebComponentsReady`, which does seem to work. I created a simple queue to handle this but I wish I didn't have to.

One possible downside to simply waiting for `WebComponentsReady` is that no code execution runs until then, which *might* slow an application down. If and how much would need to be tested. So far, I'm only doing this where I must and I don't see the downside relative to the higher time burden of instantiating components.

**Comment by TimvdLippe** [comment]
In Polymer 2, `this.$` is no longer undefined inside `ready`: https://jsbin.com/lusunayife/edit?html,console,output Using class syntax, the same behavior is happening: http://jsbin.com/fotugomari/edit?html,console,output

Given that guards are no longer necessary for `this.$`, are there any other issues that we should fix @samccone ?

**Comment by Korede-TA** [comment]
Typically, using `Polymer.RenderStatus.afterNextRender` works to put off an operations within `ready()` till stuff is fully rendered. However, I don't think it works within observers. 

I generally go with a try-catch around what I want the observer to do or something along the lines of `if(this.propertyWhichMayNotYetBeDefined)`.

**Comment by TimvdLippe** [comment]
Closing per https://github.com/Polymer/polymer/issues/3438#issuecomment-322341279 Please let us know if you can still reproduce this issue.
