### ISSUE TITLE
host style couldn't be overridden

### ISSUE THREAD

**Issue by frankiefu** [Polymer/polymer#3459]
### Description
I have a polymer element which has a `:host` rule for setting the default background color to red.  I should be able to override that by setting background color to something else in the stylesheet. 

Note: This jsbin works fine in Polymer v1.2.4

#### Live Demo
http://jsbin.com/xigabuboqo/edit?html,output

#### Steps to Reproduce
1. Run the jsbin

#### Expected Results
The box should be blue.

#### Actual Results
The box shows red.

### Versions
- Polymer: v1.3.0

**Comment by miztroh** [comment]
Looks like the issue is due to the ``@apply(--x-bar);``.  If you remove that, it works as expected.

**Comment by arthurevans** [comment]
I'm guessing this is related to the CSS specificity fix? Interestingly, if you put the global style rule into a `custom-style` element, the element is styled correctly.

**Comment by sorvell** [comment]
The only selector that's expected not to work in this setup is an element selector (e.g. `x-foo`). A class selector should [work fine](http://jsbin.com/punape/edit?html,output). As @arthurevans pointed out, using a `<style is="custom-style">` is the [preferred setup](http://jsbin.com/poyahu/1/edit?html,output) since this guarantees proper scoping. One workaround that can be used instead is to increase the specificity of the rule via the `:not` operator. [For example](http://jsbin.com/bufani/edit?html,output), `x-foo:not(.nothing)`.

We considered this issue when fixing #2642 and decided it was worth the trade off. Previously, it was possible to hit this issue under some circumstances but not others.
