### ISSUE TITLE
failed with ECONNRESET

### ISSUE THREAD

**Issue by Krazitchek** [Polymer/polymer#3494]
I used to install/update polymer with bower since a long time without trouble. It works perfectly until some days where i get this kind of message arbitrary, here downloading paper-progress:

**bower paper-progress#^1.0.0 retry Download of https://github.com/PolymerElements/paper-progress/archive/v1.0.8.tar.gz failed with ECONNRESET, retrying in 1.6s**

I found on Internet stuffs related on proxy with this error but i haven't a proxy.

I'm not sure but it seems polymer components are downloaded despite this errors (failed with ECONNRESET).

Here what i do to install Polymer:

bower install Polymer/polymer
bower install PolymerElements/iron-elements
bower install PolymerElements/paper-elements
bower install PolymerElements/neon-elements
bower install PolymerElements/gold-elements
bower install PolymerElements/marked-element
bower install PolymerElements/font-roboto-local

I don't know why this error appears suddenly.

Any idea ?

Thanks.

**Comment by arthurevans** [comment]
ECONNRESET means that the remote site (in this case, GitHub) closed the network connection. I'd guess the most likely cause of this is a load problem on their servers. This is likely a transient error, and since the components are getting installed, it sounds like Bower is handling the error appropriately by retrying the resource. 

If you have trouble and it doesn't seem to resolve itself (packages don't get installed or updated), I'd suggest retrying after a short interval in case GitHub is experiencing problems.

You can also check on the current GitHub status here: https://status.github.com/

**Comment by arthurevans** [comment]
Hope this helps. I'm going to close this since it's not an issue with Polymer.

**Comment by Krazitchek** [comment]
OK, thank you. The "strange" thing if it is a load problem on Github is that it's a permanent "problem". On each bower install listed i have some ECONNRESET error, not on the same components each time, since 3/4 days.

**Comment by miztroh** [comment]
GitHub has some sort of rate-limiting in place.  I've noticed that when I try to install a large amount of components in one go, eventually the downloads start failing.  At that point, I usually kill the bower install process and wait a few minutes before trying again.
