### ISSUE TITLE
core-scaffold 0.5 does not work in Chrome 49+ (menu sidebar blank)

### ISSUE THREAD

**Issue by vadimtsushko** [Polymer/polymer#3499]
Using a core-scaffold in Chrome >= 49, the sidebar is blank. It works fine in Edge and Chrome <= 48. 

#### Steps to reproduce:
Nothing to reproduce. core-scaffold js demo fails too: https://www.polymer-project.org/0.5/components/core-scaffold/demo.html .

### Versions

Polymer.version 0.5

**Comment by azakus** [comment]
Upstream chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=592835

**Comment by akdor1154** [comment]
Sorry, can you elaborate a bit? The chrome bug suggests that it is only triggered by syntax that is invalid (which would be a Polymer problem if so), and the other bug it's been merged into is not publicly accessible.

**Comment by arthurevans** [comment]
Not sure why that bug is not public, but it's another report of the same symptoms, which were fixed in a subsequent release. So, the quick summary is:

1) Chrome pre-49 erroneously supported `::content[attribute]` as a synonym for `[attribute]::content` (not surprisingly, because the spec is hella confusing).
2) Some people wrote selectors this way.
3) Chrome 49 broke these selectors.
4) The change that broke these selectors was reverted, because it broke existing websites. If I read the bug right, that change should roll out in the next update to 49. It's already fixed in Canary (51).

Since the 0.5 elements aren't actively maintained, we're not going to try to patch them. 

If you have an existing 0.5 website that is showing symptoms of this problem, you can post on the slack channel or stack overflow for help working around the issue. (It may be as simple as setting a manual height for your core-scaffold content, or you may need to look for components using the `::content[attribute]` selector and rewrite them as `[attribute]::content`.)

If you're working on a new project, obviously, we recommend using Polymer 1.x and the 1.x elements, which we're actively maintaining.

**Comment by akdor1154** [comment]
ah awesome, thanks. :)
Both myself and OP are using the Dart port of Polymer, which has not yet released the 1.0-based version as stable.
