### ISSUE TITLE
lazyRegister: true causes animation elements not to be found.

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer#3517]
<img width="1107" alt="screen shot 2016-03-18 at 2 12 53 pm" src="https://cloud.githubusercontent.com/assets/238208/13889273/aec59a86-ed13-11e5-984d-36414e8a388a.png">

**Comment by sorvell** [comment]
Users of `Polymer.NeonAnimationBehavior` need not to be lazily registered since they require the `registered` method to be called (https://github.com/PolymerElements/neon-animation/blob/master/neon-animation-behavior.html#L41).

If Polymer exposes a `eagerRegister` flag then the behavior can set this to true and users of it will not have to contend with this issue.

**Comment by ebidel** [comment]
For those following: https://github.com/PolymerElements/neon-animation/issues/155

**Comment by ebidel** [comment]
Going to close this in favor of https://github.com/PolymerElements/neon-animation/issues/155. There's a PR up for the issue.
