### ISSUE TITLE
Calling updateStyles before an element is attached does nothing and is confusing

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3530]
Calling `updateStyles` manually provokes the custom properties shim to update. Calling it before an element is attached has no effect. This is confusing to users and should either be fixed or produce a warning. For example, a developer might write an observer that calls `this.updateStyles`. This needs to be gated on attachment to function properly.

**Comment by peteblois** [comment]
This appears to be the result of some flakiness that we've been seeing for quite a while, where styles are not always being applied.

An repro of what has stymied us for a few months is:
http://jsbin.com/sixuquwevu/2/edit?html,js,output

Calling updateStyles on property change seems natural, I disagree that this should produce a warning (especially since the net effect appears to work after the element is attached).

The problem is that when the element is first attached styles are all updated, but after the element is re-attached, they are not.

**Comment by CSEMike** [comment]
It is surprising to me that this P0 bug has not been updated in several months. What's the latest here?

**Comment by sorvell** [comment]
Sorry for the delay. We are working on this issue. I believe it should be enough to ensure that if `updateStyles` is called when an element is not in the dom, we ensure that the scoping selector is removed. This will force the element to recalculate its style properties when it's later re-inserted into the dom.
