### ISSUE TITLE
Attached callback appears to be async while detached is sync

### ISSUE THREAD

**Issue by peteblois** [Polymer/polymer#3531]
#### Live Demo
http://jsbin.com/wuwuhubigu/edit?html,js,console,output

#### Steps to Reproduce
1. Create `my-element`
2. Append `my-element to document.body
3. Remove `my-element` from DOM
4. Append `my-element` to document.body

Expected:
 - attached() to be called before detached().
 - detached() to be called.
 - attached() to be called again.

Actual:
 - detached()
 - attached()
 - attached()

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
Latest on http://polygit.org/.

**Comment by kevinpschaaf** [comment]
Confirmed bug.  The mis-ordering occurs when an element is attached and detached before the first paint occurs.  This is because Polymer defers `attached` until the first animation frame to provide a guarantee that styles have resolved and an element can perform measurement in attached.  As noted, `detached` is not queued, which can lead to mis-ordered callbacks.  We'd likely fix this by similarly queueing `detached` in the same way, which would preserve ordering.

**Comment by peteblois** [comment]
Is there any way to force tree construction to be synchronous? This async attached is problematic because it's only sometimes async. Async detached seems to be going in the wrong direction.

We're trying to eke every millisecond out of startup time that we can- deferring view construction until after the first animation frame just to get consistent load behavior seems like the wrong solution.

I'd much prefer to be able to make a call to Polymer.RenderStatus.makeReady and have a predictable system.

**Comment by azakus** [comment]
@peteblois I've pulled out your suggestion around `RenderStatus.makeReady` into #3543
