### ISSUE TITLE
Polymer dom api childnodes array empty

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#3541]
Originally discovered by @rubenstolk . The Polymer TreeApi incorrectly reports that the childNodes array of the (root) element is empty.

#### Live Demo
https://jsbin.com/xucajipowo/edit?html,console,output

#### Steps to Reproduce
1. Open the JSBin
* Observe that the native childnodes array has length 3
* Observe that the `Polymer.dom` api `childNodes` array has length 0

#### Expected Results
`Polymer.dom` api `childNodes` array has length 3

#### Actual Results
`Polymer.dom` api `childNodes` array has length 0

### Browsers Affected
(verified broken in Chrome, but I suspect all other browsers too)
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.4.0
- webcomponents: v0.7.21

**Comment by rubenstolk** [comment]
I've started doubting what the expected result should be but it is definitely confusing to me. However I noticed that this has been the way it worked since Polymer v1.0.0.

**Comment by miztroh** [comment]
@TimvdLippe Isn't this because Polymer.dom helps approximate Shadow DOM behavior?  Note the difference between ``Polymer.dom(document.querySelector('#app')).childNodes`` and ``Polymer.dom(document.querySelector('#app').root).childNodes``.

https://jsbin.com/guleyerapa/edit?html,console,output

**Comment by arthurevans** [comment]
@miztroh is correct. If you use `Polymer.dom(my-app).childNodes`, it should return zero nodes, because my-app has no light DOM children.

If you do the native childNodes under shady DOM, you'll get a list that includes both light DOM and local DOM children mixed together—that's how shady DOM gets the browser to render nodes as if they were projected into insertion points in the shadow DOM.

If you actually want the local DOM nodes, use `Polymer.dom(element.root).childNodes`. If you want the light DOM children, use `Polymer.dom(element).childNodes`.

Related docs:
*   [Work with local DOM](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#work-with-local-dom)
*   [Work with light DOM children](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#light-dom-children)

**Comment by arthurevans** [comment]
Also: to test this in native shadow DOM, add the following to your jsbin before you import Polymer:

```
  <script>window.Polymer = { dom: 'shadow' }
  </script>
```

Notice that both methods now report 0 nodes. This shows that the shady DOM API matches the results from the native shadow DOM—which is what we expect.

**Comment by TimvdLippe** [comment]
@arthurevans Thank you for the extensive explanation! After an hour of debugging we still did not understand why it had different results.
