### ISSUE TITLE
Allow `set()` to set read-only properties

### ISSUE THREAD

**Issue by kaste** [Polymer/polymer#3552]
This is a no-brainer. Currently we are forced to use setters like `_setResult()`. Since we have a general purpose `set()`, it should be possible to use it instead `set('result', ...)`. Why the hell?
1. Way easier to find assignments to a property in standard editors. For JS we pretty much rely on '_find all occurrences of this word_' to guide us through the code.
2. One API to rule them all.

**Comment by devinivy** [comment]
I do like that one must be more deliberate about setting read-only properties.  Maybe `set()` could have a boolean argument indicating "_yes, I'm sure I want to set this even if it's read-only_."

**Comment by kaste** [comment]
Since programming is non-destructive, confirmation flags are usually not needed. I'm heading for the following interface for set `set(path, value, origin)`.

**Comment by TimvdLippe** [comment]
Looking at the [documentation of `set`](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-set) and [`setProperties`](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-setProperties), I think adding another argument to `set` to set read only would make sense. The only concern I have is that `set` can handle paths, while `setProperties` can not. Thus the option makes a lot more sense in `setProperties`, since it can only handle simple properties and thus they can be readOnly, whereas with paths this is a lot more ambigous.

**Comment by TimvdLippe** [comment]
Per discussion with @sorvell: we are not going to add readOnly to set, because set is intended for paths, whereas `setProperties` is intended for a bag of properties.
