### ISSUE TITLE
Setting value via attribute for unupgraded property doesn't fire -changed event

### ISSUE THREAD

**Issue by Saulis** [Polymer/polymer#3605]
### Description

If the element hasn't been upgraded yet, setting a value via attribute to an property which has `notify: true` does not fire a `-changed` event after element has been upgraded. The property observer is called, though. Also, setting the value directly to the property works, the problem is only related with the attribute.
#### Live Demo

http://jsbin.com/fogoru/edit?html,console,output
#### Steps to Reproduce
1. Run the Demo and watch the console logs
#### Expected Results

"listener #foo: foo"
"observer #foo: foo"
"listener #bar: default"
"observer #bar: default"
#### Actual Results

"observer #foo: foo"
"listener #bar: default"
"observer #bar: default"

**Comment by kaste** [comment]
If you declare `<x-foo id="foo" value="foo"></x-foo>` the value foo will be assumed to be coming 'from above', t.i. from a user of the element. During config phase Polymer will not echo such data changes upwards. (Assuming the producer of the value/user of the element already has knowledge of this change.) 

On the other side, if you `<x-foo id="bar"></x-foo>` the default value will propagate upwards. For the same reasons, x-foo produced this value, and the user of x-foo has otherwise no knowledge about this. T.i. the default value is not coming from above(, but from x-foo).

**Comment by Saulis** [comment]
Right, makes sense if that is indeed the intended behaviour – however if you set the `value` directly to the property instead of the attribute, the `value-changed` event will be fired after the element is upgraded. 

To me, this behaviour should be the same independent of the method of assigning the `value`.

**Comment by TimvdLippe** [comment]
This appears to be fixed in Polymer 2: http://jsbin.com/honehigita/edit?html,console,output
