### ISSUE TITLE
icon-toggle-demo - customizing icon outline color at document level fails

### ISSUE THREAD

**Issue by paulgingrich** [Polymer/polymer#3614]
It appears that custom styling using CSS properties is not working in the :root selector.  This was seen on your web site with your own demo.  I went through the demo on plunker and everything worked until the very end (step 5) where the global themes were not working.
#### Steps to Reproduce
1. go to www.polymer-project.org/1.0/docs/start/first-element/step-5.html
2. follow the instructions for building your first element
3. When you get to step 5: Theming with custom CSS properties notice the icon outline color
#### Expected Results

the icon outline color should be red.
#### Actual Results

it is black.
### Browsers Affected
- [ x] Chrome
### Versions

I'm using the latest version on your web site
    <script src="https://polygit.org/components/webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="https://polygit.org/components/polymer/polymer.html">

**Comment by arthurevans** [comment]
Sorry, that is confusing. 

The following text is _after_ the code sample (emphasis added):

Run the demo again, and you’ll notice that the pressed buttons are now blue, **but the main color and outline color haven’t changed.**

**The :root rule-set creates a document-wide default that’s overridden by the corresponding rule inside the icon-toggle-demo element. Try removing the value defined in icon-toggle-demo.html and you should see this default value show up.**

We should add a comment in the code block, because it is super confusing as written.

**Comment by paulgingrich** [comment]
That doesn’t work.

There are not the same property.  Here is the code
    <style is="custom-style">
      /* Define a document-wide default value */
      :root {
        --icon-toggle-outline-color: red;
      }
      /* Override the value specified in icon-toggle-demo */
      icon-toggle-demo {
        --icon-toggle-pressed-color: blue;
      }
      /* This rule does not work! */
      body {
        --icon-toggle-color: purple;
      }

See the rule in :root is different so it should still apply.

If you move the statement out of :root and into icon-toggle-demo rule then it works

For example, this works
    <style is="custom-style">
      /* Define a document-wide default value */
      :root {
      }
      /* Override the value specified in icon-toggle-demo */
      icon-toggle-demo {
        --icon-toggle-pressed-color: blue;
        --icon-toggle-outline-color: red;
      }
      /* This rule does not work! */
      body {
        --icon-toggle-color: purple;
      }

I can’t get anything in :root to apply.

Regards
Paul.

**Comment by arthurevans** [comment]
In `demo/icon-toggle-demo.html` you should have a line like this:

```
--icon-toggle-outline-color: black;
```

Like this: https://github.com/googlecodelabs/polymer-first-elements/blob/master/icon-toggle-finished/demo/icon-toggle-demo.html#L11

If you remove or comment out that line, the corresponding `:root` property should take effect. Basically, `:root` rules are inheriting down the tree, so anything set on a specific element will override them, including the rule in the `:host` ruleset inside `<iron-icon-demo>`.

On the other hand, the selector `iron-icon-demo` is _more_ specific, so that overrides anything in the `:host` rule.

**Comment by TimvdLippe** [comment]
Rereading the docs (https://www.polymer-project.org/2.0/start/first-element/step-5), it appears that the text has been updated to make this more clear. Therefore I am closing this issue.
