### ISSUE TITLE
Using custom element with is= inside another custom element should fail loudly

### ISSUE THREAD

**Issue by Pablo-Ivan** [Polymer/polymer#3642]
### Description

When using `webcomponents-lite.min.js', the Shady DOM is implemented by default, but when rendered, the template tag isn't encapsulated. I am also using data-bindings, and while they work fine when in the Shady DOM, they don't on the Shadow DOM.
#### Live Demo

https://jsbin.com/dexena/edit?html,output
#### Steps to Reproduce
1. Try writing something at the paper-input and see how it works.
2. Then uncomment the script tag, what? No more binding?!
#### Expected Results

Is there a way to get the best of both worlds? Data Binding AND Shadow DOM?
#### Actual Results

If you implement one, the other one breaks.
### Browsers Affected (tested)
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.4.0
- webcomponents: v0.7.2

**Comment by arthurevans** [comment]
Yes, shady DOM doesn't give you as strong style encapsulation as shadow DOM. Styles don't leak _out_ of shady DOM but they do leak in. For document-level styles, you have to use a `custom-style` element to prevent styles from leaking into shady DOM:

https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-style

The binding issue is interesting. You're actually combining two different elements in a novel way that's causing problems.

If you use either:
`<paper-input value="{{name}}">` OR `<input is="iron-input" bind-value="{{name}}">` the bindings work fine in shady DOM or shadow DOM. `<paper-input is="iron-input" bind-value="{{name}}">` fails in shadow DOM. 

Trying to use a `<paper-input>` that is _also_ an `iron-input` should fail everywhere, but for some reason it actually works in shady DOM. I think this is the actual bug here—this should at least log a warning.

If anyone's interested, here's what I believe is going on: `iron-input` adds a listener to itself for input events and uses that to update its `bindValue` property.

`<paper-input>`, which is a decorative wrapper around an `iron-input` element, shouldn't have a `bindValue` property at all, but it looks like when you declared both, the functionality of `iron-input` got mixed in. With shady DOM, this confused `<paper-input>` parent that thinks its an `iron-input` element receives the `input` event bubbling up from its internal `iron-input`, and updates its `bindValue`.

In shadow DOM, the `input` event gets stopped at the shadow root, so it doesn't propagate to the host element (`<paper-input>`), and the `bindValue` on the parent doesn't update. (Note that if you bind to `<paper-input>`'s own `value` property, it works correctly.

**Comment by Pablo-Ivan** [comment]
Oh, ok Arthur. So the solution to have both the Shadow DOM and the binding is to use
`<paper-input value="{{name}}">`. And about the bug, yes, it would be useful to log the error.

**Comment by TimvdLippe** [comment]
As @arthurevans pointed out, this is working as intended. Since `is=` is not supported by Polymer for the time being (as Apple indicated they are not going to implemented this feature, see https://github.com/w3c/webcomponents/issues/509) and as such in Polymer 2 you can not rely on this behavior. This is documented in the upgrade guide as https://www.polymer-project.org/2.0/docs/upgrade#remove-type-extension-elements
