### ISSUE TITLE
Spreading Attributes on Templates

### ISSUE THREAD

**Issue by TheIronDeveloper** [Polymer/polymer#3663]
### Description

It would be super sweet if Polymer supported attribute spreading, similar to what jsx supports [here](https://facebook.github.io/react/docs/jsx-spread.html#spread-attributes).

The idea is you could convert:

```
<my-custom-template one="{{myObj.one}}" two="{{myObj.two}}"></my-custom-template>
```

into:

```
<my-custom-template {{...myObj}}></my-custom-template>
```
#### Live Demo

n/a
#### Steps to Reproduce

n/a
#### Expected Results

n/a
#### Actual Results

n/a
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.X.X
- webcomponents: vX.X.X

**Comment by LM450N** [comment]
Good feature but I prefer know Polymer stays near from standards and doesn't turn itself into a Framework. Maybe when Polymer will support natively ES2015 syntax.

**Comment by 43081j** [comment]
Right now Polymer just parses text nodes and attribute values to detect bindings. It sticks to the HTML spec (and thus, Polymer templates are always valid HTML).

Technically, `{{...myObj}}` is a valid attribute name by the spec [here](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2). So I guess if people really, really wanted this, Polymer could parse attributes named like that and apply spread behaviour.

Personally, I'd rather Polymer stick to just being normal HTML, though. Rather than implementing extra logic on top of how tags are parsed/appended.

**Comment by LM450N** [comment]
Thank you for this clear explanation. I have figured out how much my viewpoint was stupid.

**Comment by 43081j** [comment]
Not stupid at all, it would be a handy behaviour to have :) Just not as straight forward as it seems, is all.

**Comment by TheIronDeveloper** [comment]
I'll try digging in and hopefully opening a PR (I've been on vacation for the past week) :)

**Comment by nazar-pc** [comment]
You can easily write a simple behavior like following:
```javascript
properties: {
    xyz: Object
},
ready: function () {
    for (var p in this.xyz) {
        this[p] = this.xyz[p];
    }
}
```
and then use it in more natural way:
```html
<my-custom-template xyz="[[myObj]]"></my-custom-template>
```
`my-custom-template` because this is not a jsx and as far as I remember only elements with dash are allowed for custom elements, and `[a-z]+` are reserved for future native elements.

This is for one-way data flow, but if you need arbitrary number of properties to go back and forth you can really consider to bind object instead of a bunch of separate properties.

Can you tell a little bit more about use case you have where this feature fits well other than it is already present in jsx?

**Comment by TheIronDeveloper** [comment]
> Can you tell a little bit more about use case you have where this feature fits well other than it is already present in jsx?

My own use case? I just thought it would be a nice-to-have feature. Having worked in react for the past year, I've found attribute spreading is an incredibly useful feature. 

You are totally right, you can use the `ready` function and apply similar behavior. That said, attribute spreading provides a great deal of convenience.

--
ps My bad on the template naming, I updated the original comment, thanks for the catch. 👍

**Comment by devinivy** [comment]
I'd like to reiterate that _some sort_ of solution to this would be wonderful for fully-fledged composition in Polymer.  Also, regarding the labels, I'd say this also applies to v2.0.  A good point of reference is React's "higher-order component" pattern: https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775

**Comment by TimvdLippe** [comment]
If you want to achieve this behavior, you can define your own binding parser in Polymer 2 (override [`_parseBindings`](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element#method-_parseBindings)) to define your own expressions in a base class. The core library is designed to stay slim and give you the option to extend its functionality as described in this issue.
