### ISSUE TITLE
Deep Property Observer fired too often?

### ISSUE THREAD

**Issue by pkaske** [Polymer/polymer#3670]
### Description

I have an observer like `_observeChange(prop.sub)` that is triggered again if `prop.sub` is set to the same value as it already was. The value to set is just a string. I always thought observers on sub props are only called if the value was actually changed. To make this even more odd, any subsequent `set(prop.sub, [same-value-over-and-over])` won't (as I would expect) trigger the observer. 
#### Live Demo

https://jsbin.com/tanuwunofa/1/edit?html,console
#### Steps to Reproduce

In the jsbin:
- console logs `=> a` as expected as it is the observer triggered by element initialisation.
- after 500ms console logs `=> a` again. **This shouldn't happen to my understanding.**
- after 1000ms and 1500ms _no_ console logs are made, as I would expect.
#### Expected Results

The observer should only be triggered once.
#### Actual Results

The observer is triggered twice. Any subsequent `set` operations won't trigger.
### Browsers Affected

- [x] Chrome
- [x] Firefox

I assume all other browsers too, but couldn't test.
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions

- Polymer: v1.4.0
- webcomponents: v0.7.22

**Comment by 43081j** [comment]
FYI this likely happens because Polymer's `__data__` behaves like a cache in some ways.

On initialisation, `__data__['data']` is set to your default value and your observer is called.

On set, the condition `__data__['data.foo.baz'] !== 'a'` is checked, which is false for the first `set(...)` call as no such "cached key" exists yet.

This is because when you `set('data.foo.baz', 5)` it will actually set `__data__['data.foo.baz'] = 5` as well as change `__data__.data.foo.baz`.

**Comment by ronnyroeller** [comment]
+1

**Comment by TimvdLippe** [comment]
This has been fixed in Polymer 2: https://jsbin.com/gadayiwihu/edit?html,console
