### ISSUE TITLE
Behaviors access to this.properties

### ISSUE THREAD

**Issue by lukeshiru** [Polymer/polymer#3681]
### Description

Behaviors can't access `this.properties` of element, the behavior itself and other behaviors from a method.
#### Live Demo

https://jsbin.com/tabuwev/edit?html,console
#### Steps to Reproduce
1. Create a behavior.
2. Put a method inside that behavior that access `this.properties`.
3. `this.properties` is an empty object.
#### Expected Results

`this.properties` should have the defined properties of the object (from the same behavior, other behaviors and the element itself).
#### Actual Results

`this.properties` is empty.
### Browsers Affected
- [x] Chrome
- [x] Firefox
### Versions
- Polymer: v1.4.0
- webcomponents: v0.7.22

**Comment by nazar-pc** [comment]
This is because `this.properties` is only used for element bootstrapping, it is not used after that. Instead, there are `this._config`, `this._propertyInfo` and other internals.

The thing in your demo is not that behaviors can't access `this.properties`, but rather that `this.properties` is actually empty.

> `this.properties` should have the defined properties of the object (from the same behavior, other behaviors and the element itself).

Why?

**Comment by lucasmciruzzi** [comment]
> Why?

Because in the element itself you can access `this.properties` (this is a expected behavior, because there is a "properties" property defined in the same scope), and from the behaviors you can't access it.

This has two issues:
1. **Is inconsisten:** You have access to `this.properties` in the element, but not in the behaviors. If `this.properties` emptyness is intentional, then it should be empty on both cases. If not, then it should have data in both cases.
2. **Is logical:** If I have a "properties" property defined on my scope, I want to access that property, is weird to fill it and then have an empty object.

Besides, access internals like _config an _propertyInfo is not a good practice.

**Comment by nazar-pc** [comment]
`this.properties` is exactly the same as what you've defined in element (not behaviors) and it is kept as is. If it was not defined - it'll be empty. If you want to get properties of the first behavior - you can look at `this.behaviors[0].properties` or iterate through all behaviors if needed.
If you need to know what Polymer uses in runtime under the hood - `this._propertyInfo` is your choice.

I agree that accessing `this._config` and `this._propertyInfo` is not a typical good practice, but would you agree that enumerating all the properties is also quite an edge case too?

I do not see good enough reason why Polymer should manipulate `this.properties` if it is not generally necessary. As for me - consistency is perfectly fine, you literally never access `this.properties` in runtime and thus everything looks exactly how it was defined, which is pretty logical too.

**Comment by lucasmciruzzi** [comment]
The thing is:
- If you define `properties` in the element, behaviors can't access it from methods (trough `this.properties`).
- If you define `properties` in the behavior, the behavior can't access it's own `this.properties`.

I know is an "edge case" as you say, but the thing is I'm making a pure declarative canvas game with some friends. We need to be able to write something like:

```html
<game-root>
  <game-background src="something.svg"></game-background>
  <game-character>
    <game-sprite name="run" src="run.svg"></game-sprite>
    <game-sprite name="walk" src="walk.svg"></game-sprite>
    <game-sprite name="talk" src="talk.svg"></game-sprite>
  </game-character>
</game-root>
```

In this example `game-sprite` and `game-background` both use a behavior called "GameImage", that has that `src` attribute defined. Also both implement a behavior called "GameMethods", that have a method like `getAllProperties()`. We need to always inform the parent element of the children data, so the data flows up and `game-root` uses all the data on his childrens to draw the game in a canvas.

If there is a better or more practical way that having a method to retireve all the properties let me know, but still I think this feels inconsistent... maybe is because I expected behaviors to behave like inheritance (because is the proposed workaround for it).

**Comment by nazar-pc** [comment]
> If you define properties in the element, behaviors can't access it from methods (trough `this.properties`).

1) Why can't? https://jsbin.com/veyisiditu/edit?html,console
2) Why would you even need it, this is not a part of documented public API of resulted component?

> If you define properties in the behavior, the behavior can't access it's own this.properties.

Questions are the same basically.

> The only case where you have access to properties, is in the element itself.

Not true, as I've already said nothing disappears and you can easily access everything in pieces or as the whole. Though, I do not see any public API for this, but if you need, it is definitely doable.

> If there is a better or more practical way that having a method to retireve all the properties let me know, but still I think this feels inconsistent... maybe is because I expected behaviors to behave like inheritance (because is the proposed workaround for it).

Indeed this is not an inheritance, but rather composition. Thanks for example, now I understand better what is your use case. Looks like https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes is what you need. It involves attributes instead of properties, but in you declarative example it should work well.

**Comment by lucasmciruzzi** [comment]
`element.attributes` doesn't preserve the parameters type (all attributes are converted to strings). Still, I think for now I'll solve it with this.behaviors.map(behavior=>behavior.properties) or something like that.

Thanks for the help, @nazar-pc and sorry for taking so long to answer.

**Comment by TimvdLippe** [comment]
Your JSBin is working properly in Polymer 2 now: https://jsbin.com/cefatixira/edit?html,console,output

**Comment by lukeshiru** [comment]
Great! Thanks @TimvdLippe :D
