### ISSUE TITLE
querySelector cannot find elements based on properties set from code

### ISSUE THREAD

**Issue by fejesjoco** [Polymer/polymer#3743]
Add this code to any Polymer element (and add iron-icons and paper-icon-button links):

```
  attached() {
    var el = document.createElement('paper-icon-button');
    el.icon = 'cloud';
    Polymer.dom(this.root).appendChild(el);
    Polymer.dom.flush();
    console.log(Polymer.dom(this.root).querySelector('paper-icon-button').icon);
    console.log(Polymer.dom(this.root).querySelector('paper-icon-button[icon=cloud]'));
  },
```

The code works - I can see a cloud icon in the component. The first console.log() prints cloud, as expected. The second one prints null - it can't find the element based on this property, and that's the problem. I expect querySelector to be able to find elements based on properties set from code.

As a workaround, if I do el.setAttribute('icon','cloud'), then the second console.log() also works. But I can guess reflecting properties like this into the DOM is not always scalable. Also this code is much uglier, I'd rather do querySelectorAll().filter(), but I'd really love a proper solution instead.

**Comment by TimvdLippe** [comment]
@fejesjoco If I am not mistaken, the value of an attribute in a querySelector must be escaped. E.g. `console.log(Polymer.dom(this.root).querySelector('paper-icon-button[icon="cloud"]'));`

**Comment by fejesjoco** [comment]
Escaping is not needed, you can see it works with my workaround. I tried this anyway but it didn't change the outcome.

**Comment by noahlaux** [comment]
you're right that the second selector `Polymer.dom(this.root).querySelector('paper-icon-button[icon=cloud]')` doesn't work because the icon attribute is not reflected to the attributes.

Just out of interest, is there a specific reason why you imperatively create the `paper-icon-button` and then inject it, instead of constructing your dom in the elements template? If you did the latter, you could easily create a dom with attributes that was easy to select. Also, maybe you can elaborate what you'd use that selector for?

**Comment by fejesjoco** [comment]
I'm using a framework that creates a toolbar with buttons and expects to create its own DOM. My code just implements an interface where I tell it to create paper-icon-button's. And then I need to query these buttons for unit tests only.

My expectation is that if Polymer accepts both properties and attributes when setting the icon of the paper-icon-button, it should also work the same way when using querySelector to find it.

**Comment by arthurevans** [comment]
@fejesjoco I think your original message sums the situation up well. 

- `querySelector` doesn't select properties, only attributes. This is a part of the DOM API, and we have no control over it.

- Properties don't reflect to attributes automatically because it's an extra runtime cost that's often unnecessary and frequently (in the case of object and array properties, for example) pretty much meaningless.

- If you want to be able to style based on a property or select it using `querySelector`, you need to either use [`reflectToAttribute: true`](https://www.polymer-project.org/1.0/docs/devguide/properties#attribute-reflection) or set the attribute directly (for example, using [attribute bindings](https://www.polymer-project.org/1.0/docs/devguide/data-binding#attribute-binding). In your case, setting the attribute manually is the way to go.

**Comment by TimvdLippe** [comment]
Closing per above comment and the fact that `Polymer.dom` has been deprecated.
