### ISSUE TITLE
Polymer Isomorphic App? 

### ISSUE THREAD

**Issue by YingshanDeng** [Polymer/polymer#3764]
I want to render in back-end with polymer? Any guidline, thank you!

**Comment by ebidel** [comment]
Web components are a client=side technology. That said, some of the
community is investigating
more isomorphic patterns: https://pimterry.github.io/server-components/

**Comment by MarkPieszak** [comment]
I was trying to do some research on this as well, as Angular2 for example we can use Universal to render it in the server. Ng2 and polymer play pretty well together but since Polymer attaches itself to "window" this causes issues on the server-side of course. :(

Is there anyway to dependency injection this out of Polymer Eric? @ebidel

**Comment by ebidel** [comment]
I don't think it would be too hard to create self-calling anonymous funcs for things and pass in local scopes. There would need to be changes to Polymer core.  cc @kevinpschaaf

**Comment by TimvdLippe** [comment]
Take a look at https://github.com/skatejs/ssr and check out the upcoming talk "SSR Web Components" at the summit: https://summit.polymer-project.org/schedule These two resources should probably address your questions, therefore I am closing this issue.
