### ISSUE TITLE
this.set Not Picking Up Changes to Object

### ISSUE THREAD

**Issue by tylergraf** [Polymer/polymer#3769]
### Description

I asked the question [here](http://stackoverflow.com/questions/38250286/polymer-set-array-not-updating-dom) on stack overflow to find the bug. 
#### Live Demo

http://codepen.io/tylergraf/pen/EyXZva/
Fixed with workaround: http://codepen.io/jshcrowthe/pen/JKypxr
#### Steps to Reproduce
1. Create Array of Objects
2. Call `this.set` to a property on web component
3. Change a property on an object in the array using `.map`
4. call `this.set` with the new copy of array
5. See no change to DOM
#### Expected Results

I expect the DOM to change because of the property change within the array. I'm assuming is this because the `.map` creates a new array but the object is still pointing to the old object in memory or something? I don't know.
#### Actual Results

No change to DOM.
### Browsers Affected

I only looked at Chrome.
### Versions
- Polymer: v1.5.0
- webcomponents-lite: v0.7.22

**Comment by devinivy** [comment]
From my point of view this is expected.  The child element displays `[[item.stuff]]`.  For that to update, someone has to inform the child of a new `item` or an updated `item.stuff`.  In this case there's no notification of such a change, so you don't see an update.  Maybe you expected the dom-repeat to re-render all of its children?  I agree that it appears there's an optimization being made by dom-repeat.

**Comment by tylergraf** [comment]
@devinivy Right, so the childe element has no idea it needs to update. Yeah, I expect the parent element to rerender all the children since the array has changed.

**Comment by TimvdLippe** [comment]
This is working as intended as the object that is being modified is not a property, but rather managed on `window`. Therefore, Polymer does not know you are making any changes. Either you need to make it a property of the custom element, or use the [`MutableData`](https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.MutableData) mixin to trigger the update. In general, we advise custom elements authors to not be depended on properties outside of the element scope and manage any internal data-structures in the element rather than from the outside.
