### ISSUE TITLE
Tap event doesn't fire on touchscreen tap followed by mouse click

### ISSUE THREAD

**Issue by tgsergeant** [Polymer/polymer#3784]
### Description

Tap event listeners do not fire when the user does a touchscreen tap followed by a mouse click. This issue is ported from https://crbug.com/618968.

#### Live Demo
https://jsbin.com/xewatatevi/edit?html,console,output

#### Steps to Reproduce
1. Open JSBin link above on a touchscreen laptop
2. Tap button one on a touchscreen
3. Click button two with a mouse

#### Expected Results
The event listener should fire for both events, printing 'tap' to the console twice.

#### Actual Results
The event listener only fires for the first tap, the second one is ignored.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge

Untested:
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: 1.6.0
- webcomponents: latest

**Comment by azakus** [comment]
Currently, there is a 2500ms blanket ignore of mouse input after touch input (https://github.com/Polymer/polymer/blob/master/src/standard/gestures.html#L44) to ignore delayed synthetic click events from triggering tap.

Now, that value was chosen because some _really bad_ devices could send out a synthetic clicks far after the touch. I'm open to making that configurable, or allow it to be disabled entirely.

For now, you can call `Polymer.Gestures.resetMouseCanceller()` to reset the timeout.

**Comment by azakus** [comment]
One thought: At least on Chrome, I can use the [Input Device Capabilities](http://wicg.github.io/InputDeviceCapabilities/) spec to determine if incoming events came from a touch or not.
