### ISSUE TITLE
ApplyShim can produce incorrect properties when elements are shared

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#3802]
See http://jsbin.com/qipodaq/edit?html,output. Inside `x-host2`, `my-element` should have a green background. 

In this case `x-mixin` contains a rule `@apply --mixin`. It is used within `x-host1` and `x-host2` but each of these defines a different set of properties for `--mixin`. Whichever of these elements stamps last will have incorrect properties applied via `@apply --mixin`. This is because we "bake" the stylesheet for `x-mixin` at the time its first instance is created.

Here's a proposal for how to fix this:

- For every mixin name, the ApplyShim keeps a map of elements that depend on (`@apply`) that mixin.
- Whenever the set of properties for a mixin is added to, each of the elements in the elements map is invalidated.
- Whenever an element is created, if it has already run the ApplyShim, it checks to see if any of its mixin dependencies are invalid and if so, it re-runs the ApplyShim. For ShadyDOM, this can replace the element's stylesheet. For ShadowDOM, it is probably good enough to fix the stylesheet in the element's template thus affecting all subsequent instances.

Sketch:

When `x-host1` is defined:

```
MixinMap:
  '--mixin': {
    properties: {color: true},
    elements: {'x-mixin': true}
  }
```

When `x-host2` is defined:

Add `background: green` to `--mixin` and invalidate `x-mixin`
 
```
MixinMap:
  '--mixin': {
    properties: {color: true, background: true},
    elements: {'x-mixin': false}
  }
```

When the next `x-mixin` is created:

- IF it has already run the ApplyShim, 
- then get the list of mixins it uses [`--mixin`], 
- check if any of these are invalid `(MixinMap['--mixin'].elements['x-mixin'] === false)`
 - if yes, re-run the ApplyShim

**Comment by mgiuffrida** [comment]
Some fiddles:

`paper-input ` and `paper-dropdown-menu`: 
[without native css props](https://jsfiddle.net/mgiuffrida/03wkv1yo/)
[with native css props](https://jsfiddle.net/mgiuffrida/ghnthk7f/) -- the middle of the dropdown menu is no longer `cursor: pointer`, and my test finds a bunch of properties that get thrown out:

> Property "overflow" set for --paper-input-container-input but never applied
> Property "white-space" set for --paper-input-container-input but never applied
> Property "text-overflow" set for --paper-input-container-input but never applied
> Property "max-width" set for --paper-input-container-input but never applied
> Property "box-sizing" set for --paper-input-container-input but never applied
> Property "cursor" set for --paper-input-container-input but never applied

`paper-dropdown-menu` and `paper-slider`:
[without native css props](https://jsfiddle.net/mgiuffrida/76mpofd3/)
[with native css props](https://jsfiddle.net/mgiuffrida/bhnrLyko/) -- the number input is no longer centered, because:

> Property "text-align" set for --paper-input-container-input but never applied

**Comment by mgiuffrida** [comment]
Ugh, I've found another issue caused by `useNativeCSSProperties` which seems a bit different. I actually think this may be a bug in the *non-native-properties* `@apply` shim.  It causes the search box in the toolbars of Chrome's material Web UI pages (e.g. history) to have the wrong font size and color:

[without native css props](https://jsfiddle.net/mgiuffrida/b0fLtg2j/) -- label inherits body color
[with native css props](https://jsfiddle.net/mgiuffrida/v32oyt0a/) -- inheritance fails

```
    <style is="custom-style">
      paper-input-container {
        --paper-input-container-label: { color: inherit; };
      }
    </style>
    <paper-input-container>
      <label id="prompt">Label</label>
    </paper-input-container>
```

Inside the `paper-input-container`, this becomes:

```
.input-content ::content label {
        color: var(--paper-input-container-label_-_color,
                   var(--paper-input-container-color,
                       var(--secondary-text-color)));
}
```

where `--paper-input-container-label_-_color` is `""` on the `paper-input-container` and its `label`.

It doesn't seem to matter if you set a color (`color: green`) anywhere else outside of the mixin; it will never inherit.

I filed issue #3803. I'm noting it here so I don't fall for this trap again when trying to test *this* issue.

**Comment by mgiuffrida** [comment]
Yeah, so considering both issues in paper-elements and throughout our material UIs, Chrome can't roll unless we disable useNativeCSSProperties first. It's probably not feasible for us to apply the hacks we discussed everywhere they're needed.

**Comment by sorvell** [comment]
The current fix does not address the problem reported here: https://github.com/Polymer/polymer/issues/3802#issuecomment-234704220. Specifically, if an element has a dependency on a mixin that is not yet defined, it does not mark itself as depending on that mixin.
