### ISSUE TITLE
CSS variables ignore media query rule

### ISSUE THREAD

**Issue by AndreasGalster** [Polymer/polymer#3830]
Now that #2149 seems to be fixed with 1.6, it would be nice to also allow this use case of custom properties in media queries:

```
:root {
   --xs: 600px;
}

@media screen and (max-width: var(--xs)) {
   div {
       background: blue;
   }
}
```

Custom properties are currently being ignored as a value within a media query rule.

**Comment by thgreasi** [comment]
:+1:

**Comment by AndreasGalster** [comment]
Any news if we can expect this to work in the future :)? Seems this was labeled as 1.x, which sounds like this was expected to be working with 2.x

**Comment by web-padawan** [comment]
The currens [spec](https://www.w3.org/TR/css-variables-1/#using-variables) does not support it, saying exactly this:
```
 The var() function can not be used as property names, selectors, or anything else besides property values.
``` 

Therefore, we should wait for next level of the CSS media queries module. There used to be a [custom media](https://www.w3.org/TR/2016/WD-mediaqueries-4-20160126/#custom-mq) proposal in the level 4, but later on iy became a part of the [level 5](https://drafts.csswg.org/mediaqueries-5/).

Since Polymer 2 relies much on native custom properties, I don't think this should be polyfilled now, that would require switching back to polyfill for the one limited use case.

**Comment by TimvdLippe** [comment]
Thanks @web-padawan for digging into this. As CSS variables are now widely adopted (http://caniuse.com/#feat=css-variables) Polymer does not do anything specific for this. As such, if you would like to have this feature, please participate in the spec discussion at https://github.com/w3c/csswg-drafts/issues
