### ISSUE TITLE
Forwarding parent properties to templatized templates

### ISSUE THREAD

**Issue by tpluscode** [Polymer/polymer#3835]
### Description

`_forwardParentPath` and `_forwardParentProp` are never triggered with `Polymer.Templatizer`
#### Live Demo

http://jsbin.com/kipato/edit?html,js,console,output
#### Steps to Reproduce

Stamp template by passing a property in the model to `stamp` method.
Add stamped template to DOM
Try modifying parent's properties
#### Expected Results

When a property on parent element is modified it should be possible to propagate this change to the templates.
#### Actual Results

Changing properties on the parent doesn't update them in stamped template nor are the `_forwardParentX` functions called.
### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11
### Versions
- Polymer: v1.6.0

**Comment by tpluscode** [comment]
The only way I managed to get actual two-way binding was to add the `_updateTemplate` in the linked example.

**Comment by TimvdLippe** [comment]
This appears to be fixed in Polymer 2: http://jsbin.com/zoqupatewi/edit?html,js,console,output Note that you have to specify the `instanceProps` dictionary with the properties you want to listen for. The `notifyInstanceProp` will update the instance with the new values for the host, while the template gets the properties with the `instanceProps`.
