### ISSUE TITLE
Mixing `.splices` and `.*` in observation does not work

### ISSUE THREAD

**Issue by johannesr89** [Polymer/polymer#3878]
https://jsfiddle.net/tqcrqran/70/

Please notice how the first div does **not** have the class `called`, but the other two do have it. Also please notice how `sthElse` is logged twice, but `called` is never logged.

**Comment by arthurevans** [comment]
Reproduced. Using `foo.*,bar.*` as the observer dependencies works;  using `foo.splices,bar.*` as the argument does not, even though both `foo.splices` and `bar.*` are firing individually. 

@azakus @kevinpschaaf

**Comment by kevinpschaaf** [comment]
This is as expected; [see docs here](https://www.polymer-project.org/1.0/docs/devguide/observers#multi-property-observers): "Multi-property observers are not invoked until all dependent properties are defined (!== undefined)".

Since `foo.splice` is only defined as a result of a notification from an array mutation to `foo` via `push`/`pop`/`splice`/`shift`/`unshift`, such an observer wouldn't be called simply by setting the array.  To catch every change to `foo` (both initial set and splice/mutations), listen for `array.*` as @arthurevans suggested.

**Comment by johannesr89** [comment]
Then why is the observer observing just `foo.splices` called when setting `foo`?

**Comment by arthurevans** [comment]
@johannesr89 I wondered the same thing. I feel like there's a bug here somewhere, @kevinpschaaf, because the single-property observer on `foo.splices` is getting called, and usually it isn't.

**Comment by pomber** [comment]
Note that this issue is not related to `bar` wildcard. It also happens with `(foo.splices, bar)`.  
It's very confusing that the same path (`foo.splices`) works in a simple observer but doesn't work in a complex observer.
