### ISSUE TITLE
[dom-if] Expose an API to restamp on demand without cycling the if property value.

### ISSUE THREAD

**Issue by aabdagic** [Polymer/polymer#3887]
We have a few use-cases where if a significant property changes (think ID in the URL parameter), we'd rather just destroy the whole page and recreate it, instead of even attempting to propagate the change. This is because change of this param causes reloading of all the data that depends on that param (which is really all the data on the page), but loading of this data happens in stages as there is data that depends on the ID indirectly. So instead of dealing with possibly inconsistent UI for the duration of the load, or with complex "reset" implementations in various components, an approach that works well for us it just restamp the whole page and all components.

We can currently achieve this by cycling the value of the `if` property of the dom-if template, but would like to avoid that as it introduces a fair amount of convoluted code to actually extract the property.

**Comment by jfrazzano** [comment]
Have you tried a templatizer? and do you use a prototype with classed objects as its sub-objects to manage data?

it allows you to avoid using the dom-if all together, and the related convoluted computes onto of computes needed for user switches, or nonhierarchical routing.

if you did, or are interested read the below… if not… I know exactly the difficulty of the dom-if dilemma and sympathize.  let me know if you find a good solution.


BELOW ONLY IS AN ALTERNATE APPROACH: IT STEPS OUT OF TRADITIONAL POLYMER, BUT USES ONLY NATIVE JS onto of POLYMER.

I took an approach, prior to starting work with the router (last week—I am tempted to make my own router after one week—), which creates a prototype DataManager in the script above the behavior of that same name, the function DataManager(user), takes a user object at construction, then the user objects dictates (1) which class sub-objects get attached to DataManager.  Example, for an client— dataManager.arrayWorker is webWorker with class “arrayWorker” is attached to handle any array restructuring off thread, in order to restructure data between views— we do a lot of our page building with repeats, four templates, and then just let the data and its structure dictate the css, presentation, etc.; a client will also receive the workers indexedDB, fireBase, gridBuilder, and fanOutHandler;  The client will also have sub classes: dashboardInterface, which manages a map of all the data the client will have access to and passes that data through the dataManager object to the three save sources, and the view builders.

its all connected to polymer through an intentional single instance instantiation of the dataManager behavior property userManager:{type:DataManager, value: userManager [NOTE: NO FUNCTION TO RETURN VALUE HERE TO ASSURE A SINGLE INSTANTIATION]… notify: true},

what this allows is a serialized load of the data we need via the instantiation of the various classes and the constructor of the dataManager… 

then we don’t use pages really, we use fragments to build out our system.  panels, drawers, assistants and grids… which are all really just a list, a grid, and a dialog… 

we then add an input-search-select which is a custom animated input/textarea which has what was once our context menu, as a dropdown wherever and whenever a dropdown or menu for that matter (we are ironing this out right now)… the dropdown or menu then searches via text area/input… form data is handled through a valueObject manager… tied to the userManager…  its rather simple really, and on the data grids we can load about 500,000 cells from firebase/idb in 1.8 seconds on first load… 1000 cells only limit on first load has been connection… or whoops we blew a socket, need more workers.  

What is your html structure? We are all repeater and template stampers, which has been sorta murder in terms of using the router, when combined with our dataManager UI, which has a god object model… something specifically against Pete’s talk regarding router design.

I hope this helped.  Or at least made sense.  Our approach to the same problem was to remove as much html as possible, load data in stages via structured design, and do said load based on an archive of state, that tells us the last state, for load order… it was and is a ton of logistics but its getting easier. And once a system is worked out, all the code becomes this.userManager[task][subTask][viewFragment](dataUpdate);  solid naming then allows the actual names and labels of all the subObjects functions, and properties to match the bracket interior for any change. [INTERIOR]…

But, as I said, routing has made this more complex.

Sincerely, 

Jason

**Comment by jkji** [comment]
Is there a simple workaround? Is this solved in Polymer 2.0? It would indeed be very convenient to have a way to restamp pages when IDs change.

**Comment by TimvdLippe** [comment]
For these purposes, `<dom-if>` can be used to cycle through. However, if you would like to have more control, you can use the `templatizer` directly: https://github.com/Polymer/polymer/blob/master/lib/utils/templatize.html (docs are not working atm due to #5037 ) We have no plans to support a new component for this particular use-case.
