### ISSUE TITLE
Changing value in <property>-changed listener fires observers

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3932]
_From @e111077 on August 29, 2016 17:44_
# Description

Changing a value in a `<property-name>-changed` event listener seems to fire pending observers resulting in a really-confusing order of operations.
# Repro Case

``` html
<link rel="import" href="../polymer/polymer.html">

<dom-module id="asdf-asdf">
  <template>

  </template>
  <script>
    Polymer({
      is: 'asdf-asdf',
      properties: {
        value: {
          type: String,
          notify: true
        },

        linkedValue: {
          type: String,
          notify: true,
          observer: 'linkedValueChanged'
        }
      },

      linkedValueChanged: function() {
        console.log('change value in observer');
        this.set('value', this.linkedValue);
      }
    });
  </script>
</dom-module>

<asdf-asdf id="asdf"></asdf-asdf>

<script>
  asdf.addEventListener('linked-value-changed', function() {
    console.log('change value in event listener');
    asdf.value = 'THIS IS WRITE';
    console.log(asdf.value);
  });

  asdf.set('linkedValue','THIS IS WRONG!!!');
  console.log(asdf.value);
</script>
```
## Expected Result

Optimal, prints:

```
change value in observer
change value in event listener
THIS IS WRITE!!!
THIS IS WRITE!!!
```

Still makes sense, but not-really-expected:

```
change value in event listener
THIS IS WRITE
change value in observer
THIS IS WRONG!!!
```
## Actual Result

```
change value in event listener
change value in observer
THIS IS WRONG!!!
THIS IS WRONG!!!
```
# Workaround

Do not use listeners on `<property>-changed` but instead create an observer and do all changes in the observer. This doesn't really work well because you can't add an observer to an element nicely after it has been created.

_Copied from original issue: PolymerLabs/alacarte#100_

**Comment by kevinpschaaf** [comment]
In 2.0, the order of effects is:

1. `computed`
1. **`notify`**
1. `bindings`
1. `observers`

So when the `linked-value-changed` notify effect and and listener runs, there is still a pending observer for `linkedValue` whose user code re-sets `value`.  Setting `asdf.value` in that event handler causes `_propertiesChanged` on the element to re-enter due to `value` having an effect (notify), and in the process flushes all pending effects, causing `value` to be set in the observer and revert it synchronous to the `value` set.

So the code explains why this happens; the severity of the problem is debatable.  These types of patterns (having multiple actors trying to synchronously control the value of a single property) introduces two sources of truth and brittle time-based/ordering dependencies -- basically, to be avoided when possible.

@e111077 Can you help me understand the use case so we can understand the problem a little deeper and potentially offer alternate solutions?

**Comment by e111077** [comment]
This again is an issue that stems from `app-route`.

The use case is the following:

- `app-route` has a `route` object that has a `path` property
- changing `route.path` may change the data associated with this route (e.g. pattern is `/:page` path is set to `/email` data is set to `{page: 'email'}`)
- changing the data associated with a route should change the path
- a user might want to change the path using the data in response to the path changing (e.g. path changed to `/email` and you see that they are not logged in so you do `data = {page: 'login'}`)

Regardless of the use case, the example provided in the initial issue filing is pretty leaky; reassigning a variable and having a different observer fire in response does not make much sense. If an observer must fire because of this value change, it would make sense for the flush to happen before the reassignment, or else you get this case where the value changes on the line right after it was reassigned.

In the case of `app-route` not supporting this use case will cause a user to run into a bug where they changed a value that should logically change the route, but it seems to remain unchanged.

**Comment by sorvell** [comment]
Firing the notification event late (manually in this case) seems to address the issue.

http://jsbin.com/dazonac/edit?html,console,output

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4221.

The effect order was reworked as follows:
1. `computed`
2. `bindings`
3. `observers`
4. **`notify`**
