### ISSUE TITLE
`hostAttributes` objects are applied backwards

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer#3938]
_From @bicknellr on September 8, 2016 21:2_

`hostAttributes` applied in an element definition are overridden by `hostAttributes` from behaviors they use.

The order of the two calls in this function might be the problem:
https://github.com/PolymerLabs/alacarte/blob/8f237fc635cc56092e83172832bac22ee671c8b0/src/legacy/class.html#L104
And I think the test here is wrong:
https://github.com/PolymerLabs/alacarte/blob/fe0f812a89f356496e1418e44a05cc929c8d652c/test/unit/behaviors.html#L406

_Copied from original issue: PolymerLabs/alacarte#116_

**Comment by sorvell** [comment]
This is because in 1.0, the list of `hostAttributes` was flattened (with element winning over youngest to oldest behavior) and then applied if the element did not have the attribute. In 2.0, the list is not flattened and applied per behavior in order. This is fixable to match the 1.0 order, but the 1.0 order seems a bit arbitrary. Given the limited use of `hostAttributes`, I wonder if this would be ok to break as the new order seems more sensical. Iow, @bicknellr when/how did this come up?

**Comment by bicknellr** [comment]
So this came up when looking at porting an element that uses a behavior and wants to override a value in `hostAttributes` of that behavior. Shouldn't the deepest thing in the hierarchy win? What is the new order and why would it make more sense?

**Comment by sorvell** [comment]
Per discussion, the specific use case here was an element trying to override the aria role set in a behavior. This seems totally reasonable so we'll just fix the ordering to be more like 1.x.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/3944
