### ISSUE TITLE
Unable to align "description" in different paragraph,please help

### ISSUE THREAD

**Issue by hash9** [Polymer/polymer#3942]
how can i add description in paragraph style in polymer
here is the function code:
`properties: 
            {
                config: 
                {
                    type: Array,
                    value: function() 
                    {
                        return [
{
                                value: 2, color: 'keylinepushing', image: 'img/keylinepushing.png', title: 'Keylines', role: 'Android Developer, UI/UX Designer', **description**: 'In Material Design, all components align to an 8dp square baseline grid, except type and toolbar iconography,', lightboxone: 'images/lightbox/keylines1.png', 
                            }`

**Comment by arthurevans** [comment]
From your bug title, it's not clear what your issue is. Are you having a problem with the way the code's formatted in your editor (which is not really a Polymer issue)? Or is the element not working as you expect?

I assume you were trying to highlight the word "description" above, and you don't actually have `**` surrounding it in the code...

**Comment by hash9** [comment]
Thankyou Sir, but the problem which i was facing with the code has been resolved. Actually i was unable to format the description into fragmented paragraphs.
