### ISSUE TITLE
dom-repeat doesn't stamp correctly

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#3946]
### Description
`dom-repeat` should update the values when setting `t.items = t.items` and update the dom with the new values. This currently happens only on the first setting of the array.

#### Live Demo
http://jsbin.com/rumiko/2/edit?html,console,output

#### Steps to Reproduce

1. click `add` button

#### Expected Results

Dom should have 2 paragraphs with `item 0`, `item 1`...as many times as add was clicked

**Comment by valdrinkoshi** [comment]
@kevinpschaaf FYI

**Comment by jfrazzano** [comment]
If only the items sub properties are changing, then the best way to trigger an update of the values that are changing is to use one of the notification apis, particularly on a sub-property of an item object:


.  Example: for(var i=0; i<i.items.length; i++){ this.set([“t.items”, i, “name”], this.t.items[i].name);  },


while a bit tedious it works.  If you are interacting with the dom to change the item[properties], or the items proper, var model= modelForElement(e.target);var item= itemForElement(e.target)l;  model.set(item, [newValue]);

if you know the id of the template repeater, and are in the local dom of the repeater, you can use the `this.$.`domRepeatId convenience method-- (note here if you are using a variable for the element id, you should use something like var theId=“#”+someValribleThatHoldsTheId; var theDomRepeat= this.$$(theId) to grab the domRepeat)—and then use: Polymer.dom( theDomRepeat).children, and step through the children yourself to check on the properties you think have changed and then use the modelForItem and Model for Element above.  If you do it once or twice you will quickly want to write some convenience functions for the different use cases, it makes the mutation observing and updating more pleasant.

A js mutation observer could also do the trick.  I am about to try using the templatizer and an native mutation observer to see if I can’t both compose complex elements on the fly, maintain the updates of deeper mutations, and just do something cool.  Will let send a demo if anything works out.  

Hope that helped.

Sincerely, 

Jason

PS… the document get element will likely be a bust in shadow dom, and there were a few other little things from my quick look at your code, I didn’t go further only because i couldn’t run the demo. 

I pulled the error log pasted below:

"ReferenceError: customElements is not defined
    at https://polygit.org/polymer+Polymer+:2.0-preview/webcomponentsjs+webcomponents+:v1/components/polymer/src/legacy/dom-module.html:82:3
    at https://polygit.org/polymer+Polymer+:2.0-preview/webcomponentsjs+webcomponents+:v1/components/polymer/src/legacy/dom-module.html:89:3"
"error"

**Comment by sjmiles** [comment]
Fwiw, in the repro, the additional elements are being created, but they each have (what appears to be) only a single-space as content.

**Comment by jfrazzano** [comment]
@ Scott J. Miles… That’s interesting, now I really wanna see it.  Will find the link and look.

Thanks. Scott.  You know why they are popping a single space?

**Comment by kevinpschaaf** [comment]
This is due to bad interaction between removal of 2.0's Object/Array dirty checking and the Collection abstraction's use of array identity for key tracking, which still needs to be resolved in the 2.0 codebase.  For time being please revert to using the legacy array path API's for mutating array data, which should still work.

**Comment by sjmiles** [comment]
Fwiw, it's also possible to treat the array as an _immutable data structure_ and create a fresh instance for each mutation, ala

```js
var items = t.items.slice();
items.push({
  name: 'item ' + t.items.length
});
t.items = items;
```

https://jsbin.com/vamibu/edit?html,output

**Comment by sorvell** [comment]
Closed via https://github.com/Polymer/polymer/pull/3970.
