### ISSUE TITLE
Array observer called twice whenobserving with .* (star) and using .push

### ISSUE THREAD

**Issue by johannesr89** [Polymer/polymer#3979]
http://jsbin.com/tobaloceva/edit?html,output

Is this the expected behavior?

**Comment by arthurevans** [comment]
This is expected. If you check the change record, you'll see it's getting notified for two different paths: `arr.splices` and `arr.length`. 

```
arrChanged_(cR) {
  console.info('called for ' + cR.path);
},
```

**Comment by johannesr89** [comment]
Yeah, I was expecting that, thanks for the explanation. This is still a bit confusing: What would be the use case for being notified twice? I would think you would always only want one notification?

**Comment by kevinpschaaf** [comment]
Polymer sends `array.length` notifications for array mutations that modify the length so that bindings to e.g. `<div>{{array.length}}</div>` will update.  This is separate from the `array.splices`, whose notified value carries the actual mutation information.  Since they are two separate pieces of information, it results in two notifications.
