### ISSUE TITLE
Polymer 2.x functional design proposal

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#3989]
As mentioned in your blog post Polymer 2.x is going to take advantage of ES6 and the new web-component specifications. But it also mentions to try to be backward compatible as much as possible. Here is my concern. The following example works in chrome beta today. If you would make the same example using polymer it looks completely different. My biggest fear is that polymer is going to look more like a dialect of web-components once every browser has the full web-component stack. I think it's not that hard to imagine that eventually people will want to use vanilla js as much as possible and use polymer as more jquery like for their elements and only want to use very specific parts of polymer depending what their element needs to do. I believe a more modular design of polymer is needed for elements in a few years from now.

``` html
<!DOCTYPE html>
<html>
<head>
  <title>Test</title>
  <link rel="import" href="template.html">
</head>
<body>
  <hello-world>Hello World</hello-world>
</body>
</html>
```

``` html
<template>
  <style>
    :host {                                                                                                                
      display: block;                                                                                                      
      box-sizing: border-box;                                                                                              
      border: 1px solid red;                                                                                               
    } 
  </style>
  <p>Test</p>
  <slot></slot>
</template>
<script src=template.js></script>
```

``` js
class HelloWorld extends HTMLElement {
  constructor() {
    super()
    let l = document.querySelector('link[rel="import"]')
    let t = l.import.querySelector('template')
    const instance = t.content.cloneNode(true)
    let shadowRoot = this.attachShadow({ mode: 'open' })
    shadowRoot.appendChild(instance)
  }
}
customElements.define('hello-world', HelloWorld)
```

**Comment by 43081j** [comment]
In Polymer 2.x you simply inherit `Polymer.Element`, how is this "more like a dialect"?

You could most likely use the exact code you've posted, but extend `Polymer.Element` instead (or if you must, specific parts of Polymer). It extends `HTMLElement` anyway, so if anything, 2.x is _closer_ to vanilla components than 1.x was.

**Comment by gertcuykens** [comment]
I will try to make a Polymer 2.x comparison to be more clear, as far as I can see extending `Polymer.Element` will force you to use a polymer2 constructor and have to use every polymer2 prototype.

**Comment by kevinpschaaf** [comment]
The point is that in Polymer 2.x, the fact that you used Polymer (i.e., extended from `Polymer.Element`, as opposed to `HTMLElement` or `OtherFramework.BaseElement`) is an _implementation detail_ of your element, nothing a user from the outside can tell or needs to be concerned with.  If we do our jobs right, in your "raw" custom element above you can include a `<paper-tabs>` built with Polymer 2.x in your template and poke its attributes/properties and listen to events however you want.  And a Polymer 2.x user can include your raw element (or whatever elements he/she wants) and be happy.

If what you're saying is "all I need to do is stamp a static template, and I don't need all the features of Polymer", then it's totally groovy to extend from a more raw base class, because they'll all work together.  If you want more features like data-binding, observers, declarative listeners, etc., then you might turn to a tool like Polymer to accomplish the tasks your element needs to do.  But from  goal is exactly to remove any whiff of "dialect" (how you built your element's internals) from the external API of the element.

The Polymer 2.x base class `Polymer.Element` is actually constructed out of a series of class expression mixins that compose together all of the functionality, and could also be used alacarte to build your own base class.  e.g. You can actually do something like this today:

```js
// Mix "property accessors" functionality onto class
class HelloWorld extends Polymer.PropertyAccessors(HTMLElement) {
  static get observedAttributes() { return ['foo', 'bar'] }
  constructor() {
    super();
    let l = document.querySelector('link[rel="import"]');
    let t = l.import.querySelector('template');
    const instance = t.content.cloneNode(true);
    let shadowRoot = this.attachShadow({ mode: 'open' });
    shadowRoot.appendChild(instance);
  },
  // Implement "propetiesChanged" callback
  _propertiesChanged(props) {
    // do something with `props.foo` and `props.bar`, like propagate to shadow children
  }
}
// Create accessors on class that will result in _propertiesChanged being called
HelloWorld.observedAttributes.forEach(p =>
  HelloWorld.prototype._createPropertyAccessor(p)
);
```

Then, you might want to, say, make sure the element's property API and attribute API stay in sync, so you might mix in `Polymer.Attributes` and use that API, and so on.  Polymer is really just the result of taking the experience of building a bunch of elements and codifying all the best practices and repetitive work into easier to use API's, but at any point you should feel free to fall back to more native/closer-to-the-metal techniques to get your element's job done.

But maybe we're missing your point, so feel free to clarify.

**Comment by gertcuykens** [comment]
Here is the same example using the recommended setup

```html
<link rel="import" href="bower_components/polymer/polymer-element.html">                                                
<dom-module id="hello-world">                                                                                                
  <template>                                                                                              
    <style>                                                                                                                  
      :host {                                                                                                                
        display: block;                                                                                                      
        box-sizing: border-box;                                                                                              
        border: 1px solid red;                                                                                               
      }                                                                                                                      
    </style>
    <p>Test</p>                                                                                                               
    <slot></slot>                                                                                                              
  </template>                                                                                                                
  <script>
    class HelloWorld extends Polymer.Element {
      static get is() { return 'hello-world'; }
      static get config() {
        return {}
      }
      constructor() {
        super();
      }
      connectedCallback() {
        super.connectedCallback();
      }
    }
    customElements.define(HelloWorld.is, HelloWorld);
  </script>
</dom-module>
```

I am sure a polymer expert can make it look more like my vanilla example, but as you can see the recommended polymer setup diverges allot from my vanilla example. My point is if it wasn't for backward compatibility polymer would look way more modular. And I don't think they would go for a Polymer.Element class approach but stick with the vanilla HTMLElement class and introduce optional constructors instead.

**Comment by gertcuykens** [comment]
Note that I want to envesize this is just feedback :) Meaning I am testing your commitment and logic in designing polymer. I am a noob at webcomponents :P But I want to make sure polymer team is thinking of the bigger picture here. Not just how are we going to save our paper-elements so we dont need to start over :)

**Comment by gertcuykens** [comment]
one more example of what I mean by modulare
```js
class HelloWorld extends HTMLElement {
      constructor() {
        super();
        // only if i want to use the <dom-module> tag instead of a plain vanilla template
        polymer.module('hello-world')
        // only if i want to use polymer properties and databindings
        polymer.config({is:'hello-world'})
        // and many more specific polymer things I can opt into but totally works fine without if I dont need them
        polymer...
      }
    }
```

**Comment by sorvell** [comment]
We initially tried an approach like the one suggested but found it too cumbersome for customizing via subclassing. We've chosen to layer in functionality via class expression based mixins. While we're providing a convenient base class (`Polymer.Element`) we hope that users will use our mixins piecemeal where appropriate or not at all if unnecessary!
