### ISSUE TITLE
linkPaths does not work with primitives in arrays

### ISSUE THREAD

**Issue by sandro-k** [Polymer/polymer#4024]
Not sure if its a bug or not, but the behaviour is a bit strange and should be documented if its not a bug. 

`Polymer.Base.linkPaths(to, from)` is working if the `from` value is an object, but not if its a primitive

```
data: {
          type: Array,
          value: function () {
            return [
              {value: {deep: 1}},
              {value: 2}
            ]
          }
        }
// is working if value is an object
this.linkPaths("deep", "data.#0.value");

// is not working if value is a primitive
this.linkPaths("value", "data.#1.value");
```

Looking at the code https://github.com/Polymer/polymer/blob/e614e811fa151d105239b1d5d5521fd2322700f1/src/standard/notify-path.html#L365 is false for the second case and therefor the path is not notified. This is the case because [Polymer.Path.isDescendantL35](https://github.com/Polymer/polymer/blob/e614e811fa151d105239b1d5d5521fd2322700f1/src/lib/path.html#L35) returns `false` for 

```
base = "data.#1.value"
path = "data.#1.value"
```
#### Live Demo

https://jsbin.com/tukoyoc/edit?html,output
#### Expected Results

Both paths will be update when the linked value is changed.
#### Actual Results

Only object are forwarded
### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11
### Versions
- Polymer: v1.7.0

**Comment by akc42** [comment]
I have exactly the same problem, but with a slightly different context.  I am building a router along the lines of `<app-route>`, except that instead of separate parameters everything in held within the `route` object so that I can simultaneously update all the data in one go.  I have an `inRoute` object and an `outRoute` object and like `<app-route>` want to pass the query parameters to all elements.  So I linked paths by calling `this.linkPaths('inRoute.query', 'outRoute.query')`; and the opposite also, so `this.linkPaths('outRoute.query', 'inRoute.query')`;  

I would have expected the calling `element.set('inRoute.query', {date: '20160101});`  would have resulted in `element.outRoute.query` to have been updated accordingly.  It doesn't work and as far as I can see its because `Polymer.Base.isDecendant` is returning false. 

So this is the same problem as above.  If I put an observer on `inRoute.query` it gets called with the above `set` call, and the docs imply if that happens and its the same element, then linked paths should also work.

**Comment by arthurevans** [comment]
@akc42 I'm not sure that's the same issue. Are `inRoute` and `outRoute` both references to the same JavaScript object? `linkPaths` is used for cases where you have two _paths_ that identify the same object. It's not for propagating changes from one object to another. It ensures that property effects are fired for descendants of both paths.

The original report may be related to this
