### ISSUE TITLE
attributeChanged is not being called when removing attributes

### ISSUE THREAD

**Issue by e111077** [Polymer/polymer#4026]
### Description
Removing an attribute from a Polymer element, it does not seem to call attributeChanged.

#### Live Demo
https://jsbin.com/godekapowu/6/edit?html,console,output

#### Steps to Reproduce
1. Create a polymer element with an attributeChanged function
2. Add an attribute to the element
3. From anywhere select the element
4. Call `<element>.removeAttribute(<attributeName>)`

#### Expected Results
Should call attribute changed (here is a 1.0 version of the same case)
http://jsbin.com/lunexuqajo/6/edit?html,console,output

#### Actual Results
Attribute Changed is called
https://jsbin.com/godekapowu/6/edit?html,console,output11

### Versions
- Polymer: v2

**Comment by kevinpschaaf** [comment]
In V1 custom elements, in order for `attributeChangedCallback` to be called, the spec now requires attributes to be defined in a static `observedAttributes` array on the CE class.  `Polymer.Element` (used by the `Polymer({...})` function call) implements an `observedAttributes` getter that calculates the list of attributes based on properties defined in `properties` -- only properties defined here will have `observedAttributes` added.

By adding this to your element, the smoke tests passes:

```js
        properties: {
          hidden: {
            type: Boolean
          }
        },
```

Note that there are no effects for `hidden`; simply declaring it with a type ensures the attribute will receive `attributeChanged` callbacks, without generating a setter for it (which would shadow the native accssor).  Declaring it in the `properties` block _also_ means that the attribute value will be deserialized to the property via Polymer's default implementation of `attributeChangedCallback` (aka for `type: Boolean`, `this.hidden = this.hasAttribute('hidden');`).  Although this is redundant with the native behavior of `hidden`, it shouldn't pose a problem.

Working jsBin:
https://jsbin.com/yudiba/edit?html,output

Although it wasn't required in 1.x (because there wasn't an `attributeChangedCallback` filter in the V0 spec), adding it to the properties block will be equally benign there, making it a "hybrid" solution.

Note in debugging this I discovered what looks like a bug in the 2.x codebase, in that shorthand property syntax did not result in the correct `type` used for deserialization (which is important for `Boolean`):

```js
        // did not work
        properties: {
          hidden: Boolean
        },
```

I don't recall deprecating the shorthand form, but it could have been an intentional change.  For now, filed https://github.com/Polymer/polymer/issues/4066 for that, and for time being use the longhand form.

**Comment by ergo** [comment]
Are there any other workarounds for the issue?
Maybe some way to observe changes to `*` on element?
Basicly I have an url generator element that works like this:
`<uirouter-sref  param-foo=X param-bar=Y param-baz=Z>` it should update its DOM on parameter changes - for 1.x I handled this with `attributeChanged` but since I have to declare list of observed params on the element it is failing in polymer 2.0 because I have no way of knowing attribute name changes upfront.

**Comment by e111077** [comment]
@ergo I haven't tried it but I wonder what would happen if you add an observer on [`dataset.*`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset) and annotate the element with `data-foo` and `data-bar`

**Comment by arthurevans** [comment]
I could be wrong, but I don't think you can observe a native property like
dataset because even if you could create an accessor for it, the browser
wouldn't call it when it sets the property from native code.

**Comment by ergo** [comment]
As per our slack discussion, for now the solution appears to be to use MutationObserver, and it works as expected, I'm a bit worried about performance implications of creating new observer per link, but maybe its won't be a problem.

Thanks again @arthurevans.
