### ISSUE TITLE
Update Polymer 2.0 README with guidance for observeNodes

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer#4035]
It looks like the new way of doing `observeNodes` has landed? Woot!

What do users (and the upgrader tool!) need to know?

**Comment by kevinpschaaf** [comment]
For now, just removed the comment about it being not yet implemented (https://github.com/Polymer/polymer/commit/50badc8285efe677e0b011f5aa3222f984a77294), since we ended up doing a backward-compatible implementation.

Also added a note about current differences in `Polymer.dom.flush` (https://github.com/Polymer/polymer/commit/40fb70e7228a153af5d054a3886dc1a041cf1025), which does not flush `observeNodes` observers anymore.
