### ISSUE TITLE
Polymer.dom.flush does not flush observeNodes

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4036]
In 1.x, `Polymer.dom.flush()` would cause the `observeNodes` callbacks to be invoke.
In 2.x (shadydom) this doesn't happen. If this is expected, could we update the README.md about this gotcha?

``` html
<dom-module id="x-sample">
  <template>
    <slot></slot>
  </template>

  <script>
    Polymer({
      is: 'x-sample',
      properties: {
        count: {
          type: Number,
          value: 0
        }
      },
      attached: function() {
        Polymer.dom(this).observeNodes(this._onNodesChange);
      },
      _onNodesChange: function() {
        this.count = Polymer.dom(this).children.length;
      }
    });
  </script>
</dom-module>

<button onclick="addNode()">add node</button>
<x-sample id="sample"></x-sample>

<script>
  function addNode() {
    Polymer.dom(sample).appendChild(document.createElement('div'));
    Polymer.dom.flush();
    console.log(sample.count);
  }
</script>
```

**Comment by sorvell** [comment]
Yup, this is, unfortunately, a necessary breaking change. The return value from `observeNodes` is an object with a `flush` method. Will add this to the readme.

**Comment by kevinpschaaf** [comment]
As justification, the reason that `Polymer.dom.flush` no longer flushes `observeNodes` callbacks is that `Polymer.dom.observeNodes` (and soon to be `Polymer.FlattenedNodesObserver`) relies on the native `slotchange` event when possible, which fires at microtask timing when a change in distribution occurs, and the browser exposes no way to "force" the event to fire (or to otherwise get information about whether distribution changed).

The only way to implement a flush would be to hold references to all `FlattenedNodesObserver`s and then diff their current nodes against previous; holding the references would then leak without a mandatory dispose API, which would be too onerous and footgunny.  So we landed on just exposing a flush on the observer object returned, which at least provides _a_ way to force synchrony for e.g. tests.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4337.
