### ISSUE TITLE
dom-repeat: external changes only effect [index] but [item] is empty

### ISSUE THREAD

**Issue by ColdFireIce** [Polymer/polymer#4041]
### Description
When using dom-repeat to display the content of an array, external changes are not represented correctly.
Pushing an item onto the array results in creating a new template instance but only the `index` is filled. The `ìtem` stays empty.

I know I could use the [array mutation methods](https://www.polymer-project.org/1.0/docs/devguide/model-data#array-mutation) but thats not an option here. As these changes are made from the outside.

So I tried to [override dirty checking](https://www.polymer-project.org/1.0/docs/devguide/model-data#override-dirty-check). But thats what is not working here.

I also need to keep the reference to the object. So cloning isn't an option either.

#### Live Demo
http://jsbin.com/tamugubenu/edit?html,console,output

#### Steps to Reproduce
1. Click the button in the Demo

#### Expected Results
item 0: a
item 1: b
item 2: c
item 3: d

#### Actual Results
item 0: a
item 1: b
item 2: c
item 3:

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.7.0
- webcomponents: v0.7.22

**Comment by kevinpschaaf** [comment]
Thanks for the issue.  Looks like the guidance given in [override dirty checking](https://www.polymer-project.org/1.0/docs/devguide/model-data#override-dirty-check) needs clarification, since it will only help to avoid dirty checking _for arrays_ in certain conditions, and is clearly not helping you here.

First, since `dom-repeat` renders asynchronously, simply toggling the array to empty and then setting it back won't defeat `item` dirty checking in the template instances; by the time it renders it will have the same array again and will simply update instances with the same items, which doesn't defeat the dirty checking.

Secondly, and more importantly, mutating an array bound to the `dom-repeat` _requires_ using the array mutation API's or else notifying the changes using [`notifySplices`](https://www.polymer-project.org/1.0/docs/api/Polymer.Base#method-notifySplices) in order to keep the backing Collection that `dom-repeat` uses in sync with the array; not doing so leads to corruption in the Collection's view of the world.  Based on your description that the mutations are happening outside of Polymer context, you can't do this either.

So, your best option is to treat the array as immutable, and provide `dom-repeat` with a new array identity each time mutations happen to the array, which ensures the collection is synced.

FWIW, the need to opt-in to Polymer's array mutation API is a major pain point that users hit in 1.x, and is a top priority that we've addressed in minimally-breaking changes we've made in 2.0 (which are unfortunately are still breaking, and can't be applied to the `1.x` code base).  In 2.0 we've removed requirement for notifying changes to arrays, and code like this will "just work":

```js
  // representing external changes.
  this.test.members.push('d');
  this.test.members[1] = 'x';
  // just give Polymer a hint that the array changed:
  this.notifyPath('test.members');
```

Opened docs issue https://github.com/Polymer/docs/issues/1782 to address guidance in 1.x docs.

**Comment by jfrazzano** [comment]
Hey Kevin, 
Can you point me to underlying polymer code for the just works solution? 

I been a polymer die-hard for about 18 months, but went off path on September 13 when attempted upgrade made the system we have been building untenable

We started using string templates. Then started layering shards of templates and found it relatively easy to keep view and data in synch, provided we sectioned off the portions of view that had to be re-fed through the tagged template parser. 
(When we screwed up we wiped the page). 

I am curious if the code here is tag templating or using some other parsing approach. 
Thanks 
Sincerely, 
Jason

**Comment by ColdFireIce** [comment]
Hi @kevinpschaaf 

thanks for your in depth explanation.

> So, your best option is to treat the array as immutable, and provide dom-repeat with a new array identity each time mutations happen to the array, which ensures the collection is synced.

What would be the best way to this?

Is there a way to just reset a template and let it draw everything new? Performance isn't a problem in my case. Rebuilding the whole think would be just fine.

Thanks and greetings
Daniel

**Comment by kevinpschaaf** [comment]
@ColdFireIce The easiest way is as shown in the jsBin: just assign a `slice`'ed (copied) version of the array each time it mutates.

**Comment by JGSolutions** [comment]
@kevinpschaaf What about updating a specific property for example. I can't get my template repeat to render again. Does this work?

`
this.set(['grocerylist', i, 'selected'], snap.val().selected);
this.set('grocerylist', this.grocerylist.slice());
`

**Comment by kevinpschaaf** [comment]
@JGSolutions Could you open another issue with a jsBin showing the repro?  The first call to `set` should be sufficient, in the abstract.

**Comment by JGSolutions** [comment]
@kevinpschaaf Thanks for the reply. I been refactoring my code a lot so not sure if this will be needed.

Overall I was implementing using firebase detecting modifications to my data modal using child_changed. As demonstrated above that was the techniques I used. Now I am targeting to allow the firebase-query component to handle the changes.

**Comment by karthik-hande** [comment]
I tried immediate dirty checking that's clearing and reassigning array, but this will just update nodes whose values are changed, but if my entire dom-repeat nodes should clear and it should render like how it renders for the first time, what I should do? like a blank screen for the fraction of seconds and it should render all the nodes
