### ISSUE TITLE
In shady dom + observeNodes, the disconnect throws

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer#4049]
If I use `observeNodes` to observe a local child, the disconnect bit throws:

<img width="661" alt="screen shot 2016-10-06 at 12 55 19" src="https://cloud.githubusercontent.com/assets/1369170/19168254/29a2d8be-8bc4-11e6-9be4-3cf68bd6ba80.png">

**Comment by mkazlauskas** [comment]
Here are some hopefully helpful insights on `iron-input`:
- It throws because `observeNodes` triggers `detached`, I believe it shouldn't
- It doesn't throw if you move `observeNodes` from `attached` to `ready` callback
- It doesn't throw if you don't use a container like `paper-input-container`, or if that container doesn't have a `<template>`

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/polymer/pull/4112.
