### ISSUE TITLE
[2.x] Custom Element appended synchronously after definition is imported is not upgraded

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#4073]
### Description
If .html file that contains Polymer custom element definition is loaded dynamically, then at `onload` event I add custom element to the document it does not get upgraded.

#### Live Demo
https://plnkr.co/edit/Lrdpl58BCfV7ZcZHDHQp?p=preview

complicated scenario closer to original use-case:
https://plnkr.co/edit/DgA9CUIg8TCbrH4pnE6k?p=preview

#### Steps to Reproduce
1. create my-element.html with Polymer element,
2. create index.html that imports my-element.html document,
3. once my-element.html is loaded (`onload` event) append `<my-element>` to the main document.

#### Expected Results
`<my-element>` should be stamped and upgraded

#### Actual Results
`<my-element>` is stamped but not upgraded

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- ? Safari 9
- ? Safari 8
- [x] IE 11

### Versions
- Polymer: v2.0-preview @70133aa69753fc375cfb108337e944333b160883
- webcomponents: # v1 webcomponents/webcomponentsjs@9892fbccde417a7b0cbf9c181e35b56e28d7e808

### Debugging info

If the element is vanila one - it works.

**Comment by kevinpschaaf** [comment]
I confirmed the issue you're seeing only occurs on pre-M54 Chrome (before native customElements V1 shipped) or on FF/Safari.  Running on Chrome 54 or Canary, the element upgrades and is styled properly.  The looks to be due to use of incorrect polyfills.

The current state of the `2.0-preview` branch is that you _must_ load `webcomponents/webcomponents-lite.js` from the `v1` branch (as described [here](https://github.com/Polymer/polymer/blob/2.0-preview/README.md#polyfills)), which currently still uses a development-time loader to load the V1-compliant shady DOM and custom elements polyfills.  Your plunkr's are loading the non-lite version, which includes the legacy V0 polyfills.  We still have a bit of work to do to get the polyfill situation cleaned up and into a better state, until then it requires staying on the documented rails, since that is the only configuration we are testing currently.

Running your demo locally using the correct polyfills above, I confirmed the element upgrades and is styled correctly on Safari, Chrome, and FF.
