### ISSUE TITLE
Another default value bug

### ISSUE THREAD

**Issue by pik** [Polymer/polymer#4075]
#### Live Demo
https://github.com/pik/polymer-default-value-issues/blob/master/polymer-default-value-issues.html

`git clone` and `polymer serve` go to the demo page.  

In the child element which features the bug the baseConfiguration is defined as: 
```
        baseConfiguration: {
          type: String,
          value: null
        },
```

But when `_setupConfigurationFromDefaults(defaults)` observer is called, the value of `baseConfiguration` is `undefined`. Curiously modifying `defaults` from 
```
        defaults: {
          type: Object,
          value: null
        },
```
to
```
        defaults: {
          type: Object,
        },
```

Makes the bug disappear. No idea why really, since `defaults` in each case is actually passed correctly to the observer. 

### Versions
- Polymer: 1.6.1

**Comment by kevinpschaaf** [comment]
Please take a look at this section of the docs: https://www.polymer-project.org/1.0/docs/devguide/observers#dependencies

In Polymer 1.x property defaults are "set" to the element one-by-one; as such, a common mistake is to write code that relies on the order that the initial configuration of properties is applied.  The key way to avoid this is to _always_ declare the dependencies for _all_ of the properties that an observer reads, which will guarantee that the observer doesn't run until all of its dependent properties have their initial values.

In your `_setupConfigurationFromDefaults` method, you are reading from `this.baseConfiguration` even though it was not declared as a dependency.  Thus, your code will produce a different result depending on whether `defaults` is set before or after `baseConfiguration`'s default value of `null`.  And case in point, whether the property was bound or not does in fact change the order that the initial properties are set.

To fix your code, simply declare `baseConfiguration` as a dependency to `_setupConfigurationFromDefaults` (this is the best fix and a pattern you should incorporate everywhere): http://jsbin.com/xebece/1/edit?html,output (<-- couldn't verify on jsBin due to the current github outage, but did test locally)
