### ISSUE TITLE
Binded slot name do not distribute content as expected in Polymer#1.7.0

### ISSUE THREAD

**Issue by hypnoce** [Polymer/polymer#4084]
### Description

Binded slot name do not correctly distribute slotted elements on non-chromium browser
#### Live Demo

http://jsbin.com/denumizugi/edit?html,console,output
#### Steps to Reproduce

Create a slot using binding for the name : `<slot name="[[slotName]]"></slot>`
#### Expected Results

Nothing should be displayed
#### Actual Results

'Should not be assigned' is displayed on non-chromium browser
### Browsers Affected

- [ ] Chrome
- [x] Firefox (flashes)
- [x] Edge
- [x] Safari 10
- [x] Safari TP Release 15 (Safari 10.1, WebKit 12603.1.8)
- ? Safari 9
- ? Safari 8
- [x] IE 11
### Versions

- Polymer: v1.7.0
- webcomponents: v0.7.22

I wanted to do `<slot name$="[[slotName]]"></slot>` but is failed converting to `<content select$="[slot=[[slotName]]]"></slot>`. So the converted binding looks like `<content select="[slot=[[slotName]]]"></slot>`. Therefore, when the binding occurs, it sets 'select' as a property instead of an attribute on non-chrome browser (that do not natively support v0 web components). During distribution, the `_matchesContentSelect` function 

``` javascript
var select = contentElement.getAttribute('select');
if (!select) {
  return true;
}
select = select.trim();
if (!select) {
  return true;
}
```

returns always true.

**Comment by kevinpschaaf** [comment]
The issue you pointed out can probably be most easily resolved by checking for the property in addition to the attribute, since supporting the slot->content transformation with the attribute binding is more problematic: although the parser will parse an attribute with `$` in the name, some browsers throw when trying to set it, so we can't just move the attribute binding and allow the normal annotation parsing to extract the binding from it.

However, note that even if that was fixed, in 1.x Shady DOM does not automatically watch for dynamic changes to the `select` attribute on `<content>`, so you would need to manually force distribution after setting `slotName` by calling `distributeContent`, as in this example: http://jsbin.com/tomoro/edit?html,output
