### ISSUE TITLE
`connectedCallback` not called after creating a tree with `Polymer.dom(..)` methods when using Shady DOM.

### ISSUE THREAD

**Issue by bicknellr** [Polymer/polymer#4087]
### Description

`connectedCallback` is not called when an element has children appended using `Polymer.dom(..).appendChild` before it is inserted in the document. This only occurs when using Shady DOM.
#### Live Demo

http://jsbin.com/kuvazil/1/edit?html,output
#### Steps to Reproduce
1. Open the demo.
2. Click the second button. ("... with `Polymer.dom().appendChild`.")
3. Both "test-element created" and "test-element attached" should have been logged but only "test-element created" is logged.
#### Expected Results

`connectedCallback` is called when the element is connected.
#### Actual Results

`connectedCallback` is not called when the element is connected.
### Browsers Affected

Any requiring Shady DOM.
### Versions
- webcomponentsjs: v1 (9892fbccde)
- custom-elements: master (a0f55ecbb1)
- shadydom: master (e4a8be7b4d)
- shadycss: master (053afe9c59)
- Polymer: 2.0-preview (f68560678d)

**Comment by kevinpschaaf** [comment]
Only occurs when custom elements polyfill is also in use.  On chrome, `?wc-shadydom=true` works, `?wc-shadydom=true&wc-register=true` (forced CE polyfill) fails.

**Comment by kevinpschaaf** [comment]
This basically falls under https://github.com/webcomponents/shadydom/issues/7; the behavior seen is due to the fact that `Polymer.dom(testElement)` (in the 2nd example) causes `test-element` to be patched, which requires all subsequent DOM manipulation of that element to occur via patched API.  Since `document.body` is not patched, the call to `document.body.appendChild` results in `test-element` being appended through the native method, and its composed tree tracking information does not reflect its new location; this causes the [`isConnected` check in the `custom-elements` polyfill](https://github.com/webcomponents/custom-elements/blob/master/src/custom-elements.js#L476) to fail as the patched `element.parentNode` returns null since it is out of sync.

As a short-term workaround, if `document.body` is manually patched via `ShadyDOM.patch(document.body)`, the 2nd example works: http://jsbin.com/wopozi/1/edit?html,output

**Comment by bicknellr** [comment]
Oh, this bug is probably also a dup of webcomponents/custom-elements#17.

**Comment by bicknellr** [comment]
This might be fixed; anyone able to confirm?

**Comment by JanMiksovsky** [comment]
I can still reproduce webcomponents/custom-elements#17 using what's on the master branches of the CE and ShadyDOM polyfills. To the extent that this bug is a dup of that, this bug is still active.

**Comment by sorvell** [comment]
The demo now works and the ShadyDOM issue has been addressed. Please re-open if the problem persists.
