### ISSUE TITLE
Polymer 2 inconsistency with Vanilla Web Components

### ISSUE THREAD

**Issue by thibaultsavary** [Polymer/polymer#4100]
There's an inconsistency with the `super()` call in the class declaration.

Polymer 2.0 Preview

```
class MyElement extends Polymer.Element {

  static get is() {
    return 'my-element'
  }

  static get config() {
    return {}
  }

  constructor() {
    super()

  }

  connectedCallback() {
    super.connectedCallback()
    console.log('my-element is connected')
  }

  disconnectedCallback() {
    super.disconnectedCallback()

  }

}

customElements.define(MyElement.is, MyElement)
```

Web component implementation in Chrome

```
class MyElement extends HTMLElement {

  static get observedAttributes() {
    return []
  }

  constructor() {
    super()
    const doc = document.currentScript.ownerDocument
    const template = doc.querySelector('#my-element')
    this._root = this.attachShadow({ mode: 'open' })
    this._root.appendChild(template.content.cloneNode(true))
  }

  connectedCallback() {
    console.log('my-element is connected')
  }

  disconnectedCallback() {

  }

}

customElements.define('my-element', MyElement)
```

As you can see, Polymer needs the `super.lifecycleHook()` call inside the hook itself (i.e. `connectedCallback()`)

Why is that ?
Can't this be unified for interoperability ?

**Comment by arthurevans** [comment]
@thibaultsavary If you're extending any custom element class that uses the lifecycle callbacks, you need to call `super`. It's not required for `HTMLElement` because `HTMLElement` doesn't implement these callbacks. But it's not Polymer-specific, either: this would be a best practice for extending _any_ custom element that uses these callbacks.

To answer the "why is that" question: Polymer uses the callbacks to do all of its work: init templates, properties, data bindings, configure elements from attributes, etc.

**Comment by thibaultsavary** [comment]
Okay, thanks for the informations @arthurevans .
