### ISSUE TITLE
Support dynamic property binding names

### ISSUE THREAD

**Issue by manderson23** [Polymer/polymer#4117]
I am creating some <app-route> elements in a <dom-repeat> as follows:

    <template is="dom-repeat" items="{{myItems}}">
      <app-route route="[[_route]]"
                 pattern="/view-{{index}}/:data"
                 data="{{_routeData}}"
                 active="{{_routeActive}}">
      </app-route>
    </template>

I'd like to use `{{index}}` within the data and active attribute values to create a dynamic binding property name such as `{{_route{{index}}Data}}` i.e evaluating `{{index}}` when creating the binding name. This would mean that they are unique for each route.

**Comment by sorvell** [comment]
This kind of binding will be difficult and complex to support as shown in the example. However, the same behavior can generally be achieved by using a computed annotation binding. For example, `{{_computeRouteData(index)}}`. You'd then implement `_computeRoutData` to return what's needed for the given `index`. This approach is generally pretty flexible since you can specify multiple dependencies and write code to massage the output as needed. Would something like this fit your use case?

**Comment by TimvdLippe** [comment]
Closing this per above comment. Computed bindings are the performant way to get these dynamic computations.
