### ISSUE TITLE
Dynamically added items do not trigger observers properly

### ISSUE THREAD

**Issue by nicholaswmin** [Polymer/polymer#4140]
### Description

I'm adding some items to an Array, using the Array mutation methods. The items are displayed within a `<dom-repeat>` and can can be edited on the fly. 

While the edits do change the data in the object, **any attached observers do not fire to indicate that a change occurred**

#### Live Demo

https://jsfiddle.net/g1259q4j/1/

#### Steps to Reproduce
1. Add some `Object`s to an `Array` (which is a prop on an element). The added element must have a property that can be binded to a `<paper-input>`, i.e a `Number`.
2. Render those added items using a `<dom-repeat>`
3. Bind each item's property to a `<paper-input>` so it can be edited on-the-fly
4. Register a wildcard observer for the whole `Array`
5. Edit an item via the `<dom-repeat>`-ted `<paper-input>`

#### Expected Results

The observer fires and logs that a change occured

#### Actual Results

The observer fires when adding/removing items from the `Array` but not when an item's properties are edited.

The observers fire when adding/removing items - They **do not** work only for sub-property changes

Using a direct `this.set("data.contents.0.name", "3")` with a path, does trigger the observer just fine

### Browsers Affected

- [x] Chrome

*Not sure about the rest of the browsers*

### Versions

- Polymer: 1.7.0
- webcomponents: 0.7.23

**Comment by arthurevans** [comment]
The observer isn't firing because you have one-way binding annotations on the `items` property, which prevents change notifications from flowing up to the element. Change it to: `items="{{data.contents}}"` and you'll see the changes.

https://www.polymer-project.org/1.0/docs/devguide/templates#dom-repeat
"If the items array is bound using two-way binding delimiters, changes to individual items can also flow upward."

**Comment by nicholaswmin** [comment]
Ok, then why do *changes* to the data (but not observer firings) propagate upwards with the one-way binding annotations?

[Updated fiddle][1]

[1]: https://jsfiddle.net/g1259q4j/3/

**Comment by arthurevans** [comment]
That's because both the host element and the `dom-repeat` are accessing the same array. When you bind an object or an array, you create shared data between the host and target.

A little more detail here:

https://www.polymer-project.org/1.0/docs/devguide/data-system#data-flow-objects-arrays

(If you **really** don't want the `dom-repeat`'s children to be able to mutate the original array, you'd need to clone the whole thing. For example, using a computed property. However, I don't think that's what you're looking for.)

**Comment by nicholaswmin** [comment]
Nope, all covered - thanks!
