### ISSUE TITLE
tap event not dispatched unless listener specified in polymer definition

### ISSUE THREAD

**Issue by TomK** [Polymer/polymer#4143]
I am not able to listen to `tap` using native javascript `addEventListener` UNLESS the polymer element definition includes a tap listener: e.g. `listeners:{tap:'_fn'}`

#### Live Demo
http://codepen.io/oridan/pen/YpwREv?editors=1000

#### Expected Results
action A should alert 'tapped X-ACTION-A'
action B should alert 'built-in listener' and then alert 'tapped X-ACTION-B'

#### Actual Results
:no_entry: action A does not alert anything
:white_check_mark: action B alerts 'built-in listener' and then alerts 'tapped X-ACTION-B'

### Versions
- Polymer: v1.7.0   - webcomponents: v0.7.2 
- Polymer: 2.0-preview   -  webcomponents: v1

**Comment by azakus** [comment]
The gesture system does not patch `addEventListener` because that gets super confusing.
Instead, gestures should be added with `Polymer.Gestures.addListener(node, eventType, handlerFn)` and `removeListener` for the counterpart. These functions will do the N-way listeners for mouse and touch input that generate the gesture events.

(these functions are in the process of being renamed to their 1.x names for backward compatibility).

**Comment by azakus** [comment]
Closed now that #3936 is fixed
