### ISSUE TITLE
[2.0-preview] Re-entrant modification of sub-property does not notify

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#4161]
### Description

I was observing changes to the length of an array and modifying a sub-property of the newly added items when the length changes.

I noticed that notifications for the changed sub-property do not fire if the change occurs within the call stack of the length change notification.

#### Live Demo

http://jsbin.com/tokovot/edit?html,console,output

#### Steps to Reproduce
1. Open the live demo URL
2. Note the output in the console

#### Expected Results
The following is expected in the console:

```
"x-foo noticed a change to fooArray at path fooArray"
"Array is empty, ignoring.."
"x-foo connected. pushing to array!"
"x-foo noticed a change to fooArray at path fooArray.splices"
"x-bar is setting a property on the array element at index 0"
"x-foo noticed a change to fooArray at path fooArray.0.modified" <-- important one
"x-foo noticed a change to fooArray at path fooArray.length"
```

#### Actual Results
The following is what is seen in the console:

```
"x-foo noticed a change to fooArray at path fooArray"
"Array is empty, ignoring.."
"x-foo connected. pushing to array!"
"x-foo noticed a change to fooArray at path fooArray.splices"
"x-bar is setting a property on the array element at index 0"
"x-foo noticed a change to fooArray at path fooArray.length"
```

NOTE: The live demo includes buttons to help test certain types of manipulations discretely.

### Versions
- Polymer: 2.0-preview

**Comment by kevinpschaaf** [comment]
This is due to batching; the wildcard observer `fooArrayChanged(foo.*)` is being called (once) due to changes to both `fooArray.0.modified` and `fooArray.length` in the same turn:

![image](https://cloud.githubusercontent.com/assets/1354932/21163055/a18e5c98-c145-11e6-99b3-9d3f82655d0a.png)

However, the API for wildcard observers only provides the first property that triggered the observer in the `path` field of the info argument.  In order to see both, we'd need to modify the API to provide all paths matching the wildcard, or else call the method multiple times for each trigger.

Interestingly, in the https://github.com/Polymer/polymer/tree/2.0-data-updates branch this particular problem goes away, since notification has been moved to the end (for better 1.0 compatibility), and so `x-foo` runs its observer for `fooArray.length` first, then notifies to `x-bar`, which then `set`s the modified property which comes back down and runs the wildcard observer a second time (changes back down on the element from upward notification no longer batch into single observer calls).  However, I won't call this "good" yet, since it should be possible to contrive an example that exhibits the same problem -- multiple batched paths resulting in a single call to wildcard observer and loss of path change information.

**Comment by kevinpschaaf** [comment]
Closing, as the original issue no longer repros (http://jsbin.com/mitayosumi/edit?html,console,output) and we take care never to batch path notifications as it would both a.) require breaking changes to the wildcard observer info object, and b.) can lead to undefined situations if batched path changes refer to the same nested object structure.
