### ISSUE TITLE
[2.0-preview] Property notifications for path in dom-repeat item apply to path for all stamped items.

### ISSUE THREAD

**Issue by cdata** [Polymer/polymer#4162]
### Description
In a dom-repeat, I stamp an element that produces a unique value based on an input from each item, and bind that value to a property name that is the same for each item.

It appears as though the produced value for each newly stamped item overwrites the value produced by the previously stamped item.

#### Live Demo
http://jsbin.com/kamasir/edit?html,console,output

#### Steps to Reproduce
1. Open the live demo
2. Note the console output, indicating that the inputs are unique
3. Note the rendered list, indicating that the derived outputs have been over-written

#### Expected Results
The items in the list should be:

```
 - Derived from input w/ value 1
 - Derived from input w/ value 2
 - Derived from input w/ value 3
```

#### Actual Results
The items in the list are actually:

```
 - Derived from input w/ value 3
 - Derived from input w/ value 3
 - Derived from input w/ value 3
```

### Versions
- Polymer: 2.0-preview

**Comment by kevinpschaaf** [comment]
There are no anonymous properties per `dom-repeat` instance other than `item` (from the array), `index` (and in 2.0, `itemsIndexAs`), so any other properties referenced are propagated to/from the outer scope.  This behavior was the same in 1.x: http://jsbin.com/qibedi/edit?html,console,output (all derived values are `1` rather than `3` just because of a difference in `dom-repeat`'s iteration order in 2.0.
