### ISSUE TITLE
map to on object key

### ISSUE THREAD

**Issue by misoucouma** [Polymer/polymer#4169]
Hello,
Is there any way I can do binding to an object's property that I get dynamically ?
{ { myObject [myKey] } } --> prints the literal  '{ { myObject [myKey] } }'
I tried escaping brackets but still doesn't work

**Comment by web-padawan** [comment]
You should use computed function for that, and pass both properties as parameters.

**Comment by MartinsThiago** [comment]
Right, eg...

```html
<paper-input value="{{_getPropDynamically(myObj, myKey)}}"></paper-input>
```

```js
...
_getPropDynamically(obj, key) {
    return obj[prop]
}
...
```

**Comment by misoucouma** [comment]
Hi, I already tried that, but how to get the binding to work in two ways ?
 I want the the object property to be changed when the user enters a value in the input

**Comment by web-padawan** [comment]
This is not possible and generally can be avoided.
I'd suggest keeping your structured data as much simple as posiible.

**Comment by TimvdLippe** [comment]
This is not supported in the data binding system, mostly because of performance reasons. @web-padawan suggestion is what I would like to reiterate: keep your structured data as simple as possible. This issue probably points to a deeper problem with which element has to deal with what data. If you would still like to listen to updates, you can manually add event listeners in the observer callback of both `myObject` and `myKey` (and clean the old event listeners as well).
