### ISSUE TITLE
Polymer dom-repeat not rendering changes with computed bindings as items

### ISSUE THREAD

**Issue by chromy** [Polymer/polymer#4188]
### Description

I'm using a function to compute the items for a `dom-repeat`:
```html
<template is="dom-repeat" items="[[first4People(people, people.*)]]">
  <div>
    First: <span>[[item.first]]</span>
    Last: <span>[[item.last]]</span>
  </div>
</template>
```
However the element never seems to render updates a sub-property of people (e.g. `people.0.first`)
is changed. Changes to the array itself work (e.g. `this.push('people', ...)`) and can incidentally cause the element to re-render. Perhaps I'm being hit by the [dirty check](https://www.polymer-project.org/1.0/docs/devguide/model-data#override-dirty-check) in which case it is not clear how to override it in this case.

#### Live Demo

- Codepen: http://codepen.io/diddledan/pen/GNOajp (thanks @diddledan!)
- Plunkr: http://plnkr.co/edit/Yv27I053bk4e3cFbFuhK?p=preview
- Stack-overflow: http://stackoverflow.com/questions/40901205/polymer-dom-repeat-not-rendering-changes-with-function-as-items

#### Steps to Reproduce
- In an element add a `dom-repeat` and set `items` to `myFunc(myList)` where `myList = [{'foo': 'bar'}, ...etc]`.
- Later attempt to `this.set('myList.0.foo', 'baz')`.

#### Expected Results

The new data should be reflected in the page.

#### Actual Results
The new data is not reflected in the page.

### Browsers Affected

- [x] Chrome
- [ ] :question: Firefox 
- [ ] :question: Edge
- [ ] :question: Safari 9
- [ ] :question: Safari 8
- [ ] :question: IE 11

### Versions

- Polymer: v1.7.0
- webcomponents: v0.7.23

**Comment by diddledan** [comment]
maybe related to #1713

**Comment by arthurevans** [comment]
@diddledan I don't think this is related. I followed up on SO, but he problem here is related to using a computed binding to provide the `items` for the `dom-repeat`. Because the data system doesn't know how the items in `people` relate to the items in `first4People(people, people.*)`, path change notifications don't propagate correctly.

**Comment by synthesize** [comment]
I'm also having this problem. Would using https://www.polymer-project.org/1.0/docs/api/Polymer.Base#method-linkPaths be a workaround for this issue?

**Comment by napa3um** [comment]
maybe related to #4692

**Comment by tag42git** [comment]
@arthurevans  you say "Because the data system doesn't know how the items in people relate to the items in first4People(people, people.*), path change notifications don't propagate correctly.". 

 I'm using polymer 2 and am having trouble understanding it (but getting it to work so far by trying *everything*, including sometimes even reading the docs). ..

I thought I could create a string property say "a" and then a computed binding "b" and use it like so <template is="dom-repeat" items="{{b(a)}}" as="item">  .... b(a) {return whatever items computed with or without a} and then just like that any change to a will cause the items to magically be recomputed.  I guess I don't really understand how it works.  What exactly do I have to add?  Why does b have to know anything about a? Any help appreciated.  Thanks.
