### ISSUE TITLE
Random property not created if binded to a "static" string

### ISSUE THREAD

**Issue by NicolasRannou** [Polymer/polymer#4189]
I want to pass data to a `on-tap` callback function:

```
<paper-button raised arg1="static" on-tap="doSomething">Push static not OK</paper-button>
<paper-button raised arg1="[[items]]" on-tap="doSomething">Push static OK</paper-button>
...
doSomething: function(e){

      var arg1 = e.currentTarget.arg1;
      console.log( arg1 );

}
```

That works well if `arg1="[[items]]"` but I can not access the `arg1` property if I set `arg1="static"`.
Live demo: http://jsbin.com/jojolu/5/edit?html,console,output

Is it the expected behavior? How can I pass a "static" string to my callback?

Cheers

**Comment by tony19** [comment]
The "static" string you have is setting an attribute on `<paper-button>` because `<paper-button>` does not have a declared property named `arg1`. You could get the value with:

    e.currentTarget.getAttribute('arg1');

Or you could use data attributes:

```html
<paper-button data-arg1="static" on-tap="doSomething">A</paper-button>
<paper-button raised data-arg1$="[[items]]" on-tap="doSomething">B</paper-button>
```
```javascript
doSomething: function(e) {
  var arg1 = e.currentTarget.dataset.arg1;
  ...
}
```

**Comment by NicolasRannou** [comment]
Thanks - any reason why it works if instead of a "static" string we provide a binding to a polymer element? Some polymer magics under the hood probably...

This solution you mentioned it probably good enough for me though:
```
<paper-button data-arg1="static" on-tap="doSomething">A</paper-button>
<paper-button raised data-arg1$="[[items]]" on-tap="doSomething">B</paper-button>
doSomething: function(e) {
  var arg1 = e.currentTarget.dataset.arg1;
  ...
}
```

**Comment by arthurevans** [comment]
Yes, binding to properties is much more useful in general, and it's the default case for Polymer. Attributes are the only mechanism we really have for adding declarative data mappings.  That can lead to some confusion because `foo="bar"` is treated differently from `foo="[[bar]]"`. 

`attribute="value"` is standard HTML to assign an attribute value. This is a static, one-time configuration.

`property-name="[[item]]"` also creates an attribute, and assigns an attribute value of "[[item]]", but when Polymer encounters a value like this in one of its templates, it removes the attribute value and creates a data binding (between `propertyName` and the host's `item` property.). 

Hope that helps.

**Comment by NicolasRannou** [comment]
Thanks for the explantion guys

**Comment by jfrazzano** [comment]
Does Polymer do it literally, like in Eloquent JS when he just parses the DOM for ${{\w}}, use notify flag to then bind back? (making [], and {{}} a little redundant in some instances, or is it all done with decorator patterns on setters and getters... I guess of just text thrown on the dom, it has to be parsing and actually grabbing it.  Is it then a mix with observe falling in last? Just curious and you always have the most thorough answers
