### ISSUE TITLE
dom-repeat stamps incorrect data when user slices the array used for rendering

### ISSUE THREAD

**Issue by ergo** [Polymer/polymer#4225]
It seems that dom-repeat template is handling array slices incorrectly in certain cases.

#### Live Demo
Example 1: 
http://jsbin.com/wevevuqunu/edit?html,console,output

Example 2:
http://jsbin.com/lumunemipa/edit?html,output

#### Steps to Reproduce
1. Click reorder button

#### Expected Results
Numbers in bold should change in both examples

#### Actual Results
Numbers in bold stay unchanged in example 1, example 2 with `this.async()` works as expected.

**Comment by ruphin** [comment]
This doesn't look like an error to me, it's just an optimization. I can explain why it works like this.

In your first example, you only reorder the original objects in your array. Polymer sees `[1,2,3] -> [2,1,3]` so it only reorders the position of the rendered elements, and doesn't construct new ones.

In your second example, you add `this.async()` _after_ removing two elements from the array, and in the asyc function, you add them again. This causes Polymer to see `[1,2,3] -> [3] -> [2,1,3]` so after first step it destroys the two elements, and after the second step, it constructs new ones.
Multiple array operations are batched (with a debounce-like guard), and the `async()` causes it to see the intermediate state because there is a pause in execution between the two steps.

`async()` doesn't do anything special here, if you change the `async()` to wrap all the mutations you will see that it doesn't change anything:

```
this.async(function(){
        var left = this.splice('rows', 0, 1)[0];
        var right = this.splice('rows', 0, 1)[0];
        this.splice('rows', 0, 0, right);
        this.splice('rows', 1, 0, left);
        console.log(this.rows);
})
```

If all array mutations happen without preemption, polymer will only see the array change from the original state to the new state, detect that it's only a reordering, and will only re-order the original stamped elements instead of constructing new ones.

This feature is actually great; without it every array manipulation would immediately trigger DOM manipulation and everything would be prohibitively expensive. Now operations like changing the order of your array are really cheap because it effectively only causes elements to be re-positioned in the DOM instead of having to be rebuilt completely.

If you want to explicitly rebuild elements, you have to separate removing your items and inserting them into different steps, like you did with `async()`. Something like `setTimeout` will also work. This will make Polymer first destroy the old elements before creating new ones to insert.

Hope that helps :)

**Comment by ergo** [comment]
I don't think you are right, because if it would be reordering them, the values should also switch positions.

Notice that element in bold is inside `test-elem` shadow dom, so if reordering would work - the numbers would ALSO switch position - thats my real concern here.

**Comment by diddledan** [comment]
maybe related to #4188

**Comment by ruphin** [comment]
You are right, it looks like the DOM nodes are not redistributed, and only the properties are changed. My points above still stand, but it does look like an unexpected behavior.

#1713 Has good discussion on this subject

**Comment by ergo** [comment]
I've tried another stab at the problem using sort:

http://jsbin.com/rimogiwola/edit?html,js,output

Maybe I implemented this incorrectly - but it doesn't seem to improve anything.
