### ISSUE TITLE
Object observers don't receive correct parameters

### ISSUE THREAD

**Issue by jrobinson01** [Polymer/polymer#4244]
### Description

Wrong parameters passed to observer function when the property is an object, and a property of that object is set.
#### Live Demo

http://codepen.io/anon/pen/xgbKmv?editors=1011

#### Steps to Reproduce

1. run the codepen.
2. look at the console.

#### Expected Results

The observer function's `newValue` and `oldValue` parameters should reflect the states of the `user` object.
#### Actual Results

The observer function's `newValue` parameter reflects only the value of the property that was set. `oldValue` is undefined.

### Browsers Affected

- [x] Chrome
~~- [ ] Firefox~~
~~- [ ] Edge~~
~~- [ ] Safari 9~~
~~- [ ] Safari 8~~
~~- [ ] IE 11~~
(I was unable to get the codepen to run in browsers other than chrome)

### Versions

- Polymer: v2.0#preview
- webcomponents: vX.X.X

**Comment by sorvell** [comment]
For awhile in Polymer 2.x we were experimenting with calling simple property observers when sub-properties for the observed object changed. This is likely what resulted in the issue here. We decided to revert the behavior to the way it works in 1.x:
1. simple property observers are called only when the property itself changes
1. wildcard observers (`user.*`) are called when a sub-property changes. 

Also as in Polymer 1.x simple property observers get the new and old value as arguments, but wildcard observers instead provide the changed path and the value but not the old value.

Here's an updated example showing this: http://codepen.io/anon/pen/Qpwpma?editors=1011.

Sorry for the churn here and hope this clears it up.
