### ISSUE TITLE
Dynamically changing element content should change element, not just child text node

### ISSUE THREAD

**Issue by lesliana** [Polymer/polymer#4250]
### Description
Dynamically changing element content should change element, not just child text node.

#### Live Demo
http://jsbin.com/siyalix/1
http://output.jsbin.com/qeqeqoleso

#### Steps to Reproduce
1. Go to http://jsbin.com/siyalix/1 on an iOS device.  Turn on VoiceOver.
2. Swipe through the elements on the screen.  Note that VoiceOver reads "Alpha" and "Alpha Polymer" correctly.
3. Tap on the 2 "change header" buttons.
4. Swipe through the elements on screen again.  Notice that although they visually say "Beta", they are still read out loud as "Alpha" by VoiceOver.

There is a similar repro on http://output.jsbin.com/qeqeqoleso - note that this repros for h1, h1 with an aria-label set, and span with role="heading".  It does not repro for a simple span.

#### Expected Results
VoiceOver should read the text on the screen.

#### Actual Results
VoiceOver reads the text that used to be on the screen.

### Browsers Affected
Tested iOS 9 and 10 on iPhone 6 and iPad2.  Does not seem to repro on Android.

**Comment by cdata** [comment]
@sorvell @azakus For some context, when Polymer updates the `textContent` of the `h1` in the example, it's actually updating the `textContent` of the `h1`'s child text node. If we update the `textContent` of the `h1` directly, the problem goes away.

**Comment by kevinpschaaf** [comment]
This appears to be a bug in VoiceOver.  For the following example...
```
<h1>[[headerTitle]]</h1>
```
... setting `h1.firstChild.textContent` does result in a change to `h1.textContent`, based on how the DOM API works.  So it is not "incorrect" to set textContent of the child text node; it appears that VoiceOver just does the wrong thing.

Consider the following case to understand why Polymer binds text to TextNodes rather than textContent of the parent element:
```
<h1>[[headerTitle1]]<span>Hi</span>[[headerTitle2]]</h1>
```
As you can see, since there can be child elements adjacent to child textNodes, Polymer binds to individual child nodes rather than parentElement.textContent since that is a more general approach.  

Technically Polymer could special-case the case that an element only has a single `TextNode` child and in that case bind to `parentElement.textContent`  _specifically_ to workaround the VoiceOver bug.  However, in the meantime a more straightforward workaround would be to explicitly bind to the `textContent` property of the element via a property binding (as opposed to text binding), as such:

```
<h1 text-content="[[headerTitle]]"></h1>
```

**Comment by lesliana** [comment]
Thank you for the explanation, that makes sense.  Binding to textContent explicitly works for my case, thanks!

**Comment by esprehn** [comment]
Can you file a bug on bugs.webkit.org too? This is a bug in how WebKit reports the changes to voiceover.

**Comment by eliotfallon213** [comment]
A WebKit bug has been logged here: https://bugs.webkit.org/show_bug.cgi?id=190437
