### ISSUE TITLE
Assigning a mixin will bleed out, only when using native CSS properties

### ISSUE THREAD

**Issue by mercmobily** [Polymer/polymer#4254]
We are experiencing an issue where setting a mixin within a selector seems to be misbehaving: the value seems to be "bleeding out" to other elements that do not match the CSS selector.

Even more baffling, this only seems to happen by using the custom CSS properties.

We recreated a simple tiny repository showing the issue: https://github.com/tegola/polymer-apply-bug-testcase (sorry, it was just way too painful getting this to happen on a CDN).

The short story: `<paper-input>` is configurable by changing the mixin `--paper-input-container-input`. So, in `my-app.html`, we do this:

      /* Add borders and padding, and reduce margin to underline */
        --paper-input-container-input: {
          box-sizing: border-box;
          border: 1px solid var(--paper-grey-400);
          border-bottom: 0;
          padding: 0.5rem;
        };

This should set the mixin in the scope of the `<my-app>` element.
`my-app.html` has a PSK-ish:

      <my-view1 name="view1"></my-view1>

Enter `my-view.html`. HTML-wise, it just has two elements:

    <paper-input label="Normal input"></paper-input>

    <paper-dropdown-menu label="Normal dropdown">
      <paper-listbox class="dropdown-content">
        <paper-item>Item 1</paper-item>
        <paper-item>Item 2</paper-item>
        <paper-item>Item 3</paper-item>
      </paper-listbox>
    </paper-dropdown-menu>

The first `<paper-input>` can be configured, like ANY `<paper-input>`, by setting the mixin `--paper-input-container-input`. However, `<paper-dropdown-menu>` ALSO contains internally a `<paper-input>` element. I want *that* `<paper-input>` element to look a little different. So, I write this in the CSS section of `my-view1.html`:

      /* Input borders in dropdown menus */
      paper-dropdown-menu {
        --paper-input-container-input: {
          box-sizing: border-box;
          padding: 0.5rem;
          border: 1px solid var(--paper-grey-400);
          border-bottom: 0;
          border-right: 0; /* This bleeds out */
          background-color: rgba(255, 0, 0, 0.25); /* This does not */
        };
      }

This should (I hope I am right) set the value for the mixin `--paper-input-container-input` as specified, but _only for elements matching the selector `paper-dropdown-menu`_.
So, the first `<paper-input>` should be untouched.

And yet: 

* Using the custom CSS elements polyfill, it works fine: the normal input has its border.
* Setting `useNativeCSSProperties` to true will show the straight paper input with the missing border on the right
* The issue seems to be there only for the borders. The red transparent background will only happen in `<paper-dropdown-menu>` (as you would expect)
* `<paper-dropdown-menu>` defines the mixin `--paper-input-container-input` like so in `paper-dropdown-menu-shared-styles.html`:

      --paper-input-container-input: {
          overflow: hidden;
          white-space: nowrap;
          text-overflow: ellipsis;
          max-width: 100%;
          box-sizing: border-box;
          cursor: pointer;
        };
I am not sure this is relevant. I thought I'd add it.

Is this a bug in the native implementation of native CSS properties? Or am I doing something silly?

Safari has the same issue when using native CSS properties.

**Comment by mercmobily** [comment]
@ebidel Is this issue opened in the right spot? And... am I doing something horribly wrong, or is this actually a bug?

**Comment by JMuratha** [comment]
We also have the same issue, seems like a Polymer Bug since it happens both in Chrome and Firefox.
Disabling `useNativeCSSProperties` fixed it for ustoo.

And the CSS properties only seems to bleed out if the element was appended once.

Short example: 
We have a webapp with multiple pages which we are selecting with the `<iron-lazy-pages restamp>` element.
If we directly navigate to a page with a normal `<paper-input>` it's styled as it should be.
If we are now switching to the page with the custom styled `<paper-input>` and then back to the page with the normal styled one it suddenly looks the custom styled `<paper-input>`.

If you want we could provide an example but we don't think it's necessary since @mercmobily already provided one already.

**Comment by mercmobily** [comment]
I am glad I am not the only one on Earth having this problem -- and I am glad somebody else found our reproduction work useful.
It took us a lot of hours to nail it down...

**Comment by WoodyWoodsta** [comment]
This one intrigued me, so I whipped up a jsfiddle: https://jsfiddle.net/WoodyWoodsta/r88sn2jj/

I can only assume this has something to do with CSS specificity of some sort.

**Comment by mercmobily** [comment]
I agree re: CSS specificity. I have to put my honest hat on, I am not 1000% sure what happens when you have:

* Element A with <style> in its shadow DOM defining custom CSS property --my-something
* Element B that *contains* Element A in its light DOM, and that ALSO defines --my-something using Element A as a selector

However, I doubt it's a Polymer bug. If this replicates across browsers, it might well be the side effect of an edge case of "how things are supposed to work".

Maybe.

**Comment by mercmobily** [comment]
@WoodyWoodsta About your fiddle... what do we see, and what are we *supposed* to see?

**Comment by WoodyWoodsta** [comment]
> - Element A with <style> in its shadow DOM defining custom CSS property --my-something
> - Element B that contains Element A in its light DOM, and that ALSO defines --my-something using Element A as a selector

I'm not entirely sure that the above is the condition. My fiddle has two elements (`paper-input` and `paper-dropdown-menu`) that are siblings in a non-shadow scope (to the best of my knowledge). Both elements make use of and apply the same mixin to the same element, effectively.

The custom style in the fiddle is redefining the mixin `--paper-input-container-input` and placing this definition on `body` (which should be applied to both the `paper-input` and the `paper-dropdown-menu`, but does not because `paper-dropdown-menu` itself redefines the mixin [here](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/paper-dropdown-menu-shared-styles.html#L27)). Additionally, I'm overriding `paper-dropdown-menu`'s internal redefinition of `--paper-input-container-input` (taking into consideration the style import order when using shared styles).

So, the issue is that some properties in each of mine (and your) mixin definitions are effecting the other. In my fiddle, the `border-xyz` properties are affecting both elements in an unexpected way. Hope that's clearer!

**Comment by mercmobily** [comment]
Yep. That's totally clear. It's just really strange that the very same bug
affects different implementations. It makes me thing that we are either
hitting a edge case that nobody thought about (!) or this is what *should*
be happening, and it's actually following the specs.

**Comment by mercmobily** [comment]
I think most (if not all) of the Polymer team is busy with getting Polymer 2.0 ready... I wouldn't hold my breath waiting for an answer.
I am sure we will get some attention soon-ish though! It would be great to know if this is actually a bug, and if this is the right place to report it...

**Comment by arthurevans** [comment]
Seems like something is probably wrong in the way we rewrite mixins as individual native CSS properties. @azakus, see the fiddle @WoodyWoodsta posted in this comment: https://github.com/Polymer/polymer/issues/4254#issuecomment-272441956 ... If you comment out the styles for the dropdown, the right border shows up on the normal paper-input ... which shouldn't be affected by this change.

BTW, @mercmobily note that you can work around this specific issue by explicitly declaring `border-right` in both rules. It seems to only happen where you have the shorthand form in one rule (border) overridden by the more specific form in another rule (border-right).

Nonetheless, it seems like a bug to me. Can't see why those rules would apply here.

**Comment by mercmobily** [comment]
@arthurevans Is this the right spot for this ticket? Or shall we close it from here and open it on a different repo?

**Comment by arthurevans** [comment]
@mercmobily I defer to @azakus on that. Maybe it belongs on the polyfill repo, but he should know one way or the other.

**Comment by mercmobily** [comment]
Is this likely to get fixed...?
