### ISSUE TITLE
base href: `<script src="...">....` does it respect base href?

### ISSUE THREAD

**Issue by mbana** [Polymer/polymer#4265]
Using polymer version 2.
Using `/`, to go to the root of the server doesn't seem to work.
It goes to root without respecting the base href just set.
What happens is `outputs#2` is selected instead of `http://localhost/basePath/someFile.js` as one would espect.

Is this a supported feature, if not I think it requires explicit mention.

Output of interest why do people continue to write all their JavaScript code inline? Although this isn't a valid reason, it just makes source code analysis and formatting more complicated.

---

`index.html`:

```html
<base href="/basePath/">
```

in a different directory that is a child of the index.html:

`someDir/someElement.html`:

```html
<some-element>
   <script src="someFile.js"></script>
   <script src="/someFile.js"></script>
</some-element>
```

**ouputs:**

1. `http://localhost/basePath/someDir/someFile.js`.
2. `http://localhost/someFile.js`.

**Comment by sorvell** [comment]
Sorry for the delay on this. Polymer should not be changing the default browser behavior here. 

Your setup here is not clear, would you mind clarifying or providing a reproduction of the problem. Thanks

**Comment by kevinpschaaf** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!

**Comment by flyingZippo** [comment]
<base href="/basePath/">
works for me
