### ISSUE TITLE
Property observer called with undefined after notifying push

### ISSUE THREAD

**Issue by mkazlauskas** [Polymer/polymer#4289]
### Description
Property observer called with undefined after notifying push. It's looking up the value of *prop.splices*, which doesn't exist.

#### Live Demo
Don't know how to use 2.0-preview with jsbin.

#### Steps to Reproduce
Example:

1.
```javascript
kiosks: {
   type: Array,
   observer: '_kiosksChanged',
},
```
2.
```html
<some-element something="{{kiosks}}">
```
3. In *some-element*, `this.push('something', 'item')`;

#### Expected Results
Property is notified with updated value, or not notified at all.

#### Actual Results
Property is notified with *undefined*:
![error](https://i.imgur.com/dVo5xhk.png)

### Browsers Affected

- [ X] Chrome

### Versions
- Polymer: 2.0-preview
- webcomponents: v1

**Comment by arthurevans** [comment]
I'm getting a slightly different (but still broken) result. The observer is called with an object with a single property, `indexSplices`, but `indexSplices` is `null`. 

JSBin is here:

https://jsbin.com/pudeled/2/edit

Click the button, watch the console—indexSplices is null. I tested this same  code in a local project with an outdated version of 2.0-preview, and it was giving an appropriate `indexSplices`. Updating to latest 2.0-preview yields the broken result.

Given that this is a standard, non-wildcard observer, I expected it to notify with the property value (kiosks) rather than a set of splices. So I'm not sure if that was WAI before. If so, we need to document this change.

**Comment by mkazlauskas** [comment]
I can't get jsbin to work - doesn't want to load stuff from polygit. However, my example is a bit different so that is probably why I'm getting different results. If you can get it to work please check it out: https://jsbin.com/qoduzegipi/edit?html,console

**Comment by sorvell** [comment]
We recently changed `2.x-preview` to have similar semantics as 1.x as far as observing changes to objects. It's required to use a wildcard to see path changes, e.g. `things.*`. This may explain some of the confusion. Also please note that the static `config` property must contain a `properties` object to provide property metadata.

Here's an updated jsbin for @arthurevans https://jsbin.com/japicob/edit?html,output which seems ok. 

Here's an updated jsbin for @mkazlauskas https://jsbin.com/vusezoc/edit?html,console,output which seems ok.

Please re-open if there are any issues left here.
