### ISSUE TITLE
Polymer 2.0 Safari Tech Preview 24, 10.2

### ISSUE THREAD

**Issue by tachyon1337** [Polymer/polymer#4338]
The Polymer 2 preview sites states that 2.0 and 2.0 class-style elements can be written in ES6 work without transpilation in Safari 10 & Safari Technology Preview. While that's true for the current Safari 10.0.3, it is not true for the Safari Tech Preview 24, 10.2. In fact, polymer 2 custom elements completely fail to create a Shadow DOM v1 on STP. This behavior can be verified by running the code labs polymer 2 carousel project under 10.0.3 and then 10.2.

**Comment by sorvell** [comment]
@keanulee Would you mind verifying the issue here? Thanks!

**Comment by keanulee** [comment]
I can't replicate this issue with Safari TP 24 or WebKit Nightly - seems to work fine. One thing to that changed with Polymer 2.0-preview since the codelab was last updated is that classes no longer have a static `get config()`. Instead, you now return static `get properties()`, `get observers()`, etc. I'll make a note to update the codelab soon, but in the meanwhile the mixin should look like this:

```javascript
  const MyMixin = subclass => class extends subclass {
    static get properties() {
      return {
        selected: {
          type: Object,
          observer: '_selectedChanged'
        }
      };
    }

...
```

**Comment by tachyon1337** [comment]
@keanulee 

Yeah, the codelab lesson I had locally was from a bower install roughly 30 days ago. The issue can be verified from this docker cloud demo site which is using polymer 2.0 preview pulled 1/27/2017.

http://threesixty1.mis.social

However, if a new pull obviates the problem, the issue is moot. Of course, I was reticent to simply resort to testing that out for fear of code breaking changes...which in this case would happen if the  
 `static get config()` has been refactored.
