### ISSUE TITLE
all event like listen/fire should effect after property are complete changed.

### ISSUE THREAD

**Issue by hzmnet** [Polymer/polymer#4349]
```
<data  output="{{data}}"> <data>

<div1   d1="{{data}}"/>
<div2   d2="{{data}}"/>

```
when div1 property d1 changed and fire a change event "search". div2 listen "search" and ruan function to read its property d2 but d2 is null.

**Comment by azakus** [comment]
Sorry, I don't understand what the issue you are seeing is. Can you provide a link to a reproduction with jsbin?

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with Polymer 2 for us to be able to debug and potentially fix. Polymer 2 fixes a large amount of issues, probably including this one as well.

Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with Polymer 2.  Thank you!
