### ISSUE TITLE
appending <div> with nested <content> on to Polymer.dom(this.root) does not display content

### ISSUE THREAD

**Issue by achung89** [Polymer/polymer#4355]
### Description

When I append a div with a nested content, the content will not display.  It will output when I append a content element directly, but another bug occurs when I pair a direct content element with a nested content element. In this case, the content only appears within the nested content.  
#### Live Demo
https://jsbin.com/dibizuz/3/edit?html,output EDIT: new link

#### Steps to Reproduce
1. To see the first bug, take out content tag from the xml string and place it outside div. You should see the content appear after the div
2. To see second bug, put content tag back to original location and uncomment the bottom expression.  You should see the comment show up where the nested comment is located.  

#### Expected Results
Expected comment to appear when <comment> tag is nested.  

### Browsers Affected

 [0] Chrome
 [0 ] Firefox
 [0 ] Edge

### Versions

- Polymer: vX.X.X
- webcomponents: vX.X.X

**Comment by sorvell** [comment]
This issue results from a limitation with Polymer 1.x's shadydom implementation. The insertion of `<content>` elements inside a dom tree that is not rooted at a document fragment (e.g. `<div><content></content></div>` as in the jsbin) is not automatically detected.

To fix this you should call `this.distributeContent(true);` on the element after appending the container of the `<content>` element. Here's the working jsbin: https://jsbin.com/nowilel/edit?html,output.

The 2nd `<content>` does provoke ShadyDOM to update and therefore the node appears at the first, nested `<content>` where it belongs.

This behavior has been fixed in the 2.0-preview branch.

**Comment by achung89** [comment]
That fixed it, thank you.
