### ISSUE TITLE
Vulcanization is not working

### ISSUE THREAD

**Issue by balubunny4u** [Polymer/polymer#4384]
I have used lazy loading Polymer.Base.importHref().After that vulcanization is not working.Without doing vulcanization it was taking more time to load landing page.

**Comment by web-padawan** [comment]
Are you using `polymer-cli`? If so, you should specify all elements being imported lazily as fragments in your `polymer.json` file, see [this guide](https://www.polymer-project.org/1.0/docs/tools/polymer-cli#build).

**Comment by balubunny4u** [comment]
I have not use polymer-cli.But i have specified all elements in polymer.json.
![screen shot 2017-03-07 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/15211745/23644637/423115d0-032e-11e7-8c3a-e81d3104dc9f.png)

**Comment by web-padawan** [comment]
Which versions of Polymer and vulcanize do you use?

**Comment by balubunny4u** [comment]
Polymer 1.6.1

**Comment by web-padawan** [comment]
I can suppose a few reasons, maybe I could help if you create a repro in a separate github repo (as small as it would be enough to reproduce). 
Also, consider using [polymer-cli](https://github.com/Polymer/polymer-cli) (or [polymer-build](https://github.com/Polymer/polymer-build) if you prefer to write `gulpfile` yourself) instead of just running `vulcanize` from the command line.
BTW submitting issues to corresponding github repos is a good idea, because Tools team will look into them quickly.

**Comment by azakus** [comment]
This issue was moved to Polymer/polymer-bundler#456
