### ISSUE TITLE
paper-button.active behaves differently in 1.x and 2.x

### ISSUE THREAD

**Issue by mkutny** [Polymer/polymer#4394]
### Description
I've set `on-tap` event handler on `paper-button` and checking the button state inside it:

    <template>
      <paper-button id="test-button" toggles on-tap="_processTap">
        Press me
      </paper-button>
    </template>

    <script>
        _processTap: function(ev) {
            const button = ev.currentTarget;
            if (button.active) {
              console.log('button is active in the event handler');
            } else {
              console.log('button is inactive in the event handler');
            }
          },
    </script>

In Polymer 1.8.1 `paper-button` element updates `active` property before handler is called.
In Polymer 2.0.0-rc2 the handler is called before `active` property is changed.

#### Expected Results
I expect this behavior to be consistent among versions.

#### Versions
- Polymer: v1.8.1 vs v2.0.0-rc2
- webcomponents: v0.7.24 vs v1.0.0-rc5

**Comment by TimvdLippe** [comment]
Confirmed that the behavior is still different: http://jsbin.com/sojawesiri/edit?html,console,output

**Comment by sorvell** [comment]
`paper-button` provides an explicit `change` event that can be used to inspect the `active` state. Here's a working example that uses this event: http://jsbin.com/jotoxexezu/1/edit?html,console,output

That said, this issue does reveal an unintended inconsistency between 1.x and 2.x that we'll want to fix. The ordering between events declared in the `listeners` object for a given element and those set on it via `on-*` listeners has changed between 1.x and 2.x.

In 1.x, the `listeners` object was applied before `on-*` listeners. In 2.x it's currently the reverse. Not only is this inconsistent but the new change is undesirable since an element should get first crack at its events.
