### ISSUE TITLE
[2.x] missing notifications

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#4405]
It appears that when two elements try to set the value of a parent property, an observer to that property will skip one of the updates.

Consider this jsbin:
http://jsbin.com/vafumah/edit?html,console,output

```html
<app-location route="{{_route}}" use-hash-as-path></app-location>
<app-route
    route="{{_route}}"
    pattern="/:page"
    data="{{_pageData}}"
    tail="{{_subRoute}}"></app-route>
<!-- nav menu -->
<paper-listbox
    selected="{{_pageData.page}}"
    attr-for-selected="name">
  <paper-item name="home">Home</paper-item>
  <paper-item name="favorites">Favorites</paper-item>
</paper-listbox>
```

The initial route is set in the attached callback:
`this.set('_route.path', '/home');`

Take a look at the console output from `_pageDataChanged`:

#### Expected Results

_New value, old value_
{}, undefined
{ page: 'home' }, {}
// Click on favorite
{ page: 'favorite' },  { page: 'home' } 

#### Actual Results
_New value, old value_
{},  undefined
{ page: 'home' }, {}
// Click on favorite
{ page: 'favorite' },  { page: 'favorite' }

cc @sorvell, @azakus, @kevinpschaaf

**Comment by kevinpschaaf** [comment]
After debugging, the conclusion is that this behavior is as expected.

The issue is not that Polymer is missing an observer call.  The confusion arises because the value being observed is an _Object_ whose sub-properties may change separately and without regard to how changes to the root object is reported.  As this jsBin shows, the old value is indeed the previous observer call's current value _and_ different from the current observer's current value: http://jsbin.com/yagokaj/edit?html,console,output.

What is happening is that the old object's `_pageData.page` sub-property was changed in the same turn that the `_pageData` object itself changed (and to the same value as the new `_pageData.page` property), hence the conclusion that the new value is the same as the old value, but as the equality check in the jsBin shows this is not the case.

It appears that `app-route`'s wildcard observer on `data` for deep changes external to the element causes a new `data` object to be created (and notified out); but for that to happen the original (old) `data`'s sub-property must have been changed first, followed by a brand new `data` object being produced by `app-route`.  As such, a user of `app-route`'s `data` property cannot rely on the "old" data object being frozen in time at the last observer call since the 2-way notification of existing data object sub-properties is what actually causes it to propagate new data.  It would seem that the correct pattern would be for users to capture current data sub-properties if they desire to use them for comparison in future data observer calls.

cc @rictic as FYI
