### ISSUE TITLE
Passing attribute values to properties not working in Polymer v2.0?

### ISSUE THREAD

**Issue by PaulHMason** [Polymer/polymer#4413]
### Description
I'm not sure if I missed something, but if I have an element with a property "foo" and set the value explicitly in an attribute ("foo") it doesn't get copied to the property, but it does work if I use an attribute binding.

#### Steps to Reproduce

Create a v2 Polymer element with a string property:

```javascript
static get properties() {
    return {
        foo: {
            type: String
        }
  };
}
```

Set the corresponding attribute on the element:

```html
<my-component foo="foo-3"></my-component>
```

#### Expected Results
Property "foo" should have the value "foo-3".

#### Actual Results
Property "foo" has the value undefined.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.0.0-rc2
- webcomponents: v1.0.0

**Comment by kevinpschaaf** [comment]
Can you clarify how/when you're reading `<my-element>.foo` as `undefined`?

By `connectedCallback` time all attributes have been deserialized to their properties as long as they were defined in the `properties` block.  See http://jsbin.com/motebi/edit?html,console,output.  Can you modify that jsBin to exhibit the problem?

Note that in `constructor` even after `super()` the property has not yet been set yet because the custom elements V1 spec forbids reading attributes from the constructor; as such we have to wait for `attributeChangedCallback`, which happens after `constructor` but before `connectedCallback` for attributes parsed from HTML.

**Comment by PaulHMason** [comment]
It was me being an idiot - I wasn't calling the super class in "attributeChangedCallback".

**Comment by jsilvermist** [comment]
There's an issue in the linter to add detection for this scenario, you can follow this issue here for updates: https://github.com/Polymer/polymer-linter/issues/52

**Comment by IAfanasov** [comment]
Found another unexpected thing with same symptoms. Hope it will help for sufferers who will find this topic

```javascript
static get properties() {
    return {
        fooBar: {
            type: String
        }
  };
}
```

Not work
```html
<my-component fooBar="foo-3"></my-component>
```

Work
```html
<my-component foo-bar="foo-3"></my-component>
```

**Comment by brandonag1** [comment]
Thank you @IAfanasov !
