### ISSUE TITLE
::Slotted with an appended element

### ISSUE THREAD

**Issue by RoXuS** [Polymer/polymer#4462]
### Description
How to style an element which has been appended in the DOM.

#### Steps to Reproduce
In Polymer < 2.0, I use `::content` to style the appended `td`:

`css`
https://github.com/RoXuS/paper-datatable-api/blob/2.0-preview/src/paper-datatable-api-shared-styles.html#L75
`js`
https://github.com/RoXuS/paper-datatable-api/blob/2.0-preview/src/paper-datatable-api.js#L484

#### Expected Results
Slotted doesn't work with the appended element.

#### Actual Results
Slotted should be work with the appended element ?

### Versions
- Polymer: v2.0.0-preview

**Comment by web-padawan** [comment]
As it is mentioned [here](https://github.com/Polymer/polymer#scoped-styling), `::sloted` may only target immediate children and use no descendant selectors. I guess this is the reason.

**Comment by azakus** [comment]
@RoXuS could you post a working example of the issue? Really hard to tell what's happening just from reading code :)

**Comment by RoXuS** [comment]
@web-padawan, @azakus here an example http://jsbin.com/huwiwuniqu/1/edit?html,console,output

**Comment by sorvell** [comment]
Thanks for the explanation @web-padawan. This was a spec change that came with v1 Shadow DOM.

The analog for the v0 selector `:host ::content tbody td` is just `:host ::slotted(tbody)`. The `td` cannot be targeted because only elements directly distributed into slots can be styled.

The workaround is to move the styling to a scope that can target all the elements in the desired selector. This isn't always completely satisfying but we need to adjust to the spec change.
