### ISSUE TITLE
polymer 2.0 slot[name='para1']::slotted(*) doesn't work on FF and Safari

### ISSUE THREAD

**Issue by goldenbearkin** [Polymer/polymer#4463]
Description
slot[name='para1']::slotted(*) doesn't work as expect.

Live Demo
http://plnkr.co/edit/Ep8AVOHgiwQjtv8x5kwd?p=preview

Versions
Polymer: v2.0.0-preview

The demo is just found in the polymer devguide. Open it at FF and Safari to reproduce the error.

Here is the devguide:
https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-slotted-content-distributed-children

**Comment by azakus** [comment]
@goldenbearkin This is a known limitation of the ShadyCSS scoping shim. Please put a selector to the left of `::slotted` like so: http://plnkr.co/edit/eAVHP6yOPg3ehRrJzxty?p=preview

@arthurevans we should update the docs with this limitation in mind :)

**Comment by arthurevans** [comment]
@azakus Yep. Pinging @katejeffreys who's working on these chapters.

Playing with the plunker, I was curious about some issues and differences from Polymer 1.

1. The plunker seems to break when you add the [name='para1'] selector. I think this is because the slot disappears in the shimmed version. So to select the way the OP was doing, the attributes would have to be on the outer paragraphs, like this:

    http://plnkr.co/edit/sT8BonD8vDf4Pt0ZjqHD?p=preview

    This is essentially identical to the Polymer 1.x limitation.

2.  `:host ::slotted` doesn't appear to work.

3.   In 1.x, we automatically added the `:host` so in most cases you didn't need to add a selector on the LHS. Is there a reason we're not doing that in 2.x/v1 scoping shim?

**Comment by govis** [comment]
I've been using <code>::slotted([slot=para1])</code> and it seems to be working well

**Comment by govis** [comment]
I've been using <code>::slotted([slot=para1])</code> as opposed to <code>slot[name='para1']::slotted(*)</code> and it seems to be working.

**Comment by katejeffreys** [comment]
http://plnkr.co/edit/sOoZeG5QXkdYBo5G58uS?p=preview shows the syntax used by @govis 

`p ::slotted([slot=para1])` 

working in Firefox; and shows the syntax I originally documented 

`slot[name='para1']::slotted(*)`

failing in Firefox.

Is `p ::slotted([slot=para1])` the correct syntax going forward? If so, I will update the docs to use it. 

@azakus @arthurevans

**Comment by TimvdLippe** [comment]
This has been updated at https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-slotted-content-distributed-children
