### ISSUE TITLE
Show warning when property contains cases

### ISSUE THREAD

**Issue by owencm** [Polymer/polymer#4479]
### Description

I used a name with an uppercase character (userName) as a property and then was surprised when it didn't get set on the child, due to Polymer changing userName to username.

If someone passes in a property with any upper case characters, can we consider showing a console warning to improve debug-ability? 

### Versions
- Polymer: 2.0 preview

**Comment by TomK** [comment]
It is correct to use camelCase for properties, but they are set on elements with dashes:
A property called `userName` is set by passing the attribute `user-name="value"`

**Comment by TomK** [comment]
https://www.polymer-project.org/2.0/docs/devguide/properties#property-name-mapping

**Comment by sorvell** [comment]
I'm assuming you're talking about an attribute here, e.g. `<my-element username="Bob">` where `my-element` has a property named `userName`?

Unfortunately, since elements must declare their observed attributes to be informed of changes and `userName` is (by convention) converted to `user-name`, we can't catch this directly in Polymer.

Instead it should be added to `Polymer lint`. Closing this issue in favor of one filed on the linter: https://github.com/Polymer/polymer-cli/issues/642.
