### ISSUE TITLE
2.x should test also wc-ce=true only & wc-shadydom=true only

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polymer#4484]
Currently tests are run forcing both ShowDOM & CustomElements polyfills. Permutations of ShadyDOM only and CustomElements only should be supported/tested as well

**Comment by sorvell** [comment]
There is no browser that currently supports viable versions of one but not both of these features. For that reason and because running too many test configurations puts excessive load on managing changes since the tests can take too long to run, we're opting not to do this.

**Comment by sorvell** [comment]
Some users may want to use native custom elements with shimmed Shadow DOM since there is more styling flexibility for legacy apps. For this reason we'll go ahead and add this scenario to the testing matrix.

**Comment by sorvell** [comment]
Running tests in this mode causes 4 failures in `dom-if` that are unlikely to be easily fixed. ShadyDOM moves elements in dom to distribute them. This distribution is seen by native custom elements as insertions/removals that incorrectly provoke extra connected/disconnected callbacks. This is something that the custom elements polyfill avoids when run with ShadyDOM. 

This typically does not result in code failing since typically elements must handle being connected/disconnected, but it does cuz extra churn. The failing tests are validating the # of times elements stamped with `dom-if` are connected/disconnected when the `dom-if` moves. While it may be possible to fix these specific test issues with tweaks to ShadyDOM, it's not really feasible to solve the problem in general without the custom elements polyfill.
