### ISSUE TITLE
Unable to use global style on Polymer 2.X

### ISSUE THREAD

**Issue by catalinbalu** [Polymer/polymer#4488]
In Polymer 1.X I was able to define global CSS rules for my APP and include them with one css file in index.html. All the rules were applying on all levels elements. 
In Polymer 2.0 is not working. None of my global style is applied to selectors from elements used on the page. 
How could I integrate a theme css or bootstrap css with my Polymer app?

**Comment by baocang** [comment]
See: https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-modules

**Comment by kevinpschaaf** [comment]
In Polymer 1.x, the shady DOM shim was used by default for development, and many users switched to use native shadow DOM by default when shipping to production for better performance.  However, if you did not do this, you could take advantage of the ability to "leak" styles from the document into elements in "shady roots" since they were not actually in scoped shadow roots.

Now that native shadow DOM is supported by Safari, in 2.x we switched the default to Shadow DOM by default for browsers that support it.  With this enabled, you get strict scoping of shadow roots, and document styles will not leak into shadow roots, per spec.

See the link above for a description of theming scoped elements via either style modules or custom properties.  Alternatively you could unconditionally load the `shadydom` polyfill and force it on, at the cost of performance on Chrome and Safari.

That said, it would be a mistake to e.g. include a huge bootstrap.css in every component's shadow root, since a "button" should only include the button css, etc.  This is a bit of a shift in thinking from legacy web development where we didn't have the notion of components or scoping, etc.

**Comment by kevinpschaaf** [comment]
Alternatively, you could also choose to avoid use of Shadow DOM altogether, as per the discussion in https://github.com/Polymer/polymer/issues/4473.  That would require you to deal with styling elements on your own (e.g. fully global styling) and losing e.g. content distribution, but we envision users where that's an ok tradeoff.
