### ISSUE TITLE
dom-repeat not refreshing when bound to a sub-property

### ISSUE THREAD

**Issue by govis** [Polymer/polymer#4496]
### Description
<code>dom-repeat</code> not refreshing when bound to a sub-property

#### Live Demo
http://jsbin.com/qelanehaji/edit?html,output

#### Steps to Reproduce
if you replace <code>menu.items</code> with <code>items</code> it should work

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.0.0-rc.3
- webcomponents: v1.0.0

**Comment by sorvell** [comment]
The call to `set` here fails because there is no existing `menu` object on which to set the `items` property. This is expected ([documented here](https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.PropertyEffects#method-set)). If you create the `menu` object first, the `set` will work. In your test, this would be unnecessary, of course, since you could just set `menu`.

Setting `menu` ahead of time and using `set` to set sub-property: http://jsbin.com/baxufib/edit?html,output
Setting `menu` in `ready`: http://jsbin.com/votofu/edit?html,output

**Comment by govis** [comment]
Thanks for pointing that out. My actual problem ended up being with the items property set twice - first directly and then via the Polymer .set method, which would not notify due to the same array reference, so when I tried to put a quick repro together I missed the initialization and it manifested in a similar behavior.

I think that it might be safe to throw "Can't set x property of undefined" in the case above - that would be totally expected. Thanks for your help.
