### ISSUE TITLE
JSON object/array serialization in polymer 2

### ISSUE THREAD

**Issue by siavashkavousi** [Polymer/polymer#4538]
#### Description
I want to pass some data from python to an element 
```python
data = {"name": "Master's or sth else"}
data_json = json.dumps(data)
```
and in html ($ sign is because of mako syntax... anyway doesn't matter)
```html
<my-element options='${data_json}'></my-element>
```
But data_json doesn't pass correctly to my-element. The problem is single quotation inside data_json.

#### Expected Results 
Passing data (with single quote!) to my-element

#### Actual Results
Single quote inside data_json breaks attr value
In chrome: 
![screenshot from 2017-04-17 17-01-52](https://cloud.githubusercontent.com/assets/11883216/25089107/7a6ed40a-2390-11e7-9013-6fb76eb51da8.png)
In firefox:
![screenshot from 2017-04-17 17-08-57](https://cloud.githubusercontent.com/assets/11883216/25089126/97a7e4da-2390-11e7-8eac-5fa7262ef52d.png)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: 2.0.0-rc.5
- webcomponentsjs: 1.0.0-rc.5

**Comment by kevinpschaaf** [comment]
The issue is that you are not escaping special values (single quotes) in your attribute value correctly, and so the browser's native HTML parser is not parsing it as you intend.  Since Polymer leverages the native parser, this is not a Polymer-specific issue, since Polymer never sees the value you intend.

It looks like you are using server templating to inject the JSON into the HTML attribute; if so, you need to run it through an HTML escaper to ensure the characters are valid in the HTML attribute.  Specifically, the single quote in the string you are serializing needs to be encoded using `&#39;` to ensure it doesn't close the attribute value.

See https://dev.w3.org/html5/html-author/charref for a full list of escaped HTML entities.  If you're using Python, this may help: https://wiki.python.org/moin/EscapingHtml
