### ISSUE TITLE
Polymer 2: URLs in Templates

### ISSUE THREAD

**Issue by jyounce** [Polymer/polymer#4544]
[Reference...](https://www.polymer-project.org/2.0/docs/upgrade#urls-in-templates)

I need the urls in the templates to be relative to the import url, not the main document's url.

This was default behavior in Polymer 1.x and in my opinion, one of the coolest features.

I know this can be accomplished via prefixing the urls with [[importPath]] but this causes other problems for me and at the moment not an option.

Help would be very appreciated.

### Versions

- Polymer: v2.X

**Comment by arthurevans** [comment]
Can you provide some more details about why using `importPath` isn't an option? 

This automatic modification of URLs caused a number of issues, because only the element author knows whether a given URL is supposed to be import-relative or main-document relative. So the 1.x strategy really isn't workable.

**Comment by jyounce** [comment]
Thanks for the reply,
Before going into the details of my problem, my question would be, why would anyone besides the element author need to know about the relativity of the template URLs?

**Comment by arthurevans** [comment]
Because if Polymer automatically rewrites all URLs as if they were import-relative, it breaks any URLs that are supposed to be main-document relative. That's why 2.x makes this an explicit choice instead of enforcing one pattern on all elements. See for example https://github.com/Polymer/polymer/issues/4213 for one of the related issues.

**Comment by jyounce** [comment]
I see, thanks for the issue reference .

So my problem is with the css template assets. I have a build system that automatically creates and inserts the css links into the template, these tags: <link rel="stylesheet" href="example.css">.

I need these css URLs to be import-relative without the need for prefixing them with [[importPath]] because the build system will not prefix them with [[importPath]].

Any ideas?

**Comment by jyounce** [comment]
So I have found a solution, I'm going with the [external stylesheet](https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#external-stylesheets) approach that you guys reference. When I use that approach, the css URLs appear to be import-relative and that's what I need, great.

I'm a little concerned about this approach because you guys say that it is a "deprecated feature". Any thoughts on this?

**Comment by sorvell** [comment]
External stylesheets are still supported in Polymer 2.x. Since they are deprecated, the feature may be removed in the next major version.

Urls in the contents of `<style>` elements in element templates are still re-written to be relative to the element import. It's only attributes that are not touched. We have no plan to change this behavior.

**Comment by jyounce** [comment]
Thanks for the reply sorvell,
For context, here is what I am doing. I will be creating [chord-c](https://chord-c.com/) web components that will be hosted on a separate server and consumable via html import. Example, &lt;chordc-fretboard&gt;. The build system I use is [rapid-build](http://rapid-build.io/) an [npm package](https://www.npmjs.com/package/rapid-build).
