### ISSUE TITLE
dom-repeat conflict with defined item property

### ISSUE THREAD

**Issue by rubenstolk** [Polymer/polymer#4559]
### `v1.9.1`
Did not verify this in `2.0`

### Description
When using `dom-repeat` with the default `as="item"` binding (or omitting it) and having a defined property called `item`, a conflict in the databinding occurs leading to possible memory leaks.

#### Live Demo
http://codepen.io/anon/pen/OmMgNY

#### Steps to Reproduce
See the live demo, when updating `element.item` and having a `dom-repeat` at the same time, `_clearPath` gets called recursively leading to memory leaks.

In the live demo, press the play button and see how toggling the checkbox affects the "throughput", unchecking the checkbox will no longer fire updates to `this.item` but rather to `this.itemWithAnotherName`.

**Comment by kevinpschaaf** [comment]
@rubenstolk I believe what you are seeing is roughly as expected, given the implementation.  The decoupled nature of how Polymer forwards outer-scope properties to inner template scopes means that a property referenced into an outer scope is always forwarded to the inner scope (since the outer scope makes no assumptions about how the inner template implementation may use the property), despite the fact that it may be ignored by the inner scope (i.e. in the case that it is shadowed by an inner scope property, as here).  As such, you pay the cost of forwarding outer host properties to inner scopes _per instance_.  As the instance count grows as more and more `dom-if`'s are switched on, there is more and more work to forward the property to more instances.

The decoupled nature of the template system (outer scopes not making assumptions about how inner scopes use properties) is one we'd prefer to keep, so we're unlikely to change this given it can be avoided by simply naming inner properties to not conflict with outer property names (which is why the e.g. `as="..."` and `indexAs="..."` features exists).

However, I'll also note that even without renaming the property, this can largely be mitigated in your particular example by using a different pattern to limit the number of instances created.  Any time you find yourself wrapping an entire `dom-repeat` template content with `dom-if`, consider using `dom-if`'s `filter` function instead, which limits the number of template instances being created in the first place (and hence the time complexity of forwarding outer scope properties in to each of them).  For a large number of items, this should be a significant improvement in initial render time as well as dynamic property update time.

Example: http://codepen.io/anon/pen/dWpJbd?editors=1010

I'm going to go ahead and close, but ping me if I missed something and there's more to the story here.

**Comment by rubenstolk** [comment]
Hi @kevinpschaaf thanks for the feedback. I think in that case there should at least be some kind of warning system if it detects that a property (or method) is already defined. Like the other day I ran into the issue where I had defined a method with the name `page` (to switch pages) while using a `dom-repeat` with `as="page"` only to discover later that the method doesn't exist anymore.

Perhaps `dom-repeat` could check and warn if `this.{{as}}` already exists...? Nobody tells me that I shouldn't use a property with the name `item` which I believe a lot of developers could choose for any given element...

**Comment by kevinpschaaf** [comment]
@rubenstolk If an inner scope property (the `as="page"`) is stomping on an outer scope property, that's a bug that we should fix.  Can you post a repro in a new issue?

**Comment by rubenstolk** [comment]
Hi @kevinpschaaf before me making an issue, can you validate that this is indeed an issue: http://codepen.io/anon/pen/NjRBVV

**Comment by kevinpschaaf** [comment]
@rubenstolk Ok, so it does look like there's something unexpected in 1.x: any host properties referenced in a template get an accessor on the host for purposes of ensuring changes to the host property are forwarded to the template (expected), and this accessor stomps on any previous value.  Normally when the host property is e.g. in `properties` this is not a problem since the default value is set into the accessor on the instance.  However, if the property exists on the _prototype_ (as in a prototypical _method_), the prototypical value is lost.  This is indeed unexpected.

Polymer 2.0 is much more robust in this respect and always ensures prototypical values are retained in the accessor value for the instance any time an accessor is created, and the issue does not occur in Polymer 2:

Polymer 1.x: http://jsbin.com/ruziyes/edit?html,output
Polymer 2.x: http://jsbin.com/sogosiy/edit?html,output

Since Polymer 1 will be moving into maintenance mode as Polymer 2 will be released imminently (and doesn't suffer from this issue), we're unlikely to make any big changes in that codebase to solve an issue like this with an easy workaround (specifying an `as="..."` to avoid conflicts).  So I'd probably say this will practically be "won't fix".
