### ISSUE TITLE
event.preventDefault

### ISSUE THREAD

**Issue by yanlee26** [Polymer/polymer#4560]
how to stop default event in polymer,I wrote this,but not work
`
function a(e){
e.preventDefault();
//...

}

`

**Comment by kevinpschaaf** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!

**Comment by web-padawan** [comment]
@yanlee26 in some cases you might need to check `sourceEvent`, especially for [gesture](https://www.polymer-project.org/1.0/docs/devguide/gesture-events) events, as well as for some events fired by `iron-a11y-keys` element.

**Comment by Supreme-Chandru** [comment]
@web-padawan , Thank you very much. Solved my propagation issue.
