### ISSUE TITLE
Binding doesn't update when a declared property is initially undefined

### ISSUE THREAD

**Issue by jrobinson01** [Polymer/polymer#4561]
#### Live Demo

https://jsfiddle.net/d2pqL82x/4/

#### Steps to Reproduce
1. Create `example-element`

#### Expected Results
The text "Default..." should be displayed when the component is first rendered.

#### Actual Results
The text "Default..." is not displayed until the "click" element is clicked a second time.

### Browsers Affected
the JSFiddle only seems to run in chrome so other browsers are untested.
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: 2.0-preview
- webcomponents: vX.X.X

**Comment by kevinpschaaf** [comment]
The Polymer data-binding system uses a "push" model based on property accessors (setters); property side-effects "go" when data is set via the setter.  It does not "pull" data from getters.  As such, if no value is set by default (e.g. `false`, `null`, etc.), side-effects like data-binding do not occur since the setter does not run.

You've already noted in your jsBin that using a `null` (but `false` would also work) default corrects the issue, and this is indeed the solution.
