### ISSUE TITLE
Shared styles/custom style modules doesn't work in dom-if

### ISSUE THREAD

**Issue by troublete** [Polymer/polymer#4569]
### Description

When trying to apply a shared style module via custom style inside an `dom-if` the style is applied even if the `if` expr. is false.

#### Live Demo

http://jsbin.com/mefumad/edit?html,output

#### Steps to Reproduce

None. 

#### Expected Results

Style in one of them will be different based off the value given in the `dom-if`.

#### Actual Results

Both change style defined by on the last shared style included.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: v1.2.5-npm-test.2
- webcomponents: v0.7.24

**Comment by azakus** [comment]
Conditional stylesheets are not supported in either 1.x or 2.x.
This is due to how ShadowDOM style scoping is emulated for browsers without ShadowDOM support.

In scenarios where you need to dynamically theme portions of your elements, CSS Custom Properties or css mixins are the only supported mechanism. Here's a version of your jsbin using CSS Custom Properties: http://jsbin.com/zukaqi/edit?html,output

**Comment by troublete** [comment]
Well actually it's monicas jsbin :p 
But thanks for the answer. 👍
