### ISSUE TITLE
Polymer.Gestures.removeListener removes underlying event listeners but not Polymer Gestures version

### ISSUE THREAD

**Issue by Denaszune** [Polymer/polymer#4589]
#### Live Demo
Running the removeListener event does not remove the Polymer Gestures entry so running addListener again creates another copy. This can get out of hand if you add and remove Listeners a lot.

I do believe it does remove the underlying browser listeners properly (ex. touchmove)
http://plnkr.co/edit/pNbHSfOmL8D52w0cqZ9G?p=preview

#### Steps to Reproduce
- Go to live demo
- Click the button and then the div
- Do this many times and watch some of the counts go way too high

#### Expected Results
All 3 numbers should be the same after adding and removing listeners the same number of times

#### Actual Results
Remove listener and # function call counts are way higher than add listener count

### Browsers Affected

- [x] Chrome

### Versions

- Polymer: v2.0.0-rc.2

**Comment by anuragpathak** [comment]
The problem here is the way event handler is passed. In given example it is getting passed as an anonymous function. Thus event listener is not getting removed.
Every time a new listener is added it is added as one more anonymous function.

I tried passing event as something which is attached to "this" context and everything is working now.

For refrence : http://plnkr.co/edit/wo1V6R?p=preview

**Comment by Denaszune** [comment]
I believe I may not even have to bind(this). If I stop using arrow functions I can get it to work as well. This is probably not a bug, sorry about that. I just need to learn more about Javascript :)

And thank you Anurag!
