### ISSUE TITLE
Observers not called on component inside an iron-list template

### ISSUE THREAD

**Issue by fabysdev** [Polymer/polymer#4601]
### Description

It seems like property observers are not called if the component is inside an iron-list template.
A dom-repeat renders fine outside of an iron-list but not inside of it. 
If I call `render` on the dom-repeat it renders normally.

#### Live Demo

http://jsbin.com/pulaworude/edit?html,js,output

#### Expected Results

dom-repeat renders items

#### Actual Results

dom-repeat does not render items

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge

### Versions

- Polymer: v2.0.0
- webcomponents: v1.0.0

It works with version `2.0.0-rc.8`. First broken version is `2.0.0-rc.9`.

**Comment by kownacki** [comment]
I also have exactly the same problem. Thank you reporting it and finding workaround to use `2.0.0-rc.8`.

**Comment by sorvell** [comment]
Thanks for reporting this. We can confirm this issue. There's a simple fix and it should make the first bug release version.

The issue is in `PropertyEffects` at [_readyClients](https://github.com/Polymer/polymer/blob/master/lib/mixins/property-effects.html#L1467). If a client has enabled properties prior to an element readying its clients (this can happen when using [templatize](https://github.com/Polymer/polymer/blob/master/lib/utils/templatize.html#L65)), the host element should call `_flushProperties` on it.

**Comment by jogibear9988** [comment]
see https://github.com/Polymer/polymer/issues/4609

**Comment by ktiedt** [comment]
Manually patched my local checkout and can confirm this does fix it.

Yay for not having to write a minimal demo :D

Thanks for the quick and helpful updates @sorvell!
