### ISSUE TITLE
JSON doesn't deserialize (sometimes?)

### ISSUE THREAD

**Issue by bamartin-ua** [Polymer/polymer#4602]
#### Live Demo
Since jsbin no longer seems to support saving, I'll just copy my example here
```
<!doctype html>
<html>
<head>
  <base href="https://polygit.org/polymer+:master/webcomponents+:master/shadycss+webcomponents+:master/components/">
  <script src="webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="polymer/polymer.html">
</head>
<body>


  <dom-module id="my-element">
    
    <style>
      :host {
        display: block;
      }
    </style>
    
    <template>
      <iron-ajax id="aj"
        headers='{"foo":"bar [[prop]]"}'
      ></iron-ajax>
      [[type]]
    </template>

    <script>
    HTMLImports.whenReady(function() {
      class MyElement extends Polymer.Element {
        static get is() { return 'my-element'; }
        static get properties() {
          return {
            prop: {
              type: String
            },
            type: {
              type: String,
              computed: 'gettype_(prop)'
            }
          }
        }
        
        gettype_(prop){return typeof(this.$.aj.headers)}
        
      }
      customElements.define(MyElement.is, MyElement);
    });
      
    </script>
    
  </dom-module>

  <my-element prop="baz"></my-element>
  
</body>
</html>
```

#### Steps to Reproduce

1. Have an `<iron-ajax>` element
2. Assign JSON object to 'headers' property

see https://github.com/PolymerElements/iron-ajax/issues/245

#### Expected Results
typeof(headers)==Object

#### Actual Results
typeof(headers)==String

### Browsers Affected

- [ x] Chrome
- [ x] Safari  #10

### Versions

- Polymer: 2.0-preview
- webcomponents: v1.0.0

**Comment by sorvell** [comment]
When a binding is included via `[[..]]` or `{{...}}` in an attribute value, this becomes a property binding unless you explicitly ask for an attribute binding by using `$` after the attribute name. Deserialization only occurs when setting attributes so if you want to include a binding in a value that you want to deserialize, you need to attribute bind to it. So change the `headers`to

```
headers$='{"foo":"bar [[prop]]"}'
```

Here's an example: http://jsbin.com/qenile/edit?html,output

That said, this construction where a binding is included within `json` syntax is going to be inherently brittle and slow and we'd recommend just constructing and binding in the entire object to be set to `headers`. The reason is that any time `prop` changes, the value will have to be re-`JSON.parse`'d. In addition, any value of `prop` that does not `parse` correctly will generate a warning. 

So something like this is better: http://jsbin.com/kufuli/edit?html,output

**Comment by bamartin-ua** [comment]
Polymer doesn't deserialize properties, only attributes? That's somewhat confusing from the documentation.

> Configuring object and array properties
> 
> For object and array properties you can pass an object or array in JSON format:
> 
> ```<my-element book='{ "title": "Persuasion", "author": "Austen" }'></my-element>```
> Note that JSON requires double quotes, as shown above.

https://www.polymer-project.org/2.0/docs/devguide/properties#configuring-object-and-array-properties 

However, I've confirmed that changing the `headers='{"foo":"bar [[prop]]"}'` to `headers$='{"foo":"bar [[prop]]"}'` (and importing iron-ajax... oops) does in fact deserialize as desired, so thanks!
