### ISSUE TITLE
Polymer _deserializeValue function should check type before JSON parsing

### ISSUE THREAD

**Issue by jduepmeier** [Polymer/polymer#4606]
### Description

When you provide a javascript array or object as property a parsing exceptions is thrown.

#### Steps to Reproduce

1. Create `my-element`
2. Define a property with type Array
3. Create an array with javascript and set it.
4. Polymer::Attributes: couldn't decode Array as JSON

#### Expected Results

Polymer should use the array.

#### Actual Results

Polymer::Attributes: couldn't decode Array as JSON

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: v2.0.0

**Comment by sorvell** [comment]
I don't quite follow the issue here given the description. This appears to be working as shown here: http://jsbin.com/bexalik/edit?html,output.

By design, when a property is declared with type `Array` or `Object`, it is deserialized from a corresponding attribute via `JSON.parse`. When a parse error occurs, the console warning is issued.

Can you explain more clearly what you see happening that is unexpected? Thanks.

**Comment by jduepmeier** [comment]
I forgot that the setAttribute function needs a DOMString and converts the array to a DOMString which is not valid json. Setting the attribute without setAttribute works as expected.
