### ISSUE TITLE
Polymer 1 template rendered twice in Chrome when combined with VueJS

### ISSUE THREAD

**Issue by tinlong** [Polymer/polymer#4621]
### Description

While exploring the possibility of combining Polymer 1 and VueJS, I have stumbled across this particular issue.

Without VueJS, Polymer 1 works fine. However, once a VueJS script is added, the template in the Polymer element got rendered twice. This only happens in latest version of Chrome (58.0.3029.110), and it does not affect IE11 or Firefox 53.0.3. Also, this particular problem does not happen when using Polymer v2's legacy polymer.html.

#### Live Demo

Simple example, showing one with VueJS binding works correct, but another one without VueJS binding repeated rendering in Chrome
https://plnkr.co/edit/AiNse4SDOQIiH1RlnKoE?p=preview

A more elaborated example, led to my discovery, this one with VueJS binding, and yet it renders duplicate in Chrome. Also shows that, in Chrome, the duplicated template was rendered, but never bound to any Polymer process.
https://plnkr.co/edit/v6JpKPaRcboXD7353GVL?p=preview

#### Steps to Reproduce

1. Create any element
2. Use that element in any page
3. In the main page that uses the custom element, add a VueJS ViewModel along with VueJS binding (does not even have to bind the custom element to VueJS, just adding any VueJS script and binding to other elements is enough)
4. Compare the render result between IE 11, FireFox and Chrome.

#### Expected Results

The element should only get rendered once in each browser.

#### Actual Results

The element got rendered twice particularly in Chrome.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v1.9.1
- webcomponents: v0.7.24

**Comment by kevinpschaaf** [comment]
This is a known issue/tradeoff in Polymer 1.x, which used a shimmed implementation of Shadow DOM by default that required all interactions with the DOM to use the `Polymer.dom` API.  This was a "performance-for-interoperabillty" tradeoff, in that `Polymer.dom` achieved significant performance advantage over the more transparent but much slower Shadow DOM polyfill, but led to interoperability issues when libraries other than Polymer attempted to render Polymer elements without using the `Polymer.dom` API.

In Polymer 2.0, we now use Shadow DOM by default along with a higher-fidelity polyfill which no longer requires use of a proprietary API, and generally solves all the issues with cross-framework interoperability.

As such, there are two options:

1. Use Polymer 2.0 and the newer high-fidelity "Web Components V1" polyfills.  We've spent a lot of time ensuring the migration path to Polymer 2.0 is very smooth, and there are lots of other benefits to making the switch (like being able to use native CE/SD on Safari).  Example: https://plnkr.co/edit/jbrBE4Pd82jnklNP0UKg?p=preview
2. If continuing to use Polymer 1.x, you must load the old Shadow DOM polyfill (`webcomponents.js` and not `webcomponents-lite.js`) and force Polymer 1.x to use Shadow DOM rather than Shady DOM by setting `Polymer = { dom: 'shadow' };` prior to loading `polymer.html`. Example: https://plnkr.co/edit/2jaZsrl7s0nJdiZQymL1?p=preview
