### ISSUE TITLE
<textarea> welcomes user with 'undefined' text value (only for object subproperties)

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-interxion** [Polymer/polymer#4630]
### Description
An `undefined` value, when binding to `<textarea>`,  is treated as 'undefined' text, but only if it appears in an object subproperty.
Interestingly `null` gets treated just fine. `undefined` in a flat property is also just fine.
`<input type="text">` doesn't have the issue.
 See the live demo.

#### Live Demo
http://jsbin.com/xukejamegi/edit?html,output

#### Expected Results
It should work like `<input type="text">`

#### Actual Results
The user value is an 'undefined' text.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: v1.9.1, v2.0.0 (we are using 1.9.1 - please **do** try to fix 1.X)
- webcomponents: 0.7.24

**Comment by TimvdLippe** [comment]
For native HTML elements, you should use `value$` for bindings instead of `value`: https://www.polymer-project.org/2.0/docs/devguide/data-binding#anatomy-of-a-data-binding

**Comment by slawomir-brzezinski-at-interxion** [comment]
@TimvdLippe Using `$value` can't work with `<textarea>` because [there isn't such an attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#Attributes).

If this was static HTML, you'd pass the value `<textarea>here</textarea>` but this doesn't work with binding.

Rather exists a `value` property though and binding to it is [the Polymer prescribed pattern](https://github.com/PolymerLabs/polymer-patterns/blob/master/snippets/forms/binding-to-a-textarea.html#L27)

**Comment by TimvdLippe** [comment]
@slawomir-brzezinski-at-interxion Oh sorry I missed that. Yeah seems like a bug.

**Comment by kevinpschaaf** [comment]
Thanks for the issue. Interesting that it's the first bug report we've had of this, even though Polymer 1.0 [would have suffered](http://jsbin.com/jedaxahoxo/1/edit?html,output) from the same issue.

At any rate, we avoid this for `<input>.value` only because there's an explicit special-case check for that exact case in the binding code: https://github.com/Polymer/polymer/blob/master/lib/mixins/property-effects.html#L601

Since we've already got precedent for special-casing input, I think we'd just add an `|| node.localName == 
textarea'` to the condition and fix the bug.

**Comment by slawomir-brzezinski-at-interxion** [comment]
Thanks for fixing this guys.
@azakus does this fix 1.X at all?
