### ISSUE TITLE
Polymer elements throw errors when async flag is added

### ISSUE THREAD

**Issue by bahrus** [Polymer/polymer#4631]
### Description
Errors thrown when async flag is used

#### Live Demo
http://rawgit.com/bahrus/xtal/master/tests/polymer-async.html

```html
Sample Markup:

<!DOCTYPE HTML>
<html>
    <head>
        
    </head>
    <body>
        [Imagine a shell from another framework goes here]
        <link async rel="import" href="../bower_components/polymer/polymer.html">
        <link async rel="import" href="../bower_components/iron-list/iron-list.html">
        <link async rel="import" href="../bower_components/iron-resizable-behavior/iron-resizable-behavior.html">
        <iron-list></iron-list>
    </body>
    
</html>
```

#### Expected Results
Elements can load as they arrive, using some approach to instantiate only after the depending elements are loaded
#### Actual Results
Uncaught ReferenceError: Polymer is not defined
    at iron-resizable-behavior.html:32

### Browsers Affected

- [x ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2.0.0
- webcomponents: v1.0.0

### Note

I raised something related[ in a previous](https://github.com/Polymer/polymer/issues/4487) issue that was closed almost immediately.  I wonder if I'm missing something big, which would explain why there is so little interest in this issue?

I'm using Polymer as a component library, rather than as a framework.  The framework that provides the shell is Preact.  I want to be able to let Preact render html content with zero blocking caused by waiting for the polymer elements to load, for less critical content.  If I don't set async, I see blocking.  I get similar errors with defer.  [Rob Dodson once (at least) suggested using async as a way to guarantee progressive enhancement](https://speakerdeck.com/robdodson/building-progressive-web-apps-with-polymer) and avoid blocking.  So unless I missed a memo, I thought this approach was supported?  

I tried setting the async flag on a Vaadin grid reference, and encountered similar issues as above.

**Comment by butterandfly** [comment]
Just import the iron-list, no need to import polymer at this file. Iron-list will import the polymer file, and it's(same as all the polymer elements) element definition needs the finish of polymer importing.

**Comment by bahrus** [comment]
Yes, I observed that as well, which is why I hesitated to log this.  However, are you saying we can't define a polymer element within the opening page, if we use async?  Where is this documented?

**Comment by bahrus** [comment]
Example 2:

http://rawgit.com/bahrus/xtal/master/tests/polymer-async2.html

The contents of that file are:
```html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        <link async rel="import" href="asyncRefs.html">
    </body>
</html>
```

asyncRefs.html:

```html
<link async rel="import" href="../bower_components/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html">
<link async rel="import" href="../bower_components/iron-list/iron-list.html">
<link async rel="import" href="../bower_components/iron-resizable-behavior/iron-resizable-behavior.html">
<link async rel="import" href="../bower_components/iron-scroll-target-behavior/iron-scroll-target-behavior.html">
```

Results:


iron-scroll-target-behavior.html:26 Uncaught ReferenceError: Polymer is not defined
    at iron-scroll-target-behavior.html:26
(anonymous) @ iron-scroll-target-behavior.html:26
2class.html:129 behavior is null, check for missing or 404 import
flattenBehaviors @ class.html:129
mixinBehaviors @ class.html:57
Polymer.Class @ class.html:323
window.Polymer._polymerFn @ polymer-fn.html:40
window.Polymer @ boot.html:29
(anonymous) @ iron-list.html:298
(anonymous) @ iron-list.html:1907

**Comment by kevinpschaaf** [comment]
I believe you're hitting a known issue in Chrome's native implementation of HTML Imports (I think the [repro in the 2nd comment in this Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=669710) roughly covers the behavior you're seeing).  Importing the same file, e.g. `polymer.html`, both async (as done in `index.html`) and sync (as done in e.g. `iron-resisable-behavior.html`) seems to result in the file being loaded async in all cases, which is definitely unexpected.

Given that bug, I'd recommend in your **Example 2** to remove the `async` flag from the all the imports in `asyncRefs.html` (but keep `async` on the import of `asyncRefs.html` itself) and I believe you should avoid the bug and meet your goal of having the dependencies used in the shell loaded asynchronously.  Totally acknowledge it's annoying, but we're working around a platform bug for now.

I'm going to go ahead and close the issue since there's not much in Polymer we can do to address the Chrome bug and there's already a tracking issue there.
