### ISSUE TITLE
this.$ undefined in attached in edge

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/polymer#4638]
I've a legacy element, in edge browser polymer calls attached, but this.$ is undefined

**Comment by TimvdLippe** [comment]
Did you call `super.ready()` in the ready method or any other method alike? We will need more information to debug your issue.

**Comment by jogibear9988** [comment]
I use a legacy component (means Polymer fuction). And in attached in edge this.$ in undefined

**Comment by kevinpschaaf** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and **be sure to include a live reproduction** so that the team can debug or understand your issue.  You can start from [this glitch template](https://glitch.com/edit/#!/accurate-mitten?path=public/my-element.html:2:0) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
