### ISSUE TITLE
delete this.obj.prop; notifyPath("obj.prop") doesn't notify

### ISSUE THREAD

**Issue by oskarlh** [Polymer/polymer#4652]
### Description
```
delete this.object.property;
// The following line doesn't notify, even if object.property previously had a defined value.
this.notifyPath("object.property");
```

#### Steps to Reproduce
```
<link rel="import" href="../bower_components/polymer/polymer-element.html" />
<dom-module id="test-element">
	<template>
		object.property is [[object.property]]
	</template>
	<script>
		class TestElement extends Polymer.Element {
			static get is() { return "test-element"; }
			static get properties() {
				return {
					object: {
						type: Object,
						value: () => { return { property: 1 }; },
					}
				};
			}
			ready() {
				super.ready();
				this.set("object.property", 2);
				
				delete this.object.property;
				this.notifyPath("object.property");
			}
		};
		customElements.define(TestElement.is, TestElement);
	</script>
</dom-module>
```
...
```
<test-element></test-element>
```

#### Expected Results
The text "object.property is" is shown.

#### Actual Results
The text "object.property is 2" is shown.

### Browsers Affected

- [x] Chrome
- [x] Firefox

### Versions
- Polymer: v2.0.1
- webcomponents: v1.0.1

**Comment by oskarlh** [comment]
this.set("object.property", undefined); doesn't do anything either.

**Comment by sorvell** [comment]
The issue here is that object path values are not stored (other than during "one turn" of data propagation). Therefore any "set" or "notify" is seen a change because it's dirty checked against no value; however, a change from `undefined` to `undefined` is not considered a change.The rules around this are [documented here](https://github.com/Polymer/polymer/blob/master/lib/mixins/property-effects.html#L1324-L1353) but they are complex and we're open to improving this. We'll leave this issue open for tracking improvements to the current behavior.

Currently, we recommend that you do `this.set("object.property", null);` where possible. Another option is to override `_shouldPropertyChange` and handle this case explicitly.
