### ISSUE TITLE
onclick inline script can't reference id in a shadow-dom (Polymer v2.0.1)

### ISSUE THREAD

**Issue by vdegenne** [Polymer/polymer#4661]
Consider [this Plunker minimal example code](http://plnkr.co/edit/3NYhmYSo1QmJTu6UCUUY?p=preview).

I am using Polymer v2.0. When I click on the button `dialog.open()` fails and says `dialog` is undefined.
In previous version of Polymer, this code worked but now that I have upgraded my code, I have to clear this issue everywhere I'm using paper-dialog elements. My current solution is to add a `on-click` attribute on all the buttons in my code and manually write a tied function and execute `this.$.<dialogID>.open();` but I don't understand why I have to do that, and it appears to be like an issue to me because I write more tedious code, and this afterward compatibility seems more like a disadvantage to the new version.

Am I *really* doing something wrong ?

**Comment by azakus** [comment]
Yes, `on-click` with a function you write is the correct solution here. This is because ID references in event handlers like you have written do not cross ShadowDOM boundaries, as the IDs are encapsulated in the ShadowDOM root.

In Polymer 1.x, you could write id references like that because real ShadowDOM was an opt-in feature, whereas in Polymer 2.x it is opt-out.

However, if we were to implement the feature proposed in #4647, you could write `on-click="$.dialog.open"`

**Comment by sorvell** [comment]
For completeness, here are the docs about how to force using web components polyfills: https://www.polymer-project.org/2.0/docs/polyfills. We don't recommend doing this, but it would get you unstuck.
