### ISSUE TITLE
a Polymer.Element extended class is not a polymer element ! [Feature Request]

### ISSUE THREAD

**Issue by vdegenne** [Polymer/polymer#4673]
Today I want to teach you one thing, but you have to be `ready () {` a Polymer.Element is not a polymer element !  `}`

If I make the following class 

```javascript
class IceCream extends Polymer.Element
{
  static get is () { return 'ice-cream'; }
  
  static get properties () {
    return {
      flavor: {
        type: String,
        value: 'vanilla',
        observer: '_flavorChanged'
      }
    }
  }

  _flavorChanged () {
    console.log(`the new flavor is ${this.flavor}`);
  }
}

customElements.define('ice-cream', IceCream);
```

and try to make a new Instance : 

```javascript
let icecream = new IceCream();
```
the property *flavor* is set to *vanilla* but the observer(s) is/are not called; as well as other features like **reflectToAttribute**.

All the Polymer lifecycle starts to take in effect when the Instance is attached to a location in the dom 

```javascript
document.querySelector('#location').appendChild(icecream);
/** attaching the element icecream to a location in the dom will have several effects
  * 1) the different observers will get triggered if any properties are changed
  * 2) the Polymer framework will create the shadowRoot from the template
  *     and construct subsequent Polymer.Element contained in the template.
  */
```

I think there are quite a few cases where one would want this behavior to be triggered internally, but one has to attach the element to the dom to force polymer to start the lifecycle and make a dom representation of this element.

In My Opinion this is an issue because a polymer custom element is a an object before all and when you attach it to the dom, the browser is making a visual representation of this element. However an object is not always meant to be attached, and an object can represent a part of the inner API or data structure of the application. And an object has data and spinning gears inside, and one should be able to detach and attach a living object from two different location of the dom (two views) without breaking all its consistency. 
For instance, a CountDown object is counting down internally and when attached, it should shows the remaining time. If you detach it and attach it somewhere else, the remaining time should show the appropriate data according to the count down that processed in the background during the time it were removed from the dom.

In the current version of polymer there are many tools to manipulate arrays and objects and notify the template for changes. But we can't manipulate custom-elements as data-structure of other custom-elements.

Here's a visual exemple of what i mean : 

```html
<link rel="import" href="count-down.html">

<dom-module id="count-down-app">
  <template>
    
    <!--  Normal use
          the countdown starts when the element is attached -->
    <count-down name="normal use" time="100"></count-down>
    
    
    <!--
    Using dom-repeat and create count-down elements
    The problem is the template creates new countdowns
    and then the new elements don't represent the real elements defined inside CountDownApp.countdowns
    -->
    <template is="dom-repeat" items="{{countdowns}}" as="countdown">
      <count-down name="created from dom-repeat" time="{{countdown.time}}"></count-down>
    </template>
    
    
    <!--
    The solution and FEATURE REQUEST -->
    <template is="dom-repeat" items="{{countdowns}}" as="countdown">
      {{countdown}} <!-- because the countdowns are real customElements they should attach -->
      <!-- this will print [object HTMLElement] -->
    </template>
  </template>
  
  <script>
    class CountDownApp extends Polymer.Element
    {
      static get is () { return 'count-down-app'; }
      
      static get properties () {
        return {
          countdowns: {
            type: Array,
            value: function () {
              return [
                new CountDown("from Instance", 200),
                new CountDown("from Instance", 300)
              ];
            }
          }
        }
      }
    }
    
    customElements.define('count-down-app', CountDownApp);
  </script>
</dom-module>
```

**Comment by jsilvermist** [comment]
If you want to create a custom element you can use:
```js
let icecream = document.createElement('ice-cream');
```

**Comment by vdegenne** [comment]
@jsilvermist `let icecream = new IceCream();` and `let icecream = document.createElement('ice-cream');` has the same effect and won't trigger the Polymer lifecycle. Thus the observers won't be called.

**Comment by vdegenne** [comment]
note : it seems as the **_flushProperties()** called on the Instance of the **Polymer.Element** is forcing the Polymer lifecycle. But I am not sure this is recommanded to directly use this function.

**Comment by sorvell** [comment]
You can call `_enableProperties()` on an element to "ready" an element. This will stamp its dom and enable its property accessors so that setting them produces side effects. [Note, this is currently not public API but it's reasonable that it should be made public.]

For `Polymer.Element`, we've chosen not to "ready" the element upon construction and instead wait until the element is connected. The main reason we've done this is to rationalize how an element handles its inputs, specifically attributes. 

We want to wait until any attributes have been received before doing potentially expensive setup work. Consider the `<input>` element as an example. It has a `type` attribute that defaults to `text`. Since attribute values are not available in the constructor, if it created its shadowRoot and populated the dom for the `text` type case upon construction, it would have to throw away that work and redo the dom in its shadowRoot if the element was `<input type="date">`. Since there is no explicit signal for when an element has received all of its attribute values (yes, there is attributeChangedCallback which is called when an observed attribute changes), we wait for `connectedCallback` when an element is guaranteed to have received any attributes. Unfortunately, the cases of `new MyElement()`, `createElement('my-element')`, or parser generated `<my-element>` are not distinguishable for these purposes.

We do not consider this behavior ideal and will be lobbying for a new callback to be added to the custom elements spec to help better coordinate initial setup work.

**Comment by sorvell** [comment]
@arthurevans can you make sure the above is indicated in the docs somewhere appropriate? Thanks!.
