### ISSUE TITLE
Polymer 2 - named slots not working in Chrome + Firefox

### ISSUE THREAD

**Issue by JoernT** [Polymer/polymer#4687]
See following gist with very simple Polymer 2 element.
https://gist.github.com/JoernT/81ae18de0e30b57654382b8172df16a3

Slot content ('Paul, Priya' here) is not rendering in both Chrome  59.0.3071.86 and Firefox 53.0.3 on OSX 10.12.5.

When using **without** slot @name the light DOM is shown.

#### Steps to Reproduce
1. open vra-name-demo.html

#### Expected Results
Light DOM is rendered

#### Actual Results
Light DOM is not rendered

### Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2.0.1
- webcomponents: v1.0.1

**Comment by arthurevans** [comment]
The issue here is with your sample. You're adding the `slot="vrname"` on the element itself, not on the light DOM content. If you move it to the light DOM content, your example should work:

```
<vra-name><span slot="vraname">Paul, Priya</span></vra-name>
```

There's no way to put an attribute on a text node, so you can't distribute unwrapped text to a named slot—only elements.

**Comment by JoernT** [comment]
Thanks for pointing that out. What confused me is that it works as long as i had the <vra-name> element as a light DOM child of another component.
