### ISSUE TITLE
dom-repeat not track nested (and computed?) elements by Polymer arrays mutation methods

### ISSUE THREAD

**Issue by napa3um** [Polymer/polymer#4692]
```
A:
<template is="dom-repeat" items="[[ accounts ]]" as="account">
    <template is="dom-repeat" items="[[ commentsByAccount(account.id, comments) ]]" as="comment">
        ...
B:
<template is="dom-repeat" items="[[ comments ]]" as="comment">
    ...

this.push('comments', comment) // A - not rerender (bad), B - rerender (good)
...
this.comments.push(comment)
this.comments = this.comments.slice() // A - rerender (good), B - rerender (good)
```
Polymer 2.0.1

**Comment by kevinpschaaf** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and **be sure to include a live reproduction** so that the team can debug or understand your issue.  You can start from [this glitch template](https://glitch.com/edit/#!/accurate-mitten?path=public/my-element.html:2:0) as a starting point and link it in the issue template under "Live Demo".

**Comment by napa3um** [comment]
https://glitch.com/edit/#!/join/f5609b9f-3be7-4859-b8a0-feaf17b60752

**Comment by napa3um** [comment]
commentsByAccount( account.id, comments, **comments.*** ) worked good, this is my mistake.
