### ISSUE TITLE
Cannot I disable eventDataCache?

### ISSUE THREAD

**Issue by Eymerich01** [Polymer/polymer#4693]
It's very difficult to debug leak memory using Polymer. Chrome debug show a lot of memory stored in eventDataCache. Cannot I disable it to better debug?

the row :
useCache: Polymer.Settings.eventDataCache || !Polymer.Settings.isIE

suppose that in chrome useCache is always true if I not  set also Polymer.Settings.isIE to true . is it correct?

- Polymer: v1.9.2

**Comment by kevinpschaaf** [comment]
Sorry, the `Polymer.Settings.eventDataCache` option is an "opt-in to using cache for all `fire`'s), rather than an "opt-out" setting.  In 2.x we removed event caching altogether in 2.0 since we managed to remove virtually all notification event firing from the hot path of initial render.

For testing (to help isolate what is leaking), you could consider monkey-patching `_getEvent` _just for testing_ to always pass `useCache` as `false`.  e.g.

```html
<link rel="import" href="bower_components/polymer/polymer.html">
<script>
var origGetEvent = Polymer.Base._getEvent;
Polymer.Base._getEvent = function(type, bubbles, cancelable, useCache) {
  origGetEvent.call(this, type, bubbles, cancelable, false);
}
</script>
```

If you determine it's the `detail` object's payload from the reused event that's "leaking" (it shouldn't leak in the sense of ever-increasing memory usage, but it will hold the previous `detail` event per event type), we could consider null'ing the `detail` object after use, although this would change the contract of `fire` in the case a user did set `eventDataCache` to `true`.  The only other option would be to add an additional "opt-out" setting.  Please let us know what you find.

**Comment by Eymerich01** [comment]
Thank for you response 
I have  used your patch with a little correction ...
_return_ origGetEvent.call(this, type, bubbles, cancelable, false);
and now i haven't eventDatacache in Debug. 
By the Way i think that the "fire" leak memory. I have used it to send a lot of data at another component and   with debug i see the memory not deallocated on detach.
The same data set with receiver.set("mydata",data") is deallocated on detach of component. 
Of course i used correct pattern listen unlisten to receive fire.

**Comment by Eymerich01** [comment]
Ok sorry, forgot my last sentence I have uses console.log(data) on listener and them aren't GC'ed.
All it's ok!
Thx best regards :)

**Comment by TimvdLippe** [comment]
@Eymerich01 Do I understand correctly that your original issue has been resolved using the explanation in @kevinpschaaf 's comment?

**Comment by TimvdLippe** [comment]
Closing this per above comment. Feel free to reopen if you are still encountering issues.
