### ISSUE TITLE
Statement support in data bindings - enhancement

### ISSUE THREAD

**Issue by microo8** [Polymer/polymer#4700]
### Proposal
Adding support for javascript expressions or statements in data bindings like in [QML](http://doc.qt.io/qt-5/qtqml-syntax-propertybinding.html).

Not just function calls eg:

```html
<my-elem>[[_myConcat(myAttr1, " - ", myAttr2)]]</my-elem>
```

But also valid js statements, therefore you don't have to create every function on your element class eg:

```html
<my-elem>[[myAttr1 + " - " + myAttr2]]</my-elem>
```

or: 
```html
<button style="display: [[_isAdminDisplayBlockOrNone(isAdmin)]];">Admin login</button>
```

to: 
```html
<button style='display: [[isAdmin ? "block" : "none"]];'>Admin login</button>
```

Also adding support for using builtin js objects like `Math` and `Date`. And calling global functions eg:

```html
<lint rel="import" href="an3thPartyLibrary.html">
...
<template>
    <div>[[an3thPartyFunction(myAttr)]]</div>
</template>
```

This would simplify the elements interface and the speed of coding.

The implementation wouldn't be difficult, because polymer data bindings is already watching the change events on attributes, but now it would instead of calling the function, call `eval` on the entire expression.

**Comment by web-padawan** [comment]
This used to be supported as of 0.5 but was removed intentionally due to performance issued, caused mostly by parsing data bindings in runtime AFAIK. Another reason is that having too much logic in templates is not a good idea. Personally, I took part in migration of a big project from 0.5 to 1.x and I once missed a part of a VERY long line having multiple ternary operators like so, huh.

There is a [polymer-expressions](https://github.com/Polymer/polymer-expressions/tree/2.0-preview) repo though, which has a `2.0-preview` branch and might be used as an optional mixin in the future, at least as I remember from conversation with @justinfagnani

**Comment by ma499** [comment]
The Polymer Expressions repo has now been archived. are there any new initiatives or thoughts on this request? I agree that we shouldn't have too much logic in templates but it seems overly-restrictive to completely disallow simple JavaScript expressions.

**Comment by justinfagnani** [comment]
Since we're not going to change Polymer's expression system, I'll close this now.
