### ISSUE TITLE
style include modules should be prepended before text in style

### ISSUE THREAD

**Issue by azakus** [Polymer/polymer#4770]
Somehow https://github.com/Polymer/polymer/issues/2357 might have appeared again in 2.x.

**Comment by pdesjardins90** [comment]
So to reiterate this [conversation](https://twitter.com/pdesjardins90/status/893535981571321856), style modules in Polymer 2 are now appended **after** local shadow dom styles in an element, which can override those styles when css specificity is the same. 

I realized that while migrating my app's elements, which all contained a css reset imported as a style module. My tweet was because I thought it was a normal new behavior (it's not a bug it's a feature right? 😛 )

While you guys fix that behavior, as a workaround, I'm trying to override the way Polymer templates get loaded following @kevinpschaaf 's [snippet](https://github.com/Polymer/polymer/issues/4683). I'm going on vacation next week though so more news on that workaround when I get back, for folks having the same problem.

**Comment by pdesjardins90** [comment]
Haven't found the part that stamps style modules yet, but came across the docs of [Node.insertBefore()](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore), awfully sounds like it has something to do with the bug!

> If referenceNode is null, the newNode is inserted **at the end** of the list of child nodes.

**Comment by azakus** [comment]
Hmm, I made a style import and it appears to be placed before the elements' styling, as expected: http://jsbin.com/duwewuq/edit?html,output

Is there a different setup you would have? Do you mean `<link rel="import" type="css">` style imports?

**Comment by azakus** [comment]
So, it looks like the ordering problem is only for `<link rel="import type="css">` style imports:

Polymer v1: https://mercury-grenade.glitch.me/
Polymer v2: https://colorful-chalk.glitch.me

**Comment by azakus** [comment]
Ah, it is more subtle. In 1.x, the ordering of `<template><style></style></template>` and `<link rel="import" type="css">` mattered, whereas in 2.x the css import is always last.
