### ISSUE TITLE
Start using /bower_components instead of ../bower_components

### ISSUE THREAD

**Issue by maria-le** [Polymer/polymer#4772]
I ask the element writers to begin using `/bower_components/path/to/element`  instead of `../bower_components/path/to/element` in their imports and examples because the former is a more universal way to access the `/bower_components` directory. Sometimes Polymer users locate their elements that need to import a bower element multiple levels deep in the file tree. When that happens, we have to go back and add more `../` in front of each import path. The universal solution to this is to use `/` in the first place since no one will ever be changing the location of the `/bower_components/` directory relative to the root.

**Comment by spyhole** [comment]
the npm  is better that replace bower installation.

**Comment by maria-le** [comment]
@spyhole: Please elaborate.

**Comment by spyhole** [comment]
the core team has doing that.

**Comment by web-padawan** [comment]
@maria-le you should take into account several things:
1. users can rename `bower_components` in `.bowerrc`, e. g. we called it `vendor`  to save some bytes (10 bytes per each). This makes sense due to `assetpath` attributes appearing in bundled code for each component and containing that folder name
2. that directory might NOT be located under project root, and users might NOT use `rootPath`
3. tools like `polyserve` resolve relative imports properly, but absolute mighg break them etc.

**Comment by jsilvermist** [comment]
@maria-le This pattern should be avoided as the element would break on any subdirectory deployment.

**Comment by LasaleFamine** [comment]
@maria-le Polymer and Web Components in general should use NPM (or Yarn) as package manager since [Bower is deprecating itself](https://bower.io/). This issue could be invalid when this will happen (and I hope soon).

**Comment by TimvdLippe** [comment]
> since no one will ever be changing the location of the /bower_components/ directory relative to the root.

This assumption is sadly incorrect. There are various projects that move the bower_components folder. Closing this issue as this is not something we are going to change.
