### ISSUE TITLE
<dom-bind> converts <template is="dom-if"> to <dom-if> and messes up table's cells

### ISSUE THREAD

**Issue by tanin47** [Polymer/polymer#4796]
### Description

I've found that `<dom-bind>` converts `<template is="dom-if">` to `<dom-if>`; That messes up the table's cells. 

#### Live Demo

The example is here: https://jsfiddle.net/qjgxkyj2 -- please notice that `<td colspan="2">` does __not__ span over 2 cells correctly. -- if we inspect the table cells, there are a bunch of `<dom-if>`.

However, if we use `<template is="dom-bind">`, everything works perfectly. The example is here: https://jsfiddle.net/5an34xz0/ -- if we inspect the table cells, there is __no__ `<dom-if>`.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v2.0.2
- webcomponents: v1.0.8

**Comment by web-padawan** [comment]
See (#4704 (comment))[https://github.com/Polymer/polymer/issues/4704#issuecomment-310155087]

**Comment by tanin47** [comment]
The comment doesn't work for me. In the example (https://jsfiddle.net/qjgxkyj2/), `<template is="dom-if">` is used... though its parent is `<dom-bind>`.

I have to use `<dom-bind>` because it's a glue between the backend and Polymer's elements. Here's how I use it:

```
<dom-bind id="page">
  <template>
    <our-page data="[[data]]"></our-page>
  </template
</dom-bind>

<script>
  document.getElementById('page').data = <some json data written when rendering HTML>;
</script>
```

Please let me know if there's a workaround.

**Comment by azakus** [comment]
Your example is slightly incorrect: The `<template is="dom-if">` elements do not actually work in your first example. Here's a fork of your first example where the `firstCell` and `thirdCell` properties are defined and set to `true`, yet never appear: https://jsfiddle.net/qfjq8rvg/

In the second example you have operational `dom-if` elements, which is why they appear in the element. Dom-if works by inserting the contents of the template it is given above itself, and therefore will always show the behavior you are seeing.

You should probably use a binding to the `hidden` attribute instead.

**Comment by tanin47** [comment]
Hmm... this is strange. `firstCell` and `thirdCell` do show up when they are `true`. Here's the example (https://jsfiddle.net/9vv4t9j9). Here's the snippet:

```
<base href="https://polygit.org/polymer+polymer+v2.0.2/webcomponentsjs+webcomponents+v1.0.8/components/">

<script src="webcomponentsjs/webcomponents-lite.js"></script>
<!-- Load the Polymer.Element base class -->
<link rel="import" href="polymer/polymer.html">

<dom-bind id="page">
  <template>
  <table cellpadding="2" cellspacing="2" border="1">
    <tr><td colspan="2">Span over 2 cells</td></tr>
    <tr>
      <template is="dom-if" if="[[firstCell]]">
        <td>First cell</td>
      </template>
      <td>Second cell</td>
      <template is="dom-if" if="[[thirdCell]]">
        <td>Third cell</td>
      </template>
      <td>Fourth cell</td>
    </tr>
  </table>
</template>
</dom-bind>
<script>
	document.getElementById('page').firstCell = true;
	document.getElementById('page').thirdCell = true;
</script>
```

Here's the screenshot:

![screenshot from 2017-08-18 09 44 00](https://user-images.githubusercontent.com/494417/29468605-d2763462-83f9-11e7-9014-d706b8fe15b6.png)

> You should probably use a binding to the hidden attribute instead.

This workaround works. Example: https://jsfiddle.net/p5bxwe51/  --- thank you for suggesting it.

**Comment by azakus** [comment]
I think in this case there's not a lot we can do, as `<table>` is a somewhat unique element in the parser requiring certain types of elements to be children.
In that case the `hidden` attribute should always be the preferred way to control visibility.

`dom-if` is better suited to larger sections of elements that can avoid being fully set up on the first boot (where the `dom-if` is false by default).

**Comment by sorvell** [comment]
Just want to note that there is a legit issue here, but we don't have a good solution right now so your best bet is what @azakus suggested.

Specifically, we do inject the `dom-if` element into the `table` and this is basically ok since we do this after parsing (where it is disallowed), but it does not interact with `colspan` correctly. You can see this here: http://jsbin.com/sevofuteru/edit?html,output

**Comment by tanin47** [comment]
I want to note that it works with PolymerJS 1. I encountered this issue because I was migrating to PolymerJS 2.

**Comment by TimvdLippe** [comment]
The colspan issue should be fixed on master, so please try to load master in your application and see if it is fixed.

**Comment by tanin47** [comment]
Verified. It works. See: https://jsfiddle.net/9rtq7czd 

Thanks @TimvdLippe!
