### ISSUE TITLE
Angular like formatters

### ISSUE THREAD

**Issue by fincha** [Polymer/polymer#4810]
### Description

I thinking of some problems I faces in my development, so I thought maybe some one else is interested in a feature like a angular one

ex:
> {{ item | 'currency' }} 

so you can format your output the way you wish, also supporting custom functions.

I plan to implement this for the version 3

**Comment by web-padawan** [comment]
This existed as of 0.5 in the form of [polymer-filters](https://github.com/addyosmani/polymer-filters) and was deprecated due to performance reason. Of course you can do something like this now as a mixin, see also [polymer-expressions](https://github.com/Polymer/polymer-expressions/tree/2.0-preview) for some inspiration.

BTW @justinfagnani, could you tell what is a status of `polymer-expressions` now when your focus is [lit-html](https://github.com/PolymerLabs/lit-html)?

**Comment by TimvdLippe** [comment]
We have had similar requests, for example see https://github.com/Polymer/polymer/issues/4038#issuecomment-282438033 You can override `_parseBindings` to implement this functionality. In the future, solutions like `lit-html` can streamline this even more, by taking advantage of the direct JS context when evaluating templates.
