### ISSUE TITLE
blank frames when using slots.

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/polymer#4811]
### Description
I have an app in which in which I use a slot to pass an image into the light dom of an element.

In index.html, webcomponentsloader is lazy loaded on 'load', and my-app is lazy loaded on WebComponentsReady.

I don't know where the actual problem might be...it might be with the technique I'm using, but I ran it by both @TimvdLippe and @sorvell at the Polymer Summit and they couldn't explain it either. It might be in polymer or chrome.

The problem does seem somewhat unpredictable...ie sometimes the blank frames don't appear. It is, however, very noticeable in my real app. It's surprising how short a time a flicker can be before it is noticeable :/

#### Live Demo
Not live, but I've made an example here:

https://github.com/davidmaxwaterman/light-dom-demo

#### Steps to Reproduce
1. clone the above repo
2. run `polymer serve&`
3. open a web browser tab on `localhost:8081` or whatever URL it says
4. open dev tools
5. switch to 'performance' tab
6. click on the 'start profiling and reload page' button, or ctrl-shift-e (on windows)

#### Expected Results
I expect no blank frames

#### Actual Results
I get blank frame around the FMP point.

<img width="471" alt="blank_frame" src="https://user-images.githubusercontent.com/975698/29685008-f443c6e2-890b-11e7-967b-b2f5ea4d9af3.PNG">

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: "2.0.1"
- webcomponents: 1.0.8

**Comment by davidmaxwaterman** [comment]
I should add that, in my real app, the blank frame last for almost 400ms, which is quite noticeable. The image does seem to jump up a bit too in my latest version, which is also unexpected.

**Comment by davidmaxwaterman** [comment]
Any thoughts on this?

**Comment by sorvell** [comment]
Sorry for the delay on this. It's possible that the way elements that are animating are rendered when distributed is confusing the situation. If there's a css animation/transition underway when distribution occurs, that animation will immediately complete (here's [an example](http://jsbin.com/buguzec/1/edit?html,output)).

In addition, when an element is distributed it may move position on screen (here's [an example of that](http://jsbin.com/viyogak/1/edit?html,output)).

Finally, if there's a delay that allows for paint between when a shadowRoot is created (via `attachShadow`) and when nodes (including a `slot`) are added to it, then a "blank" frame could appear. In a typical Polymer element this is unexpected since element DOM is [immediately added](https://github.com/Polymer/polymer/blob/master/lib/mixins/element-mixin.html#L587) to the shadowRoot.

Hope that helps.

**Comment by kevinpschaaf** [comment]
Since the repro is running on native Shadow DOM (not polyfill) and I don't see how the behavior being seen would be specific to Polymer, we're going to go ahead and close this.  If there's a bug here related to animations being reset when distribution occurs, it would be a Chrome bug.

If you can update the repro to find an issue specific to Polymer's handling, please re-open a new bug.  Thanks.
