### ISSUE TITLE
Polymer/shadyCSS doesn't attach polyfilled CSS node when element is using light DOM 

### ISSUE THREAD

**Issue by ergo** [Polymer/polymer#4824]
Hello,

There seems to be a problem with CSS not being added to elements when using Firefox and using elements that operate with light DOM.

    _attachDom(dom) {
      this.appendChild(dom);
    }

#### Live Demo
http://plnkr.co/edit/KwXzA2A29BCxQxJg0jNw?p=preview

#### Steps to Reproduce
Run the demo

#### Expected Results
Same behavior as with shadow dom enabled OR what chrome does - elements get styled correctly.
"red/blue colored"  elements should have proper colors.

#### Actual Results
Elements are not being styled at all

### Browsers Affected

- [x ] Firefox + probably others that use polyfill

**Comment by ergo** [comment]
Any news on this?

**Comment by sorvell** [comment]
Can acknowledge this issue. Currently the Polymer code around integrating ShadyCSS is assuming we're stamping into ShadowDOM. It's probably going to be a separate issue from #4809 since the change will likely be in Polymer rather than ShadyCSS. 

To fix this we'll probably need to move the template scope shimming into `_attachDom`.

**Comment by azakus** [comment]
This is actually a bit more complicated that just moving `ShadyCSS.prepareTemplate` into `_attachDom` because that would lead to `ShadyCSS.prepareTemplate` removing or modifying the `<style>` in the template after the metadata for data binding has been processed.

Kicking this back to @sorvell to do a deeper look

**Comment by ergo** [comment]
I'm a bit confused how come this works in chromium for me? I'm force enabling polyfills, shouldn't it be broken too.

**Comment by ergo** [comment]
Also - is there any workaround I can use right now to fix production application before this gets fixed?

**Comment by ergo** [comment]
@azakus @sorvell any ideas? I saw that 2.1.0 is tagged today, and I won't be able to deploy anything in production till I can somehow work around this problem.

**Comment by arthurevans** [comment]
@sorvell @azakus I thought that this was done on purpose. If you add styles inside the light DOM, they'll leak out to affect parent elements, right? This seems like a misfeature.

In the docs, we explicitly say not to do this:

"A template stamped into light DOM shouldn't contain any <style> tags. Styles can be applied by an enclosing host element, or at the document level if the element isn't used inside another element's shadow DOM."

https://www.polymer-project.org/2.0/docs/devguide/dom-template#stamp-templates-in-light-dom

**Comment by ergo** [comment]
@arthurevans I think it is expected that styles added inside light DOM leak to main document.
I think an equivalent of vue's styled components would be easy to create with that functionality https://vuejs.org/v2/guide/single-file-components.html.

My main rationale for light DOM using elements is a scenario where I have to wrap libraries that don't work properly inside shadow DOM (until they get patched) - like QuillJS or dragula. So my application entry node and view nodes don't use shadow.

**Comment by sorvell** [comment]
Sorry for the delay on this. @arthurevans is essentially correct. ShadyCSS is intended to mirror the capabilities of native Shadow DOM styling and therefore we don't really want to encourage its use for styling children of an element like this.

That said, the use case here is understandable. For this type of scenario, you can implement your own cooperative styling system like ShadyCSS does (adding "scoping" classes to elements and the stylesheet). The code for this static scoping is here and is relatively self contained (https://github.com/webcomponents/shadycss/blob/master/src/style-transformer.js).

Polymer does template preparation in the static `_finalizeTemplate` method. This is called just once when the first instance of the element is created. You can implement this method and override how styling is done.

All that said, this is a bit cumbersome since ShadyCSS does a lot of the heavy lifting here already. [Here is a workaround](http://plnkr.co/edit/1GXpmJHayP540eOrHKyf?p=preview) you can use that's easier than rolling your own, but it's not guaranteed to function since it makes use of the private scoping class ShadyCSS uses.
