### ISSUE TITLE
Polymer News ?

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/polymer#4859]
Again a question from me about News:

- Is there a Timeplan for the Final Polymer 3 Release? (1 Month, 3 Months, 1 Year?)
- Does anyone answer questions on https://github.com/Polymer/project?
- Will the Roadmap on https://github.com/Polymer/project be refreshed?

**Comment by wmginsberg** [comment]
Yes! I meant to get around to this this week, but a few things came up. I'll update

**Comment by jogibear9988** [comment]
thx.

and one more:
- what is planed for shared styles between components?

**Comment by web-padawan** [comment]
BTW it would be nice to also provide some insight from the Chrome dev team regarding following questions:

+ HTML imports end of support date
+ Custom elements v0 end of support date
+ Shadow DOM v0 end of support date

As we know from [this list](https://github.com/abdonrd/PolymerProjects#google), lots of Google projects still use 1.x and it would be nice to have at least year, e. g. in the same manner as Adobe recently [announced](https://blogs.adobe.com/conversations/2017/07/adobe-flash-update.html) end of life for Flash in 2020.

I'm asking because Polymer is also used by enterprise projects which obviously cannot be "rewritten from scratch every six weeks" (c)

I guess that since 2.0 will be still around at least 1 year or so, HTML imports native support might stay with us longer than e. g. Shadow DOM v0 (which is not used by default as of 1.x)

**Comment by petr001** [comment]
Any news on releasing Polymer 3? Some new features would really help us, so basic time-frame would be useful.

**Comment by web-padawan** [comment]
@petr001 as of now, there are two blockers AFAIK:
1. ES modules are still behind  the flag in Firefox and Edge, see [here](http://caniuse.com/#feat=es6-module)
2. [dynamic imports](https://hospodarets.com/native-ecmascript-modules-dynamic-import) are not there.

So, it is unlikely that Polymer 3 will be released soon. Since Polymer team schedule is kinda like event-oriented (Google IO / Polymer summit), we should wait at least until IO 18 I guess.

**Comment by jogibear9988** [comment]
No News?

**Comment by jogibear9988** [comment]
@wmginsberg any news? ;-)

**Comment by ergo** [comment]
@web-padawan I think I've read that chrome team does not remove features unless there is special need for that. You can expect web components v0 will be here for years, since they don't conflict with v1.

**Comment by jsilvermist** [comment]
@ergo Actually there is at least one conflict that I know of, which is `document.createElement()`'s 2nd argument taking a `string` for options in v0, and an `object` in v1.

For more info, see discussion and links in Polymer/docs#1705.

**Comment by jogibear9988** [comment]
Info: @Polymer3 is be expected early next year (mentioned here: https://www.youtube.com/watch?v=Wu2GCRkDecI)

**Comment by jogibear9988** [comment]
@wmginsberg maybe you will find some time? ;-)

**Comment by ergo** [comment]
Any news on the roadmap?

**Comment by TimvdLippe** [comment]
Our roadmap has now been updated per https://github.com/Polymer/project/pull/41 Check it out at https://github.com/Polymer/project/blob/master/Roadmap.md It also contains a link to [this Polymer 3 timeline](https://www.youtube.com/watch?v=JH6jEcLxJEI&feature=youtu.be&t=21m8s).

I will also ask the team what the policy is for answering questions on Polymer/project. Most of the questions should be addressed, but we will get to that if some are not.

**Comment by TimvdLippe** [comment]
Please create a new issue. This issue has been closed for more than 2 years.
