### ISSUE TITLE
Changing binding property while dom-if's if is false throws an error

### ISSUE THREAD

**Issue by 7nights** [Polymer/polymer#4877]
### Description
Recently I found a problem when I use dom-if and lazy-pages:

```html
<lazy-pages app="{{app}}">
  <template is="dom-if">
    <my-page app="{{app}}"></my-page>
  </template>
</lazy-pages>
```
When I try to change the 'if' attribute of dom-if following changing the property of `app`, an error occurs:
![image](https://user-images.githubusercontent.com/3193621/31369686-b1f42530-adb8-11e7-896e-b89b4c393e19.png)

And another problem is when dom-if's if property is false, changing a data-binding will not actually reflect on the elements which are inside the dom-if element. For example, look at the following code:

```html
<dom-module id="lazy-pages">
  <template>
    [[app.name]]
    <slot></slot>
  </template>
</dom-module>

<dom-module id="my-page">
  <template>
    [[app.name]]
  </template>
</dom-module>

<lazy-pages id="outer' app="{{app}}">
  <template id="inner" is="dom-if">
    <my-page app="{{app}}"></my-page>
  </template>
</lazy-pages>
```

Run the following code:
```
inner.if = false;
outer.set('app.name', 'a new name');

// will result in:
<lazy-pages>
  #shadow-root
    <text>a new name</text>
    <my-page>
      #shadow-root
        <text>the old name</text>    <--------- value not updated
    </my-page>
    ...
```

Is it intended to be like this?

But if you set it's `if` property back to `true`, those data still remain outdated...

#### Live Demo

http://plnkr.co/edit/uQ5OOiJKWe0nBpd7QKqM?p=preview

#### Steps to Reproduce

Open dev-tools and try to click the DOM 2 times and you'll see the error shown in dev-tools.
Strangely, if I give an id to that dom-if element, everything will work fine...

Second issue's live demo: http://plnkr.co/edit/T6GRQGChLe8F13lklTWR?p=preview

#### Expected Results
No error is throw.

#### Actual Results
Error is thrown.

### Versions

- Polymer: v2.1.1

**Comment by ernsheong** [comment]
Related JSBin: https://jsbin.com/xewuraw/edit?html,output for issue https://github.com/TimvdLippe/iron-lazy-pages/issues/62

**Comment by TimvdLippe** [comment]
The problem is that [`this.__dataHost`](https://github.com/Polymer/polymer/blob/47d1b2601348b9866e4b5a215085eef835df1f18/lib/elements/dom-if.html#L238) is undefined. However, this property is no where defined in `dom-if`. Instead, it is defined in `Templatize`. If I change that line to `this.__instance._setPendingProperty(prop, this.__instance.__dataHost.__dataHost[prop]);` (per https://github.com/Polymer/polymer/blob/47d1b2601348b9866e4b5a215085eef835df1f18/lib/utils/templatize.html#L210) it is working as intended.

I am not sure what the intention was, as updating the line does not fail any test. This would indicate no test covers this path or the update does not fail existing tests.

**Comment by ernsheong** [comment]
> Strangely, if I give an id to that dom-if element, everything will work fine...

This is the workaround. Thanks @7nights !

**Comment by justincy** [comment]
> And another problem is when dom-if's if property is false, changing a data-binding will not actually reflect on the elements which are inside the dom-if element. For example, look at the following code:

I just ran into this too. I can't quite tell if it's a bug but I think it ought to be. 

This behavior didn't exist in 1.x. It was [introduced in 2.x](https://github.com/Polymer/polymer/issues/2712#issuecomment-265568366) to accommodate the scenario of using `restamp` where you wouldn't want changes to be propagated. However it _only_ makes sense when using `restamp`. If you're not using `restamp` then you want changes to be propagated, otherwise when the `if` condition reverts to true, any bindings inside the `dom-if` are now activated even though they're stale (because they missed all data changes when deactivated). That's definitely not what we want.

**Comment by justincy** [comment]
Looks like I was wrong. When `if` is false, property changes are cached and propagated again when `if` changes back to true. I guess my case is more complex and I'm running into a different issue.
