### ISSUE TITLE
Removing a  MethodEffect created dynamically ?

### ISSUE THREAD

**Issue by vdegenne** [Polymer/polymer#4884]
Let say I have this custom element, I try to "link" it with the centralized data.

```javascript
  class CarCard extends AppData(Polymer.Element) {
    /* the AppData mixin only provides a global object
       centralizing data ("appdata" object) */

    static get is() { return 'car-card' }

    static get properties() { return {

      carId: {
        type: Number,
        observer: '_onCarIdChange'
      }
    }}

    static get observers() { return [
       `_onCarChange(appdata.cars.${this.carId}.*)`
       /* this won't work because this is a static function
          and properties get initialized after observers.
          Solution : Dynamic Observers (see "_onCarIdChange" below) */
    ]}

    _onCarChange(car) {
      console.log(`A property in car number #${this.carId} has just changed.`);
    }

    _onCarIdChange() {
      /* solution : */
      this._createMethodObserver(`_onCarChange(appdata.cars.${this.carId}.*)`);
      /* here we need to remove the old observer if any */
    }
  }
```

I don't know if this is a good idea to use `_createMethodObserver` directly (the leading underscore makes me think like that) but I can't think of another solution in this case.

I struggle to find the method/api to remove an observer created dynamically. Does someone know how I can do that ?

**Comment by TimvdLippe** [comment]
Yes you can definitely use `_createMethodObserver`, as this is part of our public API. The reason it starts with an underscore is to indicate it is only intended to be overridden by a subclass, but not intended to be invoked from an element user perspective.

You should be able to remove the effect with `this._removePropertyEffect`, however it seems the the implementation is pretty gnarly. The problem is that you have no access to the actual effect object being pushed into the internal data store. We would need to investigate how easy it would be to update this API.

**Comment by fooloomanzoo** [comment]
Why would it not be possible for `_createMethodObserver` and accordingly `_addPropertyEffect` to just return the effect and make it removable by calling `_removePropertyEffect`?

**Comment by TimvdLippe** [comment]
@fooloomanzoo Because underlying `createMethodEffect` is called, which creates effects for every argument. This means that there are a lot of effects to be returned. Instead we should consolidate this data somehow in a nice manner and make `_removePropertyEffect` able to handle that
