### ISSUE TITLE
Suggestion for Workflow in Polymer3 

### ISSUE THREAD

**Issue by OmidHekayati** [Polymer/polymer#4893]
* **set V3 as breakable version.**
as v3 release officially everyone must agree that they must use older version or new one!! there is no hybrid!! Like python 2 and 3!

* **deprecate and remove all non standards features like `html import`, `@apply`, `dom-module`, ...**
I think html import is bad idea from start. we must not use DOM for anything than user-interface markups. `dom-module` is born for problem that html import born it!! `dom-module` use DOM for nothing!!

* **don't use DOM for anything than user-interface markups.**
for example in iron-icons we use DOM just for add some markup to js variable as container (iron-meta) for feature uses!! We can easily have a simple function for adding svg markup from string to icons container.

* **Make built-in element as behavior of polymer**
Elements such as `dom-repeat` must be part of logic not UI. They have many problem e.g. in grid or flex layouts if you forget to set display:none because they are part of DOM!!
It is easy to use same feature instead of this:
```html
<dom-repeat items="[[apps]]" as="app">
   <template>
   </template>
</dom-repeat>
```
use this model and do some logic in element class:
```html
<template id="appsDetails">
</template>
```

I know some of these idea will apply in 3.0-preview branch and other developers can add more idea.

**Comment by web-padawan** [comment]
It's unlikely that 3.0 will have so much breaking changes since it is supposed to be converted by [modulizer](https://github.com/Polymer/polymer-modulizer), same for official elements.

It is meant to make migration as smooth as possible. The 0.5 -> 1.0 migration was painful in the way you describe, and our team spent a couple of months to cope with it for just the one project.

I believe that @rictic who used to be a "Polymer upgrade guy", as he told us in his [Summit 16 talk](https://www.youtube.com/watch?v=iI3G-tzbC_Q), could explain this pain much better 😃 

Maybe 4.0 will finally drop lots of legacy stuff. Until then, you could rely on 2.0 and write your own elements set in order not to rely on `@apply` and hybrid syntax anymore, see [vaadin](https://github.com/vaadin/vaadin-core) elements for example.

**Comment by TimvdLippe** [comment]
In general, Polymer 3 elements will not be hybrid in the sense that you can mix and match Polymer 2 and 3 elements. The technical reason is that we are switching from HTML imports to ES modules, which means we have no guarantees of deduplication of the same resources. E.g. if you import `polymer/polymer` with an HTML import (with the `.html` extension), this URL is not the same as importing `@polymer/polymer/polymer.js`. As such, you would get a duplicate definition of Polymer, which crashes.

However, since we are only switching the loading mechanism, the "old" Polymer 1 syntax of a Polymer element (e.g. with `Polymer({})`) will still work. This means that you can still declare an element using the old syntax in Polymer 3, as merely the loading mechanism changed.

Per above comments, we will not run into the Python 2 vs 3 problem. However, since we are only changing our loading mechanism, we will not introduce any other breaking changes. This means that features like `@apply` and `<dom-{module, repeat}>` will still be there. We would reconsider these features in a future version of Polymer, but we have not started these discussions.

If you would like to perform your logic purely in JavaScript, check out https://github.com/polymerlabs/lit-html which can generate templates similarly to what Polymer does nowadays, but that in a JavaScript context. That way you do not require `<dom-{if, repeat}>`, but use a regular JavaScript if` and `for-loop`.
