### ISSUE TITLE
Data binding in <style> tags breaks after upgrading polymer version

### ISSUE THREAD

**Issue by pineapplemachine** [Polymer/polymer#4899]
After upgrading from polymer 2.1.0 to 2.1.1 or 2.2.0, data bindings in <style> tags no longer function. For example,

``` text
.some-class {
    some-property: [[someValue]];
}
```

No longer replaces the string "[[someValue]]" with whatever the intended data was.

This seems to be related to https://github.com/Polymer/polymer/pull/4841, which removed data bindings in <style> tags. (Without providing a workaround or better pattern!)

#### Live Demo

http://jsbin.com/metupupude/edit?html,output

#### Expected Results

Data bindings in CSS should be replaced with the data they reference.

#### Actual Results

The CSS ends up containing the literal bindings, e.g. "[[someValue]]".

### Browsers Affected

Reproduced with both Chrome 61.0.3163.100 and Safari 11.1 release 42.

### Versions

This issue applies to Polymer 2.1.1 and 2.2.0.

**Comment by TimvdLippe** [comment]
Bindings in CSS stylesheets was never intended to work, but accidently worked. If you want to use databindings, use https://www.polymer-project.org/2.0/docs/devguide/custom-css-properties#style-api to dynamically update the value of a CSS variable.

**Comment by pineapplemachine** [comment]
I have found bindings in CSS to be an extremely useful feature! What was the rationale for not supporting this?

**Comment by guzmanpaniagua** [comment]
There is a lot of poblems mixing js or binding with styles, some one loves this other hate it.

personaly i prefer get my css clean of logic because with single responsability principle it is easy to mantain the code.

if you want use variables and functions in css, may be you could archive the same with scss and not use  binding inside your css.

most of the scenarios can be fullfiled adding classes with binding to the html and having the diferent states helping you to have clear concern separation in the components.

here is an example 
https://codepen.io/guzmanator/pen/ZXdMgY

I know i did not answer your question, you find a "way" of get the job done, and now some body just decide to get it from you, I was only trying to offer you other choices to get the same results without using binding in css

**Comment by azakus** [comment]
Data binding into CSS is unsupported because of all the wonderfully complicated transformations required to polyfill `@apply`, CSS Custom Properties, and ShadowDOM style scoping.

**Comment by TimvdLippe** [comment]
Closing this issue per above comments. For compatibility reasons (and in general not running into issues with the polyfill) we advise you to use CSS variables instead. It is unfortunate we didn't discover this bug earlier, to discourage its use, but we retroactively had to fix it. Using CSS variables should be rather straightforward in conjunction with `this.updateStyles`.

Let us know if you are running into issues when migrating off the bindings and we can help you out!
