### ISSUE TITLE
Polymer 2.2.0 not working in IE11

### ISSUE THREAD

**Issue by EnzoEghermanne** [Polymer/polymer#4900]
### Description
None of the code samples from https://www.polymer-project.org/2.0/start/quick-tour work on IE11.

#### Live Demo
http://plnkr.co/edit/Q4E8zO?p=preview
http://plnkr.co/edit/buPxSJ?p=preview

#### Steps to Reproduce
1. Open any of the plunkers in IE11
2. Check the console output (10 errors)

#### Expected Results
The component renders in IE11.

#### Actual Results
![errors](https://user-images.githubusercontent.com/6171742/31962754-b8a3dab4-b8fe-11e7-94ea-8e1755013729.png)

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [X] IE 11

### Versions
- Polymer: v2.2.0
- webcomponents: v1.0.0-rc.5

**Comment by TimvdLippe** [comment]
There seem to be 2 issues:

1. You are not transpiling. As IE11 does not support ES6, you have to transpile. `polymer serve` does this automatically for you. Else you have to run `babel` or use `polymer build` with `es5-bundled`
2. Your polyfill version is quite old. Please upgrade to [1.0.17](https://github.com/webcomponents/webcomponentsjs/releases/tag/v1.0.17)

**Comment by azakus** [comment]
What @TimvdLippe says is correct, IE 11 requires transpiling your code to ES5. This can be done with the [Polymer command line tool](https://github.com/polymer/polymer-cli), or any number of other tools.

**Comment by arthurevans** [comment]
These are the samples in the quick tour, so this should really be a doc bug.

1) Currently we don't have a good way to transpile the plunkers for IE11. We're working on a fix for that.

2) But we can (and should) add a note that the samples don't work on IE11, because they need to be transpiled.

3) And we should update the plunkers to use a released version of the polyfill. (The polyfill line in all of these plunkers should probably just be: `<script src="https://polygit.org/components/webcomponentsjs/webcomponents-loader.js"></script>`)

**Comment by arthurevans** [comment]
This issue was moved to Polymer/docs#2384
