### ISSUE TITLE
HTML import fails silently on Safari 11

### ISSUE THREAD

**Issue by Tanbouz** [Polymer/polymer#4905]
#### Steps to Reproduce

Use polymer-cli to create a new polymer starter kit app

Comment out lazy import and import `my-view` in `my-app.html` like so:

```
<link rel="import" href="my-view1.html">
<!-- <link rel="lazy-import" href="my-view1.html"> -->
```

polymer serve - you should get 404 on the homepage using Safari. Navigating to another page and coming back to view 1 should make it work. Refresh to break it again.

#### Expected Results
Consistent behavior. Works fine on Chrome & Firefox.

#### Actual Results
404 page on safari using polymer cli starter kit

### Browsers Affected

- ✅  Chrome (62.0.3202.75)
- ✅  Firefox (56.0.2)
- ❌  Safari (11.0 (13604.1.38.1.6))

### Versions
- polymer 2.2.0
- webcomponentsjs 1.0.17

**Comment by arthurevans** [comment]
That's pretty odd... Especially since the lazy-imports are just there to appease the linter.

I think the importHref call is erroring here because the import link already exists in the document. I'm not sure why it only happens on Safari.

If you insert a breakpoint and step through this with the debugger, you'll see the correct page being displayed, then the 404 page after the importHref error callback is invoked.

@azakus @sorvell any clue why this would happen?

**Comment by NeilujD** [comment]
Any new about this ?
Does anyone can suggest a workaround ?

**Comment by arthurevans** [comment]
The workaround is to either a) not add the `<link rel="import">` or b) not call `importHref` on the import that you've statically imported.

**Comment by TimvdLippe** [comment]
Closing this issue as it appears to be an upstream Safari issue. For now, you can use the workarounds pointed out by @arthurevans Hopefully in the future Safari will have the same behavior as the other browsers.
