### ISSUE TITLE
Using Polymer with Webjars

### ISSUE THREAD

**Issue by heruan** [Polymer/polymer#4912]
To use JavaScript packages from NPM/Bower in Java apps, [Webjars](https://www.webjars.org/) provides an on-request automatic JAR packaging of NPM/Bower packages and publish them to Maven, which makes it very straightforward for a Java developer to use these with a single package manager.

Unfortunately Webjars do no work with Polymer web components, since they put web files in a structure like this:

```
/webjars/polymer/2.2.0/polymer-element.html
/webjars/my-component/1.0.0/my-component.html
```

but Polymer assumes a certain directory structure to import dependencies, e.g. `<link rel="import" href="../polymer/polymer-element.html">`, assuming to find them in the parent directory and a specific path.

Will this be addressed in Polymer 3?

**Comment by jamesward** [comment]
Assuming a cross-component directory structure is certainly bad design.

**Comment by TimvdLippe** [comment]
Hm, this setup is not something we were considering. Since Polymer 3 is simply Polymer 2 but using ES modules instead of HTML imports, we will not be changing our URL destinations either. I am surprised that this is an issue specific with Polymer though. As I understand it, other packages rely on their dependencies and URLs as well. Could you maybe point to other packages that you have no problems with installing so that we can take a look? If there is an obvious fix, we could apply it, but I fear it will be very hard to not break everyones flow right now.

Open to any opportunity to improve adoption, if we can make it work for everyone 😄 Let us know!

**Comment by jamesward** [comment]
I think that if this is in JS then we at least have the opportunity to override defaults.  That is possible with RequireJS.  So maybe we will be ok.

**Comment by TimvdLippe** [comment]
Polymer 3 will be using ES modules, which means we will be fully in JS context. All conventional JS tools should be usable with Polymer, thus I think RequireJS should be able to deal with it 🤞

**Comment by TimvdLippe** [comment]
With our reliance on ES modules with name syntax, this issue should be resolved. We no longer assume a particular directory structure 😄
