### ISSUE TITLE
Scroll target of iron list is undefined in Firefox's console,chrome and edge is showing no error

### ISSUE THREAD

**Issue by mrraval008** [Polymer/polymer#4929]
#### Live Demo

http://jsbin.com/luhaxab/1/edit

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions

- Polymer: v 2.0.0
- webcomponents: v1.0.2

**Comment by TimvdLippe** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
