### ISSUE TITLE
Support coexistence of v3 and prior versions of Polymer

### ISSUE THREAD

**Issue by benduran** [Polymer/polymer#4951]
### Description
First off, I really appreciate that Polymer v3 has moved to a js-first library. This makes it so much easier to integrate with existing tooling and libraries without implementing crazy hacks. That being said...the need for this stemmed out of a possible bug / customElement registry clash with a v3 Polymer build and a v1 / v2 Polymer elements. 

Since Polymer v3 no longer automatically registers itself on the global scope, it is possible to have a fully-enclosed application that doesn't leak any dependencies. The exception to this, however, is custom element registration. It appears that Polymer, in any of its versions, neglects to check if the custom `dom-module` element is already registered in the custom elements registry. When executing my Polymer v3 application on a page with v1 components, the following error occurs:

`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry`

Again, this appears to happen when trying to register the `dom-module` element, since it has already been defined.

I'm not 100% sure how we could correct this issue, as we would need to ensure that the registered `dom-module` tag has feature support across Polymer versions. I wanted to bring this to the team's attention, and possibly discuss short-term and long-term workarounds.

**Comment by web-padawan** [comment]
The limitation which you mention is not Polymer-specific, this is how Custom Elements spec works. But event if it worked as you suppose, how do you imagine depending on both HTML imports and ES modules loaders? That wouldn't make sense due to performance reasons. 

BTW, there are several issues where people already discussed this, you can find them via [3.x label](https://github.com/Polymer/polymer/issues?q=is%3Aissue+is%3Aopen+label%3A3.x). No need to open yet another one. 

PS: neither 0.5 vs 1.x, nor 1.x vs 2.x could not be used together in the same page. But you can still use them in the same app, e. g. implementing some routes in 1.x and other in 2.x. You will need to handle redirects properly, but this is not something impossible.

**Comment by benduran** [comment]
Thanks for your response. I'm aware of the Custom Element spec in that regard. My question was more driven around whether the registration of that specific custom element `dom-module` could be checked first, rather than assuming it wasn't already defined and trying to register it.

As a proof of concept, I ran my v3 code on a v1 page, and simply commented out the registration of the `dom-module` element in v3 and the two seemed to be coexisting without any issues. Granted, I was running a bit of a naive test, but there didn't seem to be anything noticeably wrong with the page when this happened.

I'll take a look at existing items opened with the v3 tag in the meantime.

**Comment by web-padawan** [comment]
Co-existence issue might appear from different reasons, like polyfills timings etc. Most importantly, polymer is not tested against any of possible combinations. So this might be an interesting experiment, but not really useful for production app.

**Comment by TimvdLippe** [comment]
Running multiple versions of the same custom element definition will go wrong, regardless of (lack of) `dom-module` usage. We have no plans to support multiple Polymer versions on the same page for performance reasons and maintainability reasons. We advise you to upgrade to the new version as a whole to prevent such problems and be clear on what version of Polymer you are using.
