### ISSUE TITLE
Provide a mechanism to access an element's host before insertion

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#4965]
Users have requested to be able to access an element's host element. The typical way to do this is via `this.getRootNode().host` and this can be easily done in `ready`. This, however, will not work if the element is not yet connected to the tree (e.g. when `Polymer.templatize` is used). If users want to be able to access the host prior to any data propagation, a different API is needed. There's currently a private `__dataHost` property which may be helpful.

**Comment by kevinpschaaf** [comment]
The main use case here was understanding tree context during construction to implement tree-based dependency injection.

Since achieving this via `getRootNode().host` would require changing some performance-sensitive lifecycle in Polymer related to template stamping, we'd recommend implementing this via an opt-in mixin that maintains a stack of hosts during tree construction.

Example here: http://jsbin.com/vecedad/edit?html,output
