### ISSUE TITLE
Custom CSS properties don't work in IE11

### ISSUE THREAD

**Issue by limonte** [Polymer/polymer#5009]
### Description
Custom CSS properties aren't applied in IE11

#### Live Demo
https://jsfiddle.net/6r5htd05/104/

#### Steps to Reproduce
1. Open the https://jsfiddle.net/6r5htd05/104/ in IE11

#### Expected Results
The `div#toolbar` has red background

#### Actual Results
The `div#toolbar` doesn't have any background

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- Polymer: v2.3.1
- webcomponents: v1.0.22

**Comment by TimvdLippe** [comment]
The source code provided by the Polymer repository is ES6. I think the JSFiddle is not working because of that, as well as the incorrect url to the polyfill (which is a PolyGit quirk). Not sure if we have a ES5 JSBin lying somewhere though. @azakus How do you usually test IE11 with latest version of Polymer?

**Comment by limonte** [comment]
IE11 jsfiddle isn't possible, the issue is actually different: https://github.com/Polymer/polymer/issues/5015
