### ISSUE TITLE
importPath undefined

### ISSUE THREAD

**Issue by DarkSideOfMo0n** [Polymer/polymer#5064]
### Description
Documentation says: import Path -> "A static getter on the element class that defaults to the element HTML import document URL and is overridable. It may be useful to override importPath when an element's template is not retrieved from a <dom-module> or the element is not defined using an HTML import."
can be found [here](https://www.polymer-project.org/2.0/docs/devguide/dom-template), section: URLs in templates

But it seems that when using a component with inline template this importPath property is undefined.

#### Live Demo
repo URL: https://github.com/DarkSideOfMo0n/import-path-bug

#### Steps to Reproduce
1. git clone https://github.com/DarkSideOfMo0n/import-path-bug.git
2. bower install
3. polymer serve
4. open index.html in browser
5. inspect my-element -> importPath property is undefined

#### Expected Results
importPath property of my-element contains the path it was imported from

#### Actual Results
importPath property of my-element is undefined

### Browsers Affected
- [X ] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v2.3.1
- webcomponents: v1.1.0

**Comment by TimvdLippe** [comment]
It is working directly in a JSBin if put in the main file. This might be an issue with it is behind an HTML import: http://jsbin.com/woruzilaza/edit?html,console,output

**Comment by LarsDenBakker** [comment]
Your element definition is missing a <dom-module> wrapper. Even if you define your template in JS, you still need the dom-module declaration currently. Would be great if you didn't need it though.

**Comment by TimvdLippe** [comment]
I did a quick investigation and it appears to be impossible from a static perspective (e.g. in a class constructor) to know what the `ownerDocument` is. This means that you need a concrete instance of an element and get the `ownerDocument` from there. Since `dom-module` encapsulates a component definition (and thus the class as well), we have a concrete instance and can therefore do our calculations.

From a regular script, we can't know where it is coming from, thus we are unable to construct the `importPath`. As @LarsDenBakker pointed out, you should wrap these definitions in a `dom-module`, even if you don't define a `template` there.

Therefore, I think we have to clarify this in the docs. Would you like to contribute with a suggestion?

**Comment by TimvdLippe** [comment]
This issue was moved to Polymer/docs#2466
