### ISSUE TITLE
Using mixin in a base class triggers TypeError in descendants in Polymer 2.4.0

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polymer#5073]
_From @dpikhulya on January 30, 2018 17:41_

Adding Polymer.PaperButtonBehavior to a base class, and extending that base class in two different child elements makes the following exception to be thrown by the second subclass instance:

```
properties-changed.html:133 Uncaught TypeError: Cannot read property '_imperativeKeyBindings' of undefined
    at HTMLElement.get (properties-changed.html:133)
    at HTMLElement._prepKeyBindings (iron-a11y-keys-behavior.html:397)
    at HTMLElement.registered (iron-a11y-keys-behavior.html:325)
    at HTMLElement._registered (class.html:197)
    at HTMLElement._registered (class.html:185)
    at HTMLElement._registered (class.html:185)
    at HTMLElement._registered (class.html:185)
    at HTMLElement._registered (class.html:185)
    at HTMLElement._initializeProperties (legacy-element-mixin.html:174)
    at new PropertiesChanged (properties-changed.html:153)
    ...
```
In this example we have a hierarchy like this:
```
AbstractButton <- Polymer.PaperButtonBehavior
CustomButton1 <- AbstractButton
CustomButton2 <- AbstractButton
```
If we place BOTH `<custom-button-1>` and `<custom-button-2>` on the same page, only one of them (the second one) will fail with this exception. Commenting either of subclass instances doesn't trigger an error. 

The same example works fine with Polymer 2.3.1.

See [this example](http://jsbin.com/dovujaquji/1/edit?html,output), which fails to display "custom-button-2" text as a button.

This might not be specific to PaperButtonBehavior, but I didn't delve deeper.

### Expected outcome

No exception is thrown, and both AbstractButton descendants are displayed as buttons.

### Actual outcome

TypeError exception is thrown, the second subclass instance is not displayed properly.

### Live Demo

http://jsbin.com/dovujaquji/1/edit?html,output

### Steps to reproduce

Just open that page and see the exception in the console:
![image](https://user-images.githubusercontent.com/286459/35581426-6a39a960-05f4-11e8-80de-581a682fe748.png)

### Browsers Affected

Checked this to be reproducible at least in Chrome 64 and Firefox 58.

_Copied from original issue: PolymerElements/paper-behaviors#86_

**Comment by sorvell** [comment]
It looks like we made an unintentional breaking change here that we'll be rolling  back.

The change was to always create property accessors for properties returned in the properties object (if they were not marked readOnly or already in existence). Previous to this change property accessors were only created for properties that had explicit property effects (e.g. observer or data binding).  There was an implicit expectation made in the code in [iron-a11y-behavior](https://github.com/PolymerElements/iron-a11y-keys-behavior/blob/master/iron-a11y-keys-behavior.html#L304) that this would not be the case.

Since this was only done as a slight simplification around the rules of creating properties, we'll be rolling back this change.
