### ISSUE TITLE
Proposal: Change how metadatas are stored

### ISSUE THREAD

**Issue by zaclummys** [Polymer/polymer#5116]
The usage of metadata is very common in several programming languages.

In Polymer, metadata, such as _observers_ and _properties_, is stored in own properties in class constructors. This practice can be considered intrusive and inconvenient, since these metadata are exposed and can be enumerated.

To make the metadata store appropriate, there are some consistent solutions, including:

- **WeakMap**, included in the version ECMAScript 2015.
- **Reflect.metadata**, proposed for the version ECMAScript 2016.

These solutions have important benefits, such as:

1) Polymer will become cleaner and more organized.
2) It will become easier to debug errors, because the work is unified and avoid repetitions.
4) Avoid conflicts with properties of the same name.

**Comment by kevinpschaaf** [comment]
Thanks for the feedback. I don't think we're going to entertain changes to this API at this point.  The metadata is stored as static class properties in a similar manner to `observedAttributes` in the DOM spec, so there is consistency there.  Furthermore, once decorators reach a more stable state, we will likely move to using decorators to specify the metaprogramming inputs rather than properties.

**Comment by zaclummys** [comment]
Sorry, I don't think I was clear enough. I was referring to the metadatas that is assigned in the internal API, such as `__ownProperties` and `__ownObservers`.

Anyway, I like `static get properties` too! :)
