### ISSUE TITLE
						Polymer 2.0 having Browser compatibility issue with IE11 & Mozilla.project is properly working on a chrome browser  						and below a firefox browser 58.0.1 but not working on firefox latest version 58.0.2 and not getting any error in a console.so tell give m any idea  						how to fix this issue?

### ISSUE THREAD

**Issue by kapilSoni101** [Polymer/polymer#5121]

**Comment by TimvdLippe** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
