### ISSUE TITLE
Provide a mixin to help use immutable data patterns

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#5126]
Immutable data patterns are an excellent way to have explicit, granular control of how structured data is passed between elements. Polymer should provide a mixin which encourages using this pattern by integrating with the library's data manipulation api (e.g. `this.set`).

**Comment by MajorBreakfast** [comment]
Great to see some progress on this. I think you've talked about this internally, but could you share some details on what you plan to do, i.e. how it could look like in action? In particular, how does your current idea solve the dom-if=false issue?

***

MutableData has a big benefit: It makes it possible let a third party lib which does treat data as immutable manage the objects.

Immutable data is hard. Here's a trivial example:
`const a = { b }; const b = { prop: 1 }` and set `b.prop = 2`
- A new immutable copy of `b` needs to be created and **all references to `b` must be updated**
- To update the reference to `b` in `a` a new immutable copy of `a` needs to be created and **all references to `a` must be updated**

The part in **bold** is IMO the hard part because most objects do not know their parent(s). Requiring a library to output immutable data only is a lot to ask.

**Comment by kevinpschaaf** [comment]
@MajorBreakfast Immutable patterns are most straightforward with unidirectional data flow, where state changes are centralized at the top of the tree and flowed down, such that the _most objects do not know their parent(s)_ problem is not an issue.

`MutableData` was provided as an escape-hatch option, for cases where neither immutable data patterns nor Polymer's path mutation API's can be used, which is meant to address the _Requiring a library to output immutable data only is a lot to ask_ concern; it comes at the cost of performance, but is an option where as you say, it's too much to ask to change e.g. existing business logic that relies on making mutable changes.

However, for this issue I'm experimenting with a drop-in replacement to Polymer's path mutation API's (`set`, `push`, `pop`, ...) via an e.g. `ImmutableData` mixin that implements the immutable pattern amd can be used in conjunction with two-way binding to allow an element deep in the tree to mutate a path and ensure all parent objects up the tree (for which it does not know its placement into) to have their references cloned.  For the most part, it's a drop-in replacement for the existing API (assuming the `ImmutableData` mixin can be applied to all elements that make modifications and their 2-way-bound parents), and should allow existing code written against the `set`/`push`... API's to work unchanged.

The idea is that `ImmutableData` would be an alternative to `MutableData` for avoiding the `dom-if` bug that is compatible with existing code and should not regress performance in the same ways.  I sympathize with "reliability shouldn't be opt-in", but we've not come up with a non-breaking way to fix that bug, without just reverting https://github.com/Polymer/polymer/pull/4299 (which introduced the bug).

**Comment by kevinpschaaf** [comment]
Prototype `ImmutableData` mixin: http://jsbin.com/manudat/edit?html,output

**Comment by MajorBreakfast** [comment]
@kevinpschaaf Thanks for the demo! I'll definitely play around with it :)

**Comment by TimvdLippe** [comment]
Per discussion: this basically needs an update of the test suite to duplicate most of the data-binding logic, but not all.
