### ISSUE TITLE
paper-toggle-button with on-tap eventhandler is not handled backward compatible

### ISSUE THREAD

**Issue by thomasvogel** [Polymer/polymer#5136]
- [ x] Chrome
- [ x] Firefox
- [ x] Edge
- [ x] Safari 9
- [ x] Safari 8
- [x ] IE 11

### Versions

- Polymer: v2.4.0, v2.5.0
- webcomponents: v1.1.0

**Comment by thomasvogel** [comment]
Is this new behavior intended?

**Comment by TimvdLippe** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
