### ISSUE TITLE
nested dom-repeat - dom change not called

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/polymer#5138]
If I nest 2 dom repeats like this:

     <template is="dom-repeat" items="{{pGroupsCS}}" as="pGroupCS" on-dom-change="_aa">
           <template is="dom-repeat" items="{{pGroupCS.names}}" as="pGroupFA" on-dom-change="_bb">

the "_aa" is called for every element, but "_bb" is never called!

**Comment by dimassrio** [comment]
@jogibear9988 did you already Notify Polymer of a subproperty change?
How did you setup pGroupCS property and its subproperty?

**Comment by jogibear9988** [comment]
why should I? the elements n the second dom-repeat are created! but the callback is not called!

**Comment by jogibear9988** [comment]
I created a fiddle, but it seems to work. So I look for a error in my code. https://jsfiddle.net/1jLepepq/257/

But, I thought it will be called for each item, but it's not, it's only called once when the dom is changed. Is there a way to get the items created by the dom-repeat? I'd like to loop through my object and ask the dom-repeats for the created dom object?

Problem is, I've a special Binding Framework, and I've to bind the created nodes after creation!

**Comment by TimvdLippe** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue. Given that the JSFiddle appears to be working, we require a reproduction case that shows an issue with `dom-change`. You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
