### ISSUE TITLE
Can't access the HTML page directly?

### ISSUE THREAD

**Issue by mylovetop** [Polymer/polymer#5235]
Can't access the HTML page directly?
Do you have to have a node server?
Does it support access to normal HTML pages?Deploy the polymer project under nginx, and then index.html direct access, support?

**Comment by mylovetop** [comment]
Nodejs, that's a big problem.
2.0 at least you don't need to know nodejs.

**Comment by TimvdLippe** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
