### ISSUE TITLE
Unable to build components

### ISSUE THREAD

**Issue by RyanAfrish7** [Polymer/polymer#5276]
My use case involves developing a component which in turn uses other components. The component I develop will be delivered to clients with minimum knowledge about development. To make the integration into their website easy, I would like to deliver this as a single file component with all dependencies attached. Though polymer-cli does this internally for building websites, It doesn't exposes similar functionality for components. It also makes developing a component with backward-compatibility harder.

**Comment by kevinpschaaf** [comment]
This isn't a use case our tools support by default, since bundling a reusable components's dependencies for distribution is generally an anti-pattern, since it often leads to duplicated code and, particularly with custom elements, double-registration of elements, which will throw in the browser.

**For this reason, we don't recommend publishing or distributing generally reusable components that bundle their dependencies.**

That said, if you really want to bundle a component, it's fairly trivial to do.  You didn't specify whether you're using Polymer 2.x or 3.x, so here's some starters for both:

## 2.x
Since 2.x relies on HTML Imports, and polymer-cli is really the only game in town for HTML Imports given that the spec is deprecated, `polymer build` is your best bet.  The only reason it wouldn't work out of the box is that reusable components typically refer to their dependencies via paths like `../some-other-dependency/`, which leads to problems when you're trying to build from e.g. github source.  A way to work around this is to link your source folder into the bower_components tree, and then `polymer build` the component there.

package.json
```
{
  ...
  "scripts": {
    "build": "ln -nsf .. bower_components/my-element && polymer build --bundle --entrypoint bower_components/my-element/my-element.html && mv build/default/bower_components/my-element/my-element.html ./my-element-bundle.html"
  },
  "devDependencies": {
    ...
    "polymer-cli": "^1.7.7"
  }
}
```
And finally, this will output `my-element-bundle.html` in the root folder:
```
npm run build
```

## 3.x
Since 3.x is just standard JS, you don't have to use Polymer tools to accomplish this at all. A trivial rollup config will bundle your ES modules into a legacy script you can import.

package.json
```
{
  ...
  "scripts": {
    "build": "rollup -c"
  },
  "devDependencies": {
    ...
    "rollup": "^0.63.4",
    "rollup-plugin-node-resolve": "^3.3.0"
  }
}
```
rollup.config.js
```js
import resolve from 'rollup-plugin-node-resolve';

export default {
  input: 'my-element.js',
  output: {
    file: 'my-element-bundle.js',
    format: 'iife'
  },
  plugins: [ resolve() ]
};
```
And finally, this will output `my-element-bundle.js` in the root folder:
```
npm run build
```
