### ISSUE TITLE
Submit form using IE11 causes unresponsive website

### ISSUE THREAD

**Issue by stucker71** [Polymer/polymer#5277]
### Description
If submitting a form using IE11 then website will no longer will function correctly, clicks no longer respond. For compatibility with IE11 I'm using `polymer build --js-compile` option. See code below:

```
<paper-menu-button>
      <paper-icon-button icon="menu" slot="dropdown-trigger"></paper-icon-button>
      <paper-listbox selected="0" slot="dropdown-content">
        <paper-item on-click="_dosomething1">Option 1</paper-item>
        <paper-item on-click="_dosomething2">Option 2</paper-item>
      </paper-listbox>
</paper-menu-button>


    <form id="myform" method="post" action="https://www.mysite.com/pdfdownload">
      <input id="myinput" type="hidden" name="myinput" value="hello">
    </form>

    <paper-icon-button on-click="_submitform" icon="cloud-download"></paper-icon-button>
....

_submitform() {
        this.$.myform.submit();
      }
```
In reality I'm submitting form data to a server, the server then responds with a PDF document. Works fine using latest version of Chrome and Safari. Just IE11 where issue exists.

#### Expected Results
After submitting form I would expect paper-menu-button dropdown element to function correctly.

#### Actual Results
After submitting form paper-menu-button no longer responds.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [x ] IE 11

### Versions

- Polymer: v2.6.0
- webcomponents: v1.2.2

**Comment by TimvdLippe** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and be sure to include a live reproduction so that the team can debug or understand your issue.  You can start from [this jsBin template](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!
