### ISSUE TITLE
Polymer-3 with nodejs, express, socket.io

### ISSUE THREAD

**Issue by scenaristeur** [Polymer/polymer#5282]
Hi guys,
 Polymer is a really cool lib for working with components, but I'm a little bit disappointed migrating from Polymer 2 to Polymer-3... so I need help : 
Usually using  Polymer 2 with nodejs, express & socket.io with 'public/src/my-element' architecture, I don't know what is the right way to import Polymer 3 components and other components / external librairies like socket.io(client side), vis.js  (from node_modules instead of bower_components) .

Here is my standard architecture :
` 
. root 
.......| - node_modules
.......| - index.js (server with socket.io & app.use(express.static(__dirname + '/public'));
.......| - public 
...................| - index.html
...................| - src
...........................| - my-app
........................................| - my-app.html
...........................| - first-element
.........................................| - first-element.html

There was no probleme with Polymer 2 (i've developped many apps https://github.com/scenaristeur/heroku-spoggy)  but we can't use ' <link rel="import" href="../../bower_components/polymer/polymer-element.html">' anymore, so could you tell me what is the way to import Polymer 3 library and other components / external libs with nodejs, socket.io in this config ?

Thanks

**Comment by scenaristeur** [comment]
Thxs @web-padawan for your response, I've tried your solution but i'm not looking for performance on production, I just want to keep socket.io interaction between my Polymer front-end and my socket.io server which receive request and send response to appropriate client or braobcast tout all. With your solution and a 'packed' front-end I don't have my backend 😕

**Comment by kevinpschaaf** [comment]
It's unclear what the connection between your use of `socket.io` is and your difficulty to import components is.

In Polymer 3.x your components should be defined in ES modules (e.g. `my-app.js`) and imported from your top-level `index.html` via a `<script type="module" src="./src/my-app.js">`, and subsequent components via ES module import syntax, i.e. `import './first-element.js';`.  If you need to dynamically load components or libraries, you can use the `import(...)` to dynamically import.

If I were to guess, the issue you're probably running into is that statically serving ES modules using "module specifiers" rather than paths doesn't work natively in the browser, hence just using vanilla express as your http server won't suffice.  The `polymer serve` dev server does this light transformation (only), so that's what we'd recommend using in place of express.  If you're unable/unwilling to do that, you could look at [empathy](https://github.com/PolymerLabs/empathy/tree/initial-implementation), which is an experimental tool to transform module names to paths at install time (one-time only), so that you can still use a static server at dev time.

Your issue report doesn't have a lot to go on, so if you're hitting some other problem, please open a new issue with a reproduction case so we can help you diagnose the issue.

**Comment by emersonbottero** [comment]
I think that's what you need.

```
ready()
    {
        const ioscript = document.createElement('script');
        ioscript.src = 'https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.js';
        document.getElementsByTagName( "head" )[0].appendChild(ioscript);

        ioscript.addEventListener ("load", ()=>{
            console.log ('script socket.io loaded, be happy');
            if(this.auto) this.connect();
        });
    }
```

I didn't know if I should answer here or I should open another one linking this issue, tell me so i can do it right the next time.
