### ISSUE TITLE
'this.Function()' is undefined

### ISSUE THREAD

**Issue by M4FFS** [Polymer/polymer#5296]
#### Steps to Reproduce

Call 'this.function()' from another polymer function
Cause unknown, works differently in different random contexts. 

#### Expected Results
'this' keyword returns polymer object

#### Actual Results
'this' keyword returns the JavaScript window object

### Browsers Affected
- [x] Chrome
- [x] Firefox

### Versions
- Polymer: v1.1

**Comment by kevinpschaaf** [comment]
Thanks for the issue.  Please see [CONTRIBUTING.md](https://github.com/Polymer/polymer/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  Please fill out as many fields in the issue template as possible, and **be sure to include a live reproduction** so that the team can debug or understand your issue.  You can start from [this glitch template](https://glitch.com/edit/#!/polymer-element-example?path=index.html) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions.  Thank you!

**Comment by kevinpschaaf** [comment]
You are likely running into a common (non-Polymer-specific) JavaScript issue of forgetting to bind callbacks to the original context.  For more information, have a look at this article: https://thenewstack.io/mastering-javascript-callbacks-bind-apply-call/.
