### ISSUE TITLE
export class LiteralString from html-tag.js

### ISSUE THREAD

**Issue by rdehuyss** [Polymer/polymer#5410]
### Description
Allow usage of javascript template literals by exporting class LiteralString from html-tag.js

Use case:
- I want my elements to be self-contained, including images.
- If I use a background image in a polymer webcomponent, the url is relative to the page, not the webcomponent (see also https://github.com/Polymer/lit-html/issues/356), resulting in a 404 for these images.
- I can have a simple variable which contains the complete url using import.meta.url, yet I cannot use it in polymer as:
   - all databinding in style elements are not evaluated
   - javascript template literals are not working, resulting in the following exceptions:
      - non-template value passed to Polymer's html function
      - non-literal value passed to Polymer's htmlLiteral function

#### Steps to Reproduce
```
        const bgSvgUrl = new URL('./static/bg.svg', import.meta.url).toString();
        html`<my-element style="--background-svg: url(${bgSvgUrl})"/>`; 
```

Or 

```
        const bgSvgUrl = new URL('./static/bg.svg', import.meta.url).toString();
        htmlLiteral`<my-element style="--background-svg: url(${bgSvgUrl})"/>`; 
```

#### Expected Results
What's wrong with exporting the class LiteralString?
I want to be able to use a standard javascript literal in templating. By exporting the class LiteralString, I can do the following:

```
       new LiteralString(new URL('./static/bg.svg', import.meta.url).toString());
       html`<my-element style="--background-svg: url(${bgSvgUrl})"/>`; // Wooohooo!!!!
``` 

#### Actual Results
```
html-tag.js:64 Uncaught Error: non-template value passed to Polymer's html function: http://127.0.0.1:8081/static/bg.svg
    at htmlValue (html-tag.js:64)
    at template.innerHTML.values.reduce (html-tag.js:107)
    at Array.reduce (<anonymous>)
    at html (html-tag.js:107)
    at Function.get template [as template] (smsservice.js:9)
    at Function._finalizeClass (element-mixin.js:318)
    at Function.finalize (properties-mixin.js:142)
    at HTMLElement._initializeProperties (element-mixin.js:494)
    at new PropertiesChanged (properties-changed.js:180)
    at new PropertyAccessors (property-accessors.js:116)
```

or

```
Uncaught Error: non-literal value passed to Polymer's htmlLiteral function: http://127.0.0.1:8081/static/bg.svg
    at literalValue (html-tag.js:46)
    at values.reduce (html-tag.js:136)
    at Array.reduce (<anonymous>)
    at htmlLiteral (html-tag.js:136)
    at Function.get template [as template] (smsservice.js:9)
    at Function._finalizeClass (element-mixin.js:318)
    at Function.finalize (properties-mixin.js:142)
    at HTMLElement._initializeProperties (element-mixin.js:494)
    at new PropertiesChanged (properties-changed.js:180)
    at new PropertyAccessors (property-accessors.js:116)
```

### Browsers Affected

- [ x] Chrome
- [ x] Firefox
- [ x] Edge
- [ x] Safari 11
- [ x] Safari 10
- [ x] IE 11

### Versions
- Polymer: v3.0.5
- webcomponents: v2.1.3

**Comment by kevinpschaaf** [comment]
The `html` tag function in Polymer is designed to be used _only_ with literal strings.  Since `html` uses `innerHTML` to construct a template, interpolating variables from potentially untrusted sources would present an XSS vector. By only accepting literal strings, we can be sure they originate in trusted source (your script files) and thus are safe to `innerHTML`.  Because our intention is to be safe by default for the functionality that we provide, we will not expose a way to interpolate untrusted values.

That said, there is nothing magic about our `html` function.  It literally just does something like this:

```js
const template = document.createElement('template');
template.innerHTML = /* _your string here_ */;
return template;
```

The only requirement for `static get template()` is that it returns a template.  Thus you're free to write whatever code you'd like to construct it -- including interpolating values into a string before running `innerHTML`.  We just want _you_ to write that code since we cannot ensure it would be safe if we did.  Hope that helps.
