### ISSUE TITLE
Please include an error case in `super.js` when called from `strict` mode (missing `caller`)

### ISSUE THREAD

**Issue by zyklus** [Polymer/polymer#597]
If code calling `this.super()` is in strict mode, the following code from `super.js` fails:

    function $super(arrayOfArgs) {
      var caller = $super.caller; // caller is null

This is fairly annoying to track down to the fact that my parent file is in strict mode.  Can you add a descriptive error message here for the case when `caller === null`?

**Comment by jeffschwartz** [comment]
+1. There is no excuse to be using .caller. That Polymer does rely on its use means that there is a flaw in your library that makes using it a necessity. It is ridiculous today to believe that

    (function(){
        "use strict"; //<<==
        Polymer('extended-element', {  
            ready: function() {
                this.super();  //<<==
            }
        }
    }());

breaks your code base.

This just smells really, really bad. Polymer must break with the past and fully embrace modern JavaScript which means  there has to be 0 tolerance for these kinds of issues. If that means breaking changes to .super then so be it.

**Comment by jklein24** [comment]
+1 on this. I just ran into it as well. Would something like what closure does work here:

https://github.com/google/closure-library/blob/master/closure/goog/base.js#L2196

This is a blocker for my team using Polymer to write custom elements.

**Comment by jeffschwartz** [comment]
@jklein24 this shouldn't be blocking development. It just makes it a pita wherever you need to call this.super(). Here's how to get around it:

    (function() {
        Polymer("demo-redirect", {
            //NOTE: You cannot use strict mode if calling this.super
            domReady: function() {
                this.super();
                this.infoEl = document.getElementById("demo-redirect-info");
            },
            get: function(){
                "use strict";
                this.infoEl.textContent =  "demo-redirect \"get\" handler was called " +
                    "and is redirecting to demo-redirecttarget";
                console.log("demo-redirect \"get\" called");
                this.rtrHistoryEl.navigate({
                    path: "/rtr/components/rtr/demo-redirecttarget",
                    trigger: true
                });
            }
        });
    }());

As per the above, just don't use a module global form of "use strict". Instead include "use strict" in every function except for those that need to call this.super(). PITA and the Polymer team should definitely address this because it just smells really really really bad. It certainly isn't what to expect in a product that is paving the way to component based client-side development.

**Comment by jklein24** [comment]
Thanks, Jeff. Unfortunately it's not quite that simple for us since we are compiling our code using the closure compiler and would like to be able to continue to have it inject global "use strict" into our compiled code. Because all of our code is concatenated in to one "compiled" bundle, using this workaround would be much too large a burden.

**Comment by jeffschwartz** [comment]
@jklein24 that's unfortunate. i've never used the closure compiler. too bad javascript doesn't support  a "!strict mode" option - that would certainly come in handy in your case :)

**Comment by moderndeveloperllc** [comment]
Glad I found this ticket. That was a pain to track down. I wonder if this is one of the reasons that 0.8 will not support inheritance of anything other than built-in HTMLElements. I'm guessing that the "p1" label means this won't be fixed until 1.0 - a while from now.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
