### ISSUE TITLE
Polymers elements cannot go fullscreen

### ISSUE THREAD

**Issue by arkeros** [Polymer/polymer#745]
It seems that (nested) polymer elements cannnot go fullscreen themselves:

Suppose that all these codes are preceded by an import of https://github.com/sindresorhus/screenfull.js/#why

This does not work:

```
  <core-tooltip label='Fullscreen'>
    <core-icon-button icon='fullscreen' onclick='screenfull.toggle(this)'></core-icon-button>
  </core-tooltip>
```

But this does:      

```
<div>
    <button onclick='screenfull.toggle(this)'></button>
  </div>
```

On the other hand, they CAN send the whole page to fullscreen

```
  <core-tooltip label='Fullscreen'>
    <core-icon-button icon='fullscreen' onclick='screenfull.toggle()'></core-icon-button>
  </core-tooltip>
```

What makes me think it has to do with 'shadow-root'.

**Comment by Bodhiz** [comment]
Hi, 
I'm getting some troubles to extend a Polymer element to fullscreen. 
I did 2 codepen to demonstrate the issue. 

The first one is with a very basic element containing just a `<h1>` : https://codepen.io/Bodhiz/pen/reZXxw
As you can see, it works but on webkit I have to do few tricks : 
- force the background to white for firefox 
- force the display to block on webkit (otherwise I get blackscreen even wit the background forced to white)

The second pen contains a bit more complex element with an embedded iron-list : https://codepen.io/Bodhiz/pen/ONoGNK
On this one I can't make it work on webkit, I get a black screen. On firefox, it works better but i'm not able to scroll the list. 

I'm not 100% sure that is directly related to Polymer but if you have any clues, it would be great :)
