### ISSUE TITLE
Paper-Dialog nested event handling and scoped styling

### ISSUE THREAD

**Issue by thecaddy** [Polymer/polymer#937]
With the latest update 0.5.1 the paper-dialog component no longer attaches to the parent:

```
<my-parents>
  <paper-dialog>
    <paper-button on-click={{myFunction}}></paper-dialog>
  </paper-dialog>
</my-parent>
```

This will attach to the body:
```
<body>
  <core-overlay-layer>
    <overlay-host>
     <paper-dialog>
       //where the click event happens
       <paper-button on-click={{myFunction}}></paper-button>
     </paper-dialog>
    </overlay-host>
  </core-overlay-layer>
</body>
```

This loses context of the parent element and thus context of the event being fired.  Is there a recommended pattern to handling the events and a way for adding styling so it doesn't have to be in global context?

**Comment by davidmaxwaterman** [comment]
that jsbin doesn't seem to work...any chance it could be fixed?

I'm seeing a problem with not getting the events in the parent element. I'm using it with layered="false" so it isn't being rehosted (because I don't want it to be above the whole window, but only part of it). However, in order to make the element be in the correct size/position as the area I *do* want, I had to extend it with another element, and override the core-overlay.repositionTarget() function to use the width/height of the correct element instead of window. It seems that, by extending, I've lost the events for paper-dialog's contents (a couple of paper-buttons - 'cancel' and 'done').

It'd be nice to have a clue how to fix this 'properly', so any pointers are welcome.

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
