### ISSUE TITLE
core-dropdown: click on  scrollbar closes element!

### ISSUE THREAD

**Issue by angelcolmenares** [Polymer/polymer#947]
try 
https://www.polymer-project.org/components/core-dropdown/demo.html
"Scrolling and margin"

**Comment by micku7zu** [comment]
I think I found the fix for this bug. I somehow didn't think to submit it to the root of the problem (core-dropdown), and submit it on paper-dropdown, but I think it's the same fix. 

Try it: https://github.com/micku7zu/paper-dropdown-menu/commit/2278b46bd5dbc76e78d690037a8fc1c9aea91ec8

https://github.com/Polymer/paper-dropdown-menu/pull/56

and submit if it works :smile:

**Comment by tjsavage** [comment]
Closing this issue due to age and the release of [version 1](https://www.polymer-project.org/1.0/) of Polymer - please feel free to re-open if this is incorrect.
